gravitee-io/gravitee-access-management

gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/app.module.ts, gravitee-am-ui/src/app/domain/settings/theme/help-tips/help-tips.component.html, gravitee-am-ui/src/app/domain/settings/theme/help-tips/help-tips.component.ts, gravitee-am-ui/src/app/domain/settings/theme/theme.component.html, gravitee-am-ui/src/app/domain/settings/theme/theme.component.scss, gravitee-am-ui/src/app/domain/settings/theme/theme.component.ts
closes gravitee-io/issues#8124
**For this PR, only forms have been managed, not the email templates.**
1. Choose a form you want to update from the **Theme** section of your security domain
2. Switch to HTML mode, do your change and press `PUBLISH`
3. Refresh the page, your HTML content must have been saved
=> feat(theme): HTML mode integration

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/UserService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpointTest.java, gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html
=> fix(forgot-password): rollback gravitee-io/issues#7796

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.17.5
=> Changelog for AM - 3.17.5

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.4
=> Changelog for AM - 3.18.4

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginAbstractHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSelectionRuleHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSelectionRuleHandlerTest.java, gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.html
closes gravitee-io/issues#8396
=> Merge 3.18.2 into master

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/FormsResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/error.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/forgot_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/identifier_first_login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge_alternatives.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_recovery_code.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/oauth2_user_consent.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_register.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/FormsResourceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/FormService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FormServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/FormServiceTest.java, gravitee-am-service/src/test/resources/views/default/valid.html, gravitee-am-ui/src/app/domain/components/forms/form/form.component.ts
Shows default gateway forms if custom forms are not present.
This pull request also includes main.css and roboto font files.
The location of these files may be changed as required.
=> feat(theme): display default gateway forms

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTestConfiguration.java
closes gravitee-io/issues#8397
=> Merge 3.18.3 into master

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/VertxHttpHeaders.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/VertxHttpServerRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/VertxHttpServerResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/PolicyChainHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/EvaluableRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/EvaluableResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/UserService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/request/AuthorizationRequestFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/request/TokenRequestFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/BaseRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/AuthorizationRequestFactoryTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/TokenRequestFactoryTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/DummyRequest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/context/EvaluableAuthenticationRequest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTestConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/http/JettyHttpServerHeaders.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/http/JettyHttpServerRequest.java, gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html, pom.xml
closes gravitee-io/issues#8398
=> Merge 3.18.4 into master

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
=> fix(reset-password): do not use the external_id field to reset the user password

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.5
=> Changelog for AM - 3.18.5

docker/management-ui/Dockerfile, docker/management-ui/Dockerfile-dev, docker/management-ui/Dockerfile-nightly
=> fix: upgrade nginx based image to 1.23

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/error.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/error.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/forgot_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/identifier_first_login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge_alternatives.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_recovery_code.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/oauth2_user_consent.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_register.html, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
Default templates updated as they are in the gateway webroot
=> 8457: updated default html templates

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/password-validation.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
fixes gravitee-io/issues#8372
Fixed the password update issue and also added more informative validation for the confirmation password.
The password match notification appears with and without a password policy.
https://user-images.githubusercontent.com/99647292/190346641-323e0b58-cb26-4bbf-abf9-01e83a74bf22.mov
=> fix: improve reset password validation

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge_alternatives.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge_alternatives.html
=> fix: remove useless JS action on alternative factor selection

.circleci/workflows.yml, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/main.css, gravitee-am-ui/src/assets/css/main.css
=> feat: make body background color editable using variable

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpoint.java
=> fix: remove login_hint on backToIdentifierFirst action

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/main.css, gravitee-am-ui/src/assets/css/main.css
fixes gravitee-io/issues#8474
can be test using custom CSS
```
:root {
--container-width: 300px
}
```
=> fix: define variable for the container width

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/identifier_first_login.html, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/identifier_first_login.html, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
=> fix: add placeholder for identifier first login form

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/forgot_password.html, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/forgot_password.html, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
=> fix: test field key to adapt the placeholder

gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java, gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java
=> fix: define timeOut on blockingGet during sync process

gravitee-am-factor/gravitee-am-factor-call/src/main/resources/schemas/schema-form.json, gravitee-am-factor/gravitee-am-factor-email/src/main/resources/schemas/schema-form.json, gravitee-am-factor/gravitee-am-factor-sms/src/main/resources/schemas/schema-form.json, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-ui/src/app/domain/settings/factors/creation/steps/step2/step2.component.ts, gravitee-am-ui/src/app/domain/settings/factors/factor/factor.component.ts, gravitee-am-ui/src/app/domain/settings/factors/factor/form/form.component.scss
closes gravitee-io/issues#8444
=> feat(mfa): handle new type of MFA factors

gravitee-am-model/src/main/java/io/gravitee/am/model/User.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/UserProfileUtils.java
fixes gravitee-io/issues#8268
You can use the acceptance tests explain here https://github.com/gravitee-io/issues/issues/8039
The case where the locale claims is updated should works
=> fix: do not override the preferredLangague field by the locale claim

gravitee-am-ui/src/app/domain/settings/texts/dictionaries.component.html, gravitee-am-ui/src/app/domain/settings/texts/dictionaries.component.ts
Removed save button to simplify language and translation entries as applicable.
=> 8487: simplified Texts page

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/identifier_first_login.html
=> fix: add username value into the idfirst form when login_hint is present

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_register.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_register.html
=> fix: define error style for webauthn enrollment page

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.15.13
=> Changelog for AM - 3.15.13

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/main.css, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html, gravitee-am-ui/src/assets/css/main.css
=> fix(theme): rework MFA enroll page

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
=> fix(forms): change the french translation for the recovery code

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge.html, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge.html, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
=> fix(forms): add missing MFA recovery code description

gravitee-am-ui/src/app/domain/settings/theme/theme.component.ts
=> fix: update live preview with default theme after reset

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge_alternatives.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge_alternatives.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html
=> fix(forms): fix MFA challenge alternatives CSS style

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/identifier_first_login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_register.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/identifier_first_login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_register.html
=> fix: make error message unclickable

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/main.css, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/oauth2_user_consent.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_register.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/oauth2_user_consent.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_register.html, gravitee-am-ui/src/assets/css/main.css
=> fix(forms): fix some width components when reducing the container size

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/main.css, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/forgot_password.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/identifier_first_login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_register.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/forgot_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/identifier_first_login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_register.html, gravitee-am-ui/src/assets/css/main.css
=> fix(forms): apply good padding for the buttons

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html
=> fix: make back to login a link and not a button

gravitee-am-ui/src/app/domain/settings/texts/dictionaries.component.html
=> fix: make the translation tabs responsive

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.7
=> Changelog for AM - 3.18.7

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/PreviewRequest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/preview/PreviewService.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/preview/PreviewServiceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/theme/impl/ThemeValidatorImpl.java, gravitee-am-ui/src/app/domain/settings/theme/theme.component.ts
=> fix: preview default form template if custom form is disable

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html
=> fix(forms): do not apply background color for FranceConnect link

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/main.css, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_recovery_code.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/oauth2_user_consent.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_recovery_code.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/oauth2_user_consent.html, gravitee-am-ui/src/assets/css/main.css
=> fix(forms): rework gray boxes

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html
=> fix(forms): apply phone number validation during submit action

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/forgot_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/forgot_password.html
=> fix: Clean up forgot_password.html

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/error.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/identifier_first_login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge_alternatives.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_recovery_code.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/oauth2_user_consent.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/error.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/identifier_first_login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge_alternatives.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_recovery_code.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/oauth2_user_consent.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html
=> fix: Clean up templates

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/forgot_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/forgot_password.html
=> fix: disable the submit button until forgot password fields have value

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
=> 8553 gateways texts bad french translation for oauthconsentdescription

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/AuthenticationFlowHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/WebAuthnLoginStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/WebAuthnLoginStepTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginPostWebAuthnHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRememberDeviceHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginPostWebAuthnHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRememberDeviceHandlerTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/login/LoginSettings.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/LoginSettingsMongo.java, gravitee-am-ui/src/app/domain/components/login/login-settings.component.html, gravitee-am-ui/src/app/domain/components/login/login-settings.component.ts
closes gravitee-io/issues#8506
=> feat(webauthn): add option to remember device for the end-users

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat: implement CSP directives on ManagementAPI

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/web/WebConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSPHandlerFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/XSSHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/XSSHandlerFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/xss/NoXSSHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/xss/XSSHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
=> feat: implement XSS-Protection header

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
Filter is added so that email is not sent if client idp does not match user idp.
**How to test:**
1. Create 1st mongoDB idp and add a user.
2. Create 2nd mongoDB idp without any user.
3. Create an application and use 1st idp to check forgot password is sending email to the user.
4. Now change the application idp to 2nd ipd which does not have any user. 
5. Now use forgot password option and send email to the 1st idp email account.
6. No email should be sent to the user account as the user is not in the 2nd idp and the application is using the 2nd idp.
=> AM-71: fixed forgot password email sent issue

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.0
=> Changelog for AM - 3.19.0

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/ParamUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/AbstractLogoutEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/ParamUtilsTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestEndUserConsentHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseIdTokenHintHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseRequestObjectHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/request/AuthorizationRequestFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/par/impl/PushedAuthorizationRequestServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/InvalidTargetUrlException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java, gravitee-am-ui/src/app/domain/settings/openid/client-registration/settings/settings.component.html
ParamUtils class moved to handler core as it is used by AbstractLogoutEndpoint.
Also added test for ParamUtils class which shows the URLs it can compare.
=>  AM-69: fixed post logout query param issue

gravitee-am-ui/src/app/domain/settings/factors/creation/steps/step2/step2.component.ts, gravitee-am-ui/src/app/domain/settings/factors/factor/factor.component.ts
This change has been lost during the merge of a 3.15.x into 3.18.x
fixes AM-93
=> fix: apply proper filtering on resource for factor configuration

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/AuthenticationFlowHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/WebAuthnLoginStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/WebAuthnLoginStepTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginPostWebAuthnHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRememberDeviceHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginPostWebAuthnHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRememberDeviceHandlerTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/login/LoginSettings.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/LoginSettingsMongo.java, gravitee-am-ui/src/app/domain/components/login/login-settings.component.html, gravitee-am-ui/src/app/domain/components/login/login-settings.component.ts
=> Am 82 merge 3.18.8 into 3.19.1

gravitee-am-resource/gravitee-am-resource-infobip/pom.xml, pom.xml
spring security to 5.5.7
tink to 1.7.0
snakeyaml to 1.31
=> chore: upgrade dependencies

gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicy.java, gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/test/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicyTest.java
fixes AM-94
1. Create a OTPSender factor that use an SMTP Resource
2. Create a EnrollMFA policy in the POST Login flow to enroll the OTPSender factor
3. remove all factors of the user
4. initiate the login flow of the user, the OTP code should be received by email and the MFA challenge page is prompt
5. use the codereceived by email to finalize the login flow
=> fix: make OTP sender enrollment possible using the EnrollMFAPolicy

gravitee-am-model/src/main/java/io/gravitee/am/model/PasswordHistory.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/PasswordHistoryRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPasswordHistoryRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/Auditable.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcPasswordHistory.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringPasswordHistoryRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_20_0/3.20.0-add-password-histories-table.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/JdbcRepositoriesTestInitializer.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordHistoryRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/PasswordHistoryMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/PasswordHistoryRepositoryTest.java
Fixes [AM-55](https://graviteecommunity.atlassian.net/browse/AM-55).
This is just the persistence functionality of password history. I've left the encryption responsibility to the PasswordHistoryService.
All mongo and JDBC repo tests have been successfully run.
=> AM-55-store-password-history-for-user

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.9
=> Changelog for AM - 3.18.9

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.1
=> Changelog for AM - 3.19.1

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/impl/RequestObjectServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/RequestObjectServiceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/OIDCSettings.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/oidc/OIDCSettingsMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DomainRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/openid/PatchOIDCSettings.java, gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts, gravitee-am-ui/src/app/domain/settings/general/general.component.html, gravitee-am-ui/src/app/domain/settings/general/general.component.ts, postman/collections/graviteeio-am-openid-core-request-object-collection.json
also allow to define the restricted values through the UI and not only using DCR
fixes AM-61
=> fix: check the validity of request_uri parameter when it is a URL

gravitee-am-ui/src/app/domain/settings/general/general.component.html, gravitee-am-ui/src/app/domain/settings/general/general.component.ts
After adding a `request_uri` and save the form, then a refresh of the page keep the content of the `request_uris `
=> AM-61 fix UI refresh issue

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.15.14
=> Changelog for AM - 3.15.14

gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.ts, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts
=> AM-131 Fix UI error validation and messages

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.10
=> Changelog for AM - 3.18.10

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/pom.xml, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/PasswordHistoryHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/password-validation-v2.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/PasswordHistoryHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-ui/src/assets/js/password-validation-v2.js, pom.xml
Fixes [AM-57](https://graviteecommunity.atlassian.net/browse/AM-57)
Checking passwords against a user's history via the gateway reset form requires communication with the `PasswordHistoryService`. To that end, I've added a new gateway handler and some calling code in `reset_password.html`.
Password already in history. Can't submit:
<br>
Password not in history, submit ok:
=> AM-57-alternate

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.2
=> Changelog for AM - 3.19.2

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/OrganizationUserServiceTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/PasswordHistoryRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPasswordHistoryRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringPasswordHistoryRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordHistoryRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/PasswordHistoryRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordHistoryService.java, gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/impl/PasswordHistoryServiceTest.java
Fixes [AM-78](https://graviteecommunity.atlassian.net/browse/AM-78)
Added password history deletion step to `AbstractUserService` and SCIM user service delete methods.
=> Am 78 clean history on delete action

docs/self-service-account-api-descriptor.yml, gravitee-am-common/src/main/java/io/gravitee/am/common/exception/authentication/AuthenticationException.java, gravitee-am-common/src/main/java/io/gravitee/am/common/exception/mfa/InvalidCodeException.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/ErrorHandler.java
=> fix(account): verify MFA code for every OTP based factors and not only the PENDING_ACTIVATION ones

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/CertificateEntity.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/CertificatesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/CertificatesResourceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/Certificate.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcCertificateRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcCertificate.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_20_0/3.20.0-update-certificates-table.yml, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCertificateRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/CertificateMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/CertificateRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/CertificateTimeComparator.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/utils/CertificateTimeComparatorTest.java, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.html, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.scss, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts
1. If the certificate name is truncated, (can happen on 15" screen), the complete value is display when the mouse move over the name.
2. If the latest System certificate is deleted, the "renewed" icon is removed to the previous one
Before certificate deletion:
After cert deletion
3. the number of applications on which the certificate is assgined is displayed
=> AM-154 improve Certificate Rotation UI

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java
=> fix(account): increment moving factor for the MFA factors

docs/self-service-account-api-descriptor.yml, gravitee-am-common/src/main/java/io/gravitee/am/common/exception/mfa/SendChallengeException.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/util/AccountRoutes.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java
=> feat(account): add MFA sendChallenge method

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.11
=> Changelog for AM - 3.18.11

gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json, gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/components/navbar/navbar.component.html, gravitee-am-ui/src/app/components/navbar/navbar.component.ts, gravitee-am-ui/src/app/components/sidenav-settings/sidenav-settings.component.scss, gravitee-am-ui/src/app/domain/applications/applications.component.html, gravitee-am-ui/src/app/domain/settings/audits/audits.component.html, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.html, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.scss, gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.html, gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.scss, gravitee-am-ui/src/app/domain/settings/roles/roles.component.html, gravitee-am-ui/src/app/domain/settings/scopes/scopes.component.html, gravitee-am-ui/src/app/settings/domains/domains.component.html, gravitee-am-ui/src/styles.scss
=> fix(ui): fix some UI issues since the gio-menu component integration

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.12
=> Changelog for AM - 3.18.12

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/EnterpriseUser.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/GraviteeUser.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/User.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/AbstractUserEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UserEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UsersEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapperTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/users/CreateUserEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/users/PatchUserEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/users/UpdateUserEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
=> fix(scim): add an extension resource schema to manage custom claims

gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java, gravitee-am-model/src/main/java/io/gravitee/am/model/scim/Address.java, gravitee-am-model/src/main/java/io/gravitee/am/model/scim/Attribute.java
=> fix(customClaims): add more user information attributes in the execution context

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/ParamUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordSubmissionEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationSubmissionEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterSubmissionEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordSubmissionEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationSubmissionEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterSubmissionEndpointTest.java
=> AM-140 propagate parameters to the registration callback

gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json, gravitee-am-ui/src/app/app.module.ts, gravitee-am-ui/src/app/components/navbar/navbar.component.html, gravitee-am-ui/src/app/components/navbar/navbar.component.scss, gravitee-am-ui/src/app/components/navbar/navbar.component.ts, gravitee-am-ui/src/app/components/sidenav/sidenav.component.scss, gravitee-am-ui/src/styles.scss
=> feat(ui): integrate gio-top-bar component

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_20_0/3.20.0-add-password-histories-table.yml, gravitee-am-test/api/management/apis/AlertsApi.ts, gravitee-am-test/api/management/apis/ApplicationApi.ts, gravitee-am-test/api/management/apis/AuditApi.ts, gravitee-am-test/api/management/apis/BotDetectionApi.ts, gravitee-am-test/api/management/apis/DefaultApi.ts, gravitee-am-test/api/management/apis/DeviceIdentifierApi.ts, gravitee-am-test/api/management/apis/DeviceIdentifiersApi.ts, gravitee-am-test/api/management/apis/DevicesApi.ts, gravitee-am-test/api/management/apis/DomainApi.ts, gravitee-am-test/api/management/apis/EmailApi.ts, gravitee-am-test/api/management/apis/FlowApi.ts, gravitee-am-test/api/management/apis/FormApi.ts, gravitee-am-test/api/management/apis/IdentityProviderApi.ts, gravitee-am-test/api/management/apis/ResourceApi.ts, gravitee-am-test/api/management/apis/UserApi.ts, gravitee-am-test/api/management/models/ApplicationResource.ts, gravitee-am-test/api/management/models/ClientRegistrationSettings.ts, gravitee-am-test/api/management/models/Domain.ts, gravitee-am-test/api/management/models/DomainResource.ts, gravitee-am-test/api/management/models/EnvironmentResource.ts, gravitee-am-test/api/management/models/OrganizationResource.ts, gravitee-am-test/api/management/models/User.ts, gravitee-am-test/api/management/models/UserEntity.ts, gravitee-am-test/specs/gateway/reset-password.jest.spec.ts, gravitee-am-test/specs/management/password-history.jest.spec.ts
Fixes [https://gravitee.atlassian.net/browse/AM-129](AM-129)
Tests for both the Management and Gateway reset password endpoints. Feel free to ignore the generate api `ts` files; the tests to review are `reset-password.jest.spec` and `password-history.jest.spec`.
=> Am 129 password history jest testing

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.3
=> Changelog for AM - 3.19.3

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/audit/impl/AuditReporterManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/factor/impl/FactorManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/impl/FlowManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/authdevice/notifier/impl/AuthenticationDeviceNotifierManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/botdetection/impl/BotDetectionManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/deviceidentifiers/DeviceIdentifierManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/form/impl/FormManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/resource/impl/ResourceManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/impl/ExtensionGrantManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java, gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/test/java/io/gravitee/am/gateway/services/sync/SyncManagerTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/manager/form/impl/FormManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/manager/idp/impl/IdentityProviderManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditReporterManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java
test last update date for plugin instances to avoid multiple reload of the plugin in case of multiple event processing
fixes AM-59
=> fix: introduce a timeframe for synchronization process

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/password-validation-v2.js
Fixes [AM-201](https://gravitee.atlassian.net/browse/AM-201)
=> AM-201-forgot-password-set-new-password-button-greyed-out

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.15.15
=> Changelog for AM - 3.15.15

docker/compose/config/nginx.conf, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequestTest.java
=> AM-139 manage X-Forwarded-Port

gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts, gravitee-am-ui/src/app/domain/settings/general/general.component.ts
=> AM-49 trim urls before sending them to the backend

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-login-v3.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-register-v3.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_register.html, gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html
=> fix(webauthn): add default latency to fix potential blocked iOS applications (iOS 15.x)

gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/grantFlows/application-grant-flows.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/grantFlows/application-grant-flows.component.ts
=> fix(app): add inputs to register either the client jwks_uri or jwks values

.circleci/workflows.yml
=> chore(CI): Trigger rpm & docker images when release

.circleci/workflows.yml, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/FactorResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/FactorsResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ServiceResourceResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ServiceResourcesResource.java, gravitee-am-test/api/commands/management/factor-management-commands.ts, gravitee-am-test/api/commands/management/resource-management-commands.ts, gravitee-am-test/api/commands/management/service/utils.ts, gravitee-am-test/api/management/apis/FactorApi.ts, gravitee-am-test/api/management/apis/ResourceApi.ts, gravitee-am-test/api/management/models/AccountSettings.ts, gravitee-am-test/package-lock.json, gravitee-am-test/specs/gateway/mfa.jest.spec.ts
MFA enrol, rate limit, brute force, recovery code tests added
=> MFA integration tests added

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.13
=> Changelog for AM - 3.18.13

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/http/WebClientBuilderTest.java
=> feat(httpClient): add SSL options

gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/grantFlows/application-grant-flows.component.ts
=> fixup(ui): better management of jwks invalid format

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginEndpoint.java
Similar cookie structure is returned regardless user exists or not
=>  AM-191: updated cookie structure

gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json, gravitee-am-ui/src/app/components/navbar/navbar.component.scss, gravitee-am-ui/src/app/components/sidenav/sidenav.component.html, gravitee-am-ui/src/app/components/sidenav/sidenav.component.ts
=> fix(ui): apply latest UX/UI recommendations for the sidenav and topnav components

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.15.16
=> Changelog for AM - 3.15.16

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java
=> AM-43 diplay error page in case of attestation exception

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.4
=> Changelog for AM - 3.19.4

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
=> fix: Test if fromNameis null before sending email [AM-246]

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/AuthorizationCodeResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/AuthorizationResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/HybridResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/IDTokenResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/ImplicitResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
=> AM-236 encode state parameters when redirect is done on the callback url

.circleci/workflows.yml
=> feat(CI): add slack announcement after release

gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSAMLSettings.java, gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationSAMLSettingsMongo.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSAMLSettings.java, gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.ts
=> feat(saml2): add option to sign SAML assertions and SAML response at SP level

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.14
=> Changelog for AM - 3.18.14

.circleci/workflows.yml
=> fix(CI): initialize docker context

.circleci/workflows.yml
=> fix(CI): add push when build image

.circleci/workflows.yml
=> fix(CI): add push when buildx for ACR

.circleci/workflows.yml
=> fix(CI): Remove cp run.sh for ui image

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeAlternativesEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeAlternativesEndpointTest.java
=> fix: do not use emptyList as Thymeleaf engine [AM-347]

.circleci/workflows.yml, gravitee-am-test/specs/gateway/login-flow.jest.spec.ts
Added jest tests when users use common property [email] during sign in process
=> AM-18 login flow multiple user

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
Client check is not necessary while updating a user from management.
This check throws exception in case client is deleted.
Hence removed the check and the tests
=>  AM-46: removed client check for user update

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.5
=> Changelog for AM - 3.19.5

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
=> fix: Check target value before enrolling factor [AM-259]

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/email/EmailValidatorImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/EmailValidatorTest.java
=> fix: update the max length of TLD [AM-45]

gravitee-am-service/src/main/java/io/gravitee/am/service/exception/InvalidWebAuthnConfigurationException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java, gravitee-am-ui/src/app/domain/settings/webauthn/webauthn.component.html
Validation added to make sure origin in not null or blank
=>  AM-133: added webauthn validation

gravitee-am-test/package-lock.json, gravitee-am-test/package.json, gravitee-am-test/specs/gateway/mfa.jest.spec.ts
Fixes [AM-180](https://gravitee.atlassian.net/browse/AM-180)
Added MFA TOTP using a "virtual' authenticator to generate codes.
[AM-180]: https://gravitee.atlassian.net/browse/AM-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Am 180 mfa with totp and email

.circleci/workflows.yml
=> chore(CI): fetch slack token from KSM

.circleci/workflows.yml
This PR notifies success when the build passes
=> fix(ci): notify when the release passes only

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
Co-authored-by: aurelien-pacaud <aurelien.pacaud@graviteesource.com>
https://github.com/gravitee-io/issues/issues/8766
This PR handles updating the state of the factor when challenge is complete.
Look at the issue above.
In the end the Factor after challenge must be in ACTIVATED state
=> fix: set factor to activated everytime challenge is triggered and valid

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.15
=> Changelog for AM - 3.18.15

.circleci/workflows.yml
Remove simple quote to fix docker tags generation
=> chore(CI): fix docker tags

.circleci/workflows.yml
This PR fixes the path naming in the AM full distribution to be consistent with previous releases
=> fix: full distribution path naming

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts, gravitee-am-ui/src/app/services/organization.service.ts, gravitee-am-ui/src/app/services/user.service.ts
Modify user profile form to allow username update (https://gravitee.atlassian.net/browse/AM-381)
- Login to AM console
- Go to `Settings > Users`
- Choose a user to edit
- An input allows you to edit the username according to your rights
or
- Login to AM console
- Go to `Organization > Users`
- Choose a user to edit
- An input allows you to edit the username according to your rights
=> feat(ui): username can be updated from UI

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.6
=> Changelog for AM - 3.19.6

docker/enterprise/am/3.x/gateway/Dockerfile, docker/enterprise/am/3.x/gateway/Dockerfile-nightly, docker/enterprise/am/3.x/management-api/Dockerfile, docker/enterprise/am/3.x/management-api/Dockerfile-nightly, docker/gateway/Dockerfile, docker/gateway/Dockerfile-dev, docker/gateway/Dockerfile-nightly, docker/management-api/Dockerfile, docker/management-api/Dockerfile-dev, docker/management-api/Dockerfile-nightly, docker/management-ui/Dockerfile, docker/management-ui/Dockerfile-dev, docker/management-ui/Dockerfile-nightly
[## :id: Reference related issue. ](https://gravitee.atlassian.net/browse/AM-440)
Create a user in our Dockerfile.
https://www.tenable.com/audits/items/CIS_Docker_v1.3.1_L1_Docker_Linux.audit:bdcea17ac365110218526796ae3095b1
=> feat(Dockerfile): Switch to non root user as docker image

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/pom.xml, pom.xml
https://gravitee.atlassian.net/browse/AM-444
This PR bumps the protobuf dependency used within google tink
run `mvn depedency:tree` and verify it is set to the mentioned version
=> chore(deps): bump java protobuf dependency

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParser.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParserTest.java
Email value can contain apostrophe.
Hence the character is removed from special char set.
=> AM-174: apostrophe character allowed as value

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
=> fix: typo?

gravitee-am-ui/src/app/app-routing.module.ts
[AM-451](https://gravitee.atlassian.net/browse/AM-451)
[AM-451]: https://gravitee.atlassian.net/browse/AM-451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: login menu entry of 'Settings' displayed

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.18.16
=> Changelog for AM - 3.18.16

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenServiceTest.java
=> fix(oauth2): respond with invalid_grant when refresh token is invalid

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackDeviceIdHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login_callback_device_identifier.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackDeviceIdHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandlerTest.java
closes AM-452
closes gravitee-io/issues#8137
=> feat(mfa): manage remember device with external IdP

gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/api/FactorProvider.java, gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/api/OTPFactorProvider.java, gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/utils/HOTP.java, gravitee-am-factor/gravitee-am-factor-api/src/test/java/io/gravitee/am/factor/api/OTPFactorProviderTest.java, gravitee-am-factor/gravitee-am-factor-email/src/main/java/io/gravitee/am/factor/email/provider/EmailFactorProvider.java, gravitee-am-factor/gravitee-am-factor-email/src/test/java/io/gravitee/am/factor/email/provider/EmailFactorProviderTest.java, gravitee-am-factor/gravitee-am-factor-sms/src/main/java/io/gravitee/am/factor/sms/SMSFactorConfiguration.java, gravitee-am-factor/gravitee-am-factor-sms/src/main/java/io/gravitee/am/factor/sms/provider/SMSFactorProvider.java, gravitee-am-factor/gravitee-am-factor-sms/src/main/resources/schemas/schema-form.json, gravitee-am-factor/gravitee-am-factor-sms/src/test/java/io/gravitee/am/factor/sms/provider/SMSFactorProviderTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/resource/impl/ResourceManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java, gravitee-am-resource/gravitee-am-resource-api/src/main/java/io/gravitee/am/resource/api/Message.java, gravitee-am-resource/gravitee-am-resource-api/src/main/java/io/gravitee/am/resource/api/MessageChannel.java, gravitee-am-resource/gravitee-am-resource-api/src/main/java/io/gravitee/am/resource/api/MessageResourceProvider.java
=> feat(resources): support new type of Resource for sending only messages

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/endpoint/ErrorEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginSSOPOSTEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginNegotiateAuthenticationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/view/thymeleaf/GraviteeThymeleafTemplateEngine.java
https://gravitee.atlassian.net/browse/AM-463
=> fix: use render instead of rxRender

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RiskAssessmentService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/utils/RiskAssessmentServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/risk/RiskAssessmentHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/risk/RiskAssessmentHandlerTest.java
https://gravitee.atlassian.net/browse/AM-488
The fix handles subscription handling on geoip and risk assessment better.
Regular regression testing of risk-assessment and geoip features (MFA, Alerting)
=> fix: risk assessment handler subscribe handling

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/AbstractEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginCredentialsEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterCredentialsEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnResponseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/consent/UserConsentEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/GraviteeVerticle.java
https://gravitee.atlassian.net/browse/AM-194
=> fix: use onsuccess/onerror mechanism of subscribe

pom.xml
https://gravitee.atlassian.net/browse/AM-489
Upgrade jetty to the latest dependency 
Regular regression testing
=> fix: override gravitee bom jetty version

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.7
=> Changelog for AM - 3.19.7

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
Fix after the merge regarding FIDO2 from 3.19.x
=> fix: return after fido2 execution in mfa challenge

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.20.2
=> Changelog for AM - 3.20.2

pom.xml
https://gravitee.atlassian.net/browse/AM-506
related PR: https://github.com/gravitee-io/gravitee-access-management/pull/2482
=> fix: license INFO logging level enforced

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_21_0/3.21.0-index-upper-username-source.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
https://gravitee.atlassian.net/browse/AM-510
This PR enhances the performance of search by username and source
=> fix: add index on upper username and source for users

gravitee-am-management-api/gravitee-am-management-api-rest/pom.xml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/assembly/distribution.xml, gravitee-am-spring-web/pom.xml, pom.xml
This PR aims to bring spring-web dependencies into its own separate project
=> fix: separate spring-web dependencies in another project

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.8
=> Changelog for AM - 3.19.8

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java
The log level change will affect for expired JWT token only.
=> fix: changed log level from error to debug

.circleci/workflows.yml
This PR aims to change the values.yml file to target to the one prior 3.21.x
=> chore: change helm values

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.20.3
=> Changelog for AM - 3.20.3

gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/Claims.java, gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenServiceTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/test/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProviderTest_idToken.java
https://gravitee.atlassian.net/browse/AM-536
note: still in draft to bring proper testing to this use case
=> fix: exclude time based claims from the ID_token

.mergify.yml
https://gravitee.atlassian.net/browse/AM-533
This PR adds mergify configuration to the repository
=> chore: add mergify configuration

CHANGELOG-v3.adoc
Generate changelog for version AM - 3.19.9
=> Changelog for AM - 3.19.9

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/model/FilteredIdentityProviderInfo.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/IdentityProvidersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/idps/IdentityProvidersResource.java, pom.xml
https://gravitee.atlassian.net/browse/AM-539
This PR merges the 3.18.17 into 3.19.x
=> chore: merge 3.18.7 into 3.19.x

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CSRFHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSession.java
https://gravitee.atlassian.net/browse/AM-573
If a user opens two tabs at the same time and tries to log-in into one tab, he get an error "session expired"
Open two tabs and try to log-in into one of these tabs. The user will be able to access the application without error
=> fix: multi tab session expired

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/client/ClientSyncService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/client/impl/ClientSyncServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/client/ClientSyncServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
https://gravitee.atlassian.net/browse/AM-670
=> fix: find by client_id also when verifying jwt

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterSuccessEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_register_success.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterSuccessEndpointTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/webauthn_register_success.html, gravitee-am-reporter/gravitee-am-reporter-api/src/main/java/io/gravitee/am/reporter/api/Reporter.java
https://gravitee.atlassian.net/browse/AM-661
=> fix: handle webauthn device name character size

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RoutingContextHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/GraviteeVertxHttpServerRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/PolicyChainHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/core/http/GraviteeVertxHttpServerRequestTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/AbstractEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeAlternativesEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/mfa/MFAChallengeUserHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/mfa/MFAChallengeUserHandlerTest.java
=> feat(mfa): adapt code to support the MFA challenge policy

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/AM-687
refers to: https://github.com/gravitee-io/gravitee-access-management/pull/2742
=> fix: adapt helm charts to 3.21

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/AM-687
This PR adapts helm chart environment deploy for the 4.0.0
=> fix: adapt helm charts to 4.0.0

gravitee-am-common/src/main/java/io/gravitee/am/common/password/PasswordSaltFormat.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/spring/JdbcAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/spring/MongoAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json, gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/MessageDigestPasswordEncoder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/MD5PasswordEncoderTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/MessageDigestPasswordEncoderTest.java
=> feat(password): add new option to specify the password salt format

.circleci/workflows.yml
This PR fixes the wrong uses of the values file for 3.21.x
=> fix(helm): use the correct maintenance file

.gitignore, release/ci-steps/doc-new-release-notes.mjs, release/helpers/changelog-helper.mjs
N/A
Fix the changelog generation script to be in line with the content of `CHANGELOG-v3`
=> chore: fix changelog script

.mergify.yml
This PR brings mergify for 4.0.x
=> chore: add 4.0.x mergify

docker/management-ui/Dockerfile, docker/management-ui/Dockerfile-dev, docker/management-ui/Dockerfile-nightly, docker/management-ui/config/conf.d/constants.json.toml, docker/management-ui/config/conf.d/default.conf.toml, docker/management-ui/config/constants.json, docker/management-ui/config/default.conf, docker/management-ui/config/templates/constants.json.tmpl
This PR bumps the management ui base Docker image
=> chore: update management-ui files

.circleci/workflows.yml
N/A
Stop creating EE tags for docker images
Nothing to test
No UI
It's a breaking change to be documented in the new documentation website
@gravitee-io/am
=> Stop creating EE tags for docker images

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceImplTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/EmailServiceImplTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/EmailServiceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/EmailService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/CompositeDictionaryProvider.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/DomainBasedDictionaryProvider.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/DynamicDictionaryProvider.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/GraviteeMessageResolver.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/ThreadLocalDomainDictionaryProvider.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EmailServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/CompositeDictionaryProviderTest.java
=> fix: use domain i18n dictionaries for emails

gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProvider.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
fix AM-602
Addition of new debug logs
=> fix: add debug logs into HttpDeviceNotifier

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/LicenseResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/PlatformResource.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/GraviteeLicense.java
https://gravitee.atlassian.net/browse/APIM-1685
=> Plugins cta

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml, pom.xml
=> fix: add EE plugins in the default bundle

gravitee-am-ui/src/app/components/gio-license/gio-license.service.ts
=> fix: remove useless configuration for SMTP as it is not an EE plugin

gravitee-am-ui/src/app/components/gio-license/gio-license.service.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts, gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.ts
https://gravitee.atlassian.net/browse/AM-729
=> fix: use good plugin name for SAML2.0

.circleci/workflows.yml
release process should not be like a chocolate box...
to discover a new taste after each run 😅
=> build(release): do not update dependencies automaticaly during the release process

gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java, gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/test/java/io/gravitee/am/management/services/sync/SyncManagerTest.java
=> fix: avoid NullPointer during ManagementAPI sync process

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-4.0.0/CHANGELOG-v3.adoc)
[See all Jira issues for 4.0.0 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%204.0.0%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 4.0.0 release

helm/Chart.yaml
Surround special char in the chart.yaml
=> fix(helm): surround special char with quote

gravitee-am-repository/gravitee-am-repository-mongodb-api/pom.xml, pom.xml
=> fix: remove test scope for the async-io/mysql r2dbc driver

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/PolicyChainHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/FactorNotFoundException.java, pom.xml
=> chore: upgrade gravitee node to manage the MFA challenge policy

pom.xml
This PR bump plugins to current versions
=> chore: bump plugins from alpha to ga

gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/app.component.ts, gravitee-am-ui/src/app/components/submenu/submenu.component.html, gravitee-am-ui/src/app/components/submenu/submenu.component.scss, gravitee-am-ui/src/app/components/submenu/submenu.component.ts, gravitee-am-ui/src/app/domain/domain.component.scss, gravitee-am-ui/src/app/domain/settings/audits/audit/audit.component.html, gravitee-am-ui/src/app/newsletter/newsletter.component.scss, gravitee-am-ui/src/app/settings/domains/domains.component.html, gravitee-am-ui/src/app/settings/domains/domains.component.scss, gravitee-am-ui/src/app/settings/management/general/general.component.html, gravitee-am-ui/src/app/settings/management/management.component.html, gravitee-am-ui/src/app/settings/management/management.component.scss, gravitee-am-ui/src/app/settings/settings.component.html, gravitee-am-ui/src/app/settings/settings.component.scss, gravitee-am-ui/src/styles.scss
=> feat(ui): integrate new organization menu

pom.xml
This PR bumps guava to the latest version available
=> chore: bump guava to latest

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/factor/EnrolledFactorChannel.java
=> feat(mfa): adapt code to support extension phone number

pom.xml
Also update twilio resource version
=> AM-685: upgrade twilio resource in distribution

.circleci/workflows.yml
Before the fix:
```
git diff -w
diff --git a/helm/Chart.yaml b/helm/Chart.yaml
index 27ce13ecb..29a2f8e5c 100644
--- a/helm/Chart.yaml
+++ b/helm/Chart.yaml
@@ -1,9 +1,9 @@
apiVersion: v1
name: am
-# When the version is modified, make sure the artifacthub.io/changes list is updated
+# When the version: 3.21.6
version: 3.21.5
-appVersion: 3.21.5
+appVersion: 3.21.6
description: Official Gravitee.io Helm chart for Access Management
home: https://gravitee.io
sources:
```
After the fix:
```
git diff -w
diff --git a/helm/Chart.yaml b/helm/Chart.yaml
index 27ce13ecb..e17d4ce1a 100644
--- a/helm/Chart.yaml
+++ b/helm/Chart.yaml
@@ -2,8 +2,8 @@ apiVersion: v1
name: am
-version: 3.21.5
-appVersion: 3.21.5
+version: 3.21.6
+appVersion: 3.21.6
description: Official Gravitee.io Helm chart for Access …
```
=> fix(CI): in job-release_helm fix sed command to update Chart.yml

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractMongoRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractManagementMongoRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/AbstractOAuth2MongoRepository.java
=> fix: make index creation optional in mongo repository layer

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/groups/GroupsEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/GroupService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/GroupServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/groups/GroupsEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/GroupServiceTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/GroupRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/AbstractDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MsSqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MySqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/PostgresqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/ScimSearch.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcGroupRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcOrganizationUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelperTest.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoGroupRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/GroupRepositoryTest.java
The easiest way would be to use existing Postman SCIM collection.
1. Follow the steps and create a couple users and groups.
2. Add users to a group [we have Patch group - add operation]
3. In the Postman `List` folder we have `List Groups` which lists all the groups.
4. Add a new GET request such as `{{gateway_url}}/{{domainHrid}}/scim/Groups?filter=displayName eq "Tour Guides"` should return only the mentioned group.
Please check with any JDBC as well if possible.
=> AM-766 SCIM group endpoint filter

gravitee-am-ui/src/app/components/json-schema-form/material-file.component.ts
Please follow the steps in the jira ticket to test this fix
=> AM-777: fixed disabled create button issue

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
regression introduced by AM-685
fixe AM-769
fixe AM-767
fixe AM-768
fixe AM-813
=> fix(reg): set the registrationCompleted on user update

helm/Chart.yaml, helm/templates/api/api-ingress.yaml, helm/templates/api/api-technical-ingress.yaml, helm/templates/gateway/gateway-ingress.yaml, helm/templates/gateway/gateway-technical-ingress.yaml, helm/templates/ui/ui-ingress.yaml, helm/tests/api/ingress_technical_test.yaml, helm/tests/api/ingress_test.yaml, helm/tests/gateway/ingress_technical_test.yaml, helm/tests/gateway/ingress_test.yaml, helm/tests/ui/ingress_test.yaml
linked to https://gravitee.atlassian.net/browse/APIM-2736
DEVOPS-202 > DEVOPS-205
Allow usage of ingress wildcard.
Without quote, the use of '*' in the ingress host cause an yaml issue
@see helm unit test.
=> feat(helm): allow ingress host wildcard

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcAlertTriggerRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/AlertTriggerRepositoryTest.java
=> fix: execute the delete notifier linked to the alert trigger

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/AbstractDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelperTest.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParser.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Sample search query to test:
meta.loggedAt eq "2023-09-25T08:21:52.591Z"
meta.created gt "2023-09-26T08:33:45.000Z"
meta.mfaEnrollmentSkippedAt gt "2023-09-26T08:33:45.000Z"
meta.lastPasswordReset gt "2023-09-26T08:33:45.000Z"
=> AM-665: added searh fields

.gitignore, release/ci-steps/doc-new-release-notes.mjs, release/helpers/changelog-helper.mjs, release/helpers/jira-helper.mjs
The update enhances the changelog generation process in multiple ways. Firstly, it uses the new documentation website and ensures that directory and branch names follow a more uniform naming pattern. Also, it optimizes how the changelog information is extracted from Jira by filtering out irrelevant issues and fetching additional details, enhancing the document's content. Temporary files used in the process are now being stored in a local '.tmp' folder, which is ignored by Git, keeping the repository clean.
Cherry-pick of 074895e0b
=> chore: update changelog generation process

helm/Chart.yaml, helm/templates/extra-manifests.yaml, helm/tests/extra-manifests_test.yaml, helm/values.yaml
Allow users to define extra manifests
=> feat(helm): Allow users to define extra manifests

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
=> fix: improve mongo script to recreate indexes

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
=> fix: add commitQuorum value and fix usename unique constraint definition

docs/upgrades/username_uniqueness/username_uniqueness.js
fixes AM-942
Manage Organization duplicate during execution of migration script.
This update only manage cockpit users and organization users created with the default gravitee ognization user idp
=> fix: manage migration of OrganizationUsers duplicates

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/liquibase/UsernameUniquenessMigration.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_19_21/3.19.21-alter-org_users_username_unique.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_19_21/3.19.21-migrate-users_username_unique.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
=> fix: addition of custom liquibase script to migrate duplicate username.

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java
fixes gravitee-io/issues#9230
fixes AM-829
=> fix(idp-manager): do not stop the management API if an IdP plugin is missing or unknown

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/GraviteeVertxHttpServerRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/dummies/DummyHttpRequest.java, gravitee-am-ui/package-lock.json, pom.xml
fixe AM-964
fixe AM-947
fixe AM-946
fixe gravitee-io/issues#9313
fixe gravitee-io/issues#9310
fixe gravitee-io/issues#9308
=> chore: upgrade gravitee BOM to 6.0.14

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
Proposal to fill the doc about CSP configuration when reportOnly is true.
=> docs: add comment about csp configuration when reportOnly is true

pom.xml
=> chore: upgrade jetty from 9.4.44 to 9.4.53

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/password-validation-v3.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/assets/preview/js/password-validation-v3.js, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html
fixes AM-873
gravitee-io/issues#9276
=> fix: make confirmRegistration work when password history is enabled

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/resource/impl/ResourceManagerImpl.java
this is useful to load all valid plugins
AM-1014
gravitee-io/issues#9344
=> fix: catch exceptionn during Resource creation

pom.xml
=> chore: bump ldap idp version

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
**How To Test**
Steps are written in the JIRA issue
=> AM-1013 email verification disable confirm

gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json, gravitee-am-ui/src/app/domain/applications/application/design/flows/flows.component.html, gravitee-am-ui/src/app/domain/applications/application/design/flows/flows.component.ts
https://gravitee.atlassian.net/browse/AM-1012
=> fix: validate policy form before save

pom.xml
=> chore: bump france-connect idp version

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/code/AuthorizationCodeServiceTest.java, gravitee-am-performance/src/test/scala/io/gravitee/am/performance/BasicLoginFlow.scala, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/api/AuthorizationCodeRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAuthorizationCodeRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAuthorizationCodeRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/AuthorizationCodeRepositoryTest.java
fixe AM-837
gravitee-io/issues#9238
=> fix: refactor JdbcAuthorizationCodeRepository to avoid Deadlock error

pom.xml
AM-1057
gravitee-io/issues#9382
=> chore: bump france connect version

gravitee-am-service/src/main/java/io/gravitee/am/service/validators/password/impl/DefaultPasswordValidatorImpl.java
=> fix: remove escape character added by the IDE

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/assertion/impl/ClientAssertionServiceImpl.java
fixes AM-1072
gravitee-io/issues#9393
=> fix: keep the SAML protocol info into the session on callbak failure

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DomainResource.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchDomain.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchPasswordSettings.java, gravitee-am-service/src/test/java/io/gravitee/am/service/model/PatchDomainTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/model/PatchPasswordSettingsTest.java, gravitee-am-ui/build.json, gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts
=> AM-52: reset password policy settings

gravitee-am-service/pom.xml, gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/PBKDF2PasswordEncoder.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationClientSecretService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/spring/application/SecretHashAlgorithm.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/AbstractPasswordEncoderTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/MessageDigestPasswordEncoderTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/PBKDF2PasswordEncoderTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/SHAMD5PasswordEncoderTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/jmh/EncoderBenchmark.java
fixes AM-1050
fixes AM-1071
related-to AM-1047
=> AM-1050 Implement PBKDF2 for client secret

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/geoip/GeoIpHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/error/AsyncErrorCollector.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/geoip/GeoIpHandlerTest.java
=> AM-699: Manage error when GeoIp service is not deployed

helm/CHANGELOG.md, helm/Chart.yaml, helm/README.adoc, helm/README.md, helm/templates/api/api-configmap.yaml, helm/templates/gateway/gateway-configmap.yaml, helm/tests/api-configmap_test.yaml, helm/tests/gateway-configmap_test.yaml, helm/values.yaml
related-to AM-1047
fixes AM-1171
=> chore: addition of client secret hash settings into the helm chart

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java
fixes AM-1187
gravitee-io/issues#9427
=> fix: exclude null value from scim UserMapper

gravitee-am-common/src/main/java/io/gravitee/am/common/exception/oauth2/RedirectMismatchException.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/RedirectUriValidationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/par/impl/PushedAuthorizationRequestServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/par/PushedAuthorizationRequestServiceTest.java
=> fix: Evaluate the redirect_uri at each step of the auth flow

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/GroupMembersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/groups/GroupMembersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
=> AM-690: fix unable to list users

pom.xml
fixes AM-1134
fixes AM-1135
fixes AM-1127
fixes AM-1128
=> chore: upgrade logback to 1.4.14

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/LicenseResource.java, pom.xml
https://gravitee.atlassian.net/browse/ARCHI-278
This PR adapts the existing code to rely on `LicenseManager` and prepares for changes to support organization licenses.
=> refactor: move to LicenseManager

pom.xml
=> chore: upgrade AM account-linking & mfa-challenge policies

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java
=> fix: prevent to override factor enrollment

gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html
=> fix: provide the right parameters for an authorization_code flow

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java
=> fix: revert change that introduce regression

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/AM-13
=> AM-13: sync every 1 sec

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/ConditionalBodyHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/ConditionalBodyHandlerTest.java
fixes AM-1022
gravitee-io/issues#9352
=> fix: bypass BodyHandler on GET method

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java
Added codes in the step classes instead of the filter chain.
=> AM-1141: replaced MfaFilterChain

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/AM-1239
=> AM-1239: sonar pipeline java error fix

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java, gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/test/java/io/gravitee/am/management/services/sync/SyncManagerTest.java
https://gravitee.atlassian.net/browse/AM-1219
before
after
=> AM-1219: fix sync duplicated events

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java, gravitee-am-ui/src/app/domain/settings/certificates/certificate/certificate.component.ts, gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.ts, gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step2/step2.component.ts
https://gravitee.atlassian.net/browse/AM-1136
On error certificate upload 
Figma link
https://www.figma.com/file/G8qMgrmF337QCSzfAcca9B/AM-Certificates?type=design&node-id=4-378&mode=design&t=qpLvhAbFjW1ZNa4L-0
=> AM-1136: update certificate error messages

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
Fixed incorrect event type in between enrollment and challenge
This fix is for both AM-1243 and AM-1244
=> am-1243-fix-audit-log-event

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/handler/impl/ClientAuthHandlerImpl.java
fixes AM-1213
related-to AM-1114
=> fix: initialize the domainId when client is missing

pom.xml
fixes AM-1250
fixes AM-1251
fixes AM-1252
fixes AM-1253
fixes AM-1256
fixes AM-1257
=> chore: upgrade JSON-PATH from 2.8.0 to 2.9.0

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/JWTAuthenticationFilter.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/security/ManagementAuthenticationProvider.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java
fixes am-2133
gravitee-io/issues#9476
=> fix: apply timeout on blockingGet made in the REST API

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/ParamUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/ParamUtilsTest.java, postman/collections/graviteeio-am-oauth2-par-version.json
fixes AM-2134
gravitee-io/issues#9478
=> fix: evaluate PAR parameters from the AuthenticationFlowContext

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RoutingContextHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/PolicyChainHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java, pom.xml
=> fix(context): add missing MFA enrollment context attributes for the new version of the MFA Challenge policy

gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json
https://gravitee.atlassian.net/browse/AM-1091
https://gravitee.atlassian.net/browse/AM-2140
=> AM-1091: update particles

gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json, gravitee-am-ui/src/app/domain/settings/certificates/certificate/form/form.component.ts, gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.ts, gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step2/step2.component.ts
Main story:
https://gravitee.atlassian.net/browse/AM-1136
bugs:
https://gravitee.atlassian.net/browse/AM-2135
https://gravitee.atlassian.net/browse/AM-2136
On certificate upload error:
Upload valid certificate after the error:
=> AM-2135 AM-2136: update ajsf, fix on error certificate form

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/AuthorizationCodeResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/AuthorizationResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/HybridResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/IDTokenResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/ImplicitResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/jwt/JWTAuthorizationResponse.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/vertx/RequestUtils.java
this help to manage the form_post response_mode
fixes AM-763
gravitee-io/issues#9179
=> fix: create a method to get direct access to authorize response params

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2Request.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenEnhancerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenEnhancerTest.java
https://gravitee.atlassian.net/browse/AM-1209
=> AM-1209: invalid scope when try to generate id token without user

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/AM-2154
=> AM-2154: downgrade images

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnAuthenticatorIntegrity.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnAuthenticatorIntegrityTest.java
https://gravitee.atlassian.net/browse/AM-1004
lastCheckedAt property should be updated only when specified "max age" time elapsed.
=> AM-1004 WebAuthn auth integrity check

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/AM-2154
=> AM-2154: postman fix

gravitee-am-ui/src/app/components/emptystate/emptystate.component.html, gravitee-am-ui/src/app/components/emptystate/emptystate.component.scss
https://gravitee.atlassian.net/browse/AM-2674
=> fix(ui): correct image size

CHANGELOG-v3.adoc, gravitee-am-identityprovider/gravitee-am-identityprovider-facebook/pom.xml, gravitee-am-identityprovider/gravitee-am-identityprovider-github/pom.xml, gravitee-am-identityprovider/gravitee-am-identityprovider-google/pom.xml, gravitee-am-identityprovider/gravitee-am-identityprovider-http/pom.xml, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/pom.xml, gravitee-am-identityprovider/gravitee-am-identityprovider-linkedin/pom.xml, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/pom.xml, gravitee-am-identityprovider/gravitee-am-identityprovider-twitter/pom.xml, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/mapper/ObjectMapperResolver.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/AlertTriggerManager.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/server/ManagementApiServer.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java, gravitee-am-reporter/gravitee-am-reporter-jdbc/pom.xml, gravitee-am-repository/gravitee-am-repository-jdbc-api/pom.xml, gravitee-am-repository/gravitee-am-repository-jdbc/pom.xml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcScopeRepository.java, gravitee-am-service/pom.xml, pom.xml
=> Upgrade Gravitee BOM and other dependencies

gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/DefaultReactor.java, gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java, gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/test/java/io/gravitee/am/gateway/services/sync/SyncManagerTest.java
fixes AM-2160
gravitee-io/issues#9496
=> fix: test the DefaultReactor state before the first synchronization

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/factors-select-dialog/factors-select-dialog.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/factors-select-dialog/factors-select-dialog.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/factors-select-dialog/factors-select-dialog.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.html
=> AM-2715 MFA new look fixes

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/factors-select-dialog/factors-select-dialog.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/factors-select-dialog/factors-select-dialog.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.ts
=> AM-2715 MFA new look fixes 2

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.ts
=> AM-2719 fix device identifier link

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
fixes AM-2157
gravitee-io/issues#9494
=> fix: evaluate that the IDP is linked to the app dugin passwordless auth

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStepTest.java
https://gravitee.atlassian.net/browse/AM-2747
=> AM-2747: enrollment loop fix when it is disabled but challenge enabled

pom.xml
=> chore: upgrade nimbus to 9.37.3

gravitee-am-jwt/pom.xml, gravitee-am-service/pom.xml, pom.xml
=> chore: upgrade bouncycastle to 1.77 JDK1.8

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.ts
https://gravitee.atlassian.net/browse/AM-1139
https://gravitee.atlassian.net/browse/AM-2763
=> AM-1139: add null checks for selected factors

gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json, gravitee-am-ui/src/app/entities/plugins/Plugin.ts
n/a
update ui-particles and test any regression with license check. as some change inside ui-particles is done on this component
=> chore(ui): bump ui-particles

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/utils/MfaUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/utils/MfaUtilsTest.java
=> AM-2738: bugfix: optional but nonactive enrollment should not offer "skip for now" option

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/geoip/GeoIpHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/loginattempt/LoginAttemptHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/geoip/GeoIpHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/loginattempt/LoginAttemptHandlerTest.java, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.ts
related-to AM-1141
fixes AM-2758
=> fix: remove usage of legacy adaptiveAuthenticationRule

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RoutingContextHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/WebAuthnRegisterStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MfaFilterContext.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/utils/MfaUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStepTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStepTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnResponseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
https://gravitee.atlassian.net/browse/AM-2760
=> AM-2760: MFA step up

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/CompositeTokenGranter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/revocation/impl/RevocationTokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/ClientTokenAuditBuilder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/reporter/builder/ClientTokenAuditBuilderTest.java
fixes AM-1235
```
[
{
"op": "add",
"path": "/800f34ab-1705-406f-8f34-ab1705506f3f",
"value": {
"tokenType": "ID_TOKEN",
"userId": "800f34ab-1705-406f-8f34-ab1705506f3f"
}
},
{
"op": "add",
"path": "/gvbPe6leZUjEhXXYIaLrHwJcTt0bgkoE0T1WYl59bL0",
"value": {
"tokenId": "gvbPe6leZUjEhXXYIaLrHwJcTt0bgkoE0T1WYl59bL0",
"tokenType": "ACCESS_TOKEN"
}
},
{
"op": "add",
"path": "/p9PEZD6T-g4-QnTmFbpBsGzC86sjM0cPxLwTaWkhAxc",
"value": {
"tokenId": "p9PEZD6T-g4-QnTmFbpBsGzC86sjM0cPxLwTaWkhAxc",
"tokenType": "REFRESH_TOKEN"
}
}
]
```
```
[
{
"op": "add",
"path": "/ACCESS_TOKEN",
"value": "lngiAvmzTXFAV2nNueYKKo_hbPji0jvWC58q0dYVY2E"
},
{
"op": "add",
"path": "/ID_TOKEN",
"value": "Delivered for sub '800f34ab-1705-406f-8f34-ab1705506f3f'"
},
{
"op": "add",
"path": "/REFRESH_TOKEN",
"value": …
```
=> fix: rework token audit content

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStepTest.java
https://gravitee.atlassian.net/browse/AM-2802
=> Am 2802 step up when enroll disabled

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java
=> AM-1141: step up tests

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/utils/MfaUtils.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ApplicationFactorSettingsUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/ApplicationFactorSettingsUpgraderTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/StepUpAuthenticationSettings.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/StepUpAuthenticationMongoSettings.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/ApplicationRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchStepUpAuthentication.java
change the active attribute of StepUp settings to primitive boolean to be align with other mfa settings definition
fixes AM-2811
=> fix: always initialize the stepUp settings on applicatiopn mfa settings

pom.xml
https://gravitee.atlassian.net/browse/AM-2700
=> AM-2700: am-factor-call and am-factor-sms upgrade

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
fixes AM-2866
gravitee-io/issues#9615
=> fix: revert fix for gravitee-io/issues#9494

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select-icon.ts
https://gravitee.atlassian.net/browse/AM-2846
=> AM-2846: fix recovery code icon in mfa type

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/factors-select-dialog/factors-select-dialog.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select-icon.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.html
https://gravitee.atlassian.net/browse/AM-2846
=> AM-2846: fix recovery icon display

pom.xml
=> fix: upgrade recovery code policy to avoid useless audit logs

gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchFactorSettings.java, gravitee-am-service/src/test/java/io/gravitee/am/service/model/PatchFactorSettingsTest.java, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.ts, postman/collections/graviteeio-am-self-account-management-collection-app-version.json
https://gravitee.atlassian.net/browse/AM-2847
=> AM-2847 default factor glitch

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/risk-based/assessment/assessment.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/risk-based/assessment/assessment.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/risk-based/mfa-risk-based.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/selection-rule-dialog/selection-rule-dialog.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.scss
https://gravitee.atlassian.net/browse/AM-2814
=> AM-2814: fix mfa ui issues

gravitee-am-ui/package-lock.json, gravitee-am-ui/package.json
https://gravitee.atlassian.net/browse/AM-2873
=> AM-2873: update particles

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/selection-rule-dialog/selection-rule-dialog.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/selection-rule-dialog/selection-rule-dialog.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.scss
https://gravitee.atlassian.net/browse/AM-2717
=> AM-2717 MFA enrolment views fixes

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.html
https://gravitee.atlassian.net/browse/AM-2718
=> AM-2718 MFA challenge minor fixes

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.html
https://gravitee.atlassian.net/browse/AM-2717
=> AM-2717: update title and placeholder in mfa conditional component

gravitee-am-ui/src/app/components/snackbar/snackbar.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/expression-info-dialog/expression-info-dialog.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/tokens/dialog/claims-info.component.html, gravitee-am-ui/src/app/domain/settings/groups/group/settings/settings.component.html, gravitee-am-ui/src/app/domain/settings/providers/provider/roles/roles.component.html, gravitee-am-ui/src/app/domain/settings/scopes/creation/scope-creation.component.html, gravitee-am-ui/src/app/domain/settings/scopes/scope/scope.component.html, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
https://gravitee.atlassian.net/browse/AM-2756
=> AM-2756: fix user activities list

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/info-banner/info-banner.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/risk-based/mfa-risk-based.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.scss
https://gravitee.atlassian.net/browse/AM-2814
=> AM-2814: ui mfa fixes banner info

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/UserIdentity.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
fixes AM-2862
gravitee-io/issues#9610
=> fix: update UserIdentity list on RDBMS backends

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.scss
https://gravitee.atlassian.net/browse/AM-2756
=> AM-2756: user activites style

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.scss
https://gravitee.atlassian.net/browse/AM-2756
=> AM-2756: resize item title user activites

gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.scss
https://gravitee.atlassian.net/browse/AM-2868
=> AM-2868: add dynamic form error space

gravitee-am-ui/src/app/domain/alerts/notifiers/notifier/form/form.component.scss, gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/form/form.component.scss, gravitee-am-ui/src/app/domain/settings/certificates/certificate/form/form.component.scss, gravitee-am-ui/src/app/domain/settings/deviceidentifiers/device-identifier/form/form.component.scss, gravitee-am-ui/src/app/domain/settings/extension-grants/extension-grant/form/form.component.scss, gravitee-am-ui/src/app/domain/settings/factors/factor/form/form.component.scss, gravitee-am-ui/src/app/domain/settings/openid/ciba/device-notifiers/device-notifier/form/form.component.scss, gravitee-am-ui/src/app/domain/settings/resources/resource/form/form.component.scss
https://gravitee.atlassian.net/browse/AM-2868
=> AM-2868: dynamic form error fix

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnResponseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/consent/UserConsentPrepareContextHandler.java, gravitee-am-service/src/main/java/io/gravitee/am/service/CredentialService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CredentialServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/CredentialServiceTest.java
fixes AM-2872
gravitee-io/issues#9620
=> fix: make webAuthnCredentialInternalId available into the session

gravitee-am-ui/src/app/domain/settings/audits/audits.component.html, gravitee-am-ui/src/app/domain/settings/users/user/history/history.component.html
=> fix: added space between IP and User agent

gravitee-am-ui/src/app/domain/settings/audits/audit/audit.component.html
=> fix: undefined in userAgent

gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
https://gravitee.atlassian.net/browse/AM-2861
=> AM-2861: fix ldap user group field

gravitee-am-ui/src/app/domain/settings/audits/audit/audit.component.html, gravitee-am-ui/src/styles.scss
=> fix: status badge is relative

gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-purge/src/main/java/io/gravitee/am/management/services/purge/ScheduledPurgeService.java, gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-purge/src/main/java/io/gravitee/am/management/services/purge/TableName.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcLoginAttemptRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPermissionTicketRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAccessTokenRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAuthorizationCodeRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcPushedAuthorizationRequestRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcScopeApprovalRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/oidc/JdbcCibaAuthReqRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/oidc/JdbcRequestObjectRepository.java
https://gravitee.atlassian.net/browse/AM-2163
=> AM-2163: purge ciba records for sql db

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DomainResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPoliciesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPolicyResource.java, gravitee-am-model/src/main/java/io/gravitee/am/model/PasswordPolicy.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/PasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/AbstractJdbcRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcPasswordPolicy.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_4_0/4.4.0-add-password-policies-table.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/JdbcRepositoriesTestInitializer.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/PasswordPolicyMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/PasswordPolicyRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordPolicyService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewPasswordPolicy.java
=> feat: addition of the repository layer for PasswordPolicies

gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/app.module.ts, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.scss, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.model.ts
https://gravitee.atlassian.net/browse/AM-2890
=> AM-2890 - Password policy list component

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/client/impl/ClientManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/client/ClientManagerTest.java
Prevent loading application if is disabled. 
AM-2797
=> fix: remove disabled applications

gravitee-am-common/src/main/java/io/gravitee/am/common/saml2/Binding.java, gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSAMLSettings.java, gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationSAMLSettingsMongo.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSAMLSettings.java, gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.ts
=> feat(saml2): add response binding option to service provider

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/geoip/GeoIpHandler.java
https://gravitee.atlassian.net/browse/AM-2904
=> AM-2904: change info to debug log on geoip error

gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/app.module.ts, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-dialog.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-dialog.component.scss, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-dialog.component.ts, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-dialog.factory.ts, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-table/password-policies-idp-select-table.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-table/password-policies-idp-select-table.component.scss, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-table/password-policies-idp-select-table.component.ts
https://gravitee.atlassian.net/browse/AM-2915
=> AM-2915 - Password policies selection dialog

postman/collections/graviteeio-am-login-collection-app-version.json, postman/collections/graviteeio-am-user-management-collection-app-version.json
https://gravitee.atlassian.net/browse/AM-13
Added Utils retry function.
=> AM-13 - retry on failing postman tests

gravitee-am-ui/src/app/components/navbar/navbar.component.html
=> fix: hide the domain name area in the navbar if no domain exist

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java
=> fix: enroll optional when user has factor

gravitee-am-common/src/main/java/io/gravitee/am/common/event/Event.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/password/PasswordPolicyManager.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/SecurityDomainRouterFactory.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPoliciesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPolicyResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPoliciesResourceTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPolicyResourceTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/PasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/PasswordPolicyRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordPolicyService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/PasswordPolicyNotFoundException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/AbstractPasswordPolicy.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewPasswordPolicy.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdatePasswordPolicy.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java, gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/app.module.ts, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts, gravitee-am-ui/src/app/resolvers/password-policies-resolver.service.ts, gravitee-am-ui/src/app/resolvers/password-policies.resolver.spec.ts, gravitee-am-ui/src/app/resolvers/password-policy-resolver.ts, gravitee-am-ui/src/app/services/password-policy.service.ts
this commit also fix the sync process with the Gaetway to update the PasswordPolicyManager
fixes AM-2938
related to AM-2891
=> feat: additin of read & update password policy endpoint

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
=> fix: disable cors when origin is empty

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/PasswordPolicyEntity.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/model/FilteredIdentityProviderInfo.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/IdentityProvidersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPoliciesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/idps/IdentityProvidersResource.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderServiceProxyImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultIdentityProviderUpgraderTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/IdentityProviderRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcIdentityProviderRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringIdentityProviderRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoIdentityProviderRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/IdentityProviderMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/IdentityProviderRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/IdentityProviderService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/IdentityProviderServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateIdentityProvider.java, gravitee-am-service/src/test/java/io/gravitee/am/service/IdentityProviderServiceTest.java, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.model.ts
=> feat: backed for password policy list

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPolicyResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPolicyResourceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordPolicyService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java
fixes AM-3006
related to AM-2896
=> feat: implement REST Endpoint to manage PasswordPolicy deletion

gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.scss, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts, gravitee-am-ui/src/app/services/password-policy.service.ts
**NOTE**: PR made from branch am-2896-task-3006, can't be merge until https://github.com/gravitee-io/gravitee-access-management/pull/3886 is merged 
fixes AM-3007
related to AM-2896
=> feat: implement delete password policy in the frontend

gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.scss, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts, gravitee-am-ui/src/app/services/password-policy.service.ts
=> feat: set default policy in ui

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPoliciesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPolicyResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPolicyResourceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/PasswordPolicy.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/PasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/PasswordPolicyRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordPolicyService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdatePasswordPolicy.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java, gravitee-am-ui/src/app/services/password-policy.service.ts
=> Am 2893 task am 2992 - set default policy - backend

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPoliciesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPoliciesResourceTest.java, gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts
also fix some unit tests which where failing
fixes AM-3038
=> fix: sort Policies by creation date

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPoliciesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPolicyResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPolicyResourceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/PasswordPolicy.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/PasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/PasswordPolicyRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordPolicyService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdatePasswordPolicy.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.scss, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts, gravitee-am-ui/src/app/services/password-policy.service.ts
=> Feat: Default Password Policy

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateUser.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/user/UserValidator.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/user/UserValidatorImpl.java
relates to: https://gravitee.atlassian.net/browse/AM-475
public bug: https://github.com/gravitee-io/issues/issues/8434
This PR handles the emptiness of the email from external provider who don't require it
check https://gravitee.atlassian.net/browse/AM-475 to test
=> fix: update email if it was empty in the first place

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MfaFilterContext.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaSkipUserSilentAuthFilter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaSkipUserSilentAuthFilterTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseIdTokenHintHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
fixes: AM-2880
https://gravitee.atlassian.net/browse/AM-2880
Added request param - **silentAuth** 
Based on which, the new MFA filter determines if it should be skipped or not.
=> AM- 2880 MFA should not be issued on silent auth

gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-dialog.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-dialog.component.ts, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.scss, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts
=> fix: addition of the IdP section in the PasswordPolicy settings page

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts, gravitee-am-ui/src/app/domain/settings/users/user/profile/token/account-token-copy-dialog.component.html, gravitee-am-ui/src/app/domain/settings/users/user/profile/token/account-token-dialog.component.scss
=> fix: generate user account token view

gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/PasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/PasswordPolicyRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordPolicyService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts
feat: delete password policy
feature branch: am-2896
=> feat: delete default policy

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/OrganizationUserServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/OrganizationUserServiceTest.java
=> fix: token attribute

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
=> fix: token generation window

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPolicyResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPolicyResourceTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/PasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoPasswordPolicyRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/PasswordPolicyRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordPolicyService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.scss, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts, gravitee-am-ui/src/app/services/password-policy.service.ts
=> feat: Delete password policy - feature branch

gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.scss, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-dialog.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/password-policies-idp-select-dialog/password-policies-idp-select-dialog.component.ts
=> fix: Handle many password policies by associating them to IDPs

.circleci/config.yml, .circleci/workflows.yml, release/README.adoc, release/steps/abstract-step-release.mjs, release/steps/am-release-alpha-pipeline.mjs, release/steps/am-release-pipeline.mjs, release/steps/am-release.mjs
AM-1064
Alpha workflow
Release a new version
=> chore: release pipeline for a new version and an alpha version

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.ts
=> fix: delete old policy view

gravitee-am-model/src/main/java/io/gravitee/am/model/Application.java, gravitee-am-model/src/main/java/io/gravitee/am/model/FactorSettings.java, gravitee-am-model/src/main/java/io/gravitee/am/model/MFASettings.java, gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSettings.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplication.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationFactorSettings.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSettings.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchFactorSettings.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchMFASettings.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
fixes: AM-3065, #9685
Avoid NPE when an application has MFA factors set to null
=> fix: NPE when applying MFA to app with legacy/broken MFA config

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/password/PasswordPolicyManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/password/PasswordPolicyManagerTest.java
fixes: AM-2893
replaced coded stub with working solution :)
=> AM-2893 - filtering on default policy property

helm/templates/gateway/gateway-configmap.yaml
=> fix: added keystore.password in gateway-configmap.yaml

pom.xml
=> chore: update node version

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
15:01:36.652 [Thread-28] [] DEBUG  i.g.a.g.h.r.r.e.m.MFAEnrollEndpoint - Factor 298f0de1-be4c-4c06-8f0d-e1be4c5c064a selected for user c11e7f61-ad3d-47c2-9e7f-61ad3d67c226
15:01:36.665 [RxCachedThreadScheduler-1] [] DEBUG  i.g.a.g.h.r.r.e.m.MFAChallengeEndpoint - Challenge sent to user c11e7f61-ad3d-47c2-9e7f-61ad3d67c226
15:02:15.184 [Thread-21] [] DEBUG  i.g.a.g.h.r.r.e.m.MFAChallengeEndpoint - User c11e7f61-ad3d-47c2-9e7f-61ad3d67c226 strongly authenticated
15:02:15.187 [Thread-15] [] DEBUG  i.g.am.service.impl.UserServiceImpl - Factor 298f0de1-be4c-4c06-8f0d-e1be4c5c064a upserted for user c11e7f61-ad3d-47c2-9e7f-61ad3d67c226
=> AM-2887 MFA logs 2

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.scss
=> fix: trash icon token revoke

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json
=> feat: update password encryption rounds input description

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
=> fix: force password reset at user profile

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.scss
=> fix: trash color

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/UserServiceImplTest.java, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
=> AM-3118 - forceResetPassword property must be false for external users.

gravitee-am-jwt/pom.xml, gravitee-am-jwt/src/main/java/io/gravitee/am/json/HttpResponseAdapter.java, gravitee-am-jwt/src/main/java/io/gravitee/am/jwt/DefaultJWTBuilder.java, gravitee-am-jwt/src/test/java/io/gravitee/am/jwt/DefaultJWTParserTest.java
=> fix: add typeadapter for gson serialization

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPolicyResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPolicyResourceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordPolicyService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java
=> feat: delete password policies on domain delete

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/IdentityProviderManagerTest.java
fixes AM-3180
https://gravitee.atlassian.net/browse/AM-3180
=> fix: AM-3180 - SHA iteration rounds for Default IDPs

pom.xml
=> chore: upgrade gravitee bom to 8.x and gravtee-node to 5.14.3

gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/ConfigurationCertUtils.java, gravitee-am-certificate/gravitee-am-certificate-api/src/test/java/io/gravitee/am/certificate/api/ConfigurationCertUtilsTest.java, gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/resources/schemas/schema-form.json, gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/resources/schemas/schema-form.json, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/jwk/impl/JWKServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/jwk/JWKServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/CertificateEntity.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/CertificatesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/CertificatesResourceTest.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcCertificateRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCertificateRepository.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java, gravitee-am-ui/src/app/components/dialog/confirm/confirm.component.html, gravitee-am-ui/src/app/components/dialog/confirm/confirm.component.scss, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.html, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.scss, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts
=> AM-2999 Uploading Certificates for mTLS

gravitee-am-ui/src/app/domain/components/forms/form/form.component.ts
=> fix: unable to remove a form at organization level.

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationServiceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
fixes AM-3069
gravtee-io/issues#9687
=> fix: enforce sanitizeTemplate method

gravitee-am-ui/src/app/domain/components/forms/form/form.component.ts
=> fix: unable to remove form at organization level

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
=> fix: service name in dialog

gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.html
=> fix: added service account documentation

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.html
=> fix: save button wont be refreshed when changing time with the input arrow

pom.xml
=> chore: update mfa challenge library

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/ReactableExecutionContext.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/provider/DomainTemplateVariableProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/resources/META-INF/spring.factories
=> fix: make DomainProperties object available into EL context

pom.xml
https://gravitee.atlassian.net/browse/AM-196
=> chore: remove unused ldap dependency

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
=> fix: proper handling CertificateWithApplicationException

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/CockpitAuthenticationFilter.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/InstallationResource.java, helm/templates/api/api-deployment.yaml, helm/templates/api/api-upgrader-job.yaml, helm/templates/cloud/cloud-certificates.yaml, helm/values.yaml, pom.xml
https://gravitee.atlassian.net/browse/CJ-1221
=> add cloud rebrand properties

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_1_0/4.1.23-update-user-identities-table.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/UserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
fixes AM3095
gravitee-io/issues#9713
=> fix: manage linked identities for brute force detection

gravitee-am-certificate/gravitee-am-certificate-api/src/test/java/io/gravitee/am/certificate/api/ConfigurationCertUtilsTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/IdentityProviderCertificateReloader.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/certificate/impl/CertificateManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectConfigurationUtils.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/test/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectConfigurationUtilsTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/test/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProviderTestConfiguration.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/CertificateWithIdpException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientInitializer.java, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientOptionsConfigurer.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/impl/CertificateServiceImplTest.java, gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.ts, gravitee-am-ui/src/app/domain/settings/providers/provider/provider.oidc.enricher.ts, gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
MTLS configuration capability for WebClient for OIDC idp provider
=> AM-2998 mtls for OIDC provider

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
=> fix: always filter the users on the idp enabled to the application

gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java
fixes AM-2795
gravitee-io/issues#9581
=> fix: update organization user email after authentication

gravitee-am-ui/src/app/components/widget/data-table/widget-data-table.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts, gravitee-am-ui/src/app/domain/applications/creation/steps/step1/step1.component.ts, gravitee-am-ui/src/app/guards/auth-guard.service.ts, gravitee-am-ui/src/app/guards/license-guard.service.ts
=> fix: unable to configure applications

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordPolicyServiceTest.java
Only way to set policy as default is by calling endpoint /default
=> fix: prevent create and update policy with default flag.

gravitee-am-ciba-delegated-service/pom.xml, gravitee-am-ciba-delegated-service/src/main/java/io/gravitee/sample/ciba/notifier/CibaHttpNotifier.java, gravitee-am-ciba-delegated-service/src/main/java/io/gravitee/sample/ciba/notifier/http/CibaNotifierApiHandler.java, gravitee-am-ciba-delegated-service/src/main/java/io/gravitee/sample/ciba/notifier/http/CibaNotifierWebSockerHandler.java, gravitee-am-ciba-delegated-service/src/main/java/io/gravitee/sample/ciba/notifier/http/mock/CibaAutomatedTestActionApiHandler.java, gravitee-am-fapi-resource-api/pom.xml, gravitee-am-fapi-resource-api/src/main/java/io/gravitee/sample/fapi/api/CertUtils.java, gravitee-am-fapi-resource-api/src/main/java/io/gravitee/sample/fapi/api/FapiConsentResourceApiHandler.java, gravitee-am-fapi-resource-api/src/main/java/io/gravitee/sample/fapi/api/FapiResourceApiHandler.java
=> chore: allow to generate Java 17 image for FAPI resource

helm/templates/api/api-configmap.yaml, helm/templates/gateway/gateway-configmap.yaml, helm/tests/api/configmap_user_test.yaml, helm/tests/gateway/configmap_user_test.yaml
fixes AM-3313, also updated with values not present in Helm chart, but in gravitee.yml: mfaVerifyAttempt and webAuthn
=> fix: Remove more general duplicated "user" block in Helm chart

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java
fixes AM-3332
* Try to create an organization user and a service account.
* try to use the user profile to access the Console
=> fix: initialize gravitee idp during the IdentityProviderManager startup

docker/compose/config/nginx.conf, docker/management-ui/Dockerfile, docker/management-ui/Dockerfile-dev, docker/management-ui/Dockerfile-nightly, docker/management-ui/config/default.conf
=> fix: adapt nginx config to manage the new rw www directory

pom.xml
fixes
https://gravitee.atlassian.net/browse/AM-3317
=> AM-3317 fix: StackOverflowError on Kubernetes websocket connection issues

pom.xml
https://gravitee.atlassian.net/browse/AM-3317
=> AM-3317 [4.2] fix - StackOverflowError on Kubernetes websocket connection issues

.circleci/scripts/am-service-launcher.sh, .circleci/workflows.yml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/bin/gravitee, gravitee-am-test/api/commands/management/domain-management-commands.ts, gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts, postman/collections/graviteeio-am-flows-collection-app-version.json, postman/collections/graviteeio-am-login-collection-app-version.json, postman/collections/graviteeio-am-oauth2-collection-app-version.json, postman/collections/graviteeio-am-oauth2-par-version.json, postman/collections/graviteeio-am-openid-ciba-collection.json, postman/collections/graviteeio-am-openid-core-request-object-collection.json, postman/collections/graviteeio-am-openid-dcr-collection-app-version.json, postman/collections/graviteeio-am-openid-fapi-collection.json, postman/collections/graviteeio-am-openid-jarm-collection.json, postman/collections/graviteeio-am-scim-collection-app-version.json, postman/collections/graviteeio-am-scope-management-collection.json, postman/collections/graviteeio-am-self-account-management-collection-app-version.json, postman/collections/graviteeio-am-uma2-app-version-collection.json, postman/collections/graviteeio-am-vhost-collection.json
=> chore: align default waiting time for gateway sync to 10s

pom.xml
In new version of saml library added validation of certificate input and improved description
fixes AM-3372
=> chore: update saml library

gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts, gravitee-am-ui/src/app/services/time-converter.service.ts
[AM-3376](https://gravitee.atlassian.net/browse/AM-3376)
[AM-3376]: https://gravitee.atlassian.net/browse/AM-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: user account settings

gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/api/OTPFactorProvider.java, gravitee-am-factor/gravitee-am-factor-api/src/test/java/io/gravitee/am/factor/api/OTPFactorProviderTest.java
fixes: remove stacktrace in logs when input was not 6 digits string by adding validation of string.
=> fix: added validation of OTP

gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts
[AM-3376](https://gravitee.atlassian.net/browse/AM-3376)
[AM-3376]: https://gravitee.atlassian.net/browse/AM-3376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: user account settings time unit

gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/vertx/EventBusReporterWrapper.java
=> fix: do not start the reporter twice

gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/FileReporterConfiguration.java, gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/audit/AuditEntry.java, gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/audit/FileAuditReporter.java, gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/formatter/csv/AuditFormatter.java, gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/formatter/elasticsearch/freemarker/FreeMarkerComponent.java, gravitee-am-reporter/gravitee-am-reporter-file/src/main/resources/elasticsearch/index/audit.ftl, gravitee-am-reporter/gravitee-am-reporter-file/src/test/java/io/gravitee/am/reporter/file/audit/FileAuditReporterTest.java, gravitee-am-reporter/gravitee-am-reporter-file/src/test/java/io/gravitee/am/reporter/file/audit/JsonFileAuditReporterTest.java, gravitee-am-reporter/gravitee-am-reporter-file/src/test/java/io/gravitee/am/reporter/file/audit/MsgpackFileAuditReporterTest.java
AM-3347
Include full audit event details in the file reporter's logs
=> fix: include event details in file reporter's entries

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
=> fix: send registration confirmation form when user has no password

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/plugins/CertificatesPluginResource.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts, gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step1/step1.component.ts, pom.xml
https://gravitee.atlassian.net/browse/AM-3308
=> feat: aws secret manager certificate

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
https://gravitee.atlassian.net/browse/AM-3309
=> fix: aws certificate cache

gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/audit/KafkaAuditReporter.java
Workaround for bug in kafka vertx library https://github.com/vert-x3/vertx-kafka-client/issues/271
=> fix: close kafka producer connection without delay.

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
https://gravitee.atlassian.net/browse/AM-3474
=> fix: specify min cache value for certificate

gravitee-am-service/src/main/java/io/gravitee/am/service/validators/resource/ResourceValidatorImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/resource/http/HttpResourceValidator.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/resource/http/HttpResourceValidatorImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/resource/smtp/SmtpResourceValidatorImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/HttpResourceValidatorTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/ResourceValidatorTest.java
the schema form can't apply condition on oauth settings to require them
this fix apply validation on the resource configuration json element
fixes AM-3383
=> fix: validate OAuth2 settings on HTTP Resource

gravitee-am-ui/src/app/domain/applications/application/advanced/account/account.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/certificates/certificates.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/cookie/cookie.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/login/login.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/grantFlows/application-grant-flows.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/scopes/application-scopes.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/tokens/application-tokens.component.ts
https://gravitee.atlassian.net/browse/AM-1197
=> fix: incorrect state forms in application settings

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TagServiceImpl.java
fixes AM-3359; on 'tag' removal, the domain is updated only if it contains the tag. Also the domain update error is suppressed because 'tag' is already removed.
=> AM-3359: fix: on 'tag' removal domain is updated only if it contains tag

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2Request.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenEnhancerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2RequestTest.java
=> fix: provide a settings to mitigate the breaking change introduce in 4.3

gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/DefaultTrustStoreProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/common/IdentityProviderConfigurationUtils.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/test/java/io/gravitee/am/identityprovider/api/common/IdentityProviderConfigurationUtilsTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientInitializer.java, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientOptionsConfigurer.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/IdentityProviderServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/RetryWithDelay.java, gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.ts, gravitee-am-ui/src/app/domain/settings/providers/provider/provider.form.enricher.ts, gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
https://gravitee.atlassian.net/browse/AM-3270
plugin PR 
https://github.com/gravitee-io/gravitee-am-identityprovider-ldap/pull/27/files
=> AM-3270 MTLS for LDAP

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/AuditBuilder.java
https://gravitee.atlassian.net/browse/AM-3413
configure Http Provider message
Audit log
=> fix: add audit log with cause message

gravitee-am-model/src/main/java/io/gravitee/am/model/Domain.java, gravitee-am-model/src/main/java/io/gravitee/am/model/DomainVersion.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcDomain.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_0/4.5.0-domain-version.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/DomainMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DomainRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
this will help to adapt behaviour of the GW based on the domain version
fixes AM-3479
=> chore: introduce version attribute in the domain entity

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/conditional/mfa-conditional.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-challenge/mfa-challenge.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/selection-rule-dialog/selection-rule-dialog.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/step-up-auth/mfa-step-up.component.html
https://gravitee.atlassian.net/browse/AM-3335
=> fix: update mfa expression language links

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
https://gravitee.atlassian.net/browse/AM-3532
=> fix: update key inputs, update aws certificate plugin version

gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/scopes/application-scopes.component.ts
https://gravitee.atlassian.net/browse/AM-1197
=> fix: scope in application settings

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
https://gravitee.atlassian.net/browse/AM-3307
=> chore: update aws plugins to stable versions

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSession.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSessionHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieService.java
https://gravitee.atlassian.net/browse/AM-3475
=> fix: get default certificate provider

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/CertificateResource.java
=> AM-3546 fix: on GET cert a whole body should be returned

gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.html, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.scss
=> AM-3560 usage column alignment

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
=> fix: delete domain with idp mtls

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/Token.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenServiceTest.java
=> fix: block override token standard response parameter.

gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/JerseySpringTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/DomainsResourceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/DefaultIdentityProviderService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainIdpUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/system/upgraders/DefaultIdentityProviderUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DomainServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/IdentityProviderManagerTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/system/upgraders/DefaultIdentityProviderUpgraderTest.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, helm/tests/api/configmap_domains_test.yaml
=> feat: prevent default identity provider to be created

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html
Fixes: AM-3627 - removed unhide mock factor when going back.
=> fix: remove mock factor when go back on enroll mfa

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_enroll.html
Fixes AM-3627 - remove not needed code
PR on branches will be updated with this fix.
=> fix: remove mock factor when go back on enroll mfa 2

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationManager.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterV2.java
Fix: AM-3601. Added missing request required to prepare context in DefaultRulesEngine.
There will be created separate PR for version 4.1.x-4.4.x because of changes made for DomainV2.
=> fix: Extension grant with “create user account"

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-users/src/main/java/io/gravitee/am/gateway/handler/users/UsersProvider.java, postman/collections/graviteeio-am-oauth2-collection-app-version.json
DELETE /users/user-id/consents/consent-id wasn't handled by OAuth2AuthHandler were token is extracted and saved to rountingContext.
=> AM-3602 consent delete issue

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationManager.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java
Fix: AM-3601. This is separate PR for maintenance versions to avoid conflicts
=> fix: Extension grant with “create user account" - maintenance versions

gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.html, gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.scss
AM-3597
Fix UI logic error from the previous PR
=> AM-3597: properly toggle "entrypoint unavailable" warning

gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/main/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JWTBearerExtensionGrantProvider.java, gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/test/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JWTBearerExtensionGrantProviderTest.java
=> AM-3655 fix jwt-bearer for SubjectManagerV2

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/SubjectManager.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV1.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/spring/SecurityDomainRouterConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2Test.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterV2.java
=> fix: remove null from gis

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeGenerator.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeGeneratorTest.java
=> AM-3650 Double dashes

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/util/AccountRoutes.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java
fix: sanitize secret from EnrolledFactor and provide dedicated endpoint for shared secret
fixes: AM-3684
=> fix: sanitize secret from EnrolledFactor

helm/templates/api/api-configmap.yaml, helm/templates/gateway/gateway-configmap.yaml, helm/tests/api-configmap_test.yaml, helm/tests/gateway-configmap_test.yaml, helm/values.yaml
https://gravitee.atlassian.net/browse/AM-3467
=> fix: add missing env variables

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, helm/templates/api/api-configmap.yaml, helm/templates/gateway/gateway-configmap.yaml
https://gravitee.atlassian.net/browse/AM-3467
=> fix: helm chart and properties values

gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/api/OTPFactorProvider.java
AM-3691
https://gravitee.atlassian.net/browse/AM-3691
=> fix: debug log in OTP factory

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RiskAssessmentService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/utils/RiskAssessmentServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/rememberdevice/DeviceIdentifierHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/rememberdevice/DeviceIdentifierHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/risk/RiskAssessmentHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/risk/RiskAssessmentHandlerTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DeviceResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DevicesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/DevicesResourceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/Device.java, gravitee-am-model/src/main/java/io/gravitee/am/model/User.java, gravitee-am-model/src/main/java/io/gravitee/am/model/UserId.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/DeviceRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/AbstractJdbcRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcDeviceRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcDevice.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_0/4.5.0-device-external-user-id.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDeviceRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/DeviceMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DeviceRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/DeviceService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DeviceServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/DeviceServiceTest.java
AM-3525
This PR introduces a UserId record to wrap the internal and/or external id together to use for entities that can be linked to a user by any of these ids.
=> feat: AM-3525: support device lookup by users' externalId + source

gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/provider/spring/HttpAuthenticationDeviceProviderSpringConfiguration.java, gravitee-am-botdetection/gravitee-am-botdetection-recaptcha-v3/src/main/java/io/gravitee/am/botdetection/google/recaptcha/provider/GoogleReCaptchaV3Provider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-facebook/src/main/java/io/gravitee/am/identityprovider/facebook/authentication/spring/FacebookAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/spring/GithubAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/test/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProviderTestConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-google/src/main/java/io/gravitee/am/identityprovider/google/authentication/spring/GoogleAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/authentication/spring/HttpAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/spring/HttpUserProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/authentication/HttpAuthenticationProviderTestConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-linkedin/src/main/java/io/gravitee/am/identityprovider/linkedin/authentication/spring/LinkedinAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/test/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProviderTestConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-twitter/src/main/java/io/gravitee/am/identityprovider/twitter/authentication/spring/TwitterAuthenticationProviderConfiguration.java, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java, gravitee-am-service/src/main/java/io/gravitee/am/service/spring/WebClientsConfiguration.java, gravitee-am-service/src/test/java/io/gravitee/am/service/http/WebClientBuilderTest.java
=> fix: bot detection creation nullpointer

helm/templates/gateway/gateway-configmap.yaml, helm/tests/gateway/configmap_http_test.yaml, helm/values.yaml
=> fix: added secret and watch to helm charts

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/InstallationServiceImpl.java
https://gravitee.atlassian.net/browse/AM-1090
=> fix: one installation collection

gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/TokenPurpose.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidatorTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
Fixes: https://gravitee.atlassian.net/browse/AM-3718
=> fix: redirect_url not required for registration confirmation

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.html
https://gravitee.atlassian.net/browse/AM-1045
=> fix: mfa remember device space

gravitee-am-ui/src/app/newsletter/newsletter.component.scss
https://gravitee.atlassian.net/browse/AM-256
=> fix: add space on newsletter page

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TokenServiceImpl.java
https://gravitee.atlassian.net/browse/AM-3700
=> fix: remove tokens by correct client id

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/attestation/GraviteeTPMAttestation.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/attestation/PubArea.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/META-INF/services/io.vertx.ext.auth.webauthn.impl.attestation.Attestation
fixes: https://gravitee.atlassian.net/browse/AM-3730
=> fix: added GraviteeTPMAttestation to fix reading PubArea section

pom.xml
fixes AM-3745
fixes AM-3736
gravitee-io/issues#9969
gravitee-io/issues#9971
=> fix: upgrade ldap idp version to fix connection issues

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
https://gravitee.atlassian.net/browse/AM-3555
=> fix: create application with empty string to default behaviour

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserService.java
=> fix: call the right method to update factor and avoid stackoverflow

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
=> AM-3765 fix: added externalId nad sourceId to LOGOUT audit log

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java, gravitee-am-test/api/commands/gateway/login-commands.ts, gravitee-am-test/api/commands/utils/application-commands.ts, gravitee-am-test/api/commands/utils/idps-commands.ts, gravitee-am-test/specs/gateway/am-confirm-pre-registration.spec.ts, gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts, gravitee-am-test/specs/gateway/am-selfaccount-change-password.jest.spec.ts, gravitee-am-test/specs/gateway/enduser-logout.jest.spec.ts, gravitee-am-test/specs/gateway/flow-execution.jest.spec.ts, gravitee-am-test/specs/gateway/forgot-password.jest.spec.ts, gravitee-am-test/specs/gateway/login-flow.jest.spec.ts, gravitee-am-test/specs/gateway/mfa.jest.spec.ts, gravitee-am-test/specs/gateway/remember-me.jest.spec.ts, gravitee-am-test/specs/gateway/user-registration.jest.spec.ts, gravitee-am-test/specs/management/applications.jest.spec.ts, postman/collections/graviteeio-am-api-management-collection.json, postman/collections/graviteeio-am-client-management-collection-app-version.json, postman/collections/graviteeio-am-flows-collection-app-version.json, postman/collections/graviteeio-am-login-collection-app-version.json, postman/collections/graviteeio-am-logout-collection-app-version.json, postman/collections/graviteeio-am-oauth2-collection-app-version.json, postman/collections/graviteeio-am-oauth2-par-version.json, postman/collections/graviteeio-am-openid-core-collection-app-version.json, postman/collections/graviteeio-am-openid-jarm-collection.json, postman/collections/graviteeio-am-self-account-management-collection-app-version.json, postman/collections/graviteeio-am-uma2-app-version-collection.json, postman/collections/graviteeio-am-user-management-collection-app-version.json
fixes AM-3769
gravitee-io/issues#9987
=> fix: redirect_uri required for application type different from SERVICE

gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.html
fixes AM-3888
gravitee-io/issues#10002
=> fix: align label of 'domain whitelist' field

docs/self-service-account-api-descriptor.yml, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/model/UpdateUsername.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountResponseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/util/AccountRoutes.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/AccountService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/services/AccountServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/business/UpdateUsernameRule.java, gravitee-am-service/src/test/java/io/gravitee/am/business/UpdateUsernameRuleTest.java, postman/collections/graviteeio-am-self-account-management-collection-app-version.json
=> feat: create update username endpoint on self account

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_0/4.5.0-add-node-monitoring-index.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoNodeMonitoringRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
=> fix: add index on node_monitoring

gravitee-am-ui/src/app/domain/settings/saml2/saml2.component.html
=> AM-3891 cert saml2

gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/audit/JdbcAuditReporter.java, gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java
=> fix: do not stop the bulk processor in reporter in case of error

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
=> AM-3890 jdbc cp down issue

.circleci/workflows.yml
=> chore(ci): add aqua repository scan on PullRequest

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryInResilienceModeTest.java
=> fix: make jdbc user repository to perform upserts on user update

gravitee-am-common/src/main/java/io/gravitee/am/common/web/UriBuilder.java, gravitee-am-common/src/test/java/io/gravitee/am/common/web/UriBuilderTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java, gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts, postman/collections/graviteeio-am-oauth2-collection-app-version.json, postman/collections/graviteeio-am-openid-core-collection-app-version.json
fixes AM-3669
gravitee-io/issues#9920
=> fix: avoid double URL encoding on error redirection

.circleci/workflows.yml
=> chore(ci): fix aqua image scan

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractRepositoryConfiguration.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/gateway/GatewayRepositoryConfiguration.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/gateway/test/config/GatewayTestConfigurationLoader.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/management/test/config/ManagementTestConfigurationLoader.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/oauth2/test/config/OAuthTestConfigurationLoader.java
additionally, I removed @Bean method because 2 RepositoriesEnvrionemnt are created in both StandaloneConfigurations
=> fix: issue with dbname resolution on test environments

.circleci/workflows.yml
=> chore(ci): integrate aquasec

gravitee-am-common/src/main/java/io/gravitee/am/common/crypto/CryptoUtils.java, gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/Claims.java, gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/CodeChallengeMethod.java, gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-common/src/test/java/io/gravitee/am/common/crypto/CryptoUtilsTest.java, gravitee-am-common/src/test/java/io/gravitee/am/common/oauth2/CodeChallengeMethodTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/JWTService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/jwt/JWTServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackParseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/code/AuthorizationCodeTokenGranter.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/common/Request.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/social/SocialAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractSocialAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-google/src/main/java/io/gravitee/am/identityprovider/google/GoogleIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-google/src/test/java/io/gravitee/am/identityprovider/google/authentication/GoogleAuthenticationProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json
AM-3685
PKCE support for upstream social IDPs
This PR implements PKCE for IDPs used by the Gateway. PKCE for Management Console IDPs will be handled in a future PR.
=> AM-3685: support PKCE for identity providers

gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.html, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html
fixes AM-3963
gravitee-io/issues#10028
=> fix: remove the maxLength for password expiry

gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/Claims.java, gravitee-am-common/src/test/java/io/gravitee/am/common/oauth2/CodeChallengeMethodTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/social/SocialAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/LoginController.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/SocialAuthenticationFilter.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-api/src/main/java/io/gravitee/am/plugins/handlers/api/core/impl/ConfigurationFactoryImpl.java, gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.ts
AM-3962
Management API side counterpart to #4820
=> AM-3962 PKCE support for IDP - management console

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> AM-3977 - fix: when old-way properties are provided then they should take precedence

gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java, pom.xml
…with stacktrace
fixes AM-3909
With DEBUG turned ON:
With no DEBUG mode
=> AM-3909 too verbose sync manager

pom.xml
fixes AM-3985
gravitee-io/issues#10042
=> fix: upgrade saml idp plugin from 3.0.4 to 3.0.5

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackParseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProviderTest.java
=> fix: handle missing code verifier gracefully, error handling improvement

.circleci/workflows.yml
=> feat: checking gio_version param against version from pom.xml before release

helm/CHANGELOG.md, helm/Chart.yaml, helm/templates/api/api-configmap.yaml, helm/templates/gateway/gateway-configmap.yaml, helm/tests/api/configmap_sync_test.yaml, helm/tests/gateway/configmap_cache_test.yaml, helm/tests/gateway/configmap_sync_test.yaml
=> chore(helm): add management of the sync service and cache layer

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/ReporterServiceProxyImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ExtensionGrantServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/I18nDictionaryService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordPolicyServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ThemeServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TokenServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/I18nDictionaryServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/TokenServiceTest.java
=> fix: add missing reference for some audit logs

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/services/AccountServiceTest.java
=> fix: AM-3945 blank username self management API

helm/CHANGELOG.md, helm/Chart.yaml, helm/templates/api/api-ingress.yaml, helm/templates/api/api-technical-ingress.yaml, helm/templates/gateway/gateway-ingress.yaml, helm/templates/gateway/gateway-technical-ingress.yaml, helm/templates/ui/ui-ingress.yaml, helm/values.yaml
Cherry pick of a community PR to improve pathType
=> feat(helm): add `*.ingress.pathType` to helm/values.yaml

gravitee-am-test/api/commands/management/domain-management-commands.ts, gravitee-am-test/api/commands/utils/application-commands.ts, gravitee-am-test/api/commands/utils/misc.ts, gravitee-am-test/api/commands/utils/retry.ts, gravitee-am-test/api/config/dev.setup.js, gravitee-am-test/specs/gateway/idp-with-pkce.spec.ts
=> chore(test): jest test for OIDC provider with PKCE

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-common/src/main/java/io/gravitee/am/common/web/UriBuilder.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/HashUtil.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/endpoint/ErrorEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/AbstractErrorHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/register/RegisterFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/consent/UserConsentFailureHandler.java
To avoid manipulating error message by changing the url, I introduced hash of error message that is stored in session. 
Fixes: https://gravitee.atlassian.net/browse/PEN-10
=> fix: added hash of error to the session

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/RxWebTestBase.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/SCIMProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/business/CreateUserAction.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/exception/TooManyOperationException.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/BulkOperation.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/BulkRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/BulkResponse.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/Error.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/ErrorHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/bulk/BulkEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/AbstractUserEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UsersEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/BulkService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/BulkServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/spring/SCIMConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/bulk/BulkEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/BulkServiceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/management/UserAuditBuilder.java
This is only the Create Users action, other actions (Delete, Patch, Put)
and number of failures are coming in another PR
fixes AM-3571
Here is the link of the RFC 
https://datatracker.ietf.org/doc/html/rfc7644#section-3.7
=> feat: introduce SCIM bulk endpoint to create users

gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/TokenTypeHint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/oauth2/IntrospectionTokenFacade.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/oauth2/impl/BaseIntrospectionTokenService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/oauth2/impl/IntrospectionAccessTokenService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/oauth2/impl/IntrospectionRefreshTokenService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/auth/provider/impl/OAuth2AuthProviderImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/oauth2/IntrospectionTokenFacadeTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/oauth2/impl/IntrospectionAccessTokenServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/oauth2/impl/IntrospectionRefreshTokenServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/introspection/IntrospectionEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/IntrospectionRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/impl/IntrospectionServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/IntrospectionEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/IntrospectionRequestTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/IntrospectionServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImplTest.java
=> fix: AM-4047 introspection on refresh token

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/endpoints/user/RegisterConfirmationEndpointTest.java
=> Fix AM-4080 no password policy at confirm reg page

.circleci/workflows.yml
fixes problem with HelmCharts in v4.5 used across all maint version
=> fix: helm charts should be used in branch version

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginAbstractHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginAuthenticationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginHideFormHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSelectionRuleHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginAuthenticationHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginHideFormHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSelectionRuleHandlerTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/IdentityProvider.java
=> feat: add list of internal identity provider on login page

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/MFAValidationAttemptException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/RateLimitException.java
fixes https://gravitee.atlassian.net/browse/AM-4101
=> fix: http status code on rate limit exception

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UserEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/BulkServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/BulkServiceTest.java
=> feat: manage delete user using SCIM bulk command

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/business/AbstractUserAction.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/business/PatchUserAction.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/business/UpdateUserAction.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/BulkOperation.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UserEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/BulkServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/bulk/BulkEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/users/PatchUserEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/BulkServiceTest.java
=> feat: manage user update and patch using SCIM bulk command

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/bulk/BulkEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/bulk/BulkEndpointTest.java
=> fix: AM-3097 bulkIds should be unique

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterV2.java
Fixes https://gravitee.atlassian.net/browse/AM-4108
=> fix: find user by externalId in extension grant.

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java
=> fix: display server error when session is empty.

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/bulk/BulkEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/bulk/BulkEndpointTest.java
=> fix: evaluate bulkId only if present for non POST operation

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/FreemarkerDataHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/uma/UMATokenGranter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/notifications/NotificationDefinitionUtils.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java, gravitee-am-model/src/test/java/io/gravitee/am/model/safe/UserPropertiesTest.java
=> fix: op claims in additional information

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/plugins/IdentityProvidersPluginResource.java, gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/app.module.ts, gravitee-am-ui/src/app/resolvers/identities-organization.resolver.ts, gravitee-am-ui/src/app/services/organization.service.ts
fixes https://gravitee.atlassian.net/browse/AM-4129
=> fix: remove saml idp from organization level

.circleci/config.yml, .circleci/workflows.yml, release/README.adoc, release/steps/am-release-hotfix.mjs, release/steps/am-release.mjs
=> chore: create hotfix ci

pom.xml
=> chore: update ipfiltering version

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/bulk/BulkRequest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/bulk/BulkRequestTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java, gravitee-am-test/api/commands/management/user-management-commands.ts, gravitee-am-test/api/management/models/BulkCreateOrganizationUser.ts, gravitee-am-test/api/management/models/BulkCreateUser.ts, gravitee-am-test/api/management/models/BulkDeleteOrganizationUser.ts, gravitee-am-test/api/management/models/BulkDeleteUser.ts, gravitee-am-test/api/management/models/BulkUpdateUser.ts, gravitee-am-test/specs/management/users.jest.spec.ts
=> feat: failOnErrors property on bulk users operations

gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.ts, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
fixes https://gravitee.atlassian.net/browse/AM-4069
=> fix: unable to add additional information on user create

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/model/BulkUpdateUser.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/OrganizationResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/OrganizationUserResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/OrganizationUsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/schemas/BulkCreateOrganizationUser.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/schemas/BulkCreateUser.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/schemas/BulkDeleteOrganizationUser.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/schemas/BulkDeleteUser.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/schemas/BulkUpdateUser.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/schemas/package-info.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/OrganizationUserResourceTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/OrganizationUsersResourceTest.java
=> feat(users): bulk update users via mAPI

gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/KafkaReporterConfiguration.java, gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/audit/KafkaAuditReporter.java, gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/resources/schemas/schema-form.json, gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/form/form.component.scss
=> feat: username and password for kafka reporter

pom.xml
feat: https://gravitee.atlassian.net/browse/AM-4163
=> chore: update ldap identity provider

pom.xml
=> fix: upgrade MFA Challenge policy

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcDeviceRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DeviceRepositoryTest.java
fixes AM-4257, AM-4301
This PR fixes #4776 by also removing the user external id from device lookups in JDBC repo
=> AM-4257, AM-4301:remove user source and ext id from device query

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/ReporterServiceProxyImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/ReporterService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/ReporterDeleteException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ReporterServiceTest.java, gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
=> fix: prevent remove default reporter

gravitee-am-model/src/main/java/io/gravitee/am/model/permissions/Permission.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/RoleServiceImpl.java
=> fix: add DOMAIN_SETTINGS:DELETE permission to DOMAIN_PRIMARY_OWNER

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultRoleUpgrader.java, gravitee-am-model/src/main/java/io/gravitee/am/model/permissions/Permission.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/RoleServiceImpl.java
AM-2749
updates the upgraded so that #5098 gets applied on existing installations
=> AM-2749: missing domain primary owner permission

gravitee-am-test/api/commands/management/service/utils.ts, gravitee-am-test/specs/gateway/scim/bulk.spec.ts, gravitee-am-test/specs/management/organisation.users.jest.spec.ts, gravitee-am-test/specs/management/users.jest.spec.ts
=> chore(test): added max size bulk test

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/GroupServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/GroupServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/AbstractDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcGroupRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcOrganizationUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelperTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
=> fix: preserve processing order during SCIM list action

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
=> fix: replace flatMapSingle by concatMapSingle to preserve order

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_1_0/4.1.35-update-web-credential-index.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
=> fix: create index on credentials using createdAt and username

gravitee-am-common/src/main/java/io/gravitee/am/common/exception/jwt/InvalidGISException.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/impl/IntrospectionServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/IntrospectionServiceTest.java
=> fix: manage missing GIS from token on DomainV2 introspect

pom.xml
=> chore(twilio): upgrade twilio version to 1.2.0

gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.html, gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
=> AM-4325 kafka reporter jsonform validation

gravitee-am-ui/src/app/domain/settings/certificates/certificate/certificate.component.html, gravitee-am-ui/src/app/domain/settings/certificates/certificate/certificate.component.ts, gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.html, gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.ts
=> AM-4323 locking certificate upsert

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2Request.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenEnhancerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2RequestTest.java
=> fix: provide a settings to mitigate the breaking change introduce in 4.3.

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ThymeleafDataHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/AbstractErrorHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/EnrollmentChannelValidationException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/vertx/RequestUtils.java
=> AM-4393 enroll validation

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractMongoRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractManagementMongoRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
=> fix: removed unused indexes

pom.xml
as this lib is used internally, we are not vuln but better to upgrade it
=> fix: upgrade org.json to fix CVE-2023-5072

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/model/User.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/AbstractNewUser.java
=> feat: set latPasswordResetForNewUser

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
=> AM-4492 audit log on psswd history

pom.xml
=> chore: update ldap idp version to 1.2.4

pom.xml
=> chore: update ldap idp version

gravitee-am-service/src/main/java/io/gravitee/am/service/validators/password/impl/DefaultPasswordValidatorImpl.java, postman/collections/graviteeio-am-self-account-management-collection-app-version.json
=> fix: adapt the default password poklicy error message

gravitee-am-ui/src/app/domain/settings/password-policy/pass-policy-status/password-policy-status.component.ts
=> fix: race condition on emitted values for password policies

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateServiceProxyImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/CertificateServiceProxyImplTest.java
=> AM-4512 missing cert schema

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_2_27/4.2.27-change-client-column-size.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DeviceRepositoryTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/AccessTokenRepositoryTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/AuthorizationCodeRepositoryTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/CibaAuthRequestRepositoryTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/PushedAuthorizationRequestRepositoryTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/RefreshTokenRepositoryTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/ScopeApprovalRepositoryTest.java
Fixes AM-4549
Updating client column to 255 characters
=> fix: change field size for client

docs/scim-api-descriptor.yml
this update include SCIM Bulk operation details
fixes AM-4546
related to AM-3358
=> chore(doc): update SCIM swagger specification to OpenAPI 3.0

gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.html
=> fix: update certificate description in ui

pom.xml
=> fix: bump ldap idp version

gravitee-am-ui/src/app/domain/settings/providers/provider/provider.form.enricher.ts
=> fix: idp configuration when certificate usage is missing

gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/HttpAuthenticationDeviceNotifierConfiguration.java, gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProvider.java, gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/resources/schemas/schema-form.json
=> feat: http headers in CIBA device notifier

gravitee-am-model/src/main/java/io/gravitee/am/model/Domain.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcDomain.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-update-domain-table.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/DomainMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DomainRepositoryTest.java
=> feat: data plane id in domain entity

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainDataPlaneUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/UpgraderOrder.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DomainDataPlaneUpgraderTest.java
=> AM-4573 - upgrader for dataPlaneId

.circleci/workflows.yml, gravitee-am-reporter/gravitee-am-reporter-jdbc/pom.xml, gravitee-am-repository/gravitee-am-repository-jdbc/pom.xml, gravitee-am-repository/pom.xml, pom.xml
=> chore(ci): update backend version to latest one

gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
=> fix: allow to create user with whitespace by default

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/AbstractDomainResource.java, gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/domain/settings/general/general.component.html, gravitee-am-ui/src/app/domain/settings/general/general.component.ts, gravitee-am-ui/src/app/resolvers/data-planes.resolver.ts
fixes AM-4561
dependent on AM-4560
=> AM-4561 presenting dataplane name

gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.html, gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
=> AM-4601 fix: unable to change anything on created reporter 

gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.html, gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
=> AM-4601 fix: unable to change anything on created reporter 43 44

gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
=> fix: unable to create file reporter

gravitee-am-ui/src/app/domain/alerts/general/general.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/scopes/application-scopes.component.scss, gravitee-am-ui/src/app/domain/components/memberships/memberships.component.scss
=> fix: correct display drop down list in table

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DomainServiceTest.java
=> AM-4615 fix upgrader for data-planes

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RoutingContextHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MfaFilterContext.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/chain/MfaFilterChain.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaChallengeFilter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/utils/MfaUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaChallengeFilter_RememberDevice_Test.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java
=> fix: skip MFA Challenge flow

gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts
=> fix: audit details when message is missing

.circleci/workflows.yml
fixes issue with pushing artifacts to aws s3 repository.
=> chore: specify aws cli version

gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/scopes/application-scopes.component.ts
fixes [AM-4658]
[AM-4658]: https://gravitee.atlassian.net/browse/AM-4658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Add Scopes dialog extension

gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/utils/SanitizeUtils.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/authentication/HttpAuthenticationProviderTest.java
=> fix: escape properly double quote for password on HTTP Provider

gravitee-am-ui/src/app/domain/settings/password-policy/pass-policy-status/password-policy-status.component.ts
=> fix: remove password history from check when false

gravitee-am-ui/src/app/domain/settings/password-policy/pass-policy-status/password-policy-status.component.ts
=> fix: make password policy feedback all consistent

gravitee-am-service/src/main/java/io/gravitee/am/service/exception/InvalidPasswordException.java
=> fix: invalid password message for MAPI

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/InvalidDataPlaneException.java, gravitee-am-ui/src/app/domain/creation/domain-creation.component.html, gravitee-am-ui/src/app/domain/creation/domain-creation.component.ts, gravitee-am-ui/src/app/domain/settings/general/general.component.html
Fixes: 
AM-4671: Dataplanes not in alphabetical order
AM-4676: 500 Server error for invalid dataplaneid
AM-4691: Full stop missing from sentence & field title missing capital letter
AM-4692: Data Plane field still selectable even though its READ ONLY
=> fix: data plane UI issues after testing

gravitee-am-ui/src/app/domain/creation/domain-creation.component.html, gravitee-am-ui/src/app/domain/settings/general/general.component.html
=> fix: data plane hint

gravitee-am-dataplane/gravitee-am-dataplane-api/src/main/java/io/gravitee/am/dataplane/api/DataPlaneProvider.java, gravitee-am-dataplane/gravitee-am-dataplane-api/src/main/java/io/gravitee/am/dataplane/api/repository/PasswordHistoryRepository.java, gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/java/io/gravitee/am/dataplane/mongodb/provider/MongoDataPlaneProvider.java, gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/java/io/gravitee/am/dataplane/mongodb/repository/MongoPasswordHistoryRepository.java, gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/java/io/gravitee/am/dataplane/mongodb/repository/model/PasswordHistoryMongo.java, gravitee-am-dataplane/gravitee-am-dataplane-test/src/test/java/io/gravitee/am/dataplane/api/repository/PasswordHistoryRepositoryTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/PasswordHistoryHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/PasswordHistoryHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/ProvisioningUserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/ProvisioningUserServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/PasswordPolicyResource.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/ManagementUserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/ManagementUserServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/OrganizationUserServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DomainServiceTest.java, gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/core/DataPlaneRegistry.java, gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/core/DataPlaneRegistryImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordHistoryService.java, gravitee-am-service/src/test/java/io/gravitee/am/service/impl/PasswordHistoryServiceTest.java
Fixes AM-4706
RelatedTo AM-4569
=> AM-4706 password history in data plane

gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json, gravitee-am-test/specs/gateway/oidc-idp/common.ts, postman/collections/graviteeio-am-api-management-collection.json
=> fix: make responseMode in Oauth2 required

.circleci/workflows.yml, docker/enterprise/am/3.x/gateway/Dockerfile, docker/enterprise/am/3.x/gateway/Dockerfile-nightly, docker/enterprise/am/3.x/management-api/Dockerfile, docker/enterprise/am/3.x/management-api/Dockerfile-nightly, docker/gateway/Dockerfile, docker/gateway/Dockerfile-dev, docker/gateway/Dockerfile-dev-noble, docker/gateway/Dockerfile-noble, docker/management-api/Dockerfile, docker/management-api/Dockerfile-dev, docker/management-api/Dockerfile-dev-noble, docker/management-api/Dockerfile-noble, gravitee-am-ciba-delegated-service/pom.xml, gravitee-am-common/src/test/java/io/gravitee/am/common/crypto/CryptoUtilsTest.java, gravitee-am-fapi-resource-api/pom.xml, gravitee-am-performance/Dockerfile, pom.xml
=> chore: update jdk to 21.

gravitee-am-factor/gravitee-am-factor-email/src/main/java/io/gravitee/am/factor/email/provider/EmailFactorProvider.java
=> fix: always generate a new code for email factor

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandlerTest.java
fixes AM-4733
gravitee-io/issues#10317
=> fix(mfa): avoid infinite loop if session expired

gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/pom.xml, gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/main/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProvider.java, gravitee-am-authdevice-notifier/gravitee-am-authdevice-notifier-http/src/test/java/io/gravitee/am/authdevice/notifier/http/provider/HttpAuthenticationDeviceNotifierProviderTest.java
=> fix: provide valid scope value to DeviceNotification service

pom.xml
=> chore(deps): idp-ldap-plugin 2.1.2

gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/resources/schemas/schema-form.json
=> fix: removed default baseURL for loadPreAuthUserResource

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/certificate/impl/CertificateManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
=> fix(memory): stop services on undeploy domain

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
=> fix: loop redirect on invalid form /resetPassword

gravitee-am-common/src/main/java/io/gravitee/am/common/exception/oauth2/ReturnUrlMismatchException.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
=> AM-4761 fix: validation of return_url param

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidatorTest.java
=> AM-4794 userinfo redirect uri

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/dataplane/impl/DeviceManagementServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/dataplane/DeviceManagementServiceTest.java
=> fix: unable to remove device from user profile

pom.xml
=> fix: upgrade SMS factor to always change the moving factor

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/AuditReporterManager.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/ManagementAuditReporterManager.java
=> fix: reporter not available

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
=> fix: validate jdbc port as integer.

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidatorTest.java
=> AM-4842 fix: redirect_uri validation

gravitee-am-common/src/main/java/io/gravitee/am/common/scope/GatewayRepositoryScope.java, gravitee-am-common/src/main/java/io/gravitee/am/common/scope/ManagementRepositoryScope.java, gravitee-am-gateway/gravitee-am-gateway-core/src/main/java/io/gravitee/am/gateway/core/upgrader/GatewayUpgraderConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ApplicationFactorSettingsUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ApplicationIdentityProviderUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ApplicationScopeSettingsUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultEnvironmentUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultRoleUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainDataPlaneUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainIdpUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainPasswordPoliciesUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainReporterUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/InstallationUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/NonBCryptIterationsRoundsUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/OpenIDScopeUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/OrganizationReporterUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/PoliciesToFlowsUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ScopeUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/SystemCertificateUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/spring/ManagementUpgraderConfiguration.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/upgrader/ReporterReferenceMongoUpgrader.java, gravitee-am-service/src/main/java/io/gravitee/am/service/upgrader/AmUpgraderService.java
=> AM-4838: added repository scope for upgraders

gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-1-dataplane-webauthn-credentails-init.yml, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-2-dataplane-groups-init.yml, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-3-dataplane-devices-init.yml, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-4-dataplane-password_histories-init.yml, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-5-dataplane-scope_approvals-init.yml, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-6-dataplane-users-init.yml
fixes [AM-4845]
[AM-4845]: https://gravitee.atlassian.net/browse/AM-4845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AM-4845 changed lgw to gravitee team

gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcUser.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringDynamicUserGroupRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_5_11/4.5.11-dynamic-user-groups.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
=> fix: added dynamic user groups for jdbc

gravitee-am-dataplane/gravitee-am-dataplane-api/src/main/java/io/gravitee/am/dataplane/api/repository/UserRepository.java, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/repository/JdbcUserRepository.java, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/repository/model/JdbcUser.java, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/repository/spring/SpringDynamicUserGroupRepository.java, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-13-dataplane-dynamic-user-group.yml, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/dp-master.yml, gravitee-am-dataplane/gravitee-am-dataplane-test/src/test/java/io/gravitee/am/dataplane/api/repository/UserRepositoryTest.java
=> fix: dynamic user group for dataplane jdbc

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceImplTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/ProvisioningUserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/ProvisioningUserServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/registration_confirmation.html, gravitee-am-test/specs/gateway/scim/scim.spec.ts
feat: https://gravitee.atlassian.net/browse/AM-4813
=> feat: add preRegistration for SCIM

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EventServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/EventServiceTest.java
=> fix: warn when domain not found on event sync

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/ProvisioningUserServiceImpl.java
=> fix: default expiry time and client in email (AM-4859)

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserGatewayService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserGatewayServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserGatewayServiceImplV2.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2Test.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequestResolver.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterV2.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestParametersHandlerTest.java
this will help to update the accountLinking policy to be compatible with the DataPlane
its cherry-picked from restored AM-4570 branch
fixes AM-4570 AM-4854
=> fix(dataplane): remove reference to the domin in USerGatewayService signature

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/SecurityDomainRouterFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterCredentialsEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterSuccessEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnResponseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterSuccessEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandlerTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/DomainDataPlane.java, gravitee-am-service/src/test/java/io/gravitee/am/service/DomainDataPlaneTest.java
fixes [AM-4848]
[AM-4848]: https://gravitee.atlassian.net/browse/AM-4848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: update webauthn origin to dataplane gatewayurl if its missing

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/RedirectUriValidationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/common/RedirectUriValidationHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandlerTest.java
Backport of https://github.com/gravitee-io/gravitee-access-management/pull/5617 on 4.1.x
=> Backport: Fix MFA Challenge Policy issues #5617

gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/main/java/io/gravitee/am/plugins/dataplane/core/SingleDataPlaneLoader.java, gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-dataplane/src/test/java/io/gravitee/am/plugins/dataplane/core/SingleDataPlaneLoaderTest.java
=> AM-4848 fix: update webauth origin to dataplane gateway url

pom.xml
This update fix the issue AM-4880.
=> chore: update liquibase

pom.xml
=> chore: update gravitee node

gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
The problem with Timeout Exception was because the subscriber didn't finish. I've changed to blockingSubscribe and now all operation of creation index is finished.
=> fix: exception error on mongo index creation

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/NewsletterResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/JerseySpringTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/NewsletterResourceTest.java
=> fix: rework newsletter information

docs/upgrades/4.7.0/mariadb-migration.sh, docs/upgrades/4.7.0/mongodb-migration.sh, docs/upgrades/4.7.0/mysql-migration.sh, docs/upgrades/4.7.0/postgres-migration.sh, docs/upgrades/4.7.0/sqlserver-migration.sh, docs/upgrades/4.7.0/sqlserver.schema
this collection was part of the gateway scope, it is useless to migrate it
relate-to AM-4576
=> fix: remove the loginAttempt collection from migration scripts

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/SecureRandomString.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java, pom.xml
=> AM-4885 saml2 plugin upgrade 4.3 4.4

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/SecureRandomString.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java, pom.xml
=> AM-4885 saml2 plugin upgrade 4.5 4.6 4.7 master

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/ReturnUrlValidationHandler.java
just additional debug logs to be able to diagnose some weird behaviour in dev env
=> chore: addition of debug logs during return_url validation

gravitee-am-ui/src/app/services/organization.service.ts
=> AM-4890 AM-4892 plugin validation

gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
=> fix: rollback to subscribe on index mongo creation

gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
This reverts commit 0334d779a6f849f74bee2b5ab984b8cce692c997.
=> Revert "fix: exception error on mongo index creation"

gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/PasswordPoliciesResourceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/AbstractPasswordPolicy.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/passwordpolicy/CheckLength.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/passwordpolicy/PasswordPolicyCheckLengthValidator.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/passwordpolicy/PasswordPolicyCheckLengthValidatorTest.java
=> fix: put validation on minLength and maxLength

gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/changelogs/v4_7_0/4.7.0-13-dataplane-dynamic_user_groups-init.yml, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/resources/liquibase/dp-master.yml
=> fix: added dynamic_user_groups for dataplane

gravitee-am-ui/src/app/domain/settings/providers/provider/groups/groups/create/create.component.html, gravitee-am-ui/src/app/domain/settings/providers/provider/groups/groups/groups.component.ts, gravitee-am-ui/src/app/services/organization.service.ts
Fixes: AM-4841
This is fixing only the UI issue. Handling group mapper in organization will be handled in this task: AM-4923
=> fix: unable to select groups in group mapper in organization

pom.xml
=> chore: bump account-linking in version 2.0.0

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html
=> AM-4868 max consecutive letters

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/jwt/JWTServiceTest.java
=> AM-4870 jwt decoder issue

gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/saml2/saml2.component.ts
=> AM-4913 fix: added bidirectional relation for saml certificate

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationServiceTest.java
only when the clientSecret is not hashed
fixes AM-4849
=> fix: provide client secret on update/patch DCR response

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java
=> fix: define the Nonce variable to be able to execute JS secured by CSP

gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchOrganization.java, gravitee-am-service/src/test/java/io/gravitee/am/service/OrganizationServiceTest.java, gravitee-am-ui/src/app/settings/management/general/general.component.html, gravitee-am-ui/src/app/settings/management/general/general.component.ts
=> fix: null idp in organization

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/login.html
=> fix: enable login button when autofill from password manager

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/ErrorParamsUpdater.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CSRFHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSRFHandlerTest.java
=> fix: when session is expired, error query parameters must contain errorHash

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserStoreImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserStoreImplV2.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/user/UserStoreTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/user/UserStoreV2Test.java, pom.xml
=> fix: upgrade gravitee-node and avoid error if Redis cache is unreachable

gravitee-am-dataplane/gravitee-am-dataplane-mongodb/src/main/java/io/gravitee/am/dataplane/mongodb/repository/MongoLoginAttemptRepository.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java, gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java, gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/provider/impl/MongoFactory.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
fixes AM-4882
the alternative way may be adding subscribeOn with IO Subscriber but in such case, a failure may be omitted
=> AM-4882 fix: increased default socketTimeout for MANAGMENT mongodb client

docker/gateway/Dockerfile-dev-noble, docker/gateway/Dockerfile-noble, docker/management-api/Dockerfile-dev-noble, docker/management-api/Dockerfile-noble
=> chore: upgraded libc6 in noble images

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/AuditBuilder.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/AuthenticationAuditBuilder.java, gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts, postman/collections/graviteeio-am-user-management-collection-app-version.json
=> AM-4825 error message

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/GroupServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/GroupServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationMembersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationResourcesResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/MembersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/members/MembersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/MembersResourceTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcOrganizationUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringOrganizationUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/user/SpringUserRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/OrganizationUserRepositoryTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/CommonUserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/MembershipService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/ResourceService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/GroupServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ResourceServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/GroupServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ResourceServiceTest.java, gravitee-am-test/specs/management/groups.jest.spec.ts
=> fix:assign users to groups from domain

gravitee-am-ui/src/app/components/navbar/navbar.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa/mfa-select.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/factors/remember-device/mfa-remember-device.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts, gravitee-am-ui/src/app/domain/creation/domain-creation.component.ts, gravitee-am-ui/src/app/domain/settings/general/general.component.ts, gravitee-am-ui/src/app/environment/environment.component.ts, gravitee-am-ui/src/app/guards/auth-guard.service.ts, gravitee-am-ui/src/app/resolvers/domain.resolver.ts, gravitee-am-ui/src/app/services/domain.service.ts
fixes [AM-4811]
[AM-4811]: https://gravitee.atlassian.net/browse/AM-4811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AM-4811 use domainId instead of its hrid in webapp routing

.github/renovate.json5, renovate.json
We also base the config on the common renovate definition
=> chore: update renovate config to manage automerge

gravitee-am-performance/src/test/scala/io/gravitee/am/performance/CreateDomainWithMockMFA.scala, gravitee-am-performance/src/test/scala/io/gravitee/am/performance/LoginFlowWithMFA.scala, gravitee-am-performance/src/test/scala/io/gravitee/am/performance/utils/GatewayCalls.scala, gravitee-am-performance/src/test/scala/io/gravitee/am/performance/utils/ManagementAPICalls.scala, gravitee-am-performance/src/test/scala/io/gravitee/am/performance/utils/SimulationSettings.scala
this is simple scenario using MockResource and SMS factor
not perfect but we need a first implementation to provide insight
related-to AM-4937
=> chore(perf): first implementation for MFA evaluation

gravitee-am-ui/src/app/settings/domains/domains.component.html
fixes [AM-4811]
[AM-4811]: https://gravitee.atlassian.net/browse/AM-4811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AM-4811 routing of domains

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AuditServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/AuditServiceTest.java, helm/templates/api/api-configmap.yaml, helm/templates/gateway/gateway-configmap.yaml
since AM 4.3 the number of audits increase due to the client_auth audit, this is a way to reduce the audit volumes
fixes AM-5004
=> fix: allow to filter the type of audits

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml, pom.xml
=> AM-4737 feat: adapt new gravitee-node

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationSecretResource.java
=> fix: return 400 on the last secret delete exception

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationMembersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/MembersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/members/MembersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/MembersResourceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/MembershipService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java
fixes [AM-5001]
[AM-5001]: https://gravitee.atlassian.net/browse/AM-5001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: AM-5001 membership collects org users

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationSecretServiceImpl.java, gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/secrets-certificates.component.ts
=> fix: return a correct error message on secret creation

gravitee-am-service/src/main/java/io/gravitee/am/service/exception/TooManyClientSecretsException.java
=> fix: return 400 on TooManyClientSecretsException

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationSecretServiceImpl.java
=> fix: return client secret on DCR renew

gravitee-am-model/src/main/java/io/gravitee/am/model/Organization.java, gravitee-am-model/src/test/java/io/gravitee/am/model/OrganizationTest.java
=> fix: preserve the HRID on organization update

gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/secrets-certificates.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/secrets-certificates.component.scss, gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/secrets-certificates.component.ts
=> fix: remove expiresIn column

gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/secrets-certificates.component.ts
=> fix: refresh client secrets after renewal

gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/client-secrets-settings/client-secrets-settings.component.ts
=> fix: cancel when application secret settings equal 0

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/UsernameHelper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/VertxHttpServerRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/RedirectHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/ParamUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollFailureHandler.java
this is not a clean fix but playing with encoding is something tricky and may introduce regression
this change solve the issue but is indeed specific to the username parameter
fixes AM-4947
=> fix: manage specific encoding action for username parameter

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationSecretServiceImpl.java, gravitee-am-test/specs/management/client-secrets.jest.spec.ts
=> fix: error message on client secret creation

gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/client-secrets-settings/client-secrets-settings.component.ts, gravitee-am-ui/src/app/domain/settings/secrets/secrets.component.html, gravitee-am-ui/src/app/domain/settings/secrets/secrets.component.ts
=> fix: unable to save 0 in domain secret setting

gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/client-secrets-settings/client-secrets-settings.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/client-secrets-settings/client-secrets-settings.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/secrets-certificates.component.ts
=> fix:client secret application settings

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/ProvisioningUserServiceTest.java, gravitee-am-test/api/management/models/ClientRegistrationSettings.ts, gravitee-am-test/specs/gateway/scim/scim.spec.ts
=> feat: forceResetPassword for SCIM user

.circleci/workflows.yml
=> chore: upgrade aqua orb to 1.0.5

gravitee-am-model/src/main/java/io/gravitee/am/model/Certificate.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/management/CertificateAuditBuilder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/reporter/builder/CertificateAuditBuilderTest.java
=> fix: filter Metadata from the Certificate audits

gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/resources/schemas/schema-form.json, gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/resources/schemas/schema-form.json, gravitee-am-test/specs/management/certificates.jest.spec.ts
=> fix: update schema-form for certificate

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/spring/PlatformNotifierConfiguration.java
=> fix: incorrect log message when client secret is about to expire

gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/grantFlows/application-grant-flows.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/secrets-certificates/secrets-certificates.component.ts, gravitee-am-ui/src/app/domain/applications/application/design/emails/emails.component.ts, gravitee-am-ui/src/app/domain/applications/application/design/forms/forms.component.ts, gravitee-am-ui/src/app/domain/applications/application/endpoints/endpoints.component.ts, gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
Fixes AM-5146
use DomainStore for applications
=> fix: getting domain from store for application

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DomainsResource.java
=> fix: openapi spec for domain list

gravitee-am-test/api/management/apis/ApplicationApi.ts, gravitee-am-test/api/management/apis/DomainApi.ts, gravitee-am-test/api/management/apis/EmailApi.ts, gravitee-am-test/api/management/apis/FormApi.ts, gravitee-am-test/api/management/models/ClientRegistrationSettings.ts, gravitee-am-test/api/management/models/NewEmail.ts, gravitee-am-test/api/management/models/NewForm.ts, gravitee-am-test/api/management/models/PatchClientRegistrationSettings.ts, gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts, gravitee-am-test/specs/gateway/redirect-uri-el.spec.ts, gravitee-am-test/specs/management/applications.jest.spec.ts
Dependant on https://github.com/gravitee-io/gravitee-access-management/pull/5906
=> Feat/am 4928 JEST test redirect uri exp lan

gravitee-am-ui/angular.json
=> fix: angular dist path

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/AbstractLogoutEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java
=> fix: check presence of userInfo in the postLogout url

docs/mapi/openapi.yaml
=> chore: [4.7.x] openapi update

docs/mapi/openapi.yaml
=> chore: [4.5.x] openapi update

gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DomainServiceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/domain/DomainValidatorImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/dynamicparams/ClientRedirectUrisValidator.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/dynamicparams/ClientRegistrationSettingsValidator.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/DomainValidatorTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/dynamicparams/ClientRedirectUrisValidatorTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/dynamicparams/ClientRegistrationSettingsValidatorTest.java, gravitee-am-test/specs/management/applications.jest.spec.ts
=> fix: validation of all the apps on enabling dynamic params

gravitee-am-service/src/main/java/io/gravitee/am/service/utils/EvaluableRedirectUri.java, gravitee-am-service/src/test/java/io/gravitee/am/service/utils/EvaluableRedirectUriTest.java, gravitee-am-test/specs/gateway/redirect-uri-el.spec.ts, gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
=> fix: evaluating query param without key

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java, gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html, gravitee-am-ui/src/app/domain/applications/creation/steps/step2/step2.component.html, gravitee-am-ui/src/app/domain/settings/openid/client-registration/settings/settings.component.html
=> fix: messages rephrasing,

gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
=> fix: for dynamic parameters ensure to remove the preceding ampersand

gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/test/java/io/gravitee/am/dataplane/api/repository/test/AbstractTestRepositoryConfiguration.java, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/test/java/io/gravitee/am/dataplane/api/repository/test/JdbcDataPlaneTestConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/resources/container-license-acceptance.txt, gravitee-am-reporter/gravitee-am-reporter-jdbc/src/test/java/io/gravitee/am/reporter/jdbc/audit/JdbcReporterJUnitConfiguration.java, gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/ConnectionFactoryProvider.java
=> fix: define preferCursorExecution option only for SQLServer

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/spring/JdbcAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/utils/PasswordEncoder.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/authentication/spring/JdbcAuthenticationProviderConfigurationTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/spring/MongoAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/utils/PasswordEncoder.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/spring/MongoAuthenticationProviderConfigurationTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/PBKDF2PasswordEncoder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/PBKDF2PasswordEncoderTest.java
=> feat(idp): add support for PBKDF2 password encoder

gravitee-am-ui/yarn.lock
=> fix: regenerate yarn.lock

gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
=> AM-5255 fix: removing el dynamic params on overview page

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/XForwardedHeadersSanitizer.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
=> AM-5196 sanitize x headers

gravitee-am-ui/src/app/domain/components/emails/email/email.component.ts, gravitee-am-ui/src/app/domain/components/forms/form/form.component.ts
=> fix: open iframe after loaded

gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/PBKDF2PasswordEncoder.java
=> fix(idp): add missing encode method with dedicated salt for PBKDF2 password encoder

pom.xml
=> chore: update FranceConnect to 3.1.1

.circleci/workflows.yml, gravitee-am-test/README.adoc
=> chore: add ee plugins to jest tests pipeline

gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/FileReporterConfiguration.java, gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/audit/FileAuditReporter.java, gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/vertx/VertxFileWriter.java, gravitee-am-reporter/gravitee-am-reporter-file/src/main/resources/schemas/schema-form.json, gravitee-am-reporter/gravitee-am-reporter-file/src/test/java/io/gravitee/am/reporter/file/vertx/VertxFileWriterTest.java
=> feat(reporter): support retainDays for Reporter File

gravitee-am-test/api/commands/gateway/login-commands.ts, gravitee-am-test/api/commands/management/flow-management-commands.ts, gravitee-am-test/specs/gateway/account-link.jest.spec.ts, gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts, gravitee-am-test/specs/gateway/flow-execution.jest.spec.ts, gravitee-am-test/specs/gateway/login-flow.jest.spec.ts, gravitee-am-test/specs/gateway/mfa/mfa-challange-required.spec.ts, gravitee-am-test/specs/gateway/redirect-uri-el.spec.ts, gravitee-am-test/specs/management/applications.jest.spec.ts
=> chore: account linking jest tests

gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/spring/AbstractRepositoryConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/logback.xml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/AbstractRepositoryConfiguration.java
this is useful to diagnose a lock issue with liquibase on kubernetes
fixes AM-5130
=> chore: addition of INFO log to know when Liquibase start

gravitee-am-test/specs/gateway/mfa/fixture/mfa-flow-fixture.ts, gravitee-am-test/specs/gateway/mfa/fixture/mfa-setup-fixture.ts, gravitee-am-test/specs/gateway/mfa/mfa-challange-required.spec.ts
related to AM-5310
fix AM-5319
=> chore: mfa cookie remember device jest tests

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/code/AuthorizationCodeServiceTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/api/AuthorizationCodeRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MariadbHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MsSqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MySqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/PostgresqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/JdbcAuthorizationCodeRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/oauth2/api/spring/SpringAuthorizationCodeRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAuthorizationCodeRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/oauth2/api/AuthorizationCodeRepositoryTest.java, gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts
=> feat: retrieving auth code should remove it at the same time

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/OrganizationUsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
=> fix: min validation on users get

gravitee-am-management-api/gravitee-am-management-api-rest/pom.xml, pom.xml
This PR upgrades the libs to fix vulns
=> chore: upgrade commons-lang3 to 3.18.0 & nimbus jose to 10.4

gravitee-am-common/src/main/java/io/gravitee/am/common/el/ELFunction.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RoutingContextUtils.java, gravitee-am-model/src/main/java/io/gravitee/am/model/User.java, gravitee-am-model/src/main/java/io/gravitee/am/model/factor/EnrolledFactor.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/EnrolledFactorProperties.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java, gravitee-am-model/src/test/java/io/gravitee/am/model/UserTest.java, gravitee-am-model/src/test/java/io/gravitee/am/model/safe/UserPropertiesTest.java
closes AM-5237
`{#context.attributes['user'].enrolledFactorsByType['SMS']}`
or
`{#context.attributes['user'].enrolledFactors['factorId']}`
=> AM-5237 MFA enrollment/challenge flow utility method

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java
=> fix: prevent closing session if idToken is missing

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
=> fix: map dynamic roles when account linking is used.

gravitee-am-test/api/commands/management/user-management-commands.ts, gravitee-am-test/api/management/apis/UserApi.ts, gravitee-am-test/api/management/models/FlowEntity.ts, gravitee-am-test/specs/gateway/am-oauth2-app-version.jest.spec.ts, gravitee-am-test/specs/gateway/force-reset-password-expiration.spec.ts, gravitee-am-test/specs/gateway/mfa/fixture/mfa-extract-fixture.ts, gravitee-am-test/specs/gateway/mfa/fixture/mfa-setup-fixture.ts, gravitee-am-test/specs/gateway/mfa/mfa-factor.spec.ts
=> chore: MFA enroll multiple factors jest test

gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java, gravitee-am-model/src/main/java/io/gravitee/am/model/common/event/Event.java, gravitee-am-model/src/main/java/io/gravitee/am/model/common/event/EventKey.java, gravitee-am-model/src/test/java/io/gravitee/am/model/common/event/EventKeyTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/vertx/EventBusReporterWrapper.java
=> fix: AM-5233 global kafka reporter

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestParametersHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequestResolver.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestParametersHandlerTest.java
=> feat: add user to CIBA context

pom.xml
=> hotfix: ldap not initialized connection closing (update LDAP version)

gravitee-am-reporter/gravitee-am-reporter-file/src/main/java/io/gravitee/am/reporter/file/vertx/VertxFileWriter.java
fixes: AM-5504
Trigger the clean up process when the service first starts up to clean up any existing files left over from the service running previously. Also added in some debug logging for future investigations.
--- 
The log cleanup was working as designed, but it only ran during the daily rollover at midnight.
This meant that if the service was restarted during the day, old log files weren’t removed until the next midnight, which gave the impression cleanup wasn’t working.
We’ve updated the logic so that cleanup also runs immediately on startup (when retention is configured), in addition to the midnight rollover. This ensures old files are purged right away after a restart.
Follow steps in the ticket, key indicator here is that the clean up process is now triggered on start up as well …
=> feat: enhance file retention logic with debug logging and improved cleanup

pom.xml
=> chore: update LDAP version

pom.xml
=> fix: update LDAP version to fix connection pool

gravitee-am-ui/src/app/domain/settings/users/users.component.spec.ts, gravitee-am-ui/src/app/domain/settings/users/users.component.ts
[AM-5534](https://gravitee.atlassian.net/browse/AM-5534)
Linting fixes.
n/a
n/a
n/a
@gravitee-io/am 
[AM-5534]: https://gravitee.atlassian.net/browse/AM-5534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: AM-5534 correct typescript formatting

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java, helm/templates/common/_configmap-default-database.tpl, helm/tests/common/configmap_database_test.yaml
=> fix: missing port and host in helm charts

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/GraviteeContext.java, gravitee-am-common/src/main/java/io/gravitee/am/common/utils/WriteStreamRegistry.java, gravitee-am-common/src/test/java/io/gravitee/am/common/utils/WriteStreamRegistryTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/audit/impl/GatewayAuditReporterManager.java, gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/KafkaReporterConfiguration.java, gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/audit/KafkaAuditReporter.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/impl/AuditReporterVerticle.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/impl/ReportableHandlerLogger.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/vertx/EventBusReporterWrapper.java
fixes AM-5143
Steps to reproduce:
1. create 100 domains
2. create organization kafka reporter
3. mark it as GLOBAL
4. notice SINGLE KafkaProducer
5. enable/disable/enable/mark as non-global/mark as global
6. add domain kafka reporter to same topic - confirm no KafkaProducer is created
7. add domain kafka reporter to a different topic - confirm  KafkaProducer is created
=> AM-5143 fix: messages stopped being reported after some disables and enables

gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/main/java/io/gravitee/am/dataplane/jdbc/spring/AbstractRepositoryConfiguration.java, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/test/java/io/gravitee/am/dataplane/api/repository/test/AbstractTestRepositoryConfiguration.java, gravitee-am-dataplane/gravitee-am-dataplane-jdbc/src/test/java/io/gravitee/am/dataplane/api/repository/test/JdbcDataPlaneTestConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcIdentityProviderConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DefaultIdentityProviderServiceImpl.java, gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/JdbcReporterConfiguration.java, gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/audit/JdbcAuditReporter.java, gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/dialect/AbstractDialect.java, gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/dialect/DialectHelper.java, gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/dialect/MSSQLDialect.java, gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/dialect/PostgresqlDialect.java, gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/R2DBCConnectionConfiguration.java, gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/ConnectionFactoryProvider.java, gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/R2DBCPoolWrapper.java, gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/utils/SchemaSupport.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/AbstractRepositoryConfiguration.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/AbstractTestRepositoryConfiguration.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractRepositoryConfiguration.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java, helm/templates/common/_configmap-default-database.tpl, helm/tests/api/configmap_repositories.yaml, helm/tests/gateway/configmap_repositories.yaml
=> feat: added currentSchema property for postgres uri connection

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java
=> fix: Enhance idp plugin redeployment to avoid downtime

gravitee-am-repository/gravitee-am-repository-mongodb-api/src/main/java/io/gravitee/am/repository/mongodb/common/MongoUtils.java
[AM-5585](https://gravitee.atlassian.net/browse/AM-5585)
Add logging and retry logic to mongodb `dropIndexes` utility. This helps with race conditions that can occur when initialising collections.
For example, starting up AM in docker containers with a new mongodb causes indexes to be created and dropped simultaneously from different processes. Previously the gateway could log:
```
10:30:05.826 [nioEventLoopGroup-2-28] [] ERROR i.g.a.r.mongodb.common.MongoUtils - An error has occurred while deleting index d1c1u1
com.mongodb.MongoCommandException: Command failed with error 12587 (BackgroundOperationInProgressForNamespace): 'cannot perform operation: a background operation is currently running for collection graviteeam.scope_approvals' on server mongodb:27017. The full response is {"ok": …
```
=> fix: AM-5585 retry drop mongodb indexes

gravitee-am-test/specs/gateway/fixtures/mobile-pkce-fixture.ts, gravitee-am-test/specs/gateway/mobile-pkce-flow.jest.spec.ts
AM-4843
jest test mobile app redirect-uri validation using PKCE flow
=> test: AM-4843 jest test mobile app pkce

gravitee-am-test/api/commands/management/domain-management-commands.ts, gravitee-am-test/api/fixtures/jwt.ts, gravitee-am-test/specs/gateway/ext-grant-jwt-bearer.jest.spec.ts
closes AM-4389
npm run test ext-grant-jwt-bearer.jest.spec.ts
=> feat: AM-4389 added JEST test for ext grant + introspection scenario
