gravitee-io/gravitee-access-management

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json
It should be documented that the search-bases in ldap should be relative
=> Document that the seach-bases in ldap should be relative to base-dn

docker/management-api/Dockerfile, docker/management-api/Dockerfile-nightly
Exposed port in Dockerfiles for management-api are wrong.
=> exposing port 8093 instead of 8092

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/view/freemarker/FreeMarkerConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/spring/EmailConfiguration.java
Closes gravitee-io/issues#2232
=> fix(mail): Escape the content of the HTML templates when used for emails

Makefile, gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/GrantType.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/jwt/JWTServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/impl/OpenIDDiscoveryServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationServiceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/GrantTypeUtils.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/ResponseTypeUtils.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/UriBuilder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ClientServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/utils/GrantTypeUtilsTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/utils/ResponseTypeUtilsTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/utils/UriBuilderTest.java, gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.html, gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.ts, postman/collections/graviteeio-am-client-management-collection.json, postman/collections/graviteeio-am-login-collection.json, postman/collections/graviteeio-am-oauth2-collection.json, postman/collections/graviteeio-am-openid-core-collection.json, postman/collections/graviteeio-am-openid-dcr-collection.json, postman/collections/graviteeio-am-openid-discovery-collection.json
In order to run NRT, you must merge this [PR](https://github.com/gravitee-io/graviteeio-access-management/pull/592) before.
This fix issue [#2297](https://github.com/gravitee-io/issues/issues/2297)
Set redirect_uri as mandatory in the UI when grant_type require it
Set redirect_uris as not mandatory in DCR when grant_type does not require it
Remove default openid scope in DCR
Forbid selection of refresh_token grant when not necessary (DCR & UI)
Discovery grant & response types values are now delivered through Utils services
Add device_code grant (but not into the supported grant)
Some UI documentation improvements
=> redirect_uris management + additional behaviour

gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts
=> fix(accountSettings): display one hour duration for account settings

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/AbstractRequestResolver.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/AuthorizationRequestResolverTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/TokenRequestResolverTest.java
This PR fixes Access Management issue https://github.com/gravitee-io/issues/issues/2958.
Sopes related to user's permissions are always granted when the client is configured with option "Enhance scopes" (that is if `client.isEnhanceScopesWithUserPermissions() == true`).
Related test cases are included in this PR.
=> Always enhance request with users permissions if required

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/proxy/UserRepositoryProxy.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/UserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/management/MongoUserRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/UserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
This PR fixes issue https://github.com/gravitee-io/issues/issues/2994 by taking into account the page parameter in the users list endpoint of the Management API not only for users listing but also for searching (when parameter `q` is passed).
The actual fix is in the MongoDB query: call to `skip()` was missing in class `MongoDbRepository`. The rest are simply adaptations of methods signatures, in order to pass the `page` parameter from the endpoint to the query.
Added also a test case to check the correctness of paginated results.
=> Fix users search pagination in Management API

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html
…when query parameter `warning` is present.
Add the same message in form-info.component.html in REGISTRATION_CONFIRMATION raw template.
Closes [gravitee-io/issues#3057](https://github.com/gravitee-io/issues/issues/3057)
=> Add invalid password message on registration_confirmation.html

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxHttpServerFactory.java
Closes gravitee-io/issues#3161
=> fix(http): HTTP listener keystore not properly configured

gravitee-am-ui/src/app/domain/domain.component.html, gravitee-am-ui/src/app/domain/domain.component.ts
Closes gravitee-io/issues#3432
=> fix(ui): display domain activation banner only when user has permission

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/OrganizationResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/FactorResource.java, gravitee-am-ui/src/app/services/organization.service.ts
The OpenApi descriptor was invalid due to
* the plugins routes defined under organizations: plugins are not related to an organization but they are related to higher-level (platform).
They should be called from `/management/platform/plugins/**`
It breaks the validation of the OpenApi descriptor (swagger.json) because plugins routes were not using the `organizationId` path params therefore it was not added to the descriptor.
* the path param in `FactorResource`: `policy` was incorrect, `FactorsResource` defines `{factor}` in the path
=> Fix AM management api OpenApi descriptor

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/impl/attestation/AppleAttestation.java
=> fix(webauthn): set up default public key credential for apple attestation

gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/CertificateFormat.java, gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/CertificateKey.java, gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/RSAKeyUtils.java, gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/X509CertUtils.java, gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/provider/JavaKeyStoreProvider.java, gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/java/io/gravitee/am/certificate/pkcs12/provider/PKCS12Provider.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/CertificateResource.java, gravitee-am-ui/src/app/domain/applications/application/advanced/certificates/certificates.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/certificates/certificates.component.ts, gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts, gravitee-am-ui/src/app/domain/settings/certificates/dialog/public-key.component.html, gravitee-am-ui/src/app/services/certificate.service.ts
closes gravitee-io/issues#5005
=> feat(certificate): support PEM format

.circleci/config.yml, pom.xml
This PR brings, for `3.0.x` git branch:
* the same `.circleci/config.yml` as git branches on which releases have been done with new CICD ( `3.8.x`, `3.7.x`, `3.5.x`, etc....) : 
* worth mentioning there: this  `.circleci/config.yml` allows "choosing if `kerberos` and `cas` identity providers are in the `Gravitee AM` `EE` release" -> If pipeline parameters `ee_id_provider_cas_version` and `ee_id_provider_kerberos_version` are empty strings (they are by default), then the `Gravitee AM` `EE` Release will not include the `kerberos` and `cas` identity providers
* plus gravitee parent upgrade to `19.2.1` : the gravitee parent version currently is `19`, and the `19.2.1` version is exactly the same as  `19` version, except there is only one additional maven profile, required by the new CICD
=> New Cicd Migration : Circle CI config.yml and gravitee parent upgrade

gravitee-am-ui/pom.xml
added required maven license plugin exclusions of 'dist/' and 'node_modules' directories : 
* otherwise pull_requests Circleci workflow fails (forgot to add that with https://github.com/gravitee-io/graviteeio-access-management/pull/1125 )
* just like on `master` for example, see https://github.com/gravitee-io/graviteeio-access-management/blob/53fb94819ce5c6ce538c650d460d61e3b01204ab/gravitee-am-ui/pom.xml#L54
* fixes: https://app.circleci.com/pipelines/github/gravitee-io/graviteeio-access-management/1649/workflows/ee40dfe8-feda-4ada-ba0d-936c08414897/jobs/1883
* tested with : https://app.circleci.com/pipelines/github/gravitee-io/graviteeio-access-management/1650/workflows/0451d6d9-3853-4045-b1e7-08641696429c/jobs/1885
=> Gravitee AM UI : maven license plugin exclusions of 'dist/' and 'node_modules' directories

pom.xml
closes gravitee-io/issues#5478
=> chore(deps): bump gravitee-cockpit-connectors-ws to 1.0.1

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxHttpServerConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxHttpServerFactory.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
=> chore(): be able to override max vertx http server configuration values

.circleci/config.yml
Configure a daily scheduled job to purge Docker images.
It will purge images that are 1 day old and keep only 3 tags of each.
=> chore: purge docker images

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/AbstractRequestResolver.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/AuthorizationRequestResolverTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/TokenRequestResolverTest.java
Fixes [gravitee-io/issues#3839](https://github.com/gravitee-io/issues/issues/3839)
=> return only the requested scopes when the enhance scopes with user permission option is active

gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/OrganizationUserRepositoryTest.java
=> fix: use right source value for OrganizationUser tests

gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplication.java
=> fix: authorize empty as value to updtade the application certificate

pom.xml
gravitee-cockpit-connectors@2.0.0 needs gravitee-cockpit-api@1.7.0 & gravitee-plugin@1.18.0
Related https://github.com/gravitee-io/issues/issues/5909
=> chore: bump gravitee-plugin & gravitee-cockpit-api

.circleci/config.yml
This PR is created in order to update the orb version used,
the version used : gravitee: gravitee-io/gravitee@dev:1.0.40
After releasing the next AM version, i will merge the orb PR and edit the orb version again
=> Updating orb version

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/ParamUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java
relates to: issues/6397
Whenever we don't have wildcards in the pattern, the latter became empty
=> fix: wildcard url was not adding full pattern when no wildcard was input

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/PasswordPolicyRequestParseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserRequestHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/register/RegisterProcessHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/reset_password.css, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/password-validation.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/user/PasswordPolicyRequestParseHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/PasswordSettings.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/PasswordSettingsMongo.java, gravitee-am-service/src/main/java/io/gravitee/am/service/PasswordService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PasswordServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchPasswordSettings.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/password/impl/UserProfilePasswordValidator.java, gravitee-am-service/src/test/java/io/gravitee/am/service/PasswordServiceImplTest.java, gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.ts, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts
closes: https://github.com/gravitee-io/issues/issues/6521
This feature allows to exclude user profile information within the password (case insensitive)
The testing process is the same as this one: https://github.com/gravitee-io/gravitee-access-management/pull/1456
Instead: Toggle `Exclude user profile information in password` in the Password Policy Settings
~Also do not merge before https://github.com/gravitee-io/gravitee-access-management/pull/1456 is merged !~
=> feat: user profile pattern password validation

CHANGELOG-v3.adoc, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/rememberdevice/DeviceIdentifierHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/rememberdevice/RememberDeviceSettingsHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-login.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_login.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/rememberdevice/DeviceIdentifierHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/rememberdevice/RememberDeviceHandlerTest.java
closes: https://github.com/gravitee-io/issues/issues/6871
This PR enables remember device with WebauthN.
If testing with chrome, make sure that cross-origin security is not enabled since FpJs pro makes Cross-Origin requests to get a visitorId
=> fix: deviceId with webauthn

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UserResourceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/UserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts, gravitee-am-ui/src/app/domain/settings/users/users.component.ts, postman/collections/graviteeio-am-login-collection-app-version.json
closes: https://github.com/gravitee-io/issues/issues/6785
To test:
Ask a token: 
```bash
curl -vvv --location -g --request POST 'http://localhost:8093/management/auth/token' \                                                
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'grant_type=password' \
--data-urlencode 'username=username' \
--data-urlencode 'password=password' --header 'Authorization: Basic Base64Encode(username:password)'
```
Lock the user
```bash
curl -vvv -XPOST \ 
http://localhost:8093/management/organizations/<orgId>/environments/<envId>/domains/<domainId>/users/<userId>/lock \
-H 'Authorization: Bearer <token>'
```
Try to login.
If the user was locked already with Brute Force Login. It locks the user and removes any login attempt counter.
=> feat(management): add lock user endpoint API

.circleci/config.yml
This PR is created in purpose of migrating the secrets retrieving from the keeper CLI as secrethub will be soon migrated to 1password secrets management, and it will be non opertational at **1st of April**
New keeper orb is developped, and it works the same way as the secrethub orb, so the changes in this PR are mostly replacement of secrethub with keeper
Keeper orb link : https://github.com/gravitee-io/keeper-circleci-orb/tree/v0.5.0
CCI Pipeline link : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-access-management/5659/workflows/47381d0d-e250-4494-b91b-739539af2b9c
=> ci: secrethub to keeper

.circleci/config.yml, .circleci/workflows.yml, docker/enterprise/am/3.x/gateway/Dockerfile, docker/enterprise/am/3.x/management-api/Dockerfile, docker/enterprise/am/3.x/management-ui/Dockerfile, pom.xml
fixes: https://github.com/gravitee-io/issues/issues/7342
This PR is created in order to add the build and push workflow of v3 and v2 ee dockerfiles, that build and push the ee dockerfiles to the dockerhub repository, also all ee dockerfiles were now moved to this repo,
docker build test was launched using the orb, to build the am_v3 dockerfiles
CircleCI link : https://app.circleci.com/pipelines/github/gravitee-io/gravitee-access-management/6082/workflows/164555e4-154a-4f0b-855d-0d56681a43ec
see this slab page for documentation on how to build and push the images : https://gravitee.slab.com/posts/build-push-am-ee-docker-image-bzsehw7p
=> cicd: EE Dockerfiles migration

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java, gravitee-am-ui/src/app/domain/settings/users/users.component.ts
fixes: https://github.com/gravitee-io/issues/issues/7439
The duplicates may have been due to the search filter not being kept
=> fix: search user management api may provide duplicates

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSessionHandler.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationResource.java, gravitee-am-model/src/main/java/io/gravitee/am/model/CookieSettings.java, gravitee-am-model/src/main/java/io/gravitee/am/model/SessionSettings.java, gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSettings.java, gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/ClientProperties.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationSettingsMongo.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/CookieSettingsMongo.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/SessionSettingsMongo.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSettings.java, gravitee-am-ui/src/app/app-routing.module.ts, gravitee-am-ui/src/app/app.module.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/cookie/cookie.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/cookie/cookie.component.spec.ts, gravitee-am-ui/src/app/domain/applications/application/advanced/cookie/cookie.component.ts, gravitee-am-ui/src/app/domain/components/cookie/cookie-settings.component.html, gravitee-am-ui/src/app/domain/components/cookie/cookie-settings.component.spec.ts, gravitee-am-ui/src/app/domain/components/cookie/cookie-settings.component.ts
fixes https://github.com/gravitee-io/issues/issues/7526
This PR brings session persistence configuration at application level.
- Login to AM console
- Go to `Application > Your App > Settings > Cookie Settings`
- Configure your Cookie Settings with `Inherited Configuration`
- Initiate the login flow (`/domain/oauth/authorize`) and login normally
- Once logged in close your browser entirely
- Initiate the login flow (`/domain/oauth/authorize`
Result: You should be able to be redirected automatically without a second login
- Login to AM console
- Go to `Application > Your App > Settings > Cookie Settings`
- Configure your Cookie Settings with `Persistent session` to `false`
- Initiate the login flow (`/domain/oauth/authorize`) and login normally
- Once logged in close your browser entirely …
=> feat: persistent session at application level

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/spring/JdbcAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/spring/MongoAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json, gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/SHAMD5PasswordEncoder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/SHAMD5PasswordEncoderTest.java
closes gravitee-io/issues#7404
=> feat(idp): add support for SHA256+MD5 password encoder for JDBC

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/AbstractSensitiveProxy.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/SensitiveDataMaskingTest.java, gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/resources/schemas/schema-form.json
fixes gravitee-io/issues#7482
The purpose of this PR is to mask the user password when present into the connection URI of a plugin (IDP, reporter...)
On update, 
* if the value provided by the frontend contains only '*', the old password is reused
* if the value provided by the frontend is the same as the one provided by the GET method, the value is not updated (into DB password isn't replace by wilcard)
* if the value doesn't contains only wildcard into the user password, the URI is updated and the new password is persisted
=> fix: mask password in sensitive URI

.circleci/workflows.yml
Release job notification for release and release_dry_run workflows to slack channel. Also updated default message for snyk scan if scan job doesnt execute
https://app.zenhub.com/workspaces/graviteeio---access-management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/7568
=> chore: release job slack notification

.circleci/workflows.yml, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ApplicationResourceTest.java, gravitee-am-model/pom.xml, gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSettings.java, gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationSettingsMongo.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/risk/AssessmentSettingsMongo.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/risk/RiskAssessmentSettingsMongo.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplication.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSettings.java, gravitee-am-service/src/main/java/io/gravitee/am/service/utils/PermissionSettingUtils.java, gravitee-am-service/src/test/java/io/gravitee/am/service/utils/PermissionSettingsUtilsTest.java, pom.xml, sonar-project.properties
issue: https://github.com/gravitee-io/issues/issues/7556
Note this is only the backend part.
Also needs this one to be released before merging: 
- https://github.com/gravitee-io/gravitee-risk-assessment-api
This PR brings the Risk Assessment configuration in the AM
1. Get a token
```bash
curl -X POST \
http(s)://AM_MANAGEMENT_API/management/auth/token \
-H 'Authorization: Basic base64(username:password)' 
```
2.  Make sure you have a domain and an application
Then   
```
curl -X 'PATCH' -H "Authorization: Bearer <token>"  http://AM_MANAGEMENT_API/management/organizations/DEFAULT/environments/DEFAULT/domains/<domainId>/applications/<app_id>
--data-raw '{
"settings": {
"riskAssessment": {
"enabled": true,
"deviceAssessment": {
"enabled": true,
"thresholds": {
"HIGH": 0
}
}, …
```
=> feat(backend): risk assessment in application settings

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandlerTest.java
fixes gravitee-io/issues#7708
Changed the policy chain handler to add a property to the RoutingContext indicating a post login error and replaced call to `context.fail` with `context.next` so that the handler chain continues, rather than being interrupted.
Here's the cloudapp page after authenticating with a post login error (note the error=server_error fragment):
=> fix: redirect to RP after post login error

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/AuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/UserCredentialEvaluation.java, gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/test/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTest.java
https://github.com/gravitee-io/issues/issues/7797
This PR brings to MongoDB and JDBC identity providers to count login attempt failures based on both username and email which allows to find the user back regardless of their input username/email
Test login in with JDBC or MongoDB at least once. 
Logout and then try to fail logins with both username and email.
=> feat: handle login attempt count with 'alias' username

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutCallbackEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java
https://github.com/gravitee-io/issues/issues/7808
This PR handles decorating the redirect request with original parameters when there is an error in the Gateway
Configure a failing procedure (like HTTP callout and make it exit on error)
=> fix: decorate with initial parameters when handler is failing

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/UserService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpointTest.java, gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html
https://github.com/gravitee-io/issues/issues/7796
This PR brings forgot password submission confirmation to display the email
1. Activate forgot password
2. Initiate the login flow
3. Click to forgot password
4. Input the email of a known user
5. When confirmed your email should be display in the confirmation box
=> feat: display user email when forgot password contains email

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/pom.xml, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/listener/AuthenticationEventListener.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/client/impl/ClientManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/pom.xml, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProvider.java, gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/DefaultReactor.java, gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/pom.xml, gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/pom.xml, gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/pom.xml, gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/pom.xml, gravitee-am-monitoring/pom.xml, gravitee-am-monitoring/src/main/java/io/gravitee/am/monitoring/metrics/Constants.java, gravitee-am-monitoring/src/main/java/io/gravitee/am/monitoring/metrics/CounterHelper.java, gravitee-am-monitoring/src/main/java/io/gravitee/am/monitoring/metrics/GaugeHelper.java, gravitee-am-performance/src/test/scala/io/gravitee/am/performance/BasicLoginFlow.scala, gravitee-am-performance/src/test/scala/io/gravitee/am/performance/CreateUsers.scala, pom.xml
fixes gravitee-io/issues#7114
Enable the metris endpoint on the admin api
`gravitee_services_metrics_enabled=true`
Connect to the endpoint:
* For the GW
`http://localhost:18092/_node/metrics/prometheus`
* For the Manaement API
`http://localhost:18093/_node/metrics/prometheus`
You should see metrics related to am:
We currently have metrics about :
* number of domains
* number of apps
* number of idps
* number of authentication
* number of sync events
=> chore: instrument AM to provide metrics about AM Internals and Activity

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/UserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-gravitee/src/main/java/io/gravitee/am/identityprovider/gravitee/user/GraviteeUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/configuration/HttpUsersResourcePathsConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/HttpUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/user/HttpUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/user/HttpUserProviderTestConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider_Test.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTestConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
fixes gravitee-io/issues#7800
Purpose of this change is to provide dedicated method in the UserProvider interface to update user password instead of relying on a single update user method.
You need to do these tests with Mongo IDP, JBDBC IDP and HTTP IDP.
:warning: For JDBC & Mongo, test a configuration with and withour dedicated salf field
* Update a user attribute through UI ==> password and salt are not changed
* Update a user attribute through SCIM (do not include the password field) ==> password and salt are not changed
* Update a user password through UI ==> password and salt are changed
* Update a user attribute through SCIM by including the password field ==> password and salt are changed
* Request a new password on the GW using forgot password link ==> after the reset password …
=> fix: create & use updatePassword on UserProvider

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
=> fix: update accountNonLocked attribute after successful login

gravitee-am-common/src/main/java/io/gravitee/am/common/event/AlertEventKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/alert/AlertEventProcessor.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/RiskAssessmentConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/RiskAssessmentService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/auth/provider/impl/UserAuthProviderImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/utils/RiskAssessmentServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/AlertTriggerManager.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/alerts/AlertTriggerFactory.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/alerts/risk/GeoVelocityAlert.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/alerts/risk/IpReputationAlert.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/alerts/risk/RiskAssessmentAlert.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/alerts/risk/UnknownDeviceAlert.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/alerts/AlertTriggerFactoryTest.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-model/src/main/java/io/gravitee/am/model/alert/AlertTriggerType.java, gravitee-am-ui/src/app/domain/alerts/general/general.component.ts, sonar-project.properties
Fixes https://github.com/gravitee-io/issues/issues/7638
Two main changes in this PR:
1. Additional Risk Assessment alert that can be enabled/disabled in the UI (see screenshot below)
2. New class in `RiskAssessmentHelper`, used by `AlertEventProcessor` for retrieving these configured values which are then used to compute the risk assessment at the risk assessment service.
In the absence of the risk assessment service the most that can be manually tested is that enabling/disabling the risk assessment alert in AM leads to an alert trigger being created/removed in the Alert Engine. An instance of Alert Engine is therefore required as well as the AM plugin for connecting to Alert Engine.
You can use coma-separated values to configure the Trigger (there will be a default configuration) in the …
=> feat: risk-based alerts

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
https://github.com/gravitee-io/issues/issues/7884
This change sets context 'actual_username' conditionally base on `authentication.getPrincipal()`
Detail mentioned in github issue
=> fix: brute force detection failed for username with capital letter

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts
https://github.com/gravitee-io/issues/issues/7969
This PR fixes the display of `Activate MFA` option when a newly create application is done
1. Create An Application
2. Create a Factor
3. Go to your application MFA settings
4. Select a factor
5. Notice the option chosen is `Optional`
=> fix: display OPTIONAL option in MFA settings first when an application is newly created

gravitee-am-factor/gravitee-am-factor-email/src/main/java/io/gravitee/am/factor/email/provider/EmailFactorProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MfaFilterContext.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaSkipUserStronglyAuthFilter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/NoFactorFilter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/RememberDeviceFilter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java
https://github.com/gravitee-io/issues/issues/7971
This PR fixes the MFA challenge not being prompted when the end user has a remembered device
1. Create a domain with OTP factor
2. Create an instance of FingerPrint plugins
3. Create an app with OTP enabled as factor and the remember device toggle active (for 10 minutes to have time to do the use case)
4. Create a fresh new user
5. Authenticate this user
6. Register the OTP factor (select remember device) and provide challenge code
7. Logout the user
8. In the Management UI, check that the user have an active device id
9. Go the factor tab linked to the user and remove the OTP factor
10. Authenticate this user
11.  Flash their OTP QRCode and click verify
12. Challenge should be prompted even if device is remembered
=> fix: do not make remember device skip MFA until factor is active

gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.html
relates to closed: https://github.com/gravitee-io/issues/issues/7827
fixes gravitee-io/issues#8311
This fixes a typo on the domain whitelist description
=> fix: change the description of the idp domain whitelist

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTestConfiguration.java
This fix checks existing user in db has the credentials or not. The check is reverted code which was deleted in previous commit.
=>  fix: resolved pre-registration user login issue

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/SecurityDomainRouterFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/dictionary/I18nDictionaryManager.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/spring/HandlerConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/view/thymeleaf/DomainBasedDictionaryProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/view/thymeleaf/GraviteeMessageResolver.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/botdetection/BotDetectionManagerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/deviceidentifiers/DeviceIdentifierManagerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/dictionary/I18nDictionaryManagerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/email/EmailManagerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/view/thymeleaf/DomainBasedDictionaryProviderTest.java
closes gravitee-io/issues#8040
1. Create a new en dictionary
2. For this dictionary, create one translation  `login.page.title`  : 'New Login title`
3. Try to login to your application, the Login title page should be : **New Login title**
=> feat(i18n): manage security domain dictionaries in the gateway

gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ThemesResourceTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ThemeServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewTheme.java
=> fix(theme): manage the secondary Text color on theme creation

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTestConfiguration.java
fixes gravitee-io/issues#8379
1. Create a new MongoDB IDP on your domain
2. configure this idp to use the collection "idp-test-8379"
3. update the query to find the user by email with this one : `{ $or : [{email: ?}, {alternative_email: ?}]}`
4. insert in this collection the following user 
```
{"_id":"ed22436d-1257-463e-a243-6d1257663e33",
"username":"user01",
"password":"$2a$10$lYYqk8RHX5OQZ2QDW2boJeB3J431WuYZk2Slnwqx7IVGqOIXawZXe",
"given_name":"user01",
"family_name":"user01",
"email":"user01@acme.fr",
"alternative_email":"user01-alt@acme.fr"
}
```
5. enable a new APP and enable only this IDP
6. enable the forgot password option
7. request a new password for the user using the email or the alternative_email, the email should be received.
=> fix(idp): make multifields query parsable for the MongoDB UserProvider

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
=> fix(login): inject external identity providers during the passworless login flow

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/main.css, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/mfa_challenge.html
fixes gravitee-io/issues#8368
Added `height:auto` to the `.error-text` css class.
=> fix: gateway forms error rendering

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html
fixes gravitee-io/issues#8219
* Call login endpoint without `login_hint` parameter ==> focus should be on the usename field
`http://localhost:8092/domain/login?client_id=62db61e3-b4ec-40a8-9b61-e3b4ecc0a863&response_type=code&redirect_uri=https%3A%2F%2Fcallback`
* Call login endpoint with `login_hint` parameter ==> focus should be on the password field and username field is readonly
`http://localhost:8092/domain/login?client_id=62db61e3-b4ec-40a8-9b61-e3b4ecc0a863&response_type=code&redirect_uri=https%3A%2F%2Fcallback&login_hint=myusername`
=> fix: set autofocus on password if login_hint is provided

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/consent/DataConsentHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/consent/DataHandlerConsentImplicitTest.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
fixes gravitee-io/issues#8448
* Start the GW with the following settings or env vars: 
[settings]
```
consent:
ip: true
user-agent: true
```
[env var]
```
gravitee_consent_ip=true
gravitee_consent_useragent=true
```
* sign in a user and enroll webauthn
* check into the audit 'USER_LOGIN' event contains the IP address and the UserAgent
* check into the user profile, the credentials details contains the IP address and the UserAgent
=> fix: introduce implicit consent settings for the IP & user agent

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/preview/PreviewBuilder.java
Added missing property `factor.target` so that user who has custom templates 3.18 or before can view the preview for mfa challenge alternative.
This fix linked to :https://github.com/gravitee-io/issues/issues/8463
1. Copy the 3.18 MFA challenge alternative template from : https://am.management.v3-18-x.gravitee.xyz/
2. In 3.19 toggle and enable custom mfa alternatives page.
3. Copy the custom templates
4. Select the review
5. The review should be viewable without error
=> 8463: added missing property factor.target

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/main.css
The phone number drop down list is a div which becomes 100% in width including all children div. As a result input get masked by the div.
Had to manually add the class to fix the issue.
=> 8528: fixed sms phone number input

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-login-v2.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-login.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-register-v2.js, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-register.js
Replaces `innerHTML` with `textContent`. The latter only allows text, not markup, so can guard against XSS.
=> Sanitise for inner html

gravitee-am-resource/gravitee-am-resource-infobip/pom.xml, pom.xml
related-to gravitee-io/issues#8557
=> chore: upgrade gson from 2.8.6 to 2.8.9 in infobeep dependency

gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/audit/DtoMapper.java, gravitee-am-reporter/gravitee-am-reporter-kafka/src/test/java/io/gravitee/am/reporter/kafka/audit/DtoMapperUTests.java
Null check added for audit reference type.
**How to test**
1. Follow the instruction in the jira issue [AM-60](https://graviteecommunity.atlassian.net/browse/AM-60) to run kafka locally and configure a kafka reporter
2. Create an application and a user. 
3. Now try to login with an invalid credential. 
4. Kafka reporter should publish the login failure message instead of the null pointer exception.
=>  AM-60: fixed Kafka audit reporter null pointer exception

docker/compose/config/nginx.conf
Adding the X-Forwarded-Port header to support custom port.
Fixing the issue we have calling (for example with port 9200 configured)
`http://localhost:9200/am/management/auth/authorize?redirect_uri=http://localhost:9200/am/ui/login/callback`
and being redirected to `http://localhost/am/management/auth/login`.
@leleueri
=> Add X-Forwarded-Port header to support custom port

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
Create a custom register template based on the default template by adding this code snipet.
Social button should be displayed on the register page.
```
<div th:if="${socialProviders and !socialProviders.empty}" class="social-login-buttons">
<div th:if="${!hideLoginForm}" class="signup-or-separator">
<h6 class="text">or Sign in with</h6>
<hr>
</div>
<div class="mdl-social-button">
<a th:href="${authorizeUrls.get(socialProvider.getId())}"
th:class="'mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect btn-' + ${socialProvider.getType()}"
th:each="socialProvider : ${socialProviders}">
<span th:if="${socialProvider.getType()} != 'franceconnect'">
<i th:class="'fab fa-' + ${socialProvider.getType()}"></i> <span th:text="${socialProvider.getName()}"></span>
</span>
</a>
</div> …
```
=> Am 128 expose social urls

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfigurationTest.java
fixes gravitee-io/issues#8504
See [AM-50](https://graviteecommunity.atlassian.net/browse/AM-50)
The existing Ldaptive setup used the default connection strategy (i.e. the implicit one, not a declared one) which is why providing anything other than a valid URL, such as a comma separated list, leads to an `IllegalArgumentException` from Ldaptive. This changes detects comma or space separated lists of URLs and selects `ActivePassiveConnectionStrategy` in these instances. Commas are replaced by spaces as Ldaptive only seems to accept space separators.
=> fix: Allow secondary LDAP URL

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpoint.java
* enable "Identity First login" (at domain or application level)
* initiate the login flow, the forgot password isn't display
* enable "forgot password" (at domain or application level)
* initiate the login flow, the forgot password isn't display
* Create a custom template for the IdentityLoginFlow based of this page https://github.com/gravitee-io/gravitee-access-management/blob/3.18.x/gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/identifier_first_login.html and add the following snippet of code:
```
<div th:if="${allowForgotPassword}">
<a th:href="${forgotPasswordAction}">Forgot Password ?</a>
</div>
```
* initiate the login flow, the forgot password link should be display
* following the link, the forgot password form …
=> AM-125 add forgotPassword action into identity first login page

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/spring/PasswordHistoryConfiguration.java, gravitee-am-service/pom.xml, gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/Argon2IdPasswordEncoder.java
Fixes [AM-77](https://graviteecommunity.atlassian.net/browse/AM-77)
Adds Spring's Argon2 encrypter to AM and `PasswordHistoryService`.
=> AM-77-add-argon2id-support-to-am-

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
jira issue: https://graviteecommunity.atlassian.net/browse/AM-161
AccountInactiveException is thrown when a disabled user try to reset password through forget password link.
1. Disable a user from user profile by sliding the "Enable User" option under "Actions" section (so there should a red dot beside user name)
2. Select forgot password instead of login and the user should see "An email has been sent asking to reset your password." regular message.
3. The user shouldn't receive any email and
4. FORGOT_PASSWORD_REQUESTED with failure status should be logged in the audit log
=> AM-161: fixed disabled user receiving reset password email

pom.xml
https://github.com/gravitee-io/issues/issues/8655
⚠️ ⚠️ Wait until https://github.com/gravitee-io/gravitee-notifier-email/pull/46 is merged and update with the according version ⚠️ ⚠️
This PR encourages to upgrade the email notifier to benefit from restricting `authMethod` choices
- Set up an Alert in Alert Engine.
- Configure an Email Notifier to this Alert and select the appropriate authMethods
- Expect to receive an alert on an email
=> chore: upgrade email notifier version for authentication methods

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/IdentityProvidersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/idps/IdentityProvidersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/IdentityProviderManager.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java, gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-identityprovider/src/main/java/io/gravitee/am/plugins/idp/core/IdentityProviderPluginManager.java, gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-identityprovider/src/main/java/io/gravitee/am/plugins/idp/core/impl/IdentityProviderPluginManagerImpl.java
fixes gravitee-io/issues#8695
1. Create a custom MongoDB IDP and/or JDBC IDP
2. Create some users inside this idp (at least 2)
3. try to reset password, update user profile
4. sign in with one of this user
5. go back to the console UI, and delete the user you just used
6. try to sign in with this user (it should fail)
7. go back to the console UI and uncheck the "Allow CRUD operations"
8. try to reset password, update user profile from UI (it shouldn't be possible)
9. signin with a user you didn't deleted
10. go back to the console UI, and delete the user you just used
11. signin with this user (it should work because the user profile has not been deleted from the identity provider as CRUD is not allowed)
=> AM-202 Make UserProvider optional for Mongo & JDBC IDPs

pom.xml
**Prerequisite**: Haveing AM local env (can't do it on nightly as we have to install certificates delivered by cockpit)
1. connect to cockpit preprod env
2. create an organization
3. create an environment
4. go to the How to [How to register a new installation]
5. Select AM and follow the instruction (copy certificates and apply settings) to the AM management API (remember to set also `gravitee_cockpit_ssl_verifyHostname=false` to avoid ssl handcheck issue)
6. you should see the installation with PENDING status on cockpit, activate it.
7. you should be able to connect to AM through cockpit.
Settings should look like this
```
gravitee_cockpit_enabled=true
gravitee_cockpit_keystore_password=7318a4f5-df7a-4554-98a4-f5df7ad554f8
gravitee_cockpit_keystore_path=/path/to/66028a56-85eb-468d-828a-5 …
```
=> AM-145 upgrade cockpit connector from 2.3.0 to 2.6.0

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
1. create a user with a password on the UI, you **should** be able to request a password
2. create a user with a password on the UI then disable it, you **should NOT** be able to request a password
3. create a preregistered user on the UI,  you **should NOT** be able to request a password
4. create a preregistered user on the UI and finalize the registration, you **should** be able to request a password
5. create a preregistered user on the UI, finalize the registration and then disable the user, you **should NOT** be able to request a password
6. create a preregistered user on the UI, in user account allow the forgot password to finalize the registration, you **should** be able to request a password
=> AM-215 test user.inactive instead of user.registrationCompleted

pom.xml
fixes https://github.com/gravitee-io/issues/issues/8779
=> chore: upgrade Hazelcast from 4.1.9 to 4.1.10

gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractSocialAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/GithubIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/test/java/io/gravitee/am/identityprovider/github/authentication/DummySocialAuthentication.java, gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/test/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProviderTest.java
https://gravitee.atlassian.net/browse/AM-350
This PR aims to store the original token provided by github identity providers
- Create a Github IDP
- Tick the `Store Original Token` checkbox
- Set GITHUB IDP in your Application
- Initiate the Login Flow
- Login with Github
- Go to the Management API > Users > <GH-Users> and notice the `op_access_token`
=> feat: store original token from Github Identity provider

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
Remove  the exception that cause resetting password error due to deleted client id.
This does not affect rest of the behaviour
=>  AM-46: fixed reset password issue

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.ts
Co-authored-by: aurelien-pacaud <aurelien.pacaud@graviteesource.com>
https://github.com/gravitee-io/issues/issues/8836
This PR initializes the `mfa.enrollement` instance to be able to save on the first try the Activate MFA section 
Check issue https://github.com/gravitee-io/issues/issues/8836
=> fix: mfa.enrollement not initialized the first time

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainNotifierServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/DomainNotificationServiceTest.java
https://github.com/gravitee-io/issues/issues/8667
Instead of searching for groups at the domain level, groups are searched in the default organisation. If the group is empty an empty list of users is returned to avoid NPE
Test 1: Group with one user
1 .Create a group in organisation level with 1 member.
2. Now select Administrative role in domain level and assign the group  “DOMAIN_OWNER“ role.
3. Upload an expired certificate in the domain.
4. Restart API Management
Test 2: Group without user
1 .Create a group in organisation level without member.
2. Now select Administrative role in domain level and assign the group  “DOMAIN_OWNER“ role.
3. Upload an expired certificate in the domain.
4. Restart API Management
=> fix: set an organisation group domain owner raise a GroupNotFoundException

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceImplTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/endpoints/user/RegisterConfirmationEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/endpoints/user/ResetPasswordEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/SpyRoutingContext.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/handler/impl/ClientAuthHandlerImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/EmailServiceImplTest.java, gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html, gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts
https://github.com/gravitee-io/issues/issues/8808
This PR encodes the clientId in the Login Flow URL presented by the Overview page
It also ensure that in the email template, the client_id is encoded correctly
- Create am application with characters that needs URI encoding (`my # client-app`)
Test 1:
- Go to `Applications > Your App > Overview` and try the  `Initiate the login flow` and login with you actual user, you should be able to login with the client id being encoded
Test 2: (separately)
- Try the forgot password in order for the user to receive an email with reset password
- Try creating a user with registration confirmation email
These two last cases should have a link where the client_id is encoded
=> fix: encoding the clientId in overview so the login flow can be initiated correctly

gravitee-am-common/src/main/java/io/gravitee/am/common/audit/EventType.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/UsernameEntity.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UserResourceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/CommonUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
Fixes [AM-389](https://gravitee.atlassian.net/browse/AM-389)
Added new `/username` endpoint to management API for users.
Should be covered by jest tests; manual tests would be 
- update a username
- fail update unknown user
- fail update permissions insufficien
- fail update username invalid (already used, too short, too long, invalid characters(?))
📺
[AM-389]: https://gravitee.atlassian.net/browse/AM-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AM-389: change username endpoint.

.circleci/workflows.yml
refers to: https://github.com/gravitee-io/gravitee-access-management/pull/2421
=> fix: full distribution path naming

gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/UserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-gravitee/src/main/java/io/gravitee/am/identityprovider/gravitee/user/GraviteeUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/HttpUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/user/HttpUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest_MSSQL.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider_Test.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTestConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/UserNotFoundException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/user/UserValidator.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/user/UserValidatorImpl.java, gravitee-am-test/api/commands/management/organisation-user-commands.ts, gravitee-am-test/specs/management/organisation.users.jest.spec.ts, gravitee-am-test/specs/management/users.jest.spec.ts
https://gravitee.atlassian.net/browse/AM-445
This PR ensures that the username is update where necessary if possible
`curl -vvv -X POST http://localhost:8093/management/auth/token -H 'authorization: Basic base64(username:password)'`
Will get you an access token
```curl -vvv -X PATCH -H "content-type: application/json" -H "Authorization: Bearer <access-token>" http://localhost:8093/management/organizations/DEFAULT/environments/DEFAULT/domains/<domainId>/users/<userId>/username -d '{ "username"  : "<newUsername>" }' ```
- Test if the username respects the username pattern -- should fail
- Test if the username already exists -- should fail
- Finally update a user with its actual username -- should succeed
- Try updating the username of a non UserProvider IDP (Everything but Mongo/Jdbc/Http) …
=> feat: make sure service level updates username

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest_MSSQL.java, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider_Test.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoAbstractProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTestConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTest.java, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProviderTestConfiguration.java
https://gravitee.atlassian.net/browse/AM-450
This PR fixes the MongoDB formatting of the username when registering in MongoDB. 
- Test on AM with MongoDB backend
- Login with AM user Admin
- Create a user with a space / with several spaces / with no space
- Login with the user
- Update the users' username with the Admin user (several spaces etc ...)
- Logout and log back in
=> fix: mongodb did not allow spaces in find by username

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandlerTest.java
Align with the behaviour for post-login exit when there is only one IDP and the login form is hidden
Detailed of this issue can be found here: https://gravitee.atlassian.net/browse/AM-232
What to test:
I have added an Excel shit with before and after modification behaviours. Only one cell (D9) behaviour has been changed after this fix. Please ping me for further details. Thanks
=> AM-232: redirected to callback url for pre-login exit

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/commands/UserCommandHandler.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/commands/UserCommandHandlerTest.java
Fixes [AM-449](https://gravitee.atlassian.net/browse/AM-449)
Added a null check to `UserCommandHandler` which is Cockpit's route into AM when creating organisation users.
[AM-449]: https://gravitee.atlassian.net/browse/AM-449?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AM-449: Prevent null usernames with cockpit handler

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/alert/AlertEventProcessor.java
related to https://gravitee.atlassian.net/browse/AM-194
When refactoring with RxJava3 event is now returned twice
Enable alerting risk assessment on a domain
Either try login in from: 
- 2 different location
- From a different device (MFA with remember device necessary)
=> fix: success auth event returned twice when risk assessment enabled

gravitee-am-management-api/gravitee-am-management-api-service/pom.xml, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderServiceProxyImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/utils/JsonNodeValidator.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/utils/JsonNodeValidatorTest.java
Fixes [AM-447](https://gravitee.atlassian.net/browse/AM-447)
Created a util class that checks JSON documents for negative values. 
See the JIRA for an example IDP configuration that can be used to test this. Essentially, the steps to test are
1. Create an IDP (Suggest HTTP or In-memory as it's one of the easiest to configure)
2. Locate the IDP at the identities mongo table
3. Modify the 'configuration' field JSON to include invalid numeric values, e.g. ```"timeout" : -1000```
[AM-447]: https://gravitee.atlassian.net/browse/AM-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AM-447-AM-IDP-When-using-an-internal-API-for-AM-no-validation-of-the-requests-payload-it-provided

pom.xml
https://gravitee.atlassian.net/browse/AM-486
AM was overriding the gravitee bom with the jackson bom.
We should only rely on gravitee bom for this dependency
=> fix: rely on gravitee bom for jackson

gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/GraviteeMessageResolver.java, gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/GraviteeMessageResolverTest.java
This fix allows to use thymeleaf i18n message properties params such as:
<label th:text="#{login.description (${client.name})} + ' '" />
<label th:text="${#messages.msg('login.description', client.name, client.id)} + ' '" />
<label th:text="${#messages.msgWithParams('login.description', new Object[] {client.name, client.id})} + ' '" />
=> AM-483 thymeleaf templateengine ignore variable

pom.xml
- chore: update gravitee-node.version to 3.0.0-alpha.3
- chore: upgrade hazelcast to 4.1.10
=> chore: update gravitee-node.version to 3.0.0-alpha.3 and hazelcast to 4.1.10

gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/I18nDictionaryRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcI18nDictionaryRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringI18nDictionaryRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoI18nDictionaryRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/I18nDictionaryRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/InvalidLocaleException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/I18nDictionaryService.java, gravitee-am-service/src/test/java/io/gravitee/am/service/I18nDictionaryServiceTest.java, gravitee-am-test/specs/management/dictionaries.jest.spec.ts
Fixes [AM-472](https://gravitee.atlassian.net/browse/AM-472)  and [AM-471](https://gravitee.atlassian.net/browse/AM-471) 
The dictionary service previously searched by name before any CRUD operation. I've simply changed it to search on locale instead. Also for 471 I check the requested locale against those in the JVM (Locale.getAvailableLanguages()) for validation.
1. Try and create a dictionary with an existing locale using curl/postman (or attempt to create two identical dictionaries).
2. It should be rejected with a 400
1. Try and create a dictionary with an invalid locale e.g. 'xxx'
2. SHould reject with a 400
[AM-472]: https://gravitee.atlassian.net/browse/AM-472?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[AM-471]: …
=> AM-472-management-Shouldn-t-be-possible-to-create-two-dictionaries-with-same-locale

pom.xml
https://gravitee.atlassian.net/browse/AM-506
This PR upgrades gravitee-node in order to disable license log level enforced to INFO
Change your `logback.xml`and add 
`<logger name="io.gravitee.node.license.LicenseService" level="WARN" />`
You should be able to hide the license logs
=> fix: license INFO logging level enforced

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
Related to https://gravitee.atlassian.net/browse/AM-505
Dozer consume a lot of CPU, this change has demonstrate that removing dozer increase drastically the performance.
This change has been tested on 3.19.x, make sure that all the user fields are managed if new user attributes have been introduced between 3.19.x and 3.21.x
=> chore: do not use Dozer to convert User to JdbcUser

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/User.java, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
https://gravitee.atlassian.net/browse/AM-385
Unlock the user when his username is changed
1. Create a user
2. Enable the brut force detection at security domain level or application level (Settings -> User Accounts -> Login)
3. Try to connect with the previous user with a wrong password
4. Go to the user (Settings -> Users -> Your user)
5. The user is locked
6. Change the username
7. The user is unlocked
=> fix: user is unlocked if the username is updated

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java
https://gravitee.atlassian.net/browse/AM-453
Not reset login count and last login date when user data are updated
1. Login with  a user
2. Update firstname of the user (Settings -> Users -> Your User)
3. Check that `Logins count` and `Last login` don't change (right column of the screen)
=> fix: login count and last login date not updated when user is updated

gravitee-am-spring-web/src/main/java/io/gravitee/am/springweb/package-info.java
When we added the gravitee-am-spring-web package with content of
org.springframework:spring-web:5.3.18 via a maven-dependency-plugin:unpack.
The deploy to maven central failed because this module doesn't have source code.
The hack on the hack here is to add a package-info.java to generate
sources and add a little doc which explain the reason.
=> fix: ensure gravitee-am-spring-web have sources

gravitee-am-spring-web/src/main/java/io/gravitee/am/springweb/Dummy.java
When we added the gravitee-am-spring-web package with content of
org.springframework:spring-web:5.3.18 via a maven-dependency-plugin:unpack.
The deploy to maven central failed because this module doesn't have javadoc.
The hack on the hack here is to add a Dummy.java class to generate
sources and add a little doc which explain the reason.
=> fix: ensure gravitee-am-spring-web have javadoc

gravitee-am-service/pom.xml, gravitee-am-service/src/main/java/io/gravitee/am/service/exception/DictionaryAlreadyExistsException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/I18nDictionaryService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewDictionary.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateI18nDictionary.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/annotations/IfNotNullThenNotBlank.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/annotations/IfNotNullThenNotBlankValidator.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/dictionary/LocaleValidator.java, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/dictionary/ValidLocale.java, gravitee-am-service/src/test/java/io/gravitee/am/service/I18nDictionaryServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/annotations/IfNotNullThenNotBlankValidatorTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/dictionary/LocaleValidatorTest.java, gravitee-am-test/specs/management/dictionaries.jest.spec.ts
Fixes [AM-511](https://gravitee.atlassian.net/browse/AM-511)
Updated the DictionaryAlreadyExists exception, added an InvalidDictionaryException and added additional checks for blank name and locale (was already checking locale but "" is a valid locale in the current JRE).
[AM-511]: https://gravitee.atlassian.net/browse/AM-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Improve validation for dictionary create and update

pom.xml
bump both minidev and json smart versions
=> fix: minidev json-smart and jackson

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.3/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.3 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.3%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.3 release

CHANGELOG-v3.adoc, release/helpers/changelog-helper.mjs, release/package.json
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.9/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.9 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.9%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.9 release

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UserResource.java
https://gravitee.atlassian.net/browse/AM-692
Use the correct entity around `PATCH /username`
=> fix: use correct entity wrapper for patch username

gravitee-am-resource/gravitee-am-resource-infobip/pom.xml, pom.xml
The lib `com.infobip:infobip-api-java-client` use vulnerable version of `org.json:json`.
The lastest version 4.0 of `infobip` solve the issue but doesn’t compile anymore.
But exclude `org.json` from `infobip` and import latest fixed version by ourselve fix the issue.
=> fix: DOS vuln on org.json:json due to infobip-api-java-client

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.19.15/CHANGELOG-v3.adoc)
[See all Jira issues for 3.19.15 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.19.15%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.19.15 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.19.16/CHANGELOG-v3.adoc)
[See all Jira issues for 3.19.16 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.19.16%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.19.16 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.4/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.4 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.4%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.4 release

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
https://gravitee.atlassian.net/browse/AM-721
and most likely this one too
https://gravitee.atlassian.net/browse/AM-708
A check for null value was missing when retrieving domain settings
Before the fix:
Create a Domain and Application. Keep every setting value as default.
Manually create a user, assign it to the generated application and enable `Pre-registration`.
When the user is created, the expected email is never sent. Same thing if you go inside the user profile and try to send a new confirmation email.
After the fix, emails should flow 📧 📥
=> fix: verify domain settings when sending registration emails

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxServerConfiguration.java
fixes AM-717
By using the gravitee-node 4.0.0, the wait HttpServerOptions are initialized has changed.
Initialization is made by the builder using the Environment object, the default value for maxSizeFormAttribute is manage by the builder, for the port the builder set a default value to 8080 so we override the port settings with default value set to 8092
=> fix: fix default value initialization on HttpServerOptions

gravitee-am-ui/src/app/services/gio-license.service.ts
https://gravitee.atlassian.net/browse/AM-713
Added missing UTM tag for the HTTP flow idp.
=> fix: add UTM tag for the HTTP flow idp

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/EmailManagerTest.java
https://gravitee.atlassian.net/browse/AM-721
The method `findByDomainAndClientId` does not search an application by its id, but by auth `clientId`.
Hence, this has never worked properly.
This PR brings back the use of `emailTemplateService.findByClientAndTemplate` that correctly searches by domain and application.
Everything is described in the issue.
=> fix: retrieve the correct email templates

pom.xml
Use latest version of released AM-plugin.
Note: we still use `gravitee-plugin` and `gravitee-node` in alpha version
until we will migrate to JDK17 and Spring 6 (planned for another release).
=> chore: use release version rather than alpha one

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.5/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.5 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.5%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.5 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-4.0.1/CHANGELOG-v3.adoc)
[See all Jira issues for 4.0.1 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%204.0.1%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 4.0.1 release

.gitignore, release/ci-steps/doc-new-release-notes.mjs, release/helpers/changelog-helper.mjs, release/helpers/jira-helper.mjs
Update the script generating the changelog to match the new format and target the documentation website instead of the internal changelog.
-> To move further, we need to align filenames for APIM and AM first: https://github.com/gravitee-io/gravitee-platform-docs/pull/21
=> Update Changelog Generation

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/database/mariadb.schema, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/database/mysql.schema, gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/database/sqlserver.schema, gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_19_21/3.19.21-alter-users_username_unique.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
Brief summary:
Unique constraints are added in:
Users table and newly created idp_xxx tables as necessary.
As a result there won't be any duplicate username in the users table. 
What to check:
Postgresql already had unique constraints and had no issue. For rest of the JDBC or mongodb the easiest way to test would be running the "CreateUsers" gatling test under "gravitee-am-performance" package. 
- Run "CrateDomain" gatling test
- Change "SimulationSettigns.scala" such as
1. val NUMBER_OF_USERS = Integer.getInteger("number_of_users", 12)
2. val AGENTS = Integer.getInteger("agents", 3)
3. Remove "${index}" from username around line number 87.
The goal here to create a duplicate user. These changes allow 3 threads to try to create user with same username in total 4 times. Feel free to change …
=> fix: unique constraints added for username

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
Support issue make us notice the missing part
It seems that some tools are less forgiving when running the script and the execution was failing.
=> fix: add missing statement to index creation script

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/PolicyChainHandlerImpl.java
MFA challenge policy could throw exception in case the user does not have the factor enrolled.
In that case there won't be any parameter in the exception. Hence the null check is required.
=> fix: added null check on policy chain exception param

.mergify.yml
Thsi PR updates mergify configuration to be able to apply cherrypick on the 4.1.x branch
The config for the 3.18.x has been removed as this version is EOL
=> chore: add 4.1.x to mergify config and remove the 3.18.x

docker/management-ui/Dockerfile, docker/management-ui/Dockerfile-dev, docker/management-ui/Dockerfile-nightly, docker/management-ui/config/default.conf
Prevent $uri replacement in nginx configuration.
Environment variables that need to be replaced are now specified in the run.sh of the nginx-noconfd docker image
=> fix(docker): prevent $uri replacement in nginx configuration

gravitee-am-ui/src/app/domain/components/account/account-settings.component.html, gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts
https://gravitee.atlassian.net/browse/AM-818
https://gravitee.atlassian.net/browse/AM-819
Fix hint text and default duration of remember me option at domain and application level
=> fix: remember me default duration and hint text

.circleci/workflows.yml
fixe AM-820
This PR increases the synchronization rate of the GW.
During the OOM error analyze (AM-797), I saw that the Spring Context were more huge than previously.
My assumption is the spring context takes more time to be initialized. As the test timeout to have a domain synchronized was set to 6 second we may be to slow of few millisec to have a domain up and running against the default sync period of 5 second.
=> chore: reduce to sync delay to avoid flaky integration test

.circleci/workflows.yml
This previous commit https://github.com/gravitee-io/gravitee-access-management/commit/13236d961358397a28297c0559bfc9169685e98b was removing the SNAPSHOT publication on Nexus and artifactory for PR build. But the main branch build doesn't publish the SNAPSHOT...
This PR aims to fix this in order to publich SNAPSHOT that are representative of the product state.
=> ci: deploy SNAPSHOT mvn artifact on build_branch job

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/cors/CorsHandlerFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/cors/CorsHandlerFactoryTest.java
Linked jira issue: AM-824
The issue happen if you use a regex for allowed origin that contain a comma.
As example:
```
- name: GRAVITEE_HTTP_CORS_ALLOWORIGIN
value: "https:\/\/((.*)\.)?(mydomain|(mydomain-(\d){1,5}))\.company.cloud"
- name: GRAVITEE_HTTP_CORS_ALLOWCREDENTIALS
value: "true"
```
On another side, if you set the same regex but as domain level in
Management UI, the attribute will be badly saved and failed when
we test a CORS call.
1. On startup:
* start AM with environment variable as describe before
* check error in startup logs
2. From UI:
* start AM
* create a domain
* in domain > settings > entrypoint : setup CORS with a regex which contain comma
* save the configuration and wait that the gateway will be updated.
* do a cors call on gateway like:
```
curl -v -X OPTIONS \ …
```
=> fix: CORS allow origin issue with comma into regex

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/StaticEnvironmentProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/RedirectHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/utils/StaticEnvironmentProviderTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginCallbackEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSelectionRuleHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpointHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeAlternativesEndpointTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
https://gravitee.atlassian.net/browse/AM-737
This PR introduces a hack 😞.
So far, when computing redirect URLs in AM, the `static` class `UriBuilderRequest` decodes and encodes all parameters.
When parameters aren't url-encoded, this is not a big deal. But when parameters are already url-encoded, we introduce a few issues.
Since the method is `UriBuilderRequest.resolveProxyRequest(...)` is used all around AM, it's hard to tell if removing the extra decoding will not break stuff.
This PR introduces the parameter `legacy.openid.sanitizeParametersEncoding` that, when set to `false`, disables the extra decoding.
For the future, we should remove the hack and any extra handling of parameters, only decoding parameters when they are received and encoding them when they leave AM Handlers.
The …
=> fix: add sanitizeParametersEncoding toggle

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.11/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.11 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.11%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.11 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.6/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.6 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.6%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.6 release

gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
without this change a newly added field with default value doesn't display the default value, that lead to issue if the idp is updated
fixe AM-686
=> fix: initialize missing idp properties based on the default schema value

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
fixe AM-671
When a HTML template is invlid, some endpoint ends with `Internal Server Error` blank page.
This fix redirect page that have no specific error handleing to the default Error page.
Pages : 
* CONFIRM_REGISTRATION
* MFA_ENROLL
* MFA_CHALLENGE_ALTERNATIVE
* MFA_RECOVERY_CODE
=> fix: add default error handler on path that are managing HTML rendering

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
1. Create a domain and application as usual.
2. Add a custom claim in the application such ash `{#context.attributes['user']['claims']['email']}`. This claim access `claims` property which was missing before this fix.
3. Save and generate access token for a user by sending request to token endpoint such as `http://localhost:8092/self-account-management-test/oauth/token`
4. The generated token should have the email claim
=> AM-838: replaced User and Client with respective property object

helm/Chart.yaml, helm/templates/api/api-deployment.yaml, helm/templates/gateway/gateway-deployment.yaml, helm/templates/ui/ui-deployment.yaml, helm/tests/api/deployment_test.yaml, helm/tests/gateway/deployment_test.yaml, helm/tests/ui/deployment_test.yaml, helm/values.yaml
Issue [#9209](https://github.com/gravitee-io/issues/issues/9209) on APIM replicated to AM.
[https://gravitee.atlassian.net/browse/DEVOPS-179](DEVOPS-179)
In addition of the container level, you can now define a security
context at pod level.
Edit the `values.yml` with:
* the tag 4.0.1 of docker AM images
* the right mongo uri
* set a podSecurityContext
And then:
```
kubectl create namespace my-namespace
helm install graviteeio-am . --namespace my-namespace
kubectl --namespace my-namespace get deploy graviteeio-am-management-api -o yaml | grep -A 4 'securityContext:'
```
You should see the security context defined.
@gravitee-io/devops @gravitee-io/am
=> feat(helm): Add podSecurityContext at deployment spec level

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.19.18/CHANGELOG-v3.adoc)
[See all Jira issues for 3.19.18 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.19.18%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.19.18 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.12/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.12 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.12%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.12 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.7/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.7 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.7%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.7 release

.circleci/config.yml, .circleci/workflows.yml, .github/workflows/publish-images-for-test-env.yml, .github/workflows/remove-ready-to-test-labels.yml
=> fix(CI): pr env

pom.xml
https://gravitee.atlassian.net/browse/AM-833
Added a dependency management on the version of the library Thymeleaf so we avoid pulling an old version from another dependency (vertx).
=> chore: include thymeleaf dep in depManagement to override the version used by vertx

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.8/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.8 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.8%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.8 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.13/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.13 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.13%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.13 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.9/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.9 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.9%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.9 release

docs/self-service-account-api-descriptor.yml, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/model/EnrollmentAccount.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java, pom.xml
fixes AM-943
fixes gravitee-io/issues#9289
1. create a domain with SMS Factor and enable the "self acount api"
2. make this factor optional on the Application
3. configure the application to allow scopes "openid", "profile", "email"
4. create a user (or use a user without factor)
5. initiate login flow and get an access_token (DO NOT ENROLL THE FACTOR HERE, skip this step)
6. call the selfAccount API to list user factors (you should have empty list)
```
curl -X GET -H"Authorization: Bearer ${ACCESS_TOKEN}" http://localhost:8092/domain/account/api/factors
[ ]
```
7. list factors available on the domain
```
curl -X GET -H"Authorization: Bearer ${ACCESS_TOKEN}" http://localhost:8092/domain/account/api/factors/catalog
[ {
"id" : "fa24ccf6-2885-4df7-a4cc-f62885adf77c",
"name" : "SMS Twilio", …
```
=> fix: manage phone extension in the SelfAccountApi

gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/FreemarkerMessageResolver.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/GraviteeMessageResolver.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/MessageFormatSanitizer.java, gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/GraviteeMessageResolverTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/MessageFormatSanitizerTest.java
fixes AM-836
fixes gravitee-io/issues#9237
And also fixes AM-1003 (single quote management)
Edit a template (login page for example) with an unknown dictionnary key.
When the page is previewed on the Management Theme editor or when the page is loaded by the GW, the key should be displayed surrounded by question mark.
To test AM-1003, add single quote in the text message you want to display on the form, you should see it in the preview and in the page rendered by the Gateway
=> fix: avoid error when unknown text key is used into a template

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
fixes AM-1017
gravitee-io/issues#9347
=> fix: always enable user created using SCIM if UserProvider is missing

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.14/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.14 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.14%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.14 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.10/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.10 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.10%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.10 release

helm/values.yaml
https://gravitee.atlassian.net/browse/DEVOPS-265
The chart is putting the whole extraVolumeMounts verbatim (i.e. as is)
in the deployment spec, and existingClaim is not a kubernetes attribute.
=> fix(helm): remove nonexistant existingClaim attribute

helm/Chart.yaml, helm/templates/gateway/gateway-configmap.yaml, helm/tests/gateway/configmap_http_test.yaml, helm/values.yaml
https://gravitee.atlassian.net/browse/DEVOPS-283
Previously the `http.alpn` option was hardcoded as `true` in `gravitee.yml`.
Now we add the option `gateway.http.alpn` to configure it in helm `values.yml`
which is set to `true` by default for backward compatibility.
See unit test
=> feat(helm): backport HTTP 2 configuration from gravitee.yml to helm values

pom.xml
fixes AM-828
gravitee-io/issues#9229
Create groovy policy in flow ALL
```
import io.gravitee.policy.groovy.PolicyResult.State
result.state = State.FAILURE
result.code = 400
result.error = '{"data":' + [request.method, request.parameters, request.headers['Host'] + '}'
result.contentType = 'application/json'
```
With this script, a request on the GW to initiate a login flow should return a JSON with an array. Lastest element of the array should contains the value of the Host header
=> fix: upgrade groovy policy to allow request headers usage

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.15/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.15 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.15%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.15 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.11/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.11 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.11%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.11 release

README.md
The Github readme was pointing to the old (<4.0) documentation website.
This PR updates the link to point to the new documentation website.
=> Point to latest documentation website

helm/Chart.yaml, helm/templates/api/api-configmap.yaml, helm/templates/gateway/gateway-configmap.yaml, helm/tests/api/configmap_email_test.yaml, helm/tests/gateway/configmap_email_test.yaml, helm/values.yaml
https://gravitee.atlassian.net/browse/DEVOPS-180
* rework email configuration in helm `values.yml` in `smtp.email`
* rework also the `notifiers.email`
Note: previously, some properties was different between helm values and
`gravitee.yml` file:
* `starttlsEnable` to `starttls.enable`
* `sslTrust` to `ssl.trust`
* `sslProtocols` to `ssl.protocols`
And on another side, the `notifiers` email configuration in
`gravitee.yml` use these camelcase properties...
This refactoring take care to be backward compatible with old and new
configuration. (see unit test)
* fix also the conversion from `starttlsEnable` to `startTLSEnabled`
* remove unwanted properties from `smtp` when include to `notifiers`
* flatten the `.smtp.properties` into `api.notifiers.email` directly
see unittest
=> refactor(helm): rework email configuration to use ident

pom.xml
related AM-1056
gravitee-io/issues#9381
In FranceConnect IDP, add this additional parameter to get the AMR claims. This claims is present only into the id_token not in the UserInfo endpoint
In the User Mapper linked to FranceConnect, add these entries. Note the amr_el one that will provide in the User profile the amr claims coming from the id_token.
in the user profile, you should see something like this
=> chore: bump france-connect idp

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/certificate/impl/CertificateManagerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSRFHandlerFactory.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/configuration/ConfigurationChecker.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxServerConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/CockpitAuthenticationFilter.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/generator/JWTGenerator.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/NewsletterServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/notifications/EmailNotifierConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/EmailServiceImplTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EmailServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReCaptchaServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/spring/JWTConfiguration.java, gravitee-am-service/src/main/java/io/gravitee/am/service/spring/WebClientsConfiguration.java, gravitee-am-service/src/main/java/io/gravitee/am/service/spring/email/EmailConfiguration.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ReCaptchaServiceImplTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/http/WebClientBuilderTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/validators/EmailDomainValidatorTest.java, pom.xml
https://gravitee.atlassian.net/browse/ARCHI-299
This PR defers some `@Value` resolutions that are susceptible to holding sensitive data and are eligible for secret injection. It also defers some bean instantiations for the same purpose (waiting for a proper global solution).
This PR can be tested by enabling and configuring a Kubernetes secret provider. It can be achieved by specifying the following environment variables on both management and gateway:
```properties
gravitee_secrets_kubernetes_enabled=true
gravitee_secrets_kubernetes_namespace=graviteeio
```
You can create a Kubernetes secret with several entries representing some "sensitive" information such as jwt secret, keystore password, ..., ex:
```bash
kubectl create secret -n graviteeio generic am \ …
```
=> fix: defer some @Value resolution and bean instantiation

helm/Chart.yaml, helm/templates/common/licenses-secrets.yaml, helm/tests/api-configmap_test.yaml, helm/values.yaml
https://gravitee.atlassian.net/browse/DV-331
During an helm upgrade, the secret with gravitee license created
from `values.yml` entry: `license.key` is deleted.
It seems that the lookup implies that the ressource is not re-created,
however during the helm upgrade rotation it is deleted.
The fix consist on removing this lookup and by default name the secret
with component suffix. We set this suffix to allow specific use case
with multiple gravitee component on the same namespace (eg: AM+AE).
1. Do an helm install on a new fresh namespace
2. proceed the upgrade
2.1 the secret is now named licensekey-am
2.2 the secret still exist after the upgrade
Bonus: this PR include a fix about previous failling test 😅.
=> fix(helm): license deleted after helm upgrade

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.16/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.16 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.16%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.16 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.12/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.12 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.12%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.12 release

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CSRFHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSRFHandlerTest.java
fixes AM-1084
gravitee-io/issues#9398
=> fix: generate a new CSRF token if the current one expired

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
https://gravitee.atlassian.net/browse/AM-1174
{
"status" : "409",
"scimType" : "uniqueness",
"detail" : "User with externalId [example-external-id-1] already exists",
"schemas" : [ "urn:ietf:params:scim:api:messages:2.0:Error" ]
}
=> AM-1174: add correct error on duplicate externalId

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainNotifierServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/LogNotificationService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/notifications/LogNotifierFactoryImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/notifications/NotificationDefinitionUtils.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/DomainNotificationServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/LogNotificationServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
1. Change the cron expression for the certificate to `0 */1 * ? * *` to generate log per minute
2. Upload one expired and another about to expired certificate [please let me know if you need those certs]
3. Should be able to see AM console log entires such as below:
4. There should be entry in the `notification_acknowledgements` collection for each certificate
=> AM-1116: added license log notifier

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.17/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.17 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.17%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.17 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.13/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.13 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.13%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.13 release

docs/upgrades/3.x/3.20.0/1-licence-notification-permission.js, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/LicenseResource.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-model/src/main/java/io/gravitee/am/model/permissions/Permission.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v4_3_0/4.3.0-license-notification-permission.yml, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/RoleServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/GraviteeLicense.java, gravitee-am-ui/src/app/components/sidenav/sidenav.component.html, gravitee-am-ui/src/app/components/sidenav/sidenav.component.scss, gravitee-am-ui/src/app/components/sidenav/sidenav.component.ts
https://gravitee.atlassian.net/browse/AM-1091
The information is present when the license expires in 30 days and the user has "license_notification_read". Frontend mocks are not ready at the moment. 
29 days
12 days
expired
when the menu is collapsed
permission to see the license
=> AM-1091: License notification in UI

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java, gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html
1. Create a B2B application and send a request to the authorize endpoint with a redirect uri such as [http://localhost:8092/domain/oauth/authorize?client_id=XXXredirect_uri=https%3A%2F%2Fgoogle.co.uk]
2. The response shouldn't redirect to the site mentioned in the redirect_uri
3. Now create a Web application with a redirect uri. 
4. Change the Web application to a B2B application.
5. Send a request to the authorize endpoint.
6. The outcome should be exactly as mentioned in 2. The response won't redirect and error msg should be same.
=> AM-1085: bug fixed by implementing same behaviour in different scenarios

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.14/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.14 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.14%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.14 release

.circleci/workflows.yml, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/GraviteeVerticle.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxServerConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/node/ManagementNode.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java, gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-notifier/src/main/java/io/gravitee/am/plugins/notifier/spring/NotifierConfiguration.java, gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-policy/src/main/java/io/gravitee/am/plugins/policy/spring/PolicySpringConfiguration.java, pom.xml
https://gravitee.atlassian.net/browse/ARCHI-297
This PR upgrades `gravitee-node` and `gravitee-plugin` and brings the required adaptations to allow for loading plugins in 2 steps, first, the boot plugins such as the secret provider plugins, and second, the rest of the plugins. This allows for a wider support of secret resolution during startup.
This PR can be tested by enabling and configuring a Kubernetes secret provider. It can be achieved by specifying the following environment variables on both management and gateway:
```properties
gravitee_secrets_kubernetes_enabled=true
gravitee_secrets_kubernetes_namespace=graviteeio
```
You can create a Kubernetes secret with several entries representing some "sensitive" information such as jwt secret, keystore password, ..., ex:
```bash
kubectl …
```
=> feat: load boot plugins

release/helpers/changelog-helper.mjs, release/helpers/jira-helper.mjs
Improve Release Note generation script:
* avoid filtering on JIRA issue status (the value depend of the language preferences of the account used to generate the token, so it may not be Done but for example Terminé(e) in french)
* addition of "Public Improvement" as issue to include into the release note
=> chore: update release note generation script

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/AbstractDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelperTest.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParser.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParserTest.java
https://gravitee.atlassian.net/browse/AM-870
Fixed one bug related to passing a null value to LocalDateTime parser. 
Tweaked mongo query builder for "pr" operator to make it filter out both null and non-existing values.
@leleueri 
=> AM-870 SCIM pr operator

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/AM-2154
Added:
- retry download packages from "download.gravitee.io" domain which often does not respond correctly 
- retry postman tests
- increase waiting time for application to start
- remove sleeps
Result: 
- save developers time by removing the need for manual pipeline retry
- save costs by retiring tests/downloads instead of a whole pipeline step
[AM-2154]: https://gravitee.atlassian.net/browse/AM-2154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> AM-2154: add retries in pipeline

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.19/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.19 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.19%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.19 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.17/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.17 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.17%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.17 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.20/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.20 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.20%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.20 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.18/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.18 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.18%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.18 release

pom.xml
this upgrade contains vertx, jetty & spring security upgrade
AM-2740
=> chore: upgrade gravitee-bom to 6.0.32

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MfaFilterContext.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/utils/MfaUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStepTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStepTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java, gravitee-am-model/src/main/java/io/gravitee/am/model/RememberDeviceSettings.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/RememberDeviceSettingsMongo.java
https://gravitee.atlassian.net/browse/AM-2745
https://gravitee.atlassian.net/browse/AM-2746
- When the Remember device is active it is remembered for all challenge types except conditional when skipRemember is set.
updated diagram:
=> AM-2745: remember device mfa

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.20/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.20 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.20%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.20 release

gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/JWT.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenServiceTest.java
this claims can be a list according to the spec
WARN: to make this array usable by introspection endpoint and don't break anything, the client_id need to be the first entry
fixes AM-2865
gravitee-io/issues#9614
=> fix: allow to set a String array as aud custom value

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.20.21/CHANGELOG-v3.adoc)
[See all Jira issues for 3.20.21 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.20.21%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.20.21 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.21/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.21 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.21%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.21 release

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.22/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.22 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.22%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.22 release

gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.scss
https://gravitee.atlassian.net/browse/AM-2950
=> fix: AM-2950 - badge number centralized.

gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.html, gravitee-am-ui/src/app/domain/settings/password-policies/domain-password-policies.component.scss, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html
https://gravitee.atlassian.net/browse/AM-2979
Additionally, fixed one label in Create PP screen
"History" became "history"
=> fix: AM-2979 - pencil icon color should be black.

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.23/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.23 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.23%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.23 release

pom.xml
Upgrade BC to 1.78. upper versions are already up to date
=> chore(dep): upgrade bouncycastle in 1.78

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java, gravitee-am-ui/package-lock.json, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
Relates to: https://gravitee.atlassian.net/browse/AM-475
Public bug: https://github.com/gravitee-io/issues/issues/8434
This PR allows to edit the user profile even with an external IDP.
Note that the changes will only happen in AM and not to this external IDP.
- Create an external IDP (Google, Github, Facebook, LinkedIn ...)
- Associate it to your application
- Login with your User using the IDP
- Go to the User Profile
- Add / Remove additionalInformation
- Logout and LogIn with the user 
The custom attributes you have added should remain while the one default to your IDP should come back
This should also work with organization users
Internal users should still be able to have fields updated and removed as well
=> feat: allow users from external idp to have new attributes

release/helpers/changelog-helper.mjs
the AM pipeline to use proper link syntax, i.e., [text](url) instead of url[text]
=> chore(ci): fix link generation for changelogs

gravitee-am-common/src/main/java/io/gravitee/am/common/event/Type.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/mapper/EventConverter.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoEventRepository.java
this change allowes to keep synchronization process working
when a upper version introduce new type of event
related-to AM-2894
=> fix: avoid exception when an event has a unknown type

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java
fixes: [AM-2942](https://gravitee.atlassian.net/browse/AM-2942)
public: https://github.com/gravitee-io/issues/issues/9659
This PR fixes a typo in the configuration of the verify template on the subject.
Causing the Email not to be sent because of the enclosing `{` not being closed
- Configure your AM application with `Login > Registration` Form and  `User Accounts > User Registration > 
Account verification via email: true`
- Initiate the login flow and register
- You should receive an Email to verify your account
[AM-2942]: https://gravitee.atlassian.net/browse/AM-2942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: typo on account registration configuration

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/AnalyticsParam.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AnalyticsServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java, gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java, gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/constants/MongoAuditReporterConstants.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ReporterServiceTest.java, gravitee-am-ui/src/app/components/widget/widget.component.html, gravitee-am-ui/src/app/components/widget/widget.component.scss, gravitee-am-ui/src/app/domain/components/dashboard/dashboard.component.ts, gravitee-am-ui/src/app/utils/time-range-utils.ts
fixes AM-1110
two things: 
on the backend added extended index with outcome.status == 'SUCCESS'  
on the frontend made dashboard resilient to single indicator crash. 
for count pipeline aggregate with old index () the 3 month request for 0.5M user logins took `executionTimeMillis: 1150`
with new index `executionTimeMillis: 154`
the proof the planner takes new index: 
> winningPlan: {
stage: 'COUNT_SCAN',
keyPattern: {
referenceType: 1,
referenceId: 1,
type: 1,
'outcome.status': 1,
timestamp: -1
},
indexName: 'r1ty1s1t_1'  <-- NEW ONE
Mockups: 
https://www.figma.com/file/k7okoie28WAjDjsnnEAjFc/AM---Dashboard?type=design&node-id=119-3190&mode=design&t=IPYa2HjD9JFmxrc0-0
Dashboard after changes:
=> fix: analytics timeout

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStoreTest.java, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CredentialRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcCredentialRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringCredentialRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/CredentialRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/CredentialService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CredentialServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/CredentialServiceTest.java
Added gravitee.yaml property which limits number of credentials sent back to browser on password-less authentication.
It is due to different behaviour on different browsers. Firefox accepts max 20, Chrome max 64.
=> AM-3306 fix: Limit on webauthn credentials sending back in a response

.circleci/workflows.yml
corrupted lib: com/github/eirslett/node/16.10.0/node-16.10.0-linux-x64.tar.gz
fixes release :) hopefully.
=> fix: make job not to use maven cache with corrupted lib 3.21

.circleci/workflows.yml
corrupted lib: com/github/eirslett/node/16.10.0/node-16.10.0-linux-x64.tar.gz
fixes release :) hopefully.
=> fix: make job not to use maven cache with corrupted lib

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
`15:01:36.652 [Thread-28] [] INFO  i.g.a.g.h.r.r.e.m.MFAEnrollEndpoint - Factor 298f0de1-be4c-4c06-8f0d-e1be4c5c064a selected for user c11e7f61-ad3d-47c2-9e7f-61ad3d67c226`
`15:01:36.665 [RxCachedThreadScheduler-1] [] INFO  i.g.a.g.h.r.r.e.m.MFAChallengeEndpoint - Challenge sent to user c11e7f61-ad3d-47c2-9e7f-61ad3d67c226`
`15:02:15.184 [Thread-21] [] INFO  i.g.a.g.h.r.r.e.m.MFAChallengeEndpoint - User c11e7f61-ad3d-47c2-9e7f-61ad3d67c226 strongly authenticated`
`15:02:15.187 [Thread-15] [] INFO  i.g.am.service.impl.UserServiceImpl - Factor 298f0de1-be4c-4c06-8f0d-e1be4c5c064a upserted for user c11e7f61-ad3d-47c2-9e7f-61ad3d67c226`
=> AM-2887 fix: Added crucial MFA event logs

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.24/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.24 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.24%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.24 release

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/password/PasswordPolicyManager.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/PasswordPolicyRequestParseHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/UserRegistrationIdpResolver.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/user/PasswordPolicyRequestParseHandlerTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserRegistrationIdpResolverTest.java
added common resolver component to get IDP for registration. Reuse it, on password policy stages: presentation and validation
=> feature: AM-2892 - add common resolver component to get IDP for regisration

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/CommonUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/OrganizationUserServiceTest.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/AccountAccessTokenRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcAccountAccessTokenRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringAccountAccessTokenRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAccountAccessTokenRepository.java, gravitee-am-service/src/main/java/io/gravitee/am/service/CommonUserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/OrganizationUserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/IdentityProviderServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/OrganizationUserServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/OrganizationUserServiceTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
fixes AM-3093
- Remove tokens from access_tokens when a user is removed
- Remove tokens from account_access_tokens when an organization user is removed
=> fix: remove tokens on user delete

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/NonBCryptIterationsRoundsUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/IdpJsonConfigurationTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/NonBCryptIterationsRoundsUpgraderTest.java
As a part of migration, all non-BCrypt algorithms used for all IDPs should be reconfigured that iteration rounds options should be reset. 
The problem may arise if application with SHA (or any other non-BCrypt) had iteration rounds setup. Before 4.4, this value wasn't processed, but after the migration it will be considered. Therefore, users with existing accounts could face login issues.
=> feature: AM-3002 - all iteration rounds should be reset for non-BCrypt algortihms

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/provider/CertificateUtils.java
from AWS gateway to certificate header value add not encrypted chars like "", "/","="
as result certificate not valid.
add replaceAll
"\+" to "%2F"
"//" to "%2B"
"=" to "%3D"
to certificate add not encrypted "" or "/" or "="
and try by class CertificateUtils#extractPeerCertificate
receive certificate
=> Fixed not encode certificate header

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.25/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.25 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.25%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.25 release

gravitee-am-model/src/main/java/io/gravitee/am/model/RememberDeviceSettings.java, gravitee-am-model/src/test/java/io/gravitee/am/model/RememberDeviceSettingsTest.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/RememberDeviceSettingsMongo.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/ApplicationRepositoryTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchRememberDeviceSettings.java
AM-3186,  #9734
This PR ensure property names used for JSON serialization & deserialization of Remember Device settings match and therefore will be properly persisted.
=> fix: "skip remember device" not being saved when using JDBC storage

gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchPasswordSettings.java, gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.html, gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.ts, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html, gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts
fixes: AM-36
The problem was with setting value in mat-option to null. We cannot use null or undefined if value is number. I changed it to 0.
We can set also maxConsecutiveLetters in password policy for an application settings. But there is PATCH and undefined value was ignored (couldn't set maxConsecutiveLetters from for example 2 to unlimited). It required small change in backend.
=> fix: max consecutive letters in password policy

gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/TokenPurpose.java, gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/common/RedirectUriValidationHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidator.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/RedirectUriValidatorTest.java
AM-3187, #9735
Keep track of what flow the MFA challenge is invoked in, and allow redirect_uri to not be provided where it's not used (i.e. in the password reset flow)
=> fix: don't require a redirect_uri param in the reset password flow

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.26/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.26 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.26%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.26 release

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/Prompt.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/impl/OpenIDDiscoveryServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/discovery/OpenIDDiscoveryServiceTest.java
by default custom prompt are exposed, to remove them legacy.openid.filterCustomPrompt has to be set to true in gravitee.yml
fixes AM-2987
gravitee-io/issues#9667
=> fix: introduce legacy settings to filter out the custom prompt values

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java
this is useful to give access to the IP & UserAgent if the consent is given automatically through the gravitee config
to be align with the previous behaviour, cookie session is destroyed at the end of the forgot password request
fixes AM-3139
gravitee-io/issues#9724
=> fix: execute session handler on forgot password

gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectConfigurationUtils.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/test/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectConfigurationUtilsTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/IdentityProviderServiceImpl.java
If client auth method equals to client_secret_basic or  client_secret_post there is no use of certificate.
By removing it on create/update for configurtion, the certificate would be able to be deleted as its won't be associated with any IDP.
=> AM-3292 mtls openid delete cert

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.27/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.27 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.27%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.27 release

pom.xml
=> chore: bump gravitee-node version

helm/CHANGELOG.md, helm/values.yaml
https://gravitee.atlassian.net/browse/AM-3084
Previously, our default configuration say that even if you enable TLS, we don't redirect HTTP to HTTPS.
By default (without our overwrite config) nginx says:
```
By default the controller redirects (308) to HTTPS if TLS is enabled for that ingress.
```
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#server-side-https-enforcement-through-redirect
So both case:
- customer keep default and use HTTP
- customer only enable TLS
will be handled correctly with default nginx configuration.
As we add nginx.ingress.kubernetes.io/ssl-redirect: "false" which is ok by default without TLS.
This mean that even if we enable TLS, the redirection is still disabled.
My proposal is to remove our default setting and keep the …
=> fix: http redirection to https

.circleci/workflows.yml, gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractMongoRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractManagementMongoRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/AbstractOAuth2MongoRepository.java
this time window is used when mAPI and GW have a time drift
this is not the case in IT env
related-to AM-3078
=> chore: remove time window for sync process

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/GraviteeContext.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/DomainResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/DomainResourceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgraderTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/DomainService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TagServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/management/DomainAuditBuilder.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/impl/AuditReporterVerticle.java, gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/vertx/EventBusReporterWrapper.java, gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java, gravitee-am-ui/src/app/domain/settings/audits/audits.component.html, gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts
Only DOMAIN_CREATED, DOMAIN_DELETED are sent in addition of DOMAIN_UPDATED when the name or the enabled attributes change
This commit changes the referenceType and refenceId of the target entry for domain event (previously it was referencing the domain but it is more relevant to have the env
DOMAIN_CREATED & DOMAIN_DELETED are only sent on the Org level reporters not on the domain reporters anymore
fixes AM-3269
=> feat: publish some domain event to the Organization Audit logs

pom.xml
fixes AM-3317, stacktrace details in https://gravitee.atlassian.net/browse/AM-3317
StackOverflowError is thrown due to recursive loop on watchProperty().
As a remedy, the main Flowable is wrapped to Flowable.defer(Supplier) and chained with repeat()
=> AM-3317 [4.1] fix - StackOverflowError on Kubernetes websocket connection issues

gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/AbstractCertificateProvider.java
https://gravitee.atlassian.net/browse/AM-3308
allow get certificate content from different sources than a file for plugin gravitee-am-certificate-aws
=> feat: allow get certificate content from different sources than a file

gravitee-am-ui/src/app/app.module.ts, gravitee-am-ui/src/app/directives/gv-expression-language-style-reapply.directive.ts, gravitee-am-ui/src/app/domain/applications/application/idp/selection-rule/create/create.component.html, gravitee-am-ui/src/app/domain/settings/providers/provider/mappers/create/create.component.html, gravitee-am-ui/src/app/domain/settings/providers/provider/mappers/mappers.component.html, gravitee-am-ui/src/app/domain/settings/providers/provider/roles/create/create.component.html
fixes AM-3318; after revisit page with gv-exp-lan component some CSS are missing. The directive workarounds the shadowRoot and applies needed CSSes.
=> AM-3318 fix: obsolete gv-expression-language quirks.

gravitee-am-reporter/gravitee-am-reporter-api/src/main/java/io/gravitee/am/reporter/api/provider/NoOpReporter.java
fixes AM-3377; In Audit Logs explorer, ManagementAuditReporterManager.doGetReporter(ref) returns the first one from all canSearch=true and then, it is used to perform queries. It could happen, the NoOpReporter is used instead of running System reporter.
=> AM-3377 fix: NoOpReporter is not searchable.

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
https://gravitee.atlassian.net/browse/AM-3474
=> fix: specify min cache value for certificate, update certificate aws plugin

gravitee-am-ui/src/app/environment/environment.component.ts
I had to use relative path to domains, because when switching environments from drop down menu, ActivatedRouteSnapshot keep current path and redirected back to first environment.
=> fix: switching environments

gravitee-am-model/src/main/java/io/gravitee/am/model/RememberDeviceSettings.java, gravitee-am-model/src/test/java/io/gravitee/am/model/RememberDeviceSettingsTest.java
AM-3451, #9857
Ensure all fields of RememberDeviceSettings get copied.
Fix for 4.3+: #4459
=> [4.2.x] fix: copy all RememberDeviceSettings fields when updating an application

gravitee-am-model/src/main/java/io/gravitee/am/model/RememberDeviceSettings.java, gravitee-am-model/src/test/java/io/gravitee/am/model/RememberDeviceSettingsTest.java
AM-3451, #9857
Ensure all fields of RememberDeviceSettings get copied.
Fixed separately for 4.2 by #4458
=> [4.3.x+] fix: copy all RememberDeviceSettings fields when updating an application

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/AuthenticationFlowHandlerImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/WebAuthnLoginStep.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieService.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/WebAuthnLoginStepTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/webauthn/WebAuthnCookieServiceTest.java
fixes: when WebAuthN remember device is ON and no credential exists, user shouldn't land on /webauth/login page
=> fix: AM-3455 check credential count on WebAuthnLoginStep

CHANGELOG-v3.adoc
📝 You can modify the changelog template online [here](https://github.com/gravitee-io/gravitee-access-management/edit/changelog-AM-3.21.28/CHANGELOG-v3.adoc)
[See all Jira issues for 3.21.28 version](https://gravitee.atlassian.net/jira/software/c/projects/AM/issues/?jql=project%20%3D%20%22AM%22%20and%20fixVersion%20%3D%203.21.28%20and%20status%20%3D%20Done%20ORDER%20BY%20created%20DESC)
=> chore: Add changelog for new 3.21.28 release

gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json
AM-3549, #9879
This commit changes validation from `oneOf` (i.e. XOR) to `anyOf` (OR), allowing users to configure all 4 endpoints (.well-known, authorization, token, userInfo). In case of an endpoint being defined both in the provider configuration and in the form in AM, the backend code already handles that by giving priority to configuration obtained from the .well-known URI. 
This has been added to the field description so the users have a chance of seeing this information.
=> Relax OIDC provider config schema

helm/templates/gateway/gateway-configmap.yaml, helm/tests/gateway/configmap_http_test.yaml, helm/values.yaml
AM-3531
Add missing gateway SSL settings to the helm chart so they can be configured.
This PR only exposes new settings, no values are changed from the current config.
=> Add missing Gateway SSL settings to the helm chart

gravitee-am-service/src/main/java/io/gravitee/am/service/exception/LastDefaultEntrypointException.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EntrypointServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/EntrypointServiceTest.java, gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.html, gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.scss
AM-3597, #9888
This PR does 2 things:
1. adds a check to block deleting the (last) default entrypoint via the API to reflect the restriction already present in UI.
2. adds a bit more graceful error handling for the case when somehow there's no default entrypoint configured
=> fix: block deleting the last default entrypoint on api level

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/UserEntity.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UserResourceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/User.java, gravitee-am-model/src/test/java/io/gravitee/am/model/UserTest.java
AM-3453
This PR hides "sensitive" user properties from being viewed.
These properties will still be readable in policies, EL, etc, but the REST API and consequently the UI will see a placeholder (`●●●●●●●●`) instead of the real value.
The sensitive properties can still be deleted/updated normally.
Currently the only properties marked sensitive are the properties used for storing original tokens from OIDC providers:
`op_access_token` and `op_id_token`.
=> fix: hide sensitive additional properties from api

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgraderTest.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java
https://gravitee.atlassian.net/browse/AM-3386
Create organization user 
Create app user
=> fix: audits present twice during user creation

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/manager/subject/SubjectManagerV2Test.java
the reason is some user expect such format to not exceed a 32 characters value
fixes AM-3662
=> fix: provide UUID generated based on the internal sub for Domain in v2

.circleci/workflows.yml
```
Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.6:install-node-and-npm (install node 
and npm) on project gravitee-am-webui: Could not extract the Node archive: Could not extract archive: 
'/home/circleci/.m2/repository/com/github/eirslett/node/18.13.0/node-18.13.0-linux-x64.tar.gz'
```
This PR fchanges the cache key to force a fresh donwload of the broken archive
=> change cache key to bypass malformed node archive

gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.ts
AM-3499
IDP form component will now automatically add required ui-specific properties to the schema so that 'sensitive' properties use the password input type.
=> AM-3499 OIDC idp secret input should be password

pom.xml
its a long shot, but may be a quick win.
=> chore(deps): rollback org.mongodb:mongodb-driver-reactivestreams to v4.11.1

gravitee-am-model/src/main/java/io/gravitee/am/model/safe/RoleProperties.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java, gravitee-am-model/src/test/java/io/gravitee/am/model/safe/RolePropertiesTest.java
fixes AM-3661
gravitee-io/issues#9918
the custom claims defined in the screenshot will produce this output
```
{
...
"rolesPermissions": [
{
"id": "0b74d6f7-9d5b-488b-b4d6-f79d5b988b35",
"name": "test",
"description": "test desdc",
"permissionAcls": {},
"oauthScopes": [
"address",
"dcr",
"scim"
]
}
],
"permissions": {
"test": [
"address",
"dcr",
"scim"
]
},
...
}
```
=> fix: provide role and permission in user profile

gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java
fixes AM-3873
fixes AM-3845
fixes AM-3790
fixes AM-3897
gravitee-io/issues#10000
gravitee-io/issues#9997
gravitee-io/issues#9988
gravitee-io/issues#10006
=> fix: restore the default contructor for WebClientBuilder as it is used by EE plugins

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-model/src/main/java/io/gravitee/am/model/factor/EnrolledFactor.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/EnrolledFactorChannelProperties.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/EnrolledFactorProperties.java, gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java
we also provide the list of enrolled factor in the user profile
fixes AM-3791
gravitee-io/issues#9990
```
<span th:text="${enrolledFactor.factorId}"></span><br /> // ID of the factor 
<span th:text="${enrolledFactor.status}"></span><br /> // Status of the enrollment (PENDING_ACTIVATION or ACTIVE)
<span th:text="${enrolledFactor.channel.type}"></span><br /> // SMS, EMAIL...
<span th:text="${enrolledFactor.channel.target}"></span><br /> // phoneNumber, email...
```
The list of factor linked enrolled by the user is also available using the factors list
`user.factors[0].channel.target`
=> fix: provide enrolled factor in the MFA challenge template

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailManagerImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailManagerImpl.java
to avoid initialization error if the value is not defined which prevent the domain to load on the GW
fixes AM-3723
gravitee-io/issues#9951
=> fix: provide null as default value for email.from placeholder

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
fixes AM-3961
gravitee-io/issues#10024
This PR allowes to ignore a change introduced by gravitee-io/issues#9987 in order to not block users which are creating app witout redirectUris. This fix will be applied on 4.1.x up to 4.4.x but in 4.5.0, the application creation will require redirectUris without options to bypass it.
=> fix: introduce option to not force redirectUris during app creation

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/endpoints/user/RegisterConfirmationEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/endpoints/user/ResetPasswordEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterEndpointTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/registration_confirmation.html, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/default/reset_password.html
this will help to propose the remember device option during MFA enrollment
when the autologin is enabled after reset pwd or registration action
fixes AM-3965
gravitee-io/issues#10031
=> fix: load rememberDevice JS during resetPassword and registration

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackParseHandler.java
AM-3982
Removes left-over base64 decode step from code verifier extraction code.
=> fix: AM-3982: fix code verifier extraction

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UserEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/users/UpdateUserEndpointHandlerTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/UsernameEntity.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UserResource.java, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-service/src/main/java/io/gravitee/am/service/validators/user/UserValidatorImpl.java, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html, gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
fixes AM-3945
For 4.1-4.4 "Self account management" there is no "update username" capability.
For 4.5/master it will be separate PR.
=> fix: AM-3945 username cannot be blank

helm/templates/api/_api-deployment-probes.tpl, helm/templates/api/api-deployment.yaml, helm/templates/gateway/_gateway-deployment-probes.tpl, helm/templates/gateway/gateway-deployment.yaml, helm/tests/api/configmap_sync_test.yaml, helm/tests/api/deployment_probes_test.yaml, helm/tests/gateway/configmap_sync_test.yaml, helm/tests/gateway/deployment_probes_test.yaml, helm/values.yaml
TT-5491
This commit will keep the existing startup/liveness/readiness probe in
values.yaml but change the current behaviour:
Now we define default values which are overwrite when customer define
something in values.
It is backward compatible to ensure that existing values continue to
work as previously. Except for one specific case: if you not defined your probes definition but keep close the internal-api (to localhost).
In that case, Your deployment will fail until you open the internal api or overwrite the default probes.
Also I asked for a deprecation of `gateway.readinessProbe.domainSync` as
we can overwrite it in a "better" way now.
Deploy AM from helm package into a kube cluster and test default
and different values for probes.
=> feat(helm): rework gateway probes definition with default value and customisation

helm/templates/api/_api-deployment-probes.tpl, helm/templates/gateway/_gateway-deployment-probes.tpl
TT-5491
During previous rework about gateway probes definition with default
value and customisation, we backported default values from helm chart.
However according to the one define in application settings
(gravitee.yaml). They are false.
This commit fix it and align default value between helm chart and
application setting.
=> fix(helm): use right default service port from helm chart

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/Indexed.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/bulk/BulkOperationResult.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/bulk/BulkRequest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/bulk/BulkResponse.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/bulk/BulkRequestTest.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/bulk/BulkResponseTest.java
AM-3573
This PR introduces new bulk endpoints for creating domain & organisation users.
It's implemented using a new `BulkRequest` class that provides a unified way of representing and handling bulk execution of existing operations.
=> feat(mapi): bulk create users (domain & org)

gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/AbstractNewUser.java, gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewOrganizationUser.java
AM-4194
This PR removes the `serviceAccount` field from new user model to disallow creating service accounts on domain level.
Service accoutns should only be used in organisation context.
=> Disable creating service users in domains

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/groups/GroupsEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/UsersEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/GroupServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/GroupServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java, gravitee-am-model/src/main/java/io/gravitee/am/model/common/Page.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/GroupRepository.java, gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/AbstractDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/DatabaseDialectHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MsSqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/MySqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/dialect/PostgresqlHelper.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcGroupRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/OffsetPageRequest.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoGroupRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/GroupRepositoryTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java, gravitee-am-service/pom.xml, pom.xml
in the RFC the startIndex represent the entity position on the storage but on AM we were considering the page number
fixes AM-4310
This PR is a draft on top of AM-4300 PR to run the CI on the "ordered" result seach/list fix.
AM-4300 need to be merged first and apply on 4.6.0/master before beeing able to apply this one on 4.6.0/master
=> fix: align SCIM list behaviour with the RFC [BREAKING CHANGE]

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/impl/IntrospectionServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/IntrospectionServiceTest.java
in some cases sub may not be the client_id but still not represent a user (ex with extension grant)
fixes AM-4340
=> fix: ingore Unknown sub user during introspect

helm/templates/api/api-deployment.yaml, helm/templates/api/api-upgrader-job.yaml, helm/values.yaml
as upgraders are executed before listening the HTTP port
and we are not able to evaluate the duration of an upgrade
as consequence we decided to remove probes for upgraders
we also cleanup the cockpit/cloud settings as it is useless to connect to cockpit during upgrade
Default value for the upgrader fwk has been removed to always execute the upgraders during mAPI startup (legacy behaviour)
fixes AM-4313
=> fix(helm): remove probes from upgrader manifest

gravitee-am-ui/src/app/domain/settings/certificates/certificates.component.ts
=> fix: adapt the AWS CloudHSM name in the Certificate list page

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/mapper/UserMapper.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AbstractUserService.java
AM-4526
This PR blocks possibility of creating new users with lastPasswordReset set to a future date in SCIM and Management APIs
=> AM-4526: block creating users with future lastPasswordReset date

gravitee-am-ui/src/app/domain/settings/password-policy/pass-policy-status/password-policy-status.component.ts, gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.html, gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.ts
AM-4500
This PR changes how the password-policy-status components performs validation to avoid update-after-check error.
It also fixes the check for the 'create' button on create user screen to properly ignore password validity when pre-registration is selected.
=> fix: avoid change-after-check error in password policy component

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/OrganizationUserResource.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/OrganizationUserService.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/OrganizationUserService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/OrganizationUserServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/OrganizationUserServiceTest.java
AM-4048
Changes the org user management api to return 404 instead of 500 when revoking a non-existig account access token
=> fix: AM-4048: 500 when deleting non-existing account token

.circleci/workflows.yml
fixes: 
```
+ aws s3 sync '~/release/' s3://gravitee-releases-downloads/ --endpoint-url https://cellar-c2.services.clever-cloud.com '\
--acl' public-read
Unknown options: \
--acl,public-read
```
=> chore: fix circleci

.circleci/workflows.yml
fix pipeline error ```The user-provided path ~/release/ does not exist.```
=> chore: fix aws s3 from parameter

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java
this avoid to retrieve the user profile and force token request for external provider
fixes AM-4703
=> fix: remove GIS from the session on prompt=login

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenServiceTest.java
=> fix: backport AM-3520 on 4.4

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/InvalidGrantException.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/ciba/CibaTokenGranter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/code/AuthorizationCodeTokenGranter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/refresh/RefreshTokenGranter.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/RevocationTokenEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/granter/code/AuthorizationCodeTokenGranterTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranterTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/granter/refresh/RefreshTokenGranterTest.java
=> AM-4731 ext grant message

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummySession.java, gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/transaction/TransactionHandler.java, gravitee-am-test/specs/gateway/mfa.jest.spec.ts
this change allows to generate a new challenge even during the enrollment phase
Since the code is renewed on each challenge call, the Jest test has to be rework for
email factor otherwise the code read before the verification method is invalidated
due to the second call on challenge endpoint made to get the XSRF token
fixes AM-4734
=> fix: use the tid as seed to generate the moving factor

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpointTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpRequest.java
an invalid code redirect to the challenge page so the code can be trigger
this fix test if the page is display following an error to avoid sending a new code
fixes AM-4734
=> fix: regenerate the code only when there is not error in the URL

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
About fix: sometimes loading dictionary is on different thread then getting it and it causes an issue when sending an email. Changed to DomainBasedDictionaryProvider.
fixes: AM-4764
=> fix: changed dictionary provider for email service

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/spring/SecurityDomainRouterConfiguration.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/preview/PreviewService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/FileSystemDictionaryProvider.java, gravitee-am-service/src/main/java/io/gravitee/am/service/i18n/GraviteeMessageResolver.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EmailServiceImpl.java, gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/FileSystemDictionaryProviderTest.java, gravitee-am-service/src/test/java/io/gravitee/am/service/i18n/FreemarkerMessageResolverTest.java
There two commits:
* First one about Spring Context footprint to reduce the Domain memory footprint by 50%
* Seconf about FileSystemDictionaryProvider to load a provider only once. (save 40MB for 519 domains loaded)
=> AM-4792 - Improve memory usage in AM Gateway

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceImplTest.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/email/EmailServiceTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/EmailService.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EmailServiceImpl.java, gravitee-am-service/src/main/java/io/gravitee/am/service/impl/VerifyAttemptServiceImpl.java
this is to avoid issue oin Gateway since the common service layer is loaded before the domain so the SpringContext is not specific to the domain
the Management API has also been changed to load the dictionaries everytime an email needs to be sent
fixes AM-4945
=> fix: use DomainBased dictionary outside of the common EmailService

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/AM-4994
With that PR: https://github.com/gravitee-io/gravitee-docker/pull/211
a new image `graviteeio/rpmsign` is available to sign RPM with GPG key.
Now, after the build with FPM and before pushing the RPM to artifactHub,
we sign all generated RPM files.
Also, on dry-run mode, we now push to nightly repository.
Example of CI trigger for AM 4.7.1:
* dry-run == true: https://app.circleci.com/pipelines/github/gravitee-io/gravitee-access-management/22003/workflows/c0f4682d-a4d0-42cf-a731-faae2fff9e47/jobs/207725
* dry-run == false: https://app.circleci.com/pipelines/github/gravitee-io/gravitee-access-management/22020/workflows/20c5185d-7cbb-4052-a1fd-5a4e97a3b968/jobs/207798
=> ci(rpm): Sign RPM with Gravitee GPG key

helm/values.yaml
fixes AM-5077
This param was probably a bad copy/past from the APIM chart as this parameters is note managed by AM either by the Gravitee node module.
=> fix: remove invalid settings from the values.yaml example

.circleci/workflows.yml, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/provider/CertificateUtils.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/provider/CertificateUtilsTest.java
**A description of the changes proposed in the pull request:**
Introduced changes added to sort out the problem with situation when AWS ALB stands in front of Gravitee and make certificate encoding, skipping few characters: '+' ,'=', '/'; Proposed changes adds encoding for that, so decoding should work correctly on Gravitee side.
https://docs.aws.amazon.com/elasticloadbalancing/latest/application/mutual-authentication.html
fixes AM-5152
This PR has been opened to add UnitTest and execute the CI before merging the PR oppened by https://github.com/rkarpen2
original PR: https://github.com/gravitee-io/gravitee-access-management/pull/5914
=> Fix AWS ALB certificate decoding

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/ClientSecretManager.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoNotificationAcknowledgeRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/NotificationAcknowledgeRepositoryTest.java
Fixes: AM-5142
The problem was that when we set 2 notifiers (ui and log) then on renew it removed only one notifier from DB (log in this case). I have to change to remove all notifiers when resource is removed or renewed.
=> fix: notification after secret renewal

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest_MSSQL.java, gravitee-am-repository/gravitee-am-repository-jdbc-api/src/main/java/io/gravitee/am/repository/jdbc/provider/impl/ConnectionFactoryProvider.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/MssqlR2DBCContainer.java
fixes AM-5106
added preferCursoredExecution boolean property to mssql connection option
also made tests to work with preferCursoredExecution=false
Changes between 1.0.0 and 1.0.1 -> https://github.com/r2dbc/r2dbc-mssql/compare/v1.0.0.RELEASE...v1.0.1.RELEASE
In MssqlConnectionConfiguration they changed
The DefaultCursorPreference returns true, when the query is "SELECT"
The documenations states:
_Whether to prefer cursors or direct execution for queries. Uses by default direct. Cursors require more round-trips but are more backpressure-friendly. Defaults to direct execution. Can be boolean or a Predicate<String> accepting the SQL query. (Optional)_
It seems like the feature is broken, I created an issue on r2dbc-mssql repo
=> fix: r2dbc-mssql in 1.0.1+ version problem with cursoredExecution

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/notifications/KafkaNotifierConfigurationProvider.java
fixes AM-5254
The expected format follows the environment variables definition in kubernetes manifest.
```
additionalProperties:
- name: "batch.size"
value: 100
```
=> fix: manage to read additionalProperties for kafka notifier

gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/builder/management/ApplicationAuditBuilder.java
fixes AM-5268 AM-5268
due to removal of @JsonIgnore in ClientSecret
=> AM-5268 fix: filtering application sensitive data in logs

.circleci/workflows.yml
https://gravitee.atlassian.net/browse/TT-7804
When dryrun is true, RPM is publish on nightly,
when is it false, then RPM are publish on release repository.
On release process, and only it, we need to publish on release repo.
=> ci(publish_rpm): fix release process to publish RPM with dryrun false

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java
for some reason, if the computation scheduler contains only one thread
the blockingGet made by the CookieSession handler never respond
this is happening only when OIDC provider are defined for the application because the provider url set in the login page also sign a JWT to define the state param
related-to AM-5263
=> fix: revert the usage of Scheduler.computation for JWT signature

gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/http/WebClientBuilderTest.java
Fixes: AM-5053
This relates to https://github.com/gravitee-io/gravitee-am-resource-http-factor/pull/63.
What was the issue: when useSystemProxy was not checked then the proxy was used even if the host was in excluded hosts because it passed null as a url. With this change the system proxy is used when checkbox is selected and url is not in excluded hosts.
=> fix: allow to enable proxy from plugin

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/AbstractUsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/OrganizationUsersResource.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
In case of size greater then 1000 the api returns 400
`{"message":"[1025: must be less than or equal to 1000]","http_status":400}`
=> fix: AM-5309 lift limit on users count

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java, gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/oidc/OpenIDConnectIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderConfiguration.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json, gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/test/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProviderTest.java
fixes AM-4666
1. Create a domain "main-domain"
2. Create a domain "oidc-domain"
3. On OIDC domain, enable Open DCR and accept localhost with unsecured connection
4. On OIDC domain, create a B2B app with DCR & DCR_ADMIN scope
5. create a user in oidc-domain
6. request a token for this application
```
curl -X POST \
http://localhost:8092/oidc-domain/oauth/token \
-H 'Content-Type: application/x-www-form-urlencoded' \
-u 'service:servicesecret' \
-d 'grant_type=client_credentials'
```
7. Use this token to create a WEB application usingn DCR with a callback url targeting main-domain
```
curl -X POST http://localhost:8092/oidc-domain/oidc/register -H'Content-Type: application/json' -H'Authorization: Bearer $TOKEN' -d'
{ "redirect_uris": ["http://localhost:8092/main-domain/login/callback"], …
```
=> fix: manage application/jwt content type as UserInfo endpoint response

gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/jwt/jwks/remote/RemoteJWKSourceResolver.java
Added constructor only with url to provide compatibility with plugins
Fixes: AM-5412
=> fix: default constructor for RemoteJWKSourceResolver

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java, gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/constants/MongoAuditReporterConstants.java
closes: AM-5378
This PR introduces new configuration properties for the mongodb reporter which will allow users to set the readPreference and max staleness of the audit queries to reduce load on the system.
Save this docker compose file so you can use it to build the expected containers:
```yaml
version: '3.8'
services:
mongo1:
image: mongo:8
container_name: mongo1
ports:
- "27017:27017"
command: ["--replSet", "rs0", "--bind_ip_all"]
networks:
- mongo-cluster
healthcheck:
test: ["CMD", "mongosh", "--quiet", "localhost:27017/test", "--eval", "db.runCommand({ ping: 1 })"]
interval: 10s
timeout: 5s
retries: 5
volumes:
- ./data/mongo1:/data/db
mongo2:
image: mongo:8
container_name: mongo2
command: ["--replSet", "rs0", "--bind_ip_all"]
networks:
- mongo-cluster
healthcheck:
test: ["CMD", …
```
=> AM-5378 feat: Set read preference on audit read queries

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParser.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/common/FilterCriteriaParserTest.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java, gravitee-am-ui/src/app/domain/settings/users/users.component.ts
fixes: AM-4985 - [Link](https://gravitee.atlassian.net/browse/AM-4985)
This pull request improves the handling and testing of regex special characters in filter criteria parsing for MongoDB queries. The changes ensure that when using regex-based operators, special characters in filter values are properly escaped, preventing malformed queries and potential security issues. Additionally, comprehensive parameterised tests are added to verify correct escaping for all supported regex characters.
**Regex handling improvements:**
* Added a list of regex operators (`co`, `sw`, `ew`) and a list of allowed regex special characters to `FilterCriteriaParser`, and implemented logic to escape these characters in filter values when a regex operator is used. 
**Testing enhancements:**
* Introduced …
=> [AM-4985] Add support for escaping regex special characters in FilterCriteriaParser

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainNotifierServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/DomainNotificationServiceTest.java
fixes: [AM-5462](https://gravitee.atlassian.net/browse/AM-5462)
This PR introduces a check on the registration of certificates for a notification when the certificate expires to ensure the certificate has an expiry date.
To reproduce the issue use the following docker compose file (make sure the volumes etc are all setup correctly)
```yaml
#
#
#
#
#
volumes:
datamongo: {}
services:
nginx:
image: nginx:1.21.1-alpine
container_name: gio_am_nginx
restart: always
volumes:
- ./config/nginx.conf:/etc/nginx/nginx.conf
ports:
- 8088:80
depends_on:
- management
- gateway
- webui
mongodb:
image: mongo:4.2
container_name: gio_am_mongodb
restart: always
volumes:
- datamongo:/data/db
- ./logs/am-mongodb:/var/log/mongodb
ports:
- 27017:27017
fakesmtp:
image: gessnerfl/fake-smtp-server
container_name: …
```
=> fix: AM-5462 Only register the certifcate for notifications if it has an expiry date

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateNotifierServiceImpl.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/CertificateNotifierServiceImplTest.java
re-application of PR from [6313](https://github.com/gravitee-io/gravitee-access-management/pull/6313)
=> fix: prevent notification for certificates without expiry date

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml, gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java, gravitee-am-service/src/test/java/io/gravitee/am/service/http/WebClientBuilderTest.java
[AM-2741](https://gravitee.atlassian.net/browse/AM-2741)
Expose configurable settings for
- http/1.1 max pool size (preserves existing default of 10)
- http/2
- enabled (**true by default**; configures ALPN so that requests are made with http/2 if available, otherwise they will fall back to http/1.1)
- max pool size (mirrors existing default of 10)
- connection window size (defaults to vertx's default of 65535)
- keep alive timeout (defaults to vertx's default of 60 seconds)
Primarily affects identity provider communication in IDP modules and the gateway (OAuth2 generic, OIDC providers and http). Accordingly, steps similar to https://gravitee.atlassian.net/browse/AM-4040 can be used to configure an external IDP. We can then observe logs according to configuration provided in the gateway's …
=> feat: AM-2741 configurable web client protocol

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java, gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationServiceTest.java
fixes: AM-5385
This pull request introduces a small but important change to how user authentication information is handled before authentication. Specifically, it updates the source field in the user's additional information to use the last identity provider used, rather than the user's source.
* The `SOURCE_FIELD` in the `additionalInformation` map is now set to `user.getLastIdentityUsed()` instead of `user.getSource()`, ensuring that the most recent identity provider is accurately tracked during pre-authentication. (`gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java`)
We need to test the following scenarios:
- Authentication via LDAP
- Dynamic Role …
=> fix: Use last identity to set source field on idp user

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringAccountAccessTokenRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/AccountAccessTokenRepositoryTest.java
https://gravitee.atlassian.net/browse/AM-5510
**MsSQL server doesn’t support delete statement with alias which can cause the following error:**
```
delete from account_access_tokens a where a.user_id = 'user-1' and a.reference_id = 'account-123' and a.reference_type = 'ACCOUNT'
SQL Error [102] [S0001]: Incorrect syntax near 'a'.
```
**updating the statement to the following can fix this:**
```
delete from account_access_tokens where user_id = 'user-1' and reference_id = 'account-123' and reference_type = 'ACCOUNT'
Updated Rows	1
Execute time	0.111s
```
update the statement to not use alias.
=> AM-5510 update delete statement to support mssql

gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/repository/ratelimit/model/RateLimit.java, gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/ratelimit/api/JdbcRateLimitApiRepository.java, gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/ratelimit/RateLimitObjectRepository.java, gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/ratelimit/api/RateLimitRepositoryTest.java
fixes: AM-5599
Implements the reset of the rate limit item if the reset time has passed.
- Configure Rate Limit on Mongo/Postgres/Redis to have a small timeout, 30 secs and small limit, 5
- Make 5 requests within 30 seconds
- Verify the 6th request is status code 429
- Wait 30 seconds for the expiry to pass
- Make another request
- Verify the status code 200
n/a
n/a
=> AM-5599 rate limit expire reset

.circleci/workflows.yml
=> chore(cicd): AM-3304 the Helm publication step should be dependant on Docker images

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/CockpitAuthenticationFilter.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/utils/RedirectUtils.java, gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/utils/RedirectUtilsTest.java, gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/adapter/HelloCommandAdapter.java, gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/adapter/HelloCommandAdapterTest.java
fixes: AM-5573
This pull request improves the handling of URL concatenation and sanitization throughout the authentication and service layers, specifically addressing issues with trailing slashes that could cause malformed URLs or Jetty rejections. It introduces a new utility method for building redirect URLs safely, applies this method in authentication flows, and ensures URLs are sanitized before being sent in payloads. Comprehensive unit tests have also been added to verify these changes.
**Redirect URL handling and sanitization:**
* Added `RedirectUtils.buildCockpitRedirectUrl` to safely combine a base URI and redirect path, removing trailing slashes and preventing double slashes in redirect URLs. This method is now used in `CockpitAuthenticationFilter` to construct redirect URLs. …
=> Am 5573 sanitise redirect

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/bin/gravitee, gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/bin/gravitee.bat, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/bin/gravitee, gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/bin/gravitee.bat
This PR standardizes Java memory configuration across all products. It was enabled a few months ago on APIM but not yet on the other products.
https://gravitee.atlassian.net/browse/AE-143
=> feat: enable skip Xms and Xmx with GIO_DISABLE_STARTING_MEMORY

.circleci/workflows.yml
There was no problem with AM app
ConfigMaps for am-master-ce-dev contained wrong MongoDb username (old graviteeio, should be am-nonprod). Due to that, pre-upgrader Job cannot be finished (got Unauthorized error from Mongo) and it was blocking helm upgrade entirely. I fixed it by removing am-master-ce-management-api-pre-upgrade Job while pipeline was stucked on helm upgrade. Now CE env is up and running
Now, we can remove unused CE env :)
=> chore: AM-5592 removed helm upgrade step for master-ce

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/token/TokenEndpoint.java
fixes AM-5744
This is a minor optimization to avoid useless object creation.
=> fix: use tokenRequest HttpResponse instead of generate a new one

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoAbstractProvider.java
AM-5459
This pull request updates the logic in the `MongoAbstractProvider` class to ensure that datasource configuration is prioritized when building the MongoDB client wrapper. The main change is to check for the presence of a datasource before any other client selection logic.
Client selection logic improvements:
* The check for `shouldUseDatasource()` and the corresponding call to `configureDatasourceClient()` have been moved to the beginning of the `buildClientWrapper` method, ensuring that datasource configuration takes precedence over other client options.
* The previous redundant check for `shouldUseDatasource()` at the end of the method has been removed to prevent duplicate logic and streamline the client selection process.
Same as AM-5459
n/a
=> AM-5459: set datasource as highest precedence in mongo provider
