gravitee-io/gravitee-access-management

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/WebMvcConfiguration.java

Closes gravitee-io/graviteeio-access-management#23

fix(oauth2): Set default content-type to application/json

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/AuthorizationServerConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/CustomAuthorizationServerEndpointsConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/CustomAuthorizationServerSecurityConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/endpoint/RevokeTokenEndpoint.java

Closes gravitee-io/graviteeio-access-management#27

feat(oauth2): Token revocation support - RFC 7009

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/security/ClientBasedAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProviderConfiguration.java

Closes gravitee-io/graviteeio-access-management#29

fix(inline-idp): Return logged user after an authentication phase

---

gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/DefaultUser.java

fix(check-token) : display user information during token validation

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2SecurityConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/authentication/OAuth2LoginUrlAuthenticationEntryPoint.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/controller/LoginController.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/security/web/authentication/ClientAwareAuthenticationDetailsSource.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/security/web/authentication/ClientAwareAuthenticationFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/resources/views/login.html
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/logback.xml
pom.xml

Closes gravitee-io/graviteeio-access-management#34

feat(oauth2): Custom login form for all security domains

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/security/ClientBasedAuthenticationProvider.java

Closes gravitee-io/graviteeio-access-management#36

fix(oauth2): Check client_id while doing authentication

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/pom.xml
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/ManagementApplication.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/resources/platform/plugins/IdentityProvidersPluginResource.java

Closes gravitee-io/graviteeio-access-management#40

feat(management-api): Add Swagger descriptor

---

gravitee-am-ui/src/index.html
gravitee-am-ui/src/styles.scss

fix(splashscreen) : remove splash screen image flickering effect

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/mapper/ObjectMapperResolver.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/resources/DomainLoginFormResource.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/resources/DomainResource.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/resources/DomainsResource.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/controller/LoginController.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/view/DomainBasedTemplateResolver.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/view/ThymeleafTemplateResolverFactory.java
gravitee-am-gateway/gravitee-am-gateway-jetty/src/main/java/io/gravitee/am/gateway/jetty/handler/security/SecurityDomainHandler.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/DomainService.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/DomainServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/model/UpdateLoginForm.java
gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Domain.java
gravitee-am-model/src/main/java/io/gravitee/am/model/login/LoginForm.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/DomainMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/LoginFormMongo.java

Closes gravitee-io/graviteeio-access-management#20

feat(oauth2): Domain login form

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/resources/ClientResource.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/resources/IdentityProviderResource.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/ClientService.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/IdentityProviderService.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/exception/IdentityProviderWithClientsException.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/ClientServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/IdentityProviderServiceImpl.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/ClientRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoClientRepository.java
gravitee-am-ui/src/app/domains/domain/clients/clients.component.ts
gravitee-am-ui/src/app/domains/domain/providers/creation/steps/step2/step2.component.html
gravitee-am-ui/src/app/domains/domain/providers/provider/provider.component.html
gravitee-am-ui/src/app/domains/domain/providers/providers.component.ts
gravitee-am-ui/src/app/services/auth.service.ts
gravitee-am-ui/src/app/services/http.service.ts

feat(clients-providers): delete clients and identity providers

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/src/main/java/io/gravitee/am/gateway/handler/management/api/spring/security/SecurityConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/InitializerService.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/InitializerServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/node/GatewayNode.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-ui/constants.json
gravitee-am-ui/src/app/services/auth.service.ts
gravitee-am-ui/src/app/services/client.service.ts
gravitee-am-ui/src/app/services/domain.service.ts
gravitee-am-ui/src/app/services/platform.service.ts
gravitee-am-ui/src/app/services/provider.service.ts

Closes gravitee-io/graviteeio-access-management#51

feat(init): Add a lifecycle service to initialize admin domain

---

gravitee-am-ui/constants.json
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/components/sidenav/sidenav.component.html
gravitee-am-ui/src/app/logout/callback/callback.component.spec.ts
gravitee-am-ui/src/app/logout/callback/callback.component.ts
gravitee-am-ui/src/app/logout/logout.component.spec.ts
gravitee-am-ui/src/app/logout/logout.component.ts
gravitee-am-ui/src/app/services/auth.service.ts

feat(logout) : call authorization server to invalidate client session

---

gravitee-am-ui/src/app/oauth/callback/callback.component.ts
gravitee-am-ui/src/app/services/auth.service.ts

fix(oauth2-callback): handle oauth2 authorization callback errors

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/client/DelegateClientDetails.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/ClientServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/model/UpdateClient.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Client.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoClientRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ClientMongo.java
gravitee-am-ui/src/app/domains/domain/clients/client/form/client-form.component.html
gravitee-am-ui/src/app/domains/domain/clients/client/form/client-form.component.ts
gravitee-am-ui/src/app/domains/domain/general/general.component.html
gravitee-am-ui/src/app/services/client.service.ts

This closes #55 and closes #56

feat(auto-approval): enable auto approval client

---

gravitee-am-ui/package.json
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domains/domain/clients/client/form/client-form.component.html
gravitee-am-ui/src/app/domains/domain/clients/client/form/client-form.component.scss
gravitee-am-ui/src/app/domains/domain/login/dialog/login-info.component.html
gravitee-am-ui/src/app/domains/domain/login/login.component.html
gravitee-am-ui/src/app/domains/domain/login/login.component.scss
gravitee-am-ui/src/app/domains/domain/login/login.component.spec.ts
gravitee-am-ui/src/app/domains/domain/login/login.component.ts
gravitee-am-ui/src/app/resolvers/domain-login-form.resolver.spec.ts
gravitee-am-ui/src/app/resolvers/domain-login-form.resolver.ts
gravitee-am-ui/src/app/services/domain.service.ts
gravitee-am-ui/src/styles.scss

feat(login): create custom domain login page (ui part)

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/CustomAuthorizationServerSecurityConfiguration.java

fix(check_token): fix OPTIONS preflight request

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/assembly/plugin-assembly.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/plugin.properties
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/spring/EmbeddedLdapExecutionListener.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderTestConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/resources/test-server.ldif
gravitee-am-identityprovider/pom.xml
gravitee-am-ui/build.json
gravitee-am-ui/package.json

Closes gravitee-io/graviteeio-access-management#70

feat(ldap): Initial implementation of LDAP connector

---

gravitee-am-docs/installation-guide/installation-guide-configuration.adoc
gravitee-am-docs/installation-guide/installation-guide-gateway.adoc
gravitee-am-docs/installation-guide/installation-guide-webui.adoc
gravitee-am-docs/installation-guide/installation-guide.adoc
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/graviteeio-access-management#73

fix(gateway): Add default configuration and provide documentation

---

gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/DomainService.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/DomainServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/IdentityProviderServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/graviteeio-access-management#72

fix(oauth2): Refresh security domain after identity provider update

---

gravitee-am-gateway/gravitee-am-gateway-identityprovider/src/main/java/io/gravitee/am/gateway/idp/core/impl/IdentityProviderMapperFactoryImpl.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/IdentityProvider.java

fix(idp): Ensure backward compatiblity

---

gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/ClientServiceImpl.java

feat(oauth2) : remove default openid scope

---

gravitee-am-ui/src/app/domains/domain/login/login.component.html
gravitee-am-ui/src/app/domains/domain/login/login.component.ts

fix(domain-login): sandbox login preview page to avoid css issues

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/resources/views/login.html
gravitee-am-ui/src/app/domains/domain/login/dialog/login-info.component.html

Closes gravitee-io/graviteeio-access-management#101

fix(oauth2): Use a relative path for login action

---

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/token/MongoTokenRepository.java

fix(refresh-token): do not send null refresh token during requesting access token

---

gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/InitializerServiceImpl.java

fix(oauth2): set default scopes for the admin client

---

gravitee-am-ui/src/app/components/sidenav/sidenav.component.html
gravitee-am-ui/src/styles.scss

fix(assets): use relative assets path to avoid 404 error

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/controller/ScopeApprovalController.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/controller/SpelView.java

Closes gravitee-io/graviteeio-access-management#114

fix(oauth2): Set correct form action for scope approval page

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/token/RepositoryTokenStore.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/model/OAuth2AccessToken.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/model/OAuth2RefreshToken.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/token/MongoTokenRepository.java

fix(oauth2) : add auditable date information for access and refresh tokens

---

gravitee-am-ui/src/app/domains/domain/certificates/creation/steps/step2/step2.component.ts
gravitee-am-ui/src/app/domains/domain/providers/provider/settings/settings.component.ts

fix(providers): fix identity provider definition update

---

gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/InlineIdentityProviderRoleMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java

feat(idp): add role mapping for inline provider

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-management/pom.xml
gravitee-am-gateway/gravitee-am-gateway-repository/pom.xml
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/plugin/RepositoryPluginHandler.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/AbstractProxy.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/AuthorizationCodeRepositoryProxy.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/CertificateRepositoryProxy.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/ClientRepositoryProxy.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/DomainRepositoryProxy.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/IdentityProviderRepositoryProxy.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/RoleRepositoryProxy.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/TokenRepositoryProxy.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/resources/META-INF/spring.factories
gravitee-am-gateway/gravitee-am-gateway-service/pom.xml
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-repository/gravitee-am-repository-mongodb/pom.xml
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/assembly/plugin-assembly.xml
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/OAuth2RepositoryConfiguration.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/plugin.properties

feat(plugin): create repository plugin

---

docker/compose/config/constants.json
docker/compose/docker-compose.yml
docker/gateway/Dockerfile
docker/nginx/Dockerfile
docker/nginx/nginx.conf
docker/webui/Dockerfile
docker/webui/nginx.conf

Closes gravitee-io/graviteeio-access-management#124

technical(docker): Provide docker images and docker-compose

---

gravitee-am-ui/src/app/domains/domain/certificates/creation/steps/step2/step2.component.ts
gravitee-am-ui/src/app/domains/domain/domain.component.html

fix(ui) : fix certificate creation

---

gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/ClientServiceImpl.java

feat(topClient): do not list top client without access tokens

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/userdetails/CustomUserDetailsService.java

fix(oauth2): set default user for refresh token grant type

---

pom.xml

Closes gravitee-io/graviteeio-access-management#173

chore: Upgrade spring security oauth2 dependencies

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/AuthorizationServerConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/token/CustomTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/ExtensionGrantServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/model/NewExtensionGrant.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/model/UpdateExtensionGrant.java
gravitee-am-model/src/main/java/io/gravitee/am/model/ExtensionGrant.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoExtensionGrantRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ExtensionGrantMongo.java
gravitee-am-ui/package.json
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/steps/step2/step2.component.html
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/steps/step2/step2.component.ts
gravitee-am-ui/src/app/domain/settings/extension-grants/extension-grant/extension-grant.component.html
gravitee-am-ui/src/app/domain/settings/extension-grants/extension-grant/extension-grant.component.ts
gravitee-am-ui/src/app/services/extension-grant.service.ts

feat(extensionGrants): allow to store user information for extension grants

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/security/web/XForwardedAwareRedirectStrategy.java
gravitee-am-ui/package.json

Handle encoded redirect_uri query parameter

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/assembly/plugin-assembly.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProviderMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProviderRoleMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/spring/MongoAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/plugin.properties
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json

Closes gravitee-io/graviteeio-access-management#193

feat(mongodb): Add MongoDB identity-provider

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/jwt/CustomJwtAccessTokenConverter.java

fix(openid): correctly map user attributes with ID token custom claims

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/jwt/CustomJwtAccessTokenConverter.java

fix(oauth2): filter requested enhance scopes

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2SecurityConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/authentication/CustomSavedRequestAwareAuthenticationSuccessHandler.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/controller/LoginController.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/filter/OAuth2ClientAuthenticationFilter.java

fix(oauth2): save redirect page after login process

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/AuthorizationServerConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/CustomAuthorizationServerEndpointsConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/endpoint/RevokeTokenEndpoint.java

fix(oauth2): restore RevokeTokenEndpoint

---

gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.html
gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.scss
gravitee-am-ui/src/app/domain/settings/certificates/creation/certificate-creation.component.ts
gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step1/step1.component.html
gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step1/step1.component.scss
gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step1/step1.component.ts
gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step2/step2.component.html
gravitee-am-ui/src/app/domain/settings/certificates/creation/steps/step2/step2.component.scss
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/extension-grant-creation.component.html
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/extension-grant-creation.component.scss
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/extension-grant-creation.component.ts
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/steps/step1/step1.component.html
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/steps/step1/step1.component.scss
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/steps/step1/step1.component.ts
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/steps/step2/step2.component.html
gravitee-am-ui/src/app/domain/settings/extension-grants/creation/steps/step2/step2.component.scss
gravitee-am-ui/src/app/domain/settings/providers/creation/provider-creation.component.html
gravitee-am-ui/src/app/domain/settings/providers/creation/provider-creation.component.scss
gravitee-am-ui/src/app/domain/settings/providers/creation/provider-creation.component.ts
gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.html
gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.scss
gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.ts
gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.html
gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.scss
gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.ts

feat(ui): add stepper for providers/certificates/extension grants creation provider

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/AuthorizationServerConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/jwt/CustomTokenEnhancer.java

feat(oauth2): remove jwt format for access and refresh tokens

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/controller/LoginController.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/filter/OAuth2ClientAuthenticationFilter.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/assembly/plugin-assembly.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderRoleMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/plugin.properties
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/pom.xml

feat(idp): add oauth2 generic server support

---

gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/upgrades/InitializeUpgrader.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/upgrades/ScopeUpgrader.java

feat(oauth2): update InitializeUpgrader to be consistent with new scopes management system

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/jwt/CustomTokenEnhancer.java

fix(oauth2): add filtered enhance scopes to the access token

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/client/DelegateClientDetails.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/security/ClientBasedAuthenticationProvider.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/test/java/io/gravitee/am/gateway/handler/oauth2/provider/security/ClientBasedAuthenticationProviderTest.java

fix(oauth2): chain identity providers during user authentication

---

gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2SecurityConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handlers/gravitee-am-gateway-handlers-oauth2/src/main/java/io/gravitee/am/gateway/handler/oauth2/provider/security/web/authentication/ClientAwareAuthenticationFailureHandler.java

fix(oauth2): use x-forwarded redirect strategy for authentication failure handler

---

gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/upgrades/InitializeUpgrader.java

See issue https://github.com/gravitee-io/issues/issues/1281

Add the "client_credentials" grant type to the default admin client

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java

fix(ldap): handle array attributes while mapping user claims

---

gravitee-am-gateway/gravitee-am-gateway-jetty/src/main/java/io/gravitee/am/gateway/jetty/JettyConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-jetty/src/main/java/io/gravitee/am/gateway/jetty/JettyServerFactory.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/graviteeio-access-management#247

feat(http): Add HTTPS support

---

gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/proxy/TokenRepositoryProxy.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/ClientServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/TokenServiceImpl.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/api/TokenRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/token/MongoTokenRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/token/internal/token/OAuth2AccessTokenMongoRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/oauth2/token/MongoTokenRepositoryTest.java
gravitee-am-ui/package-lock.json

fix(dashboard): do not fetch all access and refresh token information for "count" analytics

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java

fix(oauth2): custom ldap attributes not map for refresh token flow

---

gravitee-am-ui/build.json
gravitee-am-ui/package-lock.json
gravitee-am-ui/package.json
pom.xml

This closes gravitee-io/issues#1384

chore: Upgrade Spring security dependencies

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/TokenRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AbstractAuthorizationEndpointHandler.java

fix(oidc): add subject claim when coming from a implicit token flow

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AbstractAuthorizationEndpointHandler.java

fix(oauth2): set additional parameters to the implicit redirect uri response

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/OAuth2ClientAuthHandlerImpl.java

fix(oauth2): handle proxy requests for social redirect callback

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/FormLoginHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/OAuth2ClientAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/RedirectAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/login/endpoint/LoginEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/utils/UriBuilderRequest.java

AM gateway will look for X-Forwarded-Path header to resolve the proxy context-path
fixes #273

fix(oauth2): handle proxy context-path for redirect_uri param

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/token/TokenEnhancerTest.java

fix(oauth2): unable enhance scopes option

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/utils/UriBuilder.java

fix(uri-builder): fix NPE for null request's port value

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/login/LoginRouter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/OAuth2Router.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/OIDCRouter.java

chore(oidc): mount OpenID Connect endpoints to base path /oidc

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/OAuth2ClientAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/provider/OAuth2ClientAuthenticationProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/login/LoginRouter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/provider/OAuth2ClientAuthenticationProviderTest.java

fix(oidc): save/update user after a successful oauth2 provider authentication

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json

feat(ldap): add connect and response timeout options

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java

feat(ldap): add logs on connection/authentication error

---

gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/CertificateMetadata.java
gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/provider/JavaKeyStoreProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/certificate/impl/CertificateManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/certificate/CertificateManager.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/CertificateUpgrader.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/CertificateUpgraderTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Certificate.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/main/java/io/gravitee/am/plugins/certificate/core/impl/CertificateMetadataBeanFactoryPostProcessor.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/main/java/io/gravitee/am/plugins/certificate/core/impl/CertificatePluginManagerImpl.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCertificateRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/CertificateMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/CertificateService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java

fix(certificate): move certificate binary files to the repository

---

gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.html

fix(certificate): allow to remove client's certificate

---

gravitee-am-certificate/gravitee-am-certificate-api/pom.xml
gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/CertificateProvider.java
gravitee-am-certificate/gravitee-am-certificate-javakeystore/pom.xml
gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/provider/JavaKeyStoreProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/certificate/impl/CertificateManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/jwk/JWK.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/jwk/JWKSet.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/jwk/JWKSetService.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/jwk/RSAKey.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/jwk/impl/JWKSetServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/spring/OpenIDConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/OIDCRouter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/endpoint/ProviderJWKSetEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/token/TokenEnhancerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oidc/jwk/JWKSetServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/ProviderJWKSetEndpointHandlerTest.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/CertificateResource.java
gravitee-am-model/src/main/java/io/gravitee/am/model/jose/JWK.java
gravitee-am-model/src/main/java/io/gravitee/am/model/jose/RSAKey.java

feat(oidc): add JWK Set endpoint

---

gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/provider/JavaKeyStoreProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java

fix(oidc): add kid (Key ID) Header parameter to the signed ID Token

---

gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/provider/JavaKeyStoreProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/code/impl/AuthorizationCodeServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/code/AuthorizationCodeTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/model/AuthorizationCode.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAuthorizationCodeRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/internal/model/AuthorizationCodeMongo.java

feat(oidc): handle nonce ID token claim

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/OIDCRouter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/handler/UserInfoRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/UserInfoEndpointHandlerTest.java

feat(oidc): UserInfo Endpoint access with POST and bearer body

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/AuthenticationErrorException.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/InteractionRequiredException.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/LoginRequiredException.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/utils/OIDCParameters.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/OAuth2Router.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java

feat(oidc): handle prompt=none parameter when user is not logged in

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/utils/OIDCParameters.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/model/AccessToken.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/model/AccessTokenCriteria.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAccessTokenRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/internal/model/AccessTokenMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/oauth2/MongoAccessTokenRepositoryTest.java

fix(oidc): handle nonce parameter for existing tokens.

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/code/AuthorizationCodeTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/pkce/PKCEUtils.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/utils/OAuth2Constants.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java

Closes gravitee-io/graviteeio-access-management#224

feat(oauth2): Add PKCE support

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/utils/OIDCParameters.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/FormLoginHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java

feat(oidc): handle max_age parameter

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/CodeChallengeMethod.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/GrantType.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/ResponseType.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/ClaimType.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/ClientAuthenticationMethod.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/ResponseType.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/Scope.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/discovery/OpenIDProviderMetadata.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/discovery/impl/OpenIDDiscoveryServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/endpoint/ProviderConfigurationEndpoint.java

feat(oidc): provide OpenID provider metadata

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/code/impl/AuthorizationCodeServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/code/AuthorizationCodeServiceTest.java
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/proxy/AccessTokenRepositoryProxy.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/api/AccessTokenRepository.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/model/AccessToken.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAccessTokenRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/internal/model/AccessTokenMongo.java

feat(oidc): Trying to use authorization code twice should result in an error

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/auth/impl/UserAuthenticationManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/AbstractTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/CompositeTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/TokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/client/ClientCredentialsTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/code/AuthorizationCodeTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/extensiongrant/ExtensionGrantGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/implicit/ImplicitTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/password/ResourceOwnerPasswordCredentialsTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/refresh/RefreshTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/AbstractRequestResolver.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/AuthorizationRequestResolver.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/TokenRequestResolver.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/TokenEnhancer.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/TokenService.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/token/TokenEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/granter/refresh/RefreshTokenGranterTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/request/AuthorizationRequestResolverTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/request/TokenRequestResolverTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/token/TokenEnhancerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/token/TokenServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-service/src/main/java/io/gravitee/am/gateway/service/impl/UserServiceImpl.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/model/RefreshToken.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoRefreshTokenRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/internal/model/RefreshTokenMongo.java

feat(oauth2): handle user permissions for requested scopes

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/AbstractRequestResolver.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/jackson/AccessTokenSerializer.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/request/AuthorizationRequestResolverTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/request/TokenRequestResolverTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java

fix(oauth2): handle unknown requested scopes

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/OAuth2Router.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/token/TokenEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/token/TokenRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/request/TokenRequestFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/TokenEndpointHandlerTest.java

fix(oauth2): handle empty scope parameter

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/InvalidClientException.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/AbstractTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/client/ClientCredentialsTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/implicit/ImplicitTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/token/TokenEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/TokenEndpointHandlerTest.java

fix(oauth2): do not provide refresh token if refresh token grant is not enabled for the client

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/InvalidClientException.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/OAuth2Exception.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/ClientBasicAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/token/TokenEndpointHandler.java

fix(oauth2): set proper OAuth 2.0 error response for invalid client authentication method

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java

fix(domain): delete domain's scopes during domain deleting process

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/ErrorHandlerEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/resources/webroot/assets/css/access_error.css
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/resources/webroot/views/access_error.html

fix(oauth2): handling authorization endpoint errors with the default error page

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/flow/AbstractFlow.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/flow/CompositeFlow.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/flow/Flow.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/flow/authorizationcode/AuthorizationCodeFlow.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/flow/hybrid/HybridFlow.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/flow/implicit/ImplicitFlow.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/OAuth2Router.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/ErrorHandlerEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationClientHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java

fix(oauth2): handle unknown client for authorization flow

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/AuthorizationRequestResolver.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationClientHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/request/AuthorizationRequestResolverTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java

fix(oauth2): invalid or missing redirect_uri

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/token/TokenRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/TokenEndpointHandlerTest.java

fix(oauth2): handle duplicate parameters

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/AbstractTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/flow/implicit/ImplicitFlow.java

Closes gravitee-io/graviteeio-access-management#374

fix(oidc): sub claim must be set with the end-user username / id

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/Scope.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/ScopeResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ScopesResourceTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/OpenIDScopeUpgrader.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oauth2/Scope.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoScopeRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/management/MongoScopeRepositoryTest.java
gravitee-am-service/pom.xml
gravitee-am-service/src/main/java/io/gravitee/am/service/ScopeService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/SystemScopeDeleteException.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ScopeServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewSystemScope.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateSystemScope.java
gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ScopeServiceTest.java
gravitee-am-ui/src/app/domain/settings/scopes/scopes.component.html
gravitee-am-ui/src/app/domain/settings/scopes/scopes.component.scss

feat(oidc): add default scopes while creating domains

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/handler/UserInfoRequestParseHandler.java

fix(oidc): display error message for invalid access token

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/Scope.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/idtoken/impl/IDTokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oidc/idtoken/IDTokenServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/UserInfoEndpointHandlerTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java

feat(oidc): requesting claims using scope values

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/revocation/impl/RevocationTokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/ClientChainAuthHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/ClientCredentialsAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/OAuth2Router.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/revocation/RevocationTokenEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/RevocationTokenEndpointHandlerTest.java

fix(oauth2): handle errors for revocation endpoint

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/idtoken/IDToken.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/idtoken/impl/IDTokenServiceImpl.java

fix(oidc) set ID Token 'sub' claim with the user technical identifier

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/idtoken/impl/IDTokenServiceImpl.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/InlineIdentityProviderMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/model/User.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/resources/schemas/schema-form.json

feat(idp): enable user mapper and add email field for inline provider

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/request/OAuth2Request.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenEnhancerImpl.java

fix(oidc): at_hash ID token claim is required for Implicit and Hybrid flow

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java

fix(oidc): use fragment error redirection for Implicit flow

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/resources/webroot/assets/css/access_error.css

fix(oidc): mismatch redirect uri should end up with default error page

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/OAuth2Router.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseClientHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseParametersHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationRequestParseRequiredParametersHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java

fix(oidc): we should redirect to registered client redirect uri in case of oauth2/oidc failure

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/FormLoginHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/OAuth2ClientAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/RedirectAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/login/endpoint/LoginEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/endpoint/ProviderConfigurationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/utils/UriBuilderRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/endpoint/AuthorizationEndpointHandlerTest.java

fix(oidc): 302 redirection should be done with absolute url

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/InitializeUpgrader.java
gravitee-am-ui/package-lock.json

fix(oidc): InitializeUpgrader must end before the other upgraders

---

docs/oauth2-api-descriptor.yml
docs/oidc-api-descriptor.yml

doc: add OAuth 2.0 and OpenID Connect API descriptors

---

gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java

fix(gateway): Gateway should not load master domains

---

gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/NoIdentityProviderMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/NoIdentityProviderRoleMapper.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-identityprovider/src/main/java/io/gravitee/am/plugins/idp/core/impl/IdentityProviderPluginManagerImpl.java

fix(plugins): load identity provider plugins if userMapper or/and roleMapper are null

---

docker/compose/config/nginx.conf
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/FormLoginHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/OAuth2ClientAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/RedirectAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/login/endpoint/LoginEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/endpoint/ProviderConfigurationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/utils/UriBuilderRequest.java

feat(gateway): rely on X-Forwarded-Path to handle 302 redirection

---

docker/compose/config/nginx.conf
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/cookie/CookieHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/utils/UriBuilderRequest.java

fix(gateway): rely on X-Forwarded-Prefix to set session cookie path

---

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java

fix(idp): handle idp mongo complex user claims

---

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/MongoFactory.java

Closes gravitee-io/graviteeio-access-management#443

feat(mongodb): Add TLS support

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json

fix(idp): Use a password field for the LDAP password property

---

gravitee-am-gateway/gravitee-am-gateway-repository/pom.xml
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/healthcheck/ManagementRepositoryProbe.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/java/io/gravitee/am/gateway/repository/healthcheck/OAuth2RepositoryProbe.java
gravitee-am-gateway/gravitee-am-gateway-repository/src/main/resources/META-INF/spring.factories
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/healthcheck/HttpServerProbe.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/resources/META-INF/spring.factories
gravitee-am-management-api/gravitee-am-management-api-repository/pom.xml
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/healthcheck/ManagementRepositoryProbe.java
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/healthcheck/OAuth2RepositoryProbe.java
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/resources/META-INF/spring.factories
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/healthcheck/ManagementApiProbe.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/vertx/VertxCompletableFuture.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/resources/META-INF/spring.factories

chore(): add health check probes for the Management API and the Gateway

---

gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/main/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JwtBearerExtensionGrantProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/SecurityDomainRouterFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/certificate/CertificateManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/certificate/impl/CertificateManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/client/ClientService.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/client/impl/ClientServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/event/EventManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java

feat(oauth2): able cross domains tokens introspection

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/StandardClaims.java
gravitee-am-gateway/gravitee-am-gateway-handler/pom.xml
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/handler/impl/OAuth2ClientAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/spring/GithubAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java

fix(oauth2): loadUserByUsername() must not return null value for social provider

---

gravitee-am-management-api/gravitee-am-management-api-services/gravitee-am-management-api-services-sync/src/main/java/io/gravitee/am/management/services/sync/SyncManager.java

fix(managment): sync manager must not handle null domain to avoid NPE

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AbstractAuthorizationEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oauth2/endpoint/authorization/AuthorizationEndpointHandler.java
postman/graviteeam-collection

Fixing issue #472 
Regards,
Alexandre.

fix(oauth2): authorization request is not retrieved from session

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/token/impl/TokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oauth2/token/TokenServiceTest.java
postman/graviteeam-collection

fix(oauth2): use client_id as jwt client claim value

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/OIDCRouter.java

Add CorsHandler for /oidc/.well-known/openid-configuration and /oidc/.well-known/jwks.json

Fix - Add Cors handler for endpoints openid-configuration and jwks.json

---

gravitee-am-management-api/gravitee-am-management-api-jetty/src/main/java/io/gravitee/am/management/jetty/handler/security/SecurityDomainHandlerCollection.java

fix(management): sometimes the admin context is not well deployed

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/handler/CookieClearingLogoutHandler.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/provider/jwt/JWTGenerator.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/filter/JWTAuthenticationFilter.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

fix(management): change management auth cookie name to avoid collision

---

docs/oidc-api-descriptor.yml

Adding swagger specifications : issue #508

add dcr swagger specs

---

gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/main/java/io/gravitee/am/extensiongrant/jwtbearer/JwtBearerExtensionGrantConfiguration.java
gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/main/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JwtBearerExtensionGrantProvider.java
gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/main/resources/schemas/schema-form.json
gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/test/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JwtBearerExtensionGrantProviderTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oauth2/granter/extensiongrant/ExtensionGrantGranter.java
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/proxy/ClientRepositoryProxy.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/ClientRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoClientRepository.java
gravitee-am-service/src/main/java/io/gravitee/am/service/ClientService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ExtensionGrantServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ClientServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ExtensionGrantServiceTest.java
postman/graviteeam-collection.json

feat(extension-grant): add user mapping claims for the JWT Bearer extension grant

---

docs/oauth2-api-descriptor.yml
docs/oidc-api-descriptor.yml
docs/scim-api-descriptor.yml

Closes gravitee-io/gravitee-docs#131

doc: create SCIM 2.0 API descriptor

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/discovery/impl/OpenIDDiscoveryServiceImpl.java

Closes gravitee-io/issues#1928

feat(oidc): add subject_types_supported 'public' value

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TokenServiceImpl.java

fix(dashboard): use client_id instead of technical id to fetch dashboard tokens analytics

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/CompareAuthenticationHandler.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/Base64Encoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/BinaryToTextEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/HexEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/MD5PasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/MessageDigestPasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/NoneEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/PasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/SHAMD5PasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/encoding/SHAPasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapBindAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapComparePasswordAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapComparePasswordShaMd5AuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/resources/test-server.ldif

closes gravitee-io/issues#1912

feat(ldap): add compare authentication handler

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/root/RootRouter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/root/endpoint/user/PasswordPolicyRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/root/endpoint/user/UserTokenRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/root/endpoint/user/password/ResetPasswordEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/root/endpoint/user/register/RegisterSubmissionEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/scim/SCIMRouter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/scim/endpoint/users/CreateUserEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/scim/endpoint/users/UpdateUserEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/resources/webroot/views/registration.html
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/resources/webroot/views/reset_password.html
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/handler/scim/endpoint/users/CreateUserEndpointHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/handler/scim/endpoint/users/PasswordPolicyRequestParseHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/handler/scim/endpoint/users/UpdateUserEndpointHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/UserResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/UsersResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/test/java/io/gravitee/am/management/handlers/management/api/JerseySpringTest.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UserResourceTest.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/PasswordValidator.java
gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/RegexPasswordValidator.java
gravitee-am-service/src/main/java/io/gravitee/am/service/spring/ServiceConfiguration.java
gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/PasswordValidatorTest.java
gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html

closes gravitee-io/issues#1921

feat(password): create password complexity policy v1 (regex pattern)

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/ClientResource.java
gravitee-am-service/src/main/java/io/gravitee/am/service/ClientService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchClient.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ClientServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/model/PatchClientTest.java
gravitee-am-ui/src/app/services/client.service.ts

fix(client): allow to unset client certificate

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/email/impl/EmailServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java

fix(email): do not load local image resources if src tag is an absolute http url

---

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/pom.xml
gravitee-am-repository/gravitee-am-repository-mongodb/pom.xml
pom.xml

chore(): update mongodb java driver to fix SSL/TLS connexion issue

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/scim/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/scim/model/User.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/scim/UserServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/handler/scim/endpoint/users/CreateUserEndpointHandlerTest.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/IdentityProvidersResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/IdentityProviderManager.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.html
gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.ts
gravitee-am-ui/src/app/services/provider.service.ts

closes gravitee-io/issues#2018

feat(users): allow to select an idp for user creation

---

gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

feat(prometheus): add default configuration

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/ClientResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ClientResourceTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/ClientService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ClientServiceTest.java
gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.html
gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.scss
gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.ts
gravitee-am-ui/src/app/services/client.service.ts
postman/graviteeam-collection.json

closes gravitee-io/issues#2063

feat(client): renew OAuth 2.0 client secret

---

.gitignore
docs/oidc-api-descriptor.yml
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/request/DynamicClientRegistrationRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/OIDCRouter.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/endpoint/DynamicClientAccessEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oidc/request/DynamicClientRegistrationRequestTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/vertx/handler/oidc/endpoint/DynamicClientAccessEndpointTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Client.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/JWKSet.java
gravitee-am-model/src/test/java/io/gravitee/am/model/ClientTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/utils/SetterUtils.java
gravitee-am-service/src/test/java/io/gravitee/am/service/utils/SetterUtilsTest.java
postman/graviteeam-collection.json

Linked to issue https://github.com/gravitee-io/issues/issues/2134
I have included new OpenId Connect Discovery NRT on postman.

Implement put dcr endpoint

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/oidc/discovery/impl/OpenIDDiscoveryServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/src/test/java/io/gravitee/am/gateway/handler/oidc/clientregistration/DynamicClientRegistrationServiceTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/utils/GrantTypeUtils.java
gravitee-am-service/src/main/java/io/gravitee/am/service/utils/SubjectTypeUtils.java
gravitee-am-service/src/test/java/io/gravitee/am/service/utils/SubjectTypeUtilsTest.java
postman/graviteeam-collection.json

This is related to issue https://github.com/gravitee-io/issues/issues/2135

Check unsupported subject type on oidc dcr feature

---

gravitee-am-gateway/gravitee-am-gateway-handler/src/main/java/io/gravitee/am/gateway/handler/certificate/impl/CertificateManagerImpl.java

fix(oidc): JWKS endpoint should not display all domains keys

---

gravitee-am-service/src/main/java/io/gravitee/am/service/utils/GrantTypeUtils.java
gravitee-am-service/src/main/java/io/gravitee/am/service/utils/ResponseTypeUtils.java
gravitee-am-service/src/test/java/io/gravitee/am/service/utils/ResponseTypeUtilsTest.java
postman/graviteeam-collection.json

Hello,
This close issue [#2178](https://github.com/gravitee-io/issues/issues/2178)
Regards,
Alexandre.

fix: missing response_types in DCR feature

---

gravitee-am-ui/src/app/domain/components/clients/select-clients.component.ts

Closes gravitee-io/issues#2183

fix(user): Get the domain ID from a higher level in component

---

postman/graviteeam-collection.json

Fix issue 2197 (two postman nrt failing due to bad url)

fix postman scim nrt

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/OIDCProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/handler/DynamicClientRegistrationHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/handler/DynamicClientRegistrationHandlerTest.java
postman/graviteeam-collection.json

Dear,
This PR solve the issue #2198.
Regards,
Alexandre.

fix open dynamic client registration bug

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/jwe/JWEEllipticCurveTest.java

Remove non java11 compliant packages

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/SCIMProvider.java

closes gravitee-io/issues#2262

feat(scim): add CORS support

---

docker/compose/docker-compose.yml
docker/gateway/Dockerfile-dev
docker/management-api/Dockerfile-dev
docker/management-ui/Dockerfile
docker/management-ui/Dockerfile-nightly

closes gravitee-io/issues#2277

docker: update alpine image version

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/client/ClientRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpointHandlerTest.java

fix(forms): use client custom forms after reset password and confirm registration redirection

---

Makefile
docker/gateway/Dockerfile-dev
docker/management-api/Dockerfile-dev

Hello,
This close issue [#2307](https://github.com/gravitee-io/issues/issues/2307) and add some small improvements on the Makefile.
Regards,
Alexandre.

Correct Dockerfile-dev

---

postman/collections/graviteeio-am-openid-dcr-collection.json

This fix issue [#2325](https://github.com/gravitee-io/issues/issues/2325)

fix dcr postman collection

---

Makefile
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/OIDCProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/DynamicClientAccessEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/DynamicClientAccessEndpointTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/ClientService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ClientServiceTest.java
postman/collections/graviteeio-am-openid-dcr-collection.json

In order to run NRT, you must merge this [PR](https://github.com/gravitee-io/graviteeio-access-management/pull/592) before.
This fix issue [#2323](https://github.com/gravitee-io/issues/issues/2323)

Renew client_secret through dcr

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java

fix(user): check client before create or update a user

---

gravitee-am-repository/gravitee-am-repository-mongodb/pom.xml
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoClientRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/management/MongoClientRepositoryTest.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/management/MongoUserRepositoryTest.java
gravitee-am-ui/src/app/domain/components/clients/select-clients.component.ts
gravitee-am-ui/src/app/domain/settings/groups/group/members/members.component.ts

fix(search): we should be able to search for a specific client or user

---

gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json
gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts

fix(oidc-idp): client secret should be optional if OIDC Implicit flow is used

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ScopeServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ScopeServiceTest.java
gravitee-am-ui/src/app/domain/settings/scopes/creation/scope-creation.component.html
gravitee-am-ui/src/app/domain/settings/scopes/creation/scope-creation.component.scss
gravitee-am-ui/src/app/domain/settings/scopes/creation/scope-creation.component.ts
gravitee-am-ui/src/app/domain/settings/scopes/scope/scope.component.html
gravitee-am-ui/src/app/domain/settings/scopes/scope/scope.component.scss
gravitee-am-ui/src/app/domain/settings/scopes/scope/scope.component.ts

fix(scopes): OAuth 2.0 scopes should be case sensitive

---

gravitee-am-common/src/main/java/io/gravitee/am/common/policy/ExtensionPoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/ErrorHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/ExceptionHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/ErrorHandler.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
gravitee-am-ui/src/app/domain/settings/policies/dialog/policies-info.component.html
gravitee-am-ui/src/app/domain/settings/policies/policies.component.html
gravitee-am-ui/src/app/domain/settings/policies/policies.component.scss
gravitee-am-ui/src/app/domain/settings/policies/policies.component.ts
gravitee-am-ui/src/app/domain/settings/policies/policy/form/form.component.scss

closes gravitee-io/issues#2356

feat(policies): manage policies at root level

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java

fix(dashboard): use client_id instead of technical id to fetch dashboard top clients analytics

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/UserService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
gravitee-am-model/src/main/java/io/gravitee/am/model/account/AccountSettings.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoClientRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/AccountSettingsMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/authentication/AccountDisabledException.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/authentication/AccountInactiveException.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/authentication/AccountStatusException.java
gravitee-am-ui/src/app/domain/clients/client/account/account.component.html
gravitee-am-ui/src/app/domain/clients/client/account/account.component.scss
gravitee-am-ui/src/app/domain/clients/client/account/account.component.ts
gravitee-am-ui/src/app/domain/components/account/account-settings.component.html
gravitee-am-ui/src/app/domain/components/account/account-settings.component.scss
gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts
gravitee-am-ui/src/app/domain/settings/account/account.component.html
gravitee-am-ui/src/app/domain/settings/account/account.component.ts

closes gravitee-io/issues#2345

feat(registration): add an option to complete account when user renewed his password

---

pom.xml

Closes gravitee-io/issues#2411

fix(http): Upgrade jetty dependency

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
gravitee-am-ui/build.json
gravitee-am-ui/package.json

fix(authenticate): Allow groups without members during authentication

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/utils/LdapUtils.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapBindAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapComparePasswordAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapComparePasswordShaMd5AuthenticationProviderTest.java
gravitee-am-ui/package-lock.json

fix(idp-ldap): allow complex search filters

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/gravitee-am-gateway-standalone-distribution-zip/pom.xml
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/logback.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/gravitee-am-management-api-standalone-distribution-zip/pom.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/logback.xml

fix(logback): update log dir path

---

docker/compose/docker-compose-dev.yml
docker/compose/docker-compose.yml
docker/gateway/Dockerfile
docker/gateway/Dockerfile-dev
docker/gateway/Dockerfile-nightly
docker/management-api/Dockerfile
docker/management-api/Dockerfile-dev
docker/management-api/Dockerfile-nightly
docker/management-ui/Dockerfile
docker/management-ui/config/conf.d/constants.json.toml
docker/management-ui/config/conf.d/default.conf.toml
docker/management-ui/config/templates/constants.json.tmpl
docker/management-ui/config/templates/default.conf.tmpl
docker/management-ui/run.sh

Closes gravitee-io/issues#2438

feat(docker): Remove gravitee user and move to confd to configure UI

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/UserService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTest.java
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/proxy/UserRepositoryProxy.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
gravitee-am-service/src/main/java/io/gravitee/am/service/UserService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
postman/collections/graviteeio-am-login-collection.json
postman/collections/graviteeio-am-user-management-collection.json

closes gravitee-io/issues#2445

feat(users): handle case-sensitivity for usernames and emails

---

gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/DefaultReactor.java
gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/transaction/TransactionHandler.java
gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/transaction/TransactionProcessorFactory.java
gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/spring/ReactorConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-ui/src/app/domain/components/scope-selection/scope-selection.component.ts
gravitee-am-ui/src/app/domain/settings/openid/client-registration/default-scope/default-scope.component.spec.ts
gravitee-am-ui/src/app/domain/settings/openid/client-registration/settings/settings.component.spec.ts

Closes gravitee-io/issues#2450

feat(gateway): Add a transaction-id as part of the gateway response.

---

gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.scss
gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.scss

fix(ui): Multi-line input hint overlaps with elements below for LDAP IdP HTML Form

---

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoClientRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java

fix(clients): search clients with wildcard was not working properly

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseClientHandler.java

Closes gravitee-io/issues#2470

fix(oauth): Typo

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java

closes gravitee-io/issues#2482

fix(extension-grant): fix username claim after case-sensitivity feature

---

gravitee-am-management-api/gravitee-am-management-api-core/pom.xml
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/SecurityConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/authentication/CustomSavedRequestAwareAuthenticationSuccessHandler.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/filter/CheckAuthenticationCookieFilter.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/filter/SocialAuthenticationFilter.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/service/AuthenticationService.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/service/impl/AuthenticationServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/spring/AdminConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/test/java/io/gravitee/am/management/handlers/admin/service/AuthenticationServiceTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/UserService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java

fix(idp): social identity providers not working for the management part

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/authentication/listener/AuthenticationEventListener.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/SecurityDomainRouterFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java

fix(audits): authentication events duplicated

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/event/EventManagerImpl.java

fix(eventManager): domains handle events for other domains

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/event/EventManagerImpl.java

fix(events): All events content must be evaluated to get their domain id

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/provider/ClientProperties.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Client.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoClientRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ClientMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchClient.java
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/clients/client/oauth2/oauth2.component.scss
gravitee-am-ui/src/app/domain/clients/client/settings/metadata/client-metadata.component.html
gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.html
gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.scss
gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.ts
gravitee-am-ui/src/app/domain/settings/users/users.component.scss
gravitee-am-ui/src/app/services/client.service.ts
postman/collections/graviteeio-am-oauth2-collection.json

closes gravitee-io/issues#2342

feat(clients): add client metadata information

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java
gravitee-am-ui/src/app/domain/clients/client/idp/idp.component.ts

Closes gravitee-io/issues#2568

fix(identity): Manage identity providers for a new client

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/handler/impl/FormLoginHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginErrorHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/forgot_password.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html
gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html
postman/collections/graviteeio-am-login-collection.json

closes gravitee-io/issues#2614

chore(): remove technical error messages to avoid potential security leaks

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java

fix(users): handle empty user external id values

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/approval/UserApprovalRequestParseHandler.java

fix(oidc): ID Token must be propagate if Implicit Flow is used

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java

Closes gravitee-io/issues#2679

fix(oauth2): Add handlers for preflight requests (CORS)

---

gravitee-am-ui/src/app/domain/clients/client/settings/settings.component.ts

fix(ui): client metadata key and value was inverted

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/CustomClaims.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/Scope.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/OIDCProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpointHandlerTest.java
gravitee-am-ui/src/app/domain/settings/groups/group/members/members.component.ts

closes gravitee-io/issues#2544

feat(oidc): add roles and groups to the UserInfo Endpoint

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/AuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/CompareAuthenticationHandler.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/GroupSearchEntryHandler.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/test/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProviderTest.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-admin/src/main/java/io/gravitee/am/management/handlers/admin/security/impl/IdentityProviderManagerImpl.java

closes gravitee-io/issues#2691

feat(ldap): manage pooled connexions for LDAP Identity Provider

---

gravitee-am-service/src/main/java/io/gravitee/am/service/UserService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/LoginAttemptServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/LoginAttemptServiceTest.java
gravitee-am-ui/src/app/domain/clients/client/account/account.component.ts
gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts

fix(users): unlock user who has never been authenticated

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/GroupMemberResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/GroupMembersResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/GroupResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/test/java/io/gravitee/am/management/handlers/management/api/resources/GroupMemberResourceTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/MemberAlreadyExistsException.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/MemberNotFoundException.java

Closes gravitee-io/issues#1923

feat(groups): group member management (Rest API)

---

gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/test/java/io/gravitee/am/identityprovider/github/authentication/DummyAuthenticationContext.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/test/java/io/gravitee/am/identityprovider/github/authentication/DummyRequest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/test/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/test/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProviderTest.java

fix(oidc): fix social authentication via OIDC protocol

---

gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/Claims.java
gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/JWT.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/EvaluableRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/approval/impl/ApprovalServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/code/impl/AuthorizationCodeServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/code/AuthorizationCodeTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/refresh/RefreshTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/BaseRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/OAuth2Request.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/TokenRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oauth2/ScopeApproval.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/model/AuthorizationCode.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAuthorizationCodeRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoScopeApprovalRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/internal/model/AuthorizationCodeMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/internal/model/ScopeApprovalMongo.java
gravitee-am-ui/src/app/domain/clients/client/oauth2/dialog/claims-info.component.html
gravitee-am-ui/src/app/domain/clients/client/oauth2/oauth2.component.html
gravitee-am-ui/src/app/domain/clients/client/oauth2/oauth2.component.ts
postman/collections/graviteeio-am-oauth2-collection.json

closes gravitee-io/issues#2715

feat(customClaims): propagate the custom claims to the refresh token

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/impl/UserAuthenticationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/provider/UserProperties.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java
postman/collections/graviteeio-am-openid-core-collection.json

fix(oidc): auth_time should be a long value all the way

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/auth/handler/impl/OAuth2AuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/OIDCProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpointHandlerTest.java
postman/collections/graviteeio-am-openid-core-collection.json

fix(oidc): handle UserInfo POST method with bearer in body

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ClientServiceTest.java
postman/collections/graviteeio-am-openid-dcr-collection.json

fix(oidc): reject registration where a redirect_uri has a fragment

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java
pom.xml

Closes gravitee-io/issues#2878

feat(node): Use node factory instead of node implementation

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseClientHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Domain.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/OIDCSettings.java
gravitee-am-model/src/test/java/io/gravitee/am/model/DomainTest.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/oidc/OIDCSettingsMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/openid/PatchOIDCSettings.java
gravitee-am-ui/src/app/domain/settings/openid/client-registration/settings/settings.component.html
gravitee-am-ui/src/app/domain/settings/openid/client-registration/settings/settings.component.ts
postman/collections/graviteeio-am-oauth2-collection.json

fix(oidc): apply redirect_uri strict matching

---

Makefile
docs/oauth2-api-descriptor.yml
docs/oidc-api-descriptor.yml
docs/scim-api-descriptor.yml
docs/session-api-descriptor.yml
docs/users-api-descriptor.yml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/proxy/AccessTokenRepositoryProxy.java
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/proxy/RefreshTokenRepositoryProxy.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oauth2/api/AccessTokenRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoAccessTokenRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/MongoRefreshTokenRepository.java
gravitee-am-service/src/main/java/io/gravitee/am/service/TokenService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TokenServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/TokenServiceTest.java
postman/collections/graviteeio-am-logout-collection.json

closes gravitee-io/issues#2879

feat(logout): add an option (query param) to invalidate tokens after logout

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AbstractAuthorizationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationFailureEndpoint.java

fix(oidc): propagate initial authorization request

---

gravitee-am-gateway/gravitee-am-gateway-core/src/main/java/io/gravitee/am/gateway/core/event/Event.java
gravitee-am-gateway/gravitee-am-gateway-core/src/main/java/io/gravitee/am/gateway/core/event/UserEvent.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/web/WebConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandlerFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/SecurityDomainRouterFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationFailureEndpoint.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
postman/collections/graviteeio-am-login-collection.json

closes gravitee-io/issues#2563

feat(login): deny access for disabled users with current session

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/UserStore.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/InMemoryUserStore.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/User.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/user/InMemoryUserStoreTest.java

related to gravitee-io/issues#2563
closes gravitee-io/issues#2899

feat(login): add ttl option for user manager to check for disabled users

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandlerFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationFailureEndpoint.java
postman/collections/graviteeio-am-login-collection.json

fix(SSO): deny access if the user is not on a shared identity provider

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/VertxHttpServerRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/auth/handler/impl/RedirectAuthHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/EvaluableRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/handler/impl/FormLoginHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpoint.java
postman/collections/graviteeio-am-login-collection.json
postman/collections/graviteeio-am-logout-collection.json
postman/collections/graviteeio-am-oauth2-collection.json
postman/collections/graviteeio-am-openid-core-collection.json
postman/collections/graviteeio-am-policies-collection.json

closes gravitee-io/issues#2904

feat(login): propagate request parameters from the previous request

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxHttpServerConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxHttpServerFactory.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-jetty/src/main/java/io/gravitee/am/management/jetty/JettyConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-jetty/src/main/java/io/gravitee/am/management/jetty/JettyServerFactory.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#2978

feat(http): Add support for PKCS12 for HTTP server

---

gravitee-am-ui/src/app/domain/settings/audits/audits.component.html
gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts
gravitee-am-ui/src/app/services/audit.service.ts

closes gravitee-io/issues#2748

feat(audits): add quick time ranges for audit logs

---

gravitee-am-gateway/gravitee-am-gateway-core/src/main/java/io/gravitee/am/gateway/core/manager/ClientManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/client/ClientSyncService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/client/impl/ClientSyncServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/client/ClientSyncServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/SecurityDomainRouterFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/DefaultClientManager.java
gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/spring/ReactorConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java
gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/test/java/io/gravitee/am/gateway/services/sync/SyncManagerTest.java
postman/collections/graviteeio-am-oauth2-collection.json

fix(oauth2): cross domains introspection must look for new domains

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/manager/membership/impl/MembershipManagerImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/RoleService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/RoleServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.html
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.scss
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.ts

closes gravitee-io/issues#3022 and closes gravitee-io/issues#3023

feat(acl): assign owner to application and security domain

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/manager/membership/impl/MembershipManagerImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/RoleService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/RoleServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.html
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.scss
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.ts

Reverts gravitee-io/graviteeio-access-management#698

Revert "feat(acl): assign owner to application and security domain"

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json

closes gravitee-io/issues#3083

feat(ldap): add option to either fetch or not the user groups

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/impl/IntrospectionServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/introspection/IntrospectionServiceTest.java
postman/collections/graviteeio-am-oauth2-collection.json

fix(oauth2) : remove "aud" claim in the introspection endpoint response

---

gravitee-am-ui/src/app/domain/settings/audits/audits.component.html

closes gravitee-io/issues#3157

fix(audits): change audit logs date format to get more information

---

pom.xml

Got some issues while trying to connect to Atlas: https://jira.mongodb.org/browse/JAVARS-189
Closes gravitee-io/issues#3240

chore: Upgrade MongoDB driver

---

gravitee-am-common/src/main/java/io/gravitee/am/common/web/UriBuilder.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json

closes gravitee-io/issues#3324

feat(idp): add an option to encode redirect_uri for the OIDC provider

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/ClientsResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/dashboard/DashboardClientsResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ClientsResourceTest.java
gravitee-am-management-api/gravitee-am-management-api-repository/src/main/java/io/gravitee/am/management/repository/proxy/ClientRepositoryProxy.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/ClientRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoClientRepository.java
gravitee-am-service/src/main/java/io/gravitee/am/service/ClientService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-ui/src/app/clients/clients.component.html
gravitee-am-ui/src/app/clients/clients.component.scss
gravitee-am-ui/src/app/clients/clients.component.ts
gravitee-am-ui/src/app/components/widget/clients/clients.component.html
gravitee-am-ui/src/app/components/widget/clients/clients.component.ts
gravitee-am-ui/src/app/components/widget/top-clients/top-clients.component.html
gravitee-am-ui/src/app/domain/settings/openid/client-registration/templates/templates.component.ts
gravitee-am-ui/src/app/resolvers/clients.resolver.ts
gravitee-am-ui/src/app/services/client.service.ts
gravitee-am-ui/src/app/services/dashboard.service.ts

closes gravitee-io/issues#3309 and closes gravitee-io/issues#3310

feat(clients): add search and pagination features

---

gravitee-am-common/src/main/java/io/gravitee/am/common/exception/oauth2/InvalidTokenException.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/oauth2/impl/IntrospectionTokenServiceImpl.java

closes gravitee-io/issues#3326

feat(oauth2): add more log during OAuth 2.0 introspection process

---

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/AbstractRepositoryConfiguration.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractManagementMongoRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/ManagementRepositoryConfiguration.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/OAuth2RepositoryConfiguration.java

closes gravitee-io/issues#3340

feat(mongo): retrieve db name from uri

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-bootstrap/pom.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-bootstrap/pom.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-bootstrap/src/main/java/io/gravitee/am/management/standalone/bootstrap/Bootstrap.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/bin/gravitee
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/bin/gravitee.bat

chore(): rename Main Class Bootstrap package

---

gravitee-am-ui/constants.json
gravitee-am-ui/src/app/domain/settings/forms/form/form.component.ts
gravitee-am-ui/src/app/domain/settings/providers/provider/provider.component.ts
gravitee-am-ui/src/app/domain/settings/roles/roles.component.ts
gravitee-am-ui/src/app/domain/settings/scopes/creation/scope-creation.component.ts
gravitee-am-ui/src/app/domain/settings/users/creation/user-creation.component.ts
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
gravitee-am-ui/src/app/login/login.component.ts
gravitee-am-ui/src/app/logout/logout.component.ts
gravitee-am-ui/src/app/resolvers/certificates.resolver.ts
gravitee-am-ui/src/app/resolvers/consents.resolver.ts
gravitee-am-ui/src/app/resolvers/domain.resolver.ts
gravitee-am-ui/src/app/resolvers/form.resolver.ts
gravitee-am-ui/src/app/resolvers/scope.resolver.ts
gravitee-am-ui/src/app/resolvers/scopes.resolver.ts
gravitee-am-ui/src/app/services/auth.service.ts
gravitee-am-ui/src/main.ts

closes gravitee-io/issues#2460

feat(ui): clean up the constants.json file

---

gravitee-am-ui/src/assets/theme/gravitee.css

fix(ui): fix default theme

---

gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/applications/application/advanced/memberships/memberships.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/memberships/memberships.component.scss
gravitee-am-ui/src/app/domain/applications/application/advanced/memberships/memberships.component.ts
gravitee-am-ui/src/app/domain/components/memberships/dialog/memberships-dialog.html
gravitee-am-ui/src/app/domain/components/memberships/dialog/memberships-dialog.scss
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.html
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.scss
gravitee-am-ui/src/app/domain/components/memberships/memberships.component.ts
gravitee-am-ui/src/app/domain/settings/memberships/memberships.component.html
gravitee-am-ui/src/app/domain/settings/memberships/memberships.component.scss
gravitee-am-ui/src/app/domain/settings/memberships/memberships.component.ts
gravitee-am-ui/src/app/services/application.service.ts
gravitee-am-ui/src/app/services/domain.service.ts
gravitee-am-ui/src/app/services/organization.service.ts
gravitee-am-ui/src/app/settings/memberships/memberships.component.ts
gravitee-am-ui/src/styles.scss

closes gravitee-io/issues#3378

feat(memberships): rework memberships administration screen

---

docs/scripts/migration-v3.js
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/roles/RoleResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/roles/SystemRoleResource.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/PermissionService.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultRoleUpgrader.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/helpers/MembershipHelper.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/PermissionServiceTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/CertificateUpgraderTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgraderTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultRoleUpgraderTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/OpenIDScopeUpgraderTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/ScopeUpgraderTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/helpers/MembershipHelperTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Role.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoRoleRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/RoleMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/RoleServiceImpl.java

Closes gravitee-io/issues#3408

feat(migration): Migration to v3 must not impact v2 gateways

---

gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts

Closes gravitee-io/issues#3428

fix(ui): access domains audits settings

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/GroupsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/RolesResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/groups/GroupsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/roles/RolesResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/tags/TagsResource.java

Closes gravitee-io/issues#3440

fix(ui): add 'description' field for all kind of entity listing

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/UserEntity.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
gravitee-am-ui/src/app/components/user-avatar/user-avatar.component.html
gravitee-am-ui/src/app/components/user-avatar/user-avatar.component.ts

fix(user): add picture field to user and fix ui component

---

gravitee-am-ui/README.adoc
gravitee-am-ui/pom.xml
gravitee-am-ui/src/app/domain/domain.component.ts

closes gravitee-io/issues#2272

chore(ui): bump node version to the latest v12 LTS (12.16.1)

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/GithubIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/spring/GithubAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/OAuth2GenericIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/resources/schemas/schema-form.json
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/SocialAuthenticationFilter.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

closes gravitee-io/issues#3154

feat(idp): move http client configuration to dedicated section

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationResource.java
gravitee-am-service/src/main/java/io/gravitee/am/service/ApplicationService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/ApplicationTemplateManager.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/application/ApplicationBrowserTemplate.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/application/ApplicationNativeTemplate.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/application/ApplicationServiceTemplate.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/application/ApplicationWebTemplate.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/application/DefaultApplicationTemplateManager.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplication.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationType.java
gravitee-am-service/src/test/java/io/gravitee/am/service/application/ApplicationBrowserTemplateTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/application/ApplicationNativeTemplateTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/application/ApplicationServiceTemplateTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/application/ApplicationWebTemplateTest.java
gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.scss
gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts
gravitee-am-ui/src/app/services/application.service.ts

closes gravitee-io/issues#3098

fix(app): be able to change application type

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationsResource.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java

fix(app): fix applications pagination

---

gravitee-am-ui/src/app/settings/management/roles/role/role.component.html
gravitee-am-ui/src/app/settings/management/roles/role/role.component.scss
gravitee-am-ui/src/app/settings/management/roles/role/role.component.ts

Closes gravitee-io/issues#3454

feat(roles): stick role header and add permission filter

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationEmailsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationFormsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/EmailsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/FormsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/forms/FormsResource.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Email.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Form.java
gravitee-am-ui/src/app/resolvers/email.resolver.ts
gravitee-am-ui/src/app/resolvers/form.resolver.ts

fix(templates): send empty content if a form or an email template does not exist

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ClientServiceTest.java
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/domain/settings/users/user/applications/application/application.component.html
gravitee-am-ui/src/app/domain/settings/users/user/applications/application/application.component.ts
gravitee-am-ui/src/app/domain/settings/users/user/applications/applications.component.html
gravitee-am-ui/src/app/domain/settings/users/user/applications/applications.component.ts
gravitee-am-ui/src/app/resolvers/application.resolver.ts
gravitee-am-ui/src/app/resolvers/consents.resolver.ts

Closes gravitee-io/issues#3546

fix(user): revoke user data access of an application

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandler.java
gravitee-am-ui/src/app/domain/settings/users/user/applications/application/application.component.ts
postman/collections/graviteeio-am-client-management-collection-app-version.json
postman/collections/graviteeio-am-openid-dcr-collection-app-version.json

Closes gravitee-io/issues#3549
Closes gravitee-io/issues#3551

fix(gateway): sso should not be used on application without active idp

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/UsersResource.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
gravitee-am-model/src/main/java/io/gravitee/am/model/account/AccountSettings.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/AccountSettingsMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/UserMongo.java
gravitee-am-ui/src/app/domain/components/account/account-settings.component.html
gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts
postman/collections/graviteeio-am-user-management-collection.json

closes gravitee-io/issues#3399

feat(users): add dynamic user registration

---

gravitee-am-ui/src/app/domain/applications/application/endpoints/endpoints.component.html

Closes gravitee-io/issues#3559
Closes gravitee-io/issues#3558

fix(endpoints): add missing jwks endpoint and fix userinfo description

---

postman/collections/graviteeio-am-client-management-collection.json

Closes gravitee-io/issues#3593

fix(postman): Fix client management test

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationServiceTest.java

Closes gravitee-io/issues#3598

fix(dcr): set default client name on dynamic client registration

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/impl/OpenIDDiscoveryServiceImpl.java

closes gravitee-io/issues#3614

fix(oidc): remove "public" supported_subject_type for certification purpose

---

gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html
gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts

closes gravitee-io/issues#3613

feat(app): display curl command according to the token auth endpoint method

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java

fix(mfa): handle X-Forwarded-* headers for the MFA flow

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java

fix(users): enable account when reset password after pre-registration

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/mapper/ObjectMapperResolver.java
gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.ts

fix(oidc): add jwks deserializer to be able to update application configuration

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/idtoken/Claims.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/AuthorizationRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/flow/hybrid/HybridFlow.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/flow/implicit/ImplicitFlow.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenUtils.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
postman/collections/graviteeio-am-openid-core-collection-app-version.json
postman/collections/graviteeio-am-openid-core-collection.json

Closes gravitee-io/issues#3702

feat(oidc): Add s_hash claim into the id_token

---

Makefile
gravitee-am-common/src/main/java/io/gravitee/am/common/exception/oauth2/MethodNotAllowedException.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/OIDCProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/RequestObjectRegistrationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/handler/authorization/AuthorizationRequestParseRequestObjectHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/OpenIDProviderMetadata.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/impl/OpenIDDiscoveryServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/RequestObjectRegistrationRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/RequestObjectRegistrationResponse.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/RequestObjectService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/impl/RequestObjectServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/handler/authorization/AuthorizationRequestParseRequestObjectHandlerTest.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oidc/api/RequestObjectRepository.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/oidc/model/RequestObject.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/OAuth2RepositoryConfiguration.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oidc/AbstractOIDCMongoRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oidc/MongoRequestObjectRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oidc/iinternal/model/RequestObjectMongo.java
postman/collections/graviteeio-am-openid-fapi-collection.json

Closes gravitee-io/issues#3707

feat(fapi): Add support for request object registration

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/CommonConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/jwk/impl/JWKServiceImpl.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/spring/GithubAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/LoginController.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/RecaptchaFilter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/login.html
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-service/pom.xml
gravitee-am-service/src/main/java/io/gravitee/am/service/ReCaptchaService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReCaptchaServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/spring/WebClientsConfiguration.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ReCaptchaServiceImplTest.java
postman/collections/graviteeio-am-user-management-collection-app-version.json
postman/collections/graviteeio-am-user-management-collection.json

Closes gravitee-io/issues#3675

feat(captcha): add captcha support on AM login page

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/forgot_password.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login_sso_post.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
gravitee-am-management-api/gravitee-am-management-api-rest/pom.xml
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/csrf/CookieCsrfSignedTokenRepository.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/csrf/CsrfRequestMatcher.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/CsrfIncludeFilter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/jwt/JWTGenerator.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html
gravitee-am-ui/src/app/interceptors/http-request.interceptor.ts
pom.xml

Closes gravitee-io/issues#3674

feat(csrf): enable csrf on domain forms and AM management UI by default

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterSubmissionEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/exception/UniquenessException.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/ErrorHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/users/CreateUserEndpointHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/resources/users/UpdateUserEndpointHandlerTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/RegexPasswordValidator.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/EmailFormatInvalidException.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewUser.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateUser.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/EmailValidator.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/UserValidator.java
gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/UserValidatorTest.java
postman/collections/graviteeio-am-scim-collection-app-version.json
postman/collections/graviteeio-am-scim-collection.json
postman/collections/graviteeio-am-user-management-collection-app-version.json
postman/collections/graviteeio-am-user-management-collection.json

Closes gravitee-io/issues#3755

feat(security): improve inputs validation

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
pom.xml

Note: depends on https://github.com/gravitee-io/gravitee-expression-language/pull/11
Closes gravitee-io/issues#3699

feat(el): sandbox EL to whitelisted methods

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json

Closes gravitee-io/issues#3782

feat(ldap): add Use StartTLS option

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/server/ManagementApiServer.java

Closes gravitee-io/issues#3775

fix(cors): propagate x-forwarded header to correctly resolve cors

---

gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html
gravitee-am-ui/src/app/domain/applications/application/endpoints/endpoints.component.ts
gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html

fix(app): display application domain path instead of domain id

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
pom.xml

closes gravitee-io/issues#3254

chore(): update external policy dependencies

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ClientsResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ApplicationsResourceTest.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ClientsResourceTest.java

fix(app): applications total count must take in account user permissions

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/CompleteProfileController.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/handler/CustomAuthenticationSuccessHandler.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/web/LoginUrlAuthenticationEntryPoint.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/web/XForwardedAwareRedirectStrategy.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/assets/css/complete_profile.css
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/resources/views/complete_profile.html
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/NewsletterService.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/NewsletterServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-model/src/main/java/io/gravitee/am/model/Template.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/UserMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/spring/WebClientsConfiguration.java
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html
gravitee-am-ui/src/app/domain/components/forms/form/form.component.ts
gravitee-am-ui/src/app/domain/components/forms/forms.component.ts
gravitee-am-ui/src/app/domain/settings/forms/form/form.component.ts
gravitee-am-ui/src/app/domain/settings/forms/forms.component.ts
gravitee-am-ui/src/app/resolvers/form.resolver.ts

closes gravitee-io/issues#3666

feat(portal): be able to subscribe to newsletter

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/CompleteProfileController.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/UserValidator.java

fix(users): handle empty values for the default administrator user

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ClientsToApplicationsUpgrader.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/utils/GrantTypeUtils.java
postman/collections/graviteeio-am-policies-collection-app-version.json
postman/collections/graviteeio-am-policies-collection.json

closes gravitee-io/issues#3822

chore(): fix postman tests

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/provider/UserProperties.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
gravitee-am-ui/src/app/domain/clients/client/oauth2/dialog/claims-info.component.html
postman/collections/graviteeio-am-oauth2-collection.json

fix(oidc): add user groups to the execution context

---

docker/compose/config/nginx.conf
gravitee-am-ui/src/app/login/login.component.ts
gravitee-am-ui/src/app/logout/logout.component.ts

fix(ui): fix login and logout callback URLs

---

gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Missing # in cookie domain value.

Missing # in config

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-model/src/main/java/io/gravitee/am/model/account/AccountSettings.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/AccountSettingsMongo.java
gravitee-am-ui/src/app/domain/components/account/account-settings.component.html
gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts

closes gravitee-io/issues#3910

feat(users): configure a default idp for user registration

---

gravitee-am-model/src/main/java/io/gravitee/am/model/account/AccountSettings.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-ui/src/app/domain/components/account/account-settings.component.html
gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts

fixes gravitee-io/issues#3871 and fixes gravitee-io/issues#3872 and fixes gravitee-io/issues#3873

fix(account): handle latest 2.10.x account settings for the v3

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PermissionTicketServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/PermissionTicketServiceTest.java
postman/collections/graviteeio-am-uma2-app-version-collection.json

This is related to issue [#4006](https://github.com/gravitee-io/issues/issues/4006)

merge permission resource ids

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/uma/UMAProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/uma/resources/endpoint/PermissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/uma/resources/endpoint/PermissionEndpointTest.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/ResourceRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoResourceRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/management/MongoResourceRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/PermissionTicketService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/ResourceService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/InvalidPermissionRequestException.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/PermissionTicketServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ResourceServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/application/ApplicationResourceServerTemplate.java
gravitee-am-service/src/test/java/io/gravitee/am/service/PermissionTicketServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ResourceServiceTest.java
postman/collections/graviteeio-am-uma2-app-version-collection.json

Hello,
This enable a RS to request resource permission using a PAT that represent the RS a client & sub (client_credentials).  
Avoiding the RS to require an end user token (and so a blocking action from the RO).

uma2 RS request permissions with a client_credentials PAT

---

pom.xml

Closes gravitee-io/issues#4003

fix(el): fix el initialization

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserTokenRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java

fix(templates): keep custom HTML template if an error has occurred

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/email/impl/EmailServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java

fix(email): attach base64 images to email template

---

gravitee-am-service/src/main/java/io/gravitee/am/service/validators/UserValidator.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/EmailValidatorTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/UserValidatorTest.java

Closes gravitee-io/issues#4032

fix(username): allows '+' and '#' characters for username

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/AcrValues.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseProviderConfigurationHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseRequiredParametersHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/impl/OpenIDDiscoveryServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/ClaimRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/ClaimsRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/ClaimsRequestResolver.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/discovery/OpenIDDiscoveryServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenServiceTest.java

closes gravitee-io/issues#4031

feat(oidc): support acr claim

---

gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/JavaKeyStoreConfiguration.java
gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/provider/JavaKeyStoreProvider.java
gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/resources/schemas/schema-form.json
gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/java/io/gravitee/am/certificate/pkcs12/PKCS12Configuration.java
gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/java/io/gravitee/am/certificate/pkcs12/provider/PKCS12Provider.java
gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/resources/schemas/schema-form.json
gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/CodeChallengeMethod.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/ClaimType.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/ClientAuthenticationMethod.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/ResponseMode.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/jwt/impl/JWTServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/impl/OpenIDDiscoveryServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/utils/JWAlgorithmUtils.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/discovery/OpenIDDiscoveryServiceTest.java
gravitee-am-jwt/pom.xml
gravitee-am-jwt/src/main/java/io/gravitee/am/jwt/DefaultJWTBuilder.java
gravitee-am-jwt/src/main/java/io/gravitee/am/jwt/DefaultJWTParser.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/main/java/io/gravitee/am/plugins/certificate/core/CertificateSchemaProperty.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
pom.xml

closes gravitee-io/issues#4029

feat(jwt): support RSSA-PSS (PS256, PS384, PS512) signing algorithms

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/AuthorizationController.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/CompleteProfileController.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/LoginController.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/TokenController.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/csrf/CookieCsrfSignedTokenRepository.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/BuiltInAuthenticationFilter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/CheckAuthenticationCookieFilter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/CheckRedirectionCookieFilter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/SocialAuthenticationFilter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/handler/CookieClearingLogoutHandler.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/handler/CustomAuthenticationFailureHandler.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/handler/CustomAuthenticationSuccessHandler.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/generator/JWTGenerator.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/generator/RedirectCookieGenerator.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/web/LoginUrlAuthenticationEntryPoint.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/web/WebAuthenticationDetails.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/server/ManagementApiServer.java
postman/collections/graviteeio-am-api-management-collection.json

Closes gravitee-io/issues#4079
Closes gravitee-io/issues#4081

feat(sessionless): remove use of session for management api

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/swagger/GraviteeApiDefinition.java

doc: add security definition to the swagger descriptor

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java

fix(oidc): prompt login issue when user is coming from consent or MFA step

---

docker/compose/config/nginx.conf
docker/environments/demo/docker-compose-traefik-latest.yml
docker/environments/nightly/docker-compose-traefik-nightly.yml
docker/management-ui/config/templates/default.conf.tmpl

Closes gravitee-io/issues#4094

docker: Use non-root ports to run nginx

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java

Closes gravitee-io/issues#4114

feat(users): display users additional information for the UsersResource endpoint

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/assembly/plugin-assembly.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/AzureADIdentityProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/AzureADIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/AzureADIdentityProviderMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/AzureADIdentityProviderRoleMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/authentication/AzureADAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/authentication/spring/AzureADAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/jwks/JWKSourceResolver.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/jwks/hmac/MACJWKSourceResolver.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/jwks/remote/RemoteJWKSourceResolver.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/jwks/rsa/RSAJWKSourceResolver.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/processor/AbstractKeyProcessor.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/processor/HMACKeyProcessor.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/processor/JWKSKeyProcessor.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/processor/KeyProcessor.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/jwt/processor/RSAKeyProcessor.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/resolver/KeyResolver.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/utils/URLEncodedUtils.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/resources/plugin.properties
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/test/java/io/gravitee/am/identityprovider/azure/authentication/AzureADAuthenticationProviderTest.java
gravitee-am-identityprovider/pom.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
gravitee-am-ui/package-lock.json
gravitee-am-ui/src/app/domain/applications/application/idp/idp.component.ts
gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step1/step1.component.ts
gravitee-am-ui/src/app/domain/settings/providers/providers.component.ts

Closes gravitee-io/issues#4074

feat(azure-idp): azure identity provider plugin

---

gravitee-am-ui/src/app/domain/settings/extension-grants/extension-grant/extension-grant.component.ts
gravitee-am-ui/src/app/domain/settings/factors/factor/factor.component.ts

Closes gravitee-io/issues#4133

fix(permissions): Fix bad code for permission

---

gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/main/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JWTBearerExtensionGrantProvider.java
gravitee-am-extensiongrant/gravitee-am-extensiongrant-jwtbearer/src/test/java/io/gravitee/am/extensiongrant/jwtbearer/provider/JWTBearerExtensionGrantProviderTest.java

Closes gravitee-io/issues#4135

fix(jwt-bearer): sub claims is an optional claim

---

gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/DomainResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/DomainsResource.java
gravitee-am-management-api/gravitee-am-management-api-handlers/gravitee-am-management-api-handlers-management/src/main/java/io/gravitee/am/management/handlers/management/api/resources/ReporterResource.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/AuditReporterManager.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditReporterManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DomainReporterUpgrader.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java

fix(reporters): reporters should be loaded on all cluster AM Management API nodes

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java

fix(email): registration confirmation email expires after not working

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/impl/UserAuthenticationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/management/MongoUserRepositoryTest.java
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts

fix(users): user must be editable if identity provider provides user provisioning feature

---

gravitee-am-ui/src/app/domain/applications/application/advanced/metadata/metadata.component.ts

fix(ui): application metadata key and value was inverted

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieHandlerImpl.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/csrf/CookieCsrfSignedTokenRepository.java

closes gravitee-io/issues#4205

chore(): change CSRF cookie name for the management to avoid collision

---

.gitignore
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/handler/impl/FormLoginHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/error/ErrorHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/provider/ClientAssertionAuthProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseProviderConfigurationHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/DynamicClientAccessEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/DynamicClientRegistrationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/uma/resources/endpoint/ProviderConfigurationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/uma/resources/endpoint/ResourceAccessPoliciesEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/uma/resources/endpoint/ResourceRegistrationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/groups/AbstractGroupEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/resources/users/AbstractUserEndpoint.java
postman/collections/graviteeio-am-user-management-collection-app-version.json
postman/collections/graviteeio-am-user-management-collection.json

Closes gravitee-io/issues#4034

fix(cookie): fix crsf cookie path

---

gravitee-am-jwt/src/main/java/io/gravitee/am/jwt/DefaultJWTParser.java
gravitee-am-jwt/src/test/java/io/gravitee/am/jwt/DefaultJWTParserTest.java
postman/collections/graviteeio-am-oauth2-collection-app-version.json
postman/collections/graviteeio-am-oauth2-collection.json

fix(jwt): JWT Parser must check the value of the verify method status response

---

gravitee-am-identityprovider/gravitee-am-identityprovider-facebook/src/main/java/io/gravitee/am/identityprovider/facebook/FacebookIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-facebook/src/main/java/io/gravitee/am/identityprovider/facebook/model/FacebookUser.java

Closes gravitee-io/issues#4235

fix(facebook): move to api v8 and remove deprecated fields

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java

fix(scim): user enabled status can be changed

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/user/impl/UserManagerImpl.java

fix(register): autologin feature must not block the SSOSessionHandler

---

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html

fix(user): user profile fields should be disabled when insufficient permissions

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-model/src/main/java/io/gravitee/am/model/account/AccountSettings.java

fix(register): account settings should be null during user registration

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/IdentityProviderManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/idp/impl/IdentityProviderManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java

fix(login): skip external identity provider for authentication with credentials

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CorsHandlerFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/uma/UMAProvider.java
gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.ts

fixes gravitee-io/issues#4237 and fixes gravitee-io/issues#4238

fix(uma2): add missing CORS configuration and UMA Ticket grant selection for the UI

---

gravitee-am-ui/src/app/domain/applications/application/endpoints/endpoints.component.html
gravitee-am-ui/src/app/domain/applications/application/endpoints/endpoints.component.ts

closes gravitee-io/issues#4305

feat(ui): add UMA 2 endpoints

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/request/impl/RequestObjectServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/RequestObjectServiceTest.java

closes gravitee-io/issues#4051

feat(fapi): ensure request object signature algorithm is not none

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/EnvironmentsResource.java
gravitee-am-service/src/main/java/io/gravitee/am/service/DomainService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/EnvironmentService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EnvironmentServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/DomainValidator.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/VirtualHostValidator.java
gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/EnvironmentServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/DomainValidatorTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/VirtualHostValidatorTest.java
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.html
gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.ts
gravitee-am-ui/src/app/resolvers/current-environment.resolver.spec.ts
gravitee-am-ui/src/app/resolvers/current-environment.resolver.ts

Closes gravitee-io/issues#4224

feat(domain-restrictions): apply domain restrictions on vhosts

---

gravitee-am-service/src/main/java/io/gravitee/am/service/EntrypointService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/EntrypointServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/OrganizationServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/VirtualHostValidator.java
gravitee-am-service/src/test/java/io/gravitee/am/service/EntrypointServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/OrganizationServiceTest.java
gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.ts

Closes gravitee-io/issues#4317

feat(domain-restrictions): apply domain restrictions on entrypoints

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/healthcheck/HttpServerProbe.java

Closes gravitee-io/issues#4384

fix(probe): close http client after http health check

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java

Closes gravitee-io/issues#4359

fix(user):strict mode when searching user for forgot password

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/UserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/configuration/HttpUsersResourceConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/configuration/HttpUsersResourcePathsConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/HttpUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/user/HttpUserProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/user/HttpUserProviderTestConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json

closes gravitee-io/issues#4360

feat(users): users should be found from their IDP during forgot password process

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/spring/GithubAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/test/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProviderTestConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/authentication/spring/HttpAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/authentication/HttpAuthenticationProviderTestConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/test/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProviderTestConfiguration.java
gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java
gravitee-am-service/src/main/java/io/gravitee/am/service/spring/WebClientsConfiguration.java

Closes gravitee-io/issues#4396

feat(proxy): add http proxy support for all identity providers

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgraderTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java

Closes gravitee-io/issues#4353

fix(user): filter user only when not having read permission

---

docs/upgrades/3.x/3.0.0/mongodb/1-migration-v3.js
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgraderTest.java

Closes gravitee-io/issues#4425

fix(migrationv3): properly migrate domain's roles

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditReporterManagerImpl.java

fix(audit): start internal reporter for the organization audit logs

---

gravitee-am-ui/src/app/domain/applications/application/design/forms/forms.component.ts
gravitee-am-ui/src/app/domain/settings/forms/forms.component.ts

fix(form): enable custom reset password form even if the SSPR is disabled

---

gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationOAuthSettings.java

fix(application): correctly handle optional value for the application tokenEndpointAuthMethod

---

gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/HttpUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/test/java/io/gravitee/am/identityprovider/http/user/HttpUserProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/OAuth2GenericAuthenticationProvider.java

fix(idp-http): properly cast attribute to string

---

gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.html

fix(application): be able to force tokenEndpointAuthMethod to "Based on incoming request"

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/AuthenticationFlowHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/AutoLoginStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordSubmissionEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationSubmissionEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterSubmissionEndpointTest.java

fix(auto-login): store return_url in the http session if the auto login feature is used

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/pool/CustomBlockingConnectionPool.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json

feat(ldap): add a max retries option for the LDAP pool initialization

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserFactorResource.java

fix(users): remove user's mfa factors

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java

fix(users): list users at organization level

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnResponseEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/consent/UserConsentPrepareContextHandler.java
gravitee-am-ui/src/app/domain/settings/policies/dialog/policies-info.component.html

closes gravitee-io/issues#4495

feat(context): add webauthn credential ID and MFA factor ID to the execution context

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java

fix(webauthn): correctly end the webauthn register flow if it's skipped

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java

fix(users): delete user's webauthn credentials

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/impl/ExtensionGrantManagerImpl.java

fix(gateway/oidc): fix exception during removeExtensionGrant

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/WebAuthnRegisterStep.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java

closes gravitee-io/issues#4497

feat(webauthn): register page should always be displayed to the user

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnResponseEndpoint.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Credential.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/CredentialMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/CredentialService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CredentialServiceImpl.java
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/settings/users/user/credentials/credential/credential.component.html
gravitee-am-ui/src/app/domain/settings/users/user/credentials/credential/credential.component.spec.ts
gravitee-am-ui/src/app/domain/settings/users/user/credentials/credential/credential.component.ts
gravitee-am-ui/src/app/domain/settings/users/user/credentials/credentials.component.html
gravitee-am-ui/src/app/resolvers/user-credential.resolver.spec.ts
gravitee-am-ui/src/app/resolvers/user-credential.resolver.ts
gravitee-am-ui/src/app/services/user.service.ts

closes gravitee-io/issues#4498

feat(webauthn): provide more information for the webauthn credentials

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_4_0/schema.yml

fix(repository/jdbc): change verchar limit from 256 to 255

---

.circleci/config.yml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java

fix(login): end the flow if we have a unexpected error during social login

---

.circleci/config.yml
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/MembershipRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoMembershipRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/management/MongoMembershipRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/MembershipService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
gravitee-am-ui/src/app/domain/settings/users/users.component.ts
gravitee-am-ui/src/app/services/organization.service.ts
gravitee-am-ui/src/app/services/user.service.ts

fix(users): delete administrative users (organization)

---

gravitee-am-service/src/main/java/io/gravitee/am/service/validators/UserValidator.java
gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/UserValidatorTest.java
postman/collections/graviteeio-am-user-management-collection-app-version.json
postman/collections/graviteeio-am-user-management-collection.json

fix(users): use the same validator for both displayName and username

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcFlowRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcFlow.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringFlowRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_5_0/schema.yml
gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/management/api/JdbcFlowRepositoryTest.java

feat(repository): addition of Flow in jdbc repository

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ConstantKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSession.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSessionHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnResponseEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java

Closes gravitee-io/issues#4734

fix(webauthn): Ensure to not override userId in the cookie session

---

gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/InlineIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/resources/schemas/schema-form.json
gravitee-am-ui/package-lock.json
gravitee-am-ui/package.json
gravitee-am-ui/src/app/domain/settings/providers/creation/provider-creation.component.ts
gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts
gravitee-am-ui/src/app/services/provider.service.ts

closes gravitee-io/issues#4695

feat(idp): add password encoder for Inline identity provider

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSRFHandlerFactory.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/configuration/ConfigurationChecker.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml

fix(gateway): CSRF must work in cluster environment

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/SSOSessionHandler.java

fix(sso): should not kill current session during reset password

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/token/impl/TokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/token/TokenServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenServiceTest.java

closes gravitee-io/issues#4729

feat(oidc): override OIDC standard claims with custom claims feature

---

pom.xml

closes gravitee-io/issues#4834

fix(repository): check repository type before loading the repository implementations

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-login.js
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-register.js
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn.auth.js
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_login.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_register.html

feat(webauthn): split webauthn js file to enable custom handlers

---

pom.xml

fix(dependencies): update bouncycastle

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java

fix(emails): remove sensitive data from the JWT token

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java

fix(registration): set custom expiresAfter for dynamic user registration

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/RequestUtils.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/WebAuthnFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/WebAuthnFactoryTest.java
gravitee-am-ui/package-lock.json
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/domain/settings/webauthn/webauthn.component.html
gravitee-am-ui/src/app/domain/settings/webauthn/webauthn.component.ts

fix(webauthn): set relying party ID and name

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnResponseEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStoreTest.java

fix(webauthn): prevent username enumeration

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/impl/attestation/AndroidSafetynetAttestation.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/attestation/AttestationTest.java

fix(webauthn): change AndroidSafetynet attestation base64 decoder

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProviderTest.java

feat(gateway) log social IdP login in audit logs

---

gravitee-am-ui/src/app/domain/applications/application/analytics/analytics.component.html
gravitee-am-ui/src/app/domain/applications/application/analytics/analytics.component.ts
gravitee-am-ui/src/app/domain/applications/application/application.component.ts

fix(ui): do not display analytics tab for b2b application

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/commands/InstallationCommandHandler.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/commands/InstallationCommandHandlerTest.java

Closes gravitee-io/issues#4942

feat(cockpit): handle cockpit installation events

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/InstallationEntity.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/InstallationResource.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-ui/src/app/settings/cockpit/cockpit.component.html

Closes gravitee-io/issues#4947

feat(cockpit): make cockpit url configurable

---

.circleci/config.yml
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/CockpitAuthenticationFilter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/SocialAuthenticationFilter.java

Closes gravitee-io/issues#4528

fix(auth): attach user to the proper organization when using social idp

---

gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.ts
gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts
gravitee-am-ui/src/app/domain/components/dashboard/dashboard.component.ts
gravitee-am-ui/src/app/domain/settings/audits/audits.component.html
gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts
gravitee-am-ui/src/app/domain/settings/scopes/creation/scope-creation.component.ts
gravitee-am-ui/src/app/domain/settings/scopes/scope/scope.component.ts
gravitee-am-ui/src/app/domain/settings/scopes/scopes.component.ts
gravitee-am-ui/src/app/domain/settings/users/user/history/history.component.html
gravitee-am-ui/src/app/domain/settings/users/user/history/history.component.scss
gravitee-am-ui/src/app/domain/settings/users/user/history/history.component.spec.ts
gravitee-am-ui/src/app/domain/settings/users/user/history/history.component.ts
gravitee-am-ui/src/app/domain/settings/users/user/user.component.ts
gravitee-am-ui/src/app/pipes/human-date.pipe.ts
gravitee-am-ui/src/app/services/audit.service.spec.ts
gravitee-am-ui/src/app/services/audit.service.ts
gravitee-am-ui/src/app/utils/time-range-utils.ts
gravitee-am-ui/src/styles.scss
gravitee-am-ui/tsconfig.json

Closes: https://github.com/gravitee-io/issues/issues/3291

Add user history

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/WebAuthnFactory.java

closes gravitee-io/issues#4950

feat(webauthn): select Authenticator Transport

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/impl/attestation/AndroidSafetynetAttestation.java

closes gravitee-io/issues#4933

fix(webauthn): corretly set the signature for the AndroidSafetynet attestation

---

gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.html
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts

fix(UI): display claims with object value as json

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/Authenticator.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/AuthenticatorConverter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/WebAuthn.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/impl/WebAuthnImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStoreTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Credential.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/CredentialMongo.java
gravitee-am-ui/src/app/domain/settings/users/user/credentials/credential/credential.component.html
gravitee-am-ui/src/app/domain/settings/users/user/credentials/credentials.component.html

closes gravitee-io/issues#4949

feat(webauthn): store attestation information

---

gravitee-am-ui/src/app/domain/settings/providers/provider/mappers/mappers.component.ts
gravitee-am-ui/src/app/domain/settings/providers/provider/roles/roles.component.ts

fix(idp): parse json before saving identity provider mappers

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/Parameters.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationRequest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Application.java
gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationOAuthSettings.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationOAuthSettingsMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationOAuthSettings.java
gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts
gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html

closes gravitee-io/issues#4978

feat(logout): add post_logout_redirect_uri

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/commands/HelloCommandProducer.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/commands/HelloCommandProducerTest.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

Closes gravitee-io/issues#4984

feat(cockpit): add am urls when registering to cockpit

---

gravitee-am-common/src/main/java/io/gravitee/am/common/jwt/Claims.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/CockpitAuthenticationFilter.java
gravitee-am-ui/package-lock.json
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/components/sidenav/sidenav.component.ts
gravitee-am-ui/src/app/environment/environment.component.html
gravitee-am-ui/src/app/environment/environment.component.scss
gravitee-am-ui/src/app/environment/environment.component.spec.ts
gravitee-am-ui/src/app/environment/environment.component.ts
gravitee-am-ui/src/app/home/home.component.html

Closes gravitee-io/issues#4985

feat(cockpit): login to the expected environment

---

gravitee-am-ui/src/app/app-routing.module.ts

fix(ui): user should be able to navigate to their applications

---

gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.html
gravitee-am-ui/src/app/domain/settings/entrypoints/entrypoints.component.ts

fix(ui): fix domain vhost listening host pattern

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcDomain.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_5_2/schema.yml

fix(repository): change column name override_endpoints by override_entrypoint (domain vhost jdbc)

---

gravitee-am-ui/src/app/settings/cockpit/cockpit.component.html

Closes gravitee-io/issues#5022

fix(cockpit): bad cockpit url on registration step 1

---

gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js

fix(mongo): add missing index

---

gravitee-am-ui/src/app/app-routing.module.ts

fix(ui): add entrypoint resolver for the WebAuthn page

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login_callback.html

fix(idp): better handle OIDC identity provider with implicit flow

---

gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.ts

Closes gravitee-io/issues#5050

fix(ui): fix loss of application infos when updating oauth config

---

postman/collections/graviteeio-am-api-management-collection.json

fix(postman): remove test on completeProfile

---

gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchClient.java
postman/collections/graviteeio-am-flows-collection.json

fix(management): manage flowsInherit attribute into PatchClient object

---

Makefile
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
pom.xml

Closes gravitee-io/issues#4992

chore(cockpit): add cockpit-connector-ws to distribution

---

gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/domain/applications/application/advanced/metadata/metadata.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/metadata/metadata.component.ts
gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.ts

Closes gravitee-io/issues#5065

fix(metadata): refresh metadata after update

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/cockpit/schema-add-environment-permissions.yml

fix(memberships) : assign ENVIRONMENT_USER role to all existing users for JDBC

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserTokenRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/ResetPasswordOneTimeTokenHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/model/UserToken.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/ResetPasswordOneTimeTokenHandlerTest.java

fix(resetPassword): use one time token for reset password action

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/account/AccountSettings.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CredentialRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/AccountSettingsMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/CredentialService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CredentialServiceImpl.java
gravitee-am-ui/src/app/domain/components/account/account-settings.component.html
gravitee-am-ui/src/app/domain/components/account/account-settings.component.ts

closes gravitee-io/issues#4998

feat(resetPassword): add option to delete passwordless devices after reset password action

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStoreTest.java

closes gravitee-io/issues#5079

feat(webauthn): prevent username enumeration v2

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/OIDCSettings.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/oidc/OIDCSettingsMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/openid/PatchOIDCSettings.java
gravitee-am-ui/src/app/domain/settings/general/general.component.html
gravitee-am-ui/src/app/domain/settings/general/general.component.scss
gravitee-am-ui/src/app/domain/settings/general/general.component.ts
gravitee-am-ui/src/app/services/domain.service.ts

closes gravitee-io/issues#5078

feat(logout): add registered logout uris for a security domain

---

gravitee-am-common/src/main/java/io/gravitee/am/common/policy/PasswordInclude.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ApplicationResourceTest.java
gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSettings.java
gravitee-am-model/src/main/java/io/gravitee/am/model/application/PasswordSettings.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationSettingsMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/PasswordSettingsMongo.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/ApplicationRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/application/DefaultApplicationTemplateManager.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSettings.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchPasswordSettings.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/impl/ApplicationServiceImplTest.java
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.scss
gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.ts

closes gravitee-io/issues#5129

[management] password policy - add settings to application

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java

Closes gravitee-io/issues#5048

fix(proxy): add property to explicitly enable httpclient proxy

---

gravitee-am-common/src/main/java/io/gravitee/am/common/exception/authentication/NegotiateContinueException.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ConstantKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/AuthenticationFlowHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/AuthenticationFlowChain.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/SPNEGOStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginNegotiateAuthenticationHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login_sso_spnego.html
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/CompareAuthenticationHandler.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/GroupSearchEntryHandler.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/Base64Encoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/BinaryToTextEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/HexEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/MD5PasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/MessageDigestPasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/NoneEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/PasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/SHAMD5PasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/encoding/SHAPasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/config/LdapProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/pool/CustomBlockingConnectionPool.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/utils/LdapUtils.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/pom.xml

feat(idp/kerberos): addition of kerberos IdentityProvider

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/Scope.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpointHandlerTest.java

closes gravitee-io/issues#5107

feat(oauth2): add full_profile scope

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/service/impl/AuthenticationServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/authentication/service/AuthenticationServiceTest.java

fix(organization): update orga roles after authentication if role mapper has changed

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java

fix(logout): lax id_token_hint parameter

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationMembersResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/MembersResource.java

fix(members): add media type to the members rest resources

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ConstantKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/AbstractEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/password_validation.css
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/register.css
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/css/reset_password.css
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/password-validation.js
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/PasswordValidator.java
gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/PasswordValidatorTest.java

closes gravitee-io/issues#5128

Show password config on validation failure on taping

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ApplicationServiceTest.java

closes gravitee-io/issues#5006

feat(application): set default certificate when creating an application

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/commands/GoodbyeCommandHandler.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/commands/GoodbyeCommandHandlerTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/InstallationService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/InstallationServiceImpl.java
pom.xml

closes gravitee-io/issues#5154

feat(cockpit): handle good bye command

---

gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/provider/JavaKeyStoreProvider.java
gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/java/io/gravitee/am/certificate/pkcs12/provider/PKCS12Provider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/VertxSecurityDomainHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/pom.xml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/main/assembly/plugin-assembly.xml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/main/java/io/gravitee/am/gateway/handler/saml2/SAML2Protocol.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/main/java/io/gravitee/am/gateway/handler/saml2/SAML2Provider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/main/java/io/gravitee/am/gateway/handler/saml2/resources/endpoint/ServiceProviderMetadataEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/main/java/io/gravitee/am/gateway/handler/saml2/service/sp/ServiceProviderService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/main/java/io/gravitee/am/gateway/handler/saml2/service/sp/impl/ServiceProviderServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/main/java/io/gravitee/am/gateway/handler/saml2/spring/SAMLConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/main/resources/plugin.properties
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/test/java/io/gravitee/am/gateway/handler/saml2/resources/endpoint/ServiceProviderMetadataEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-saml2/src/test/java/io/gravitee/am/gateway/handler/saml2/service/sp/ServiceProviderServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/pom.xml
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/Metadata.java
gravitee-am-service/src/main/java/io/gravitee/am/service/exception/IdentityProviderMetadataNotFoundException.java

closes gravitee-io/issues#5007

feat(saml): add SP metadata endpoint

---

gravitee-am-ui/angular.json

fix gravitee-io/gravitee-ui-components#265

chore: add configuration for ui-components integration

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxHttpServerConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/vertx/VertxHttpServerFactory.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml

closes gravitee-io/issues#5355

feat(ssl): add tls protocols

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/CurrentUserResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/NewsletterResource.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/NewsletterServiceImpl.java
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/newsletter/newsletter.component.ts
gravitee-am-ui/src/app/resolvers/newsletter.resolver.spec.ts
gravitee-am-ui/src/app/resolvers/newsletter.resolver.ts
gravitee-am-ui/src/app/services/auth.service.ts

closes gravitee-io/issues#5270

feat(newsletter): handle dynamic taglines

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/ApplicationType.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ClientServiceImpl.java

fix(oidc): handle browser app via DCR

---

gravitee-am-common/src/main/java/io/gravitee/am/common/oauth2/ResponseMode.java
gravitee-am-common/src/main/java/io/gravitee/am/common/oidc/ResponseMode.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/RequestUtils.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login_sso_post.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java
postman/collections/graviteeio-am-api-management-collection.json
postman/collections/graviteeio-am-openid-discovery-collection.json
postman/collections/graviteeio-am-scope-management-collection.json

closes gravitee-io/issues#5211

feat(oauth2): handle form_post response mode

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UsersResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/users/UsersResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/JerseySpringTest.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-model/src/main/java/io/gravitee/am/model/IUser.java
gravitee-am-model/src/main/java/io/gravitee/am/model/User.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewUser.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateUser.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/UserValidator.java
gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/UserValidatorTest.java

Closes gravitee-io/issues#5262

feat(user): Customize user validation

---

pom.xml
postman/collections/graviteeio-am-openid-dcr-collection-app-version.json
postman/collections/graviteeio-am-openid-dcr-collection.json

closes gravitee-io/issues#5239

chore(deps): bump vertx from 3.8.5 to 3.9.6

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java

fix(registration): add missing POST_REGISTER flow for registration confirmation

---

gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/FlowRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcFlowRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringFlowRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoFlowRepository.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FlowServiceImpl.java
gravitee-am-ui/src/app/domain/settings/flows/flows.component.ts

fix(flows): check if flow exists before create a new one

---

gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts

fix(ui): update domain property 'passwordSettings' after update

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java
gravitee-am-model/src/main/java/io/gravitee/am/model/login/WebAuthnSettings.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CredentialRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcCredentialRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_8_0/schema.yml
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAlertNotifierRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAlertTriggerRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/WebAuthnSettingsMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/resources/scripts/create-index.js
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/CredentialRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/CredentialService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CredentialServiceImpl.java
gravitee-am-ui/src/app/domain/settings/webauthn/webauthn.component.html

closes gravitee-io/issues#5305

feat(webauthn): add option to force credential registration

---

gravitee-am-model/src/main/java/io/gravitee/am/model/Membership.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/MembershipServiceImpl.java

fix(memberships): properly check primary owner unicity

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/node/GatewayNode.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/commands/InstallationCommandHandler.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
gravitee-am-repository/gravitee-am-repository-api/pom.xml
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcNodeMonitoringRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcMonitoring.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/SpringNodeMonitoringRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_8_0/schema.yml
gravitee-am-repository/gravitee-am-repository-jdbc/src/test/java/io/gravitee/am/repository/jdbc/common/JdbcRepositoriesTestInitializer.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractManagementMongoRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoNodeMonitoringRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/MonitoringMongo.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/NodeMonitoringRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/InstallationServiceImpl.java
pom.xml

Closes gravitee-io/issues#5171

feat(cockpit): monitoring data gathering

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/commands/GoodbyeCommandHandler.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/commands/GoodbyeCommandHandlerTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/InstallationService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/InstallationServiceImpl.java
gravitee-am-ui/src/app/settings/cockpit/cockpit.component.html
pom.xml

fix(cockpit): set cockpit status to deleted when handling GoodBye command

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/audit/impl/AuditReporterManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditReporterManagerImpl.java
gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/audit/JdbcAuditReporter.java

fix(jdbc): avoid blocking management api and gw during reporter startup

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditReporterManagerImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/reporter/vertx/EventBusReporterWrapper.java

fix(audits): ensure to filter audit reporters to search for audits

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/utils/ParametersUtils.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest_MSSQL.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTestConfiguration.java
postman/collections/graviteeio-am-user-management-collection-app-version.json
postman/collections/graviteeio-am-user-management-collection.json

feat(idp): add multiple login value

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackOpenIDConnectFlowHandler.java

fix(saml): handle relay state for POST binding flow

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/authentication/spring/AzureADAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-facebook/src/main/java/io/gravitee/am/identityprovider/facebook/authentication/spring/FacebookAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-franceconnect/src/main/java/io/gravitee/am/identityprovider/franceconnect/authentication/spring/FranceConnectAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/spring/GithubAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-google/src/main/java/io/gravitee/am/identityprovider/google/authentication/spring/GoogleAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/authentication/spring/HttpAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/spring/HttpUserProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-linkedin/src/main/java/io/gravitee/am/identityprovider/linkedin/authentication/spring/LinkedinAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-oauth2-generic/src/main/java/io/gravitee/am/identityprovider/oauth2/authentication/spring/OAuth2GenericAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-twitter/src/main/java/io/gravitee/am/identityprovider/twitter/authentication/spring/TwitterAuthenticationProviderConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java

closes gravitee-io/issues#5337

feat(httpClient): add proxy host exclusion

---

gravitee-am-identityprovider/gravitee-am-identityprovider-api/pom.xml
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/encoding/Base64Encoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/encoding/BinaryToTextEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/encoding/HexEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/encoding/NoneEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/spring/JdbcAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/configuration/JdbcAuthenticationProviderConfigurationTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/MongoIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/spring/MongoAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/user/MongoUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/utils/PasswordEncoder.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTestConfiguration.java
gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/MD5PasswordEncoder.java
gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/MessageDigestPasswordEncoder.java
gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/PasswordEncoder.java
gravitee-am-service/src/main/java/io/gravitee/am/service/authentication/crypto/password/SHAPasswordEncoder.java
gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/MD5PasswordEncoderTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/authentication/crypto/password/SHAPasswordEncoderTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/PasswordValidatorTest.java

closes gravitee-io/issues#5470

feat(password): support new password encoders (SHA-* and MD5)

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/UriBuilderRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CSRFHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginCallbackEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginPostEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnResponseEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginNegotiateAuthenticationHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserRequestHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/register/RegisterFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/consent/UserConsentPostEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/consent/UserConsentFailureHandler.java
gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.html
gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts

fix(gateway): handle encoded redirectUri

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/bin/gravitee
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/bin/gravitee

chore(HEAP): update HEAP settings into gravitee startup scripts

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditReporterManagerImpl.java

fix(reporter): start reporter when ManagementAPi start

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java

Fix(idp): set default findyEmail query for Mongo & JDBC

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ConstantKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/MFAChallengeStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/MFAEnrollStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/MFAStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/EvaluableExecutionContext.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationAdvancedSettings.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationAdvancedSettingsMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationAdvancedSettings.java
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/applications/application/advanced/factors/dialog/mfa-step-up-info.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.ts

closes gravitee-io/issues#5168

feat(mfa): add selection rule a.k.a set up authentication

---

gravitee-am-ui/src/app/domain/settings/scopes/scope/scope.component.html

fix(ui): disable scope toggle in detail view for System scopes

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/MFAChallengeStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/MFAEnrollStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ApplicationResource.java
gravitee-am-model/src/main/java/io/gravitee/am/model/MFASettings.java
gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationAdvancedSettings.java
gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationSettings.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationSettingsMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/MFASettingsMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationAdvancedSettings.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationSettings.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchMFASettings.java
gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.ts

fix(mfa): rewrite mfa data structure

---

gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/settings/scopes/scopes.component.html
gravitee-am-ui/src/app/domain/settings/scopes/scopes.component.scss
gravitee-am-ui/src/app/resolvers/scopes-all.resolver.spec.ts
gravitee-am-ui/src/app/resolvers/scopes-all.resolver.ts
gravitee-am-ui/src/app/services/scope.service.ts

fix(ui): fetch all scopes in ScopeResolver

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcFlow.java

fix(flows): correctly map application field for flows (JDBC)

---

postman/collections/graviteeio-am-flows-collection-app-version.json
postman/collections/graviteeio-am-flows-collection.json

Fix(postman): test encodedUrl in Location header

---

gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/java/io/gravitee/am/reporter/jdbc/dialect/MariaDBDialect.java

fix: generate right value for time slot in MariaDB reporter

---

gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/resolvers/page-roles.resolver.spec.ts
gravitee-am-ui/src/app/resolvers/page-roles.resolver.ts

fix: return all roles by the roles resolver

---

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/spring/MongoAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/EmbeddedClient.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTestConfiguration.java
gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/common/MongoFactory.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAlertNotifierRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoAlertTriggerRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoUserRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/test/java/io/gravitee/am/repository/mongodb/MongodbProvider.java
pom.xml

chore(mongo): Update MongoDB driver

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java

fix(users): merge additional information from IdP user and AM user

---

gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts
gravitee-am-ui/src/app/domain/settings/groups/group/members/members.component.ts

fix(users): correctly apply users search filter

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml

chore: disable liquibase schema updates in Gateway

---

gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/AuthenticationContext.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/DefaultIdentityProviderMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/DefaultIdentityProviderRoleMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/IdentityProviderMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-azure-ad/src/main/java/io/gravitee/am/identityprovider/azure/authentication/AzureADAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractOpenIDConnectAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-common/src/main/java/io/gravitee/am/identityprovider/common/oauth2/authentication/AbstractSocialAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-facebook/src/main/java/io/gravitee/am/identityprovider/facebook/authentication/FacebookAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-franceconnect/src/main/java/io/gravitee/am/identityprovider/franceconnect/authentication/FranceConnectAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-github/src/main/java/io/gravitee/am/identityprovider/github/authentication/GithubAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-google/src/main/java/io/gravitee/am/identityprovider/google/authentication/GoogleAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/authentication/HttpAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-linkedin/src/main/java/io/gravitee/am/identityprovider/linkedin/authentication/LinkedinAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-twitter/src/main/java/io/gravitee/am/identityprovider/twitter/authentication/TwitterAuthenticationProvider.java
gravitee-am-ui/src/app/domain/settings/providers/provider/mappers/mappers.component.html

feat: add EL support for user mapper into identity providers

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java

fix: create session on pre register step

---

.circleci/config.yml

update config.yml to prepare AM relase 3.5.14

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java

fix(users): handle unknown AM users during forgot password flow

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/controller/LoginController.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/manager/idp/impl/IdentityProviderManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/security/ManagementAuthenticationProvider.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/IdentityProviderManager.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/InMemoryIdentityProviderListener.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgrader.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/helpers/MembershipHelper.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/utils/InlineOrganizationProviderConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/utils/OrganizationProviderConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/IdentityProviderManagerTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/DefaultOrganizationUpgraderTest.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/RoleRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcRoleRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/spring/role/SpringRoleRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoRoleRepository.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/RoleRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/RoleService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/RoleServiceImpl.java

feat: add inline provider in gravitee.yaml for Management API

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java
gravitee-am-model/src/main/java/io/gravitee/am/model/login/WebAuthnSettings.java
gravitee-am-ui/src/app/domain/settings/webauthn/webauthn.component.html

fix(webauthn): do not remove credentials based on AAGUID

---

gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts

fix(application): do not uppercase the application type after a save

---

gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/oauth2.component.ts

fix(customClaims): correctly map table between view and component

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/AbstractDomainResource.java

fix(domains): add created_at and updated_at fields for domains resource

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java

fix: assign tableSuffix variable with transformed domain to avoid NPE

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java

fix: assign tableSuffix variable with transformed domain

---

gravitee-am-resource/gravitee-am-resource-infobip/README.md
gravitee-am-resource/gravitee-am-resource-infobip/pom.xml
gravitee-am-resource/gravitee-am-resource-infobip/src/main/assembly/plugin-assembly.xml
gravitee-am-resource/gravitee-am-resource-infobip/src/main/java/io/gravitee/am/resource/infobip/InfobipResource.java
gravitee-am-resource/gravitee-am-resource-infobip/src/main/java/io/gravitee/am/resource/infobip/InfobipResourceConfiguration.java
gravitee-am-resource/gravitee-am-resource-infobip/src/main/java/io/gravitee/am/resource/infobip/provider/InfobipResourceProvider.java
gravitee-am-resource/gravitee-am-resource-infobip/src/main/resources/plugin.properties
gravitee-am-resource/gravitee-am-resource-infobip/src/main/resources/schemas/schema-form.json
gravitee-am-resource/pom.xml

Hi! I created this plugin to make it possible to use the 2FA with SMS service from [Infobip](https://www.infobip.com/). The plugin was created using [the Infobip SDK](https://github.com/infobip/infobip-api-java-client) and I used the Twilio plugin as a reference.

feat: Infobip plugin

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java

fix: return 401 if user isn't authenticated on MFA step

---

gravitee-am-ui/src/app/domain/settings/audits/settings/reporter/reporter.component.ts
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts

fix(users): page not found after user deletion

---

.circleci/config.yml

closes gravitee-io/issues#5773

chore(ee): add AE connector to the AM EE distribution

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FlowServiceImpl.java

fix: test if flow type is null for an update

---

gravitee-am-ui/src/app/domain/components/memberships/memberships.component.ts

fix: add 'q' query parameter on membership search

---

.circleci/config.yml

chore: enable postman tests on CircleCI

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/audit/impl/AuditReporterManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/AuditReporterManagerImpl.java

feat: improve the reporter loading

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSocialAuthenticationHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html
gravitee-am-model/src/main/java/io/gravitee/am/model/login/LoginSettings.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/LoginSettingsMongo.java
gravitee-am-ui/src/app/domain/components/login/login-settings.component.html
gravitee-am-ui/src/app/domain/components/login/login-settings.component.ts

feat: hide login form and redirect to single OIDC if any

---

gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/server/ManagementApiServer.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

feat: make management endpoint configurable

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java

fix: use mongo uri if available to create IDP configuration

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/ManagementRepositoryConfiguration.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/oauth2/OAuth2RepositoryConfiguration.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/utils/BackendConfigurationUtils.java

fix: initialize DBName from URI if available

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/handler/CustomLogoutSuccessHandler.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java

feat: trace organization logout in the Organization AuditReporter

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/code/AuthorizationCodeTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/refresh/RefreshTokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/uma/UMATokenGranter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/granter/uma/UmaTokenGranterTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/AuthenticationProvider.java

feat(oauth2): add more context for the refresh token flow

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/OIDCProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpointHandlerTest.java

fix(userinfo): add user group roles

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseIdTokenHintHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
postman/collections/graviteeio-am-openid-core-collection-app-version.json

closes gravitee-io/issues#5840

feat(oidc): handle id_token_hint parameter to silently sign in users

---

gravitee-am-ui/src/app/domain/settings/users/users.component.html
gravitee-am-ui/src/app/domain/settings/users/users.component.scss
gravitee-am-ui/src/app/domain/settings/users/users.component.ts

closes gravitee-io/issues#5837

feat(ui): improve UX for users advanced search

---

gravitee-am-identityprovider/gravitee-am-identityprovider-gravitee/src/main/java/io/gravitee/am/identityprovider/gravitee/authentication/GraviteeAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-gravitee/src/main/java/io/gravitee/am/identityprovider/gravitee/user/GraviteeUserProvider.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java

fix(org): set missing id and external id for organization users

---

.circleci/config.yml

chore: deploy AM with PSQL on nigthly

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_10_0/users-migration.yml

fix: create specific queries for SQLServer

---

gravitee-am-identityprovider/gravitee-am-identityprovider-inline/src/main/java/io/gravitee/am/identityprovider/inline/authentication/InlineAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java

fix: avoid execution of UserMapper if the map is empty

---

gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/tokens/application-tokens.component.ts

fix: initialize tokenCustomClaims array to avoid NPE

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java

fix(users): update user during forgot password operation

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/auth/UserAuthenticationManagerTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProviderTest.java

fix(users): do not create user after brute force detection if user does not exist

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/password/ForgotPasswordSubmissionRequestParseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html

fix: enable submit button even if there are no password settings

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/service/user/UserServiceTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/DefaultUser.java

fix(users): do not duplicate users during forgot password

---

gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/authentication/HttpAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/configuration/HttpAuthResourcePathsConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/configuration/HttpResourceConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/resources/schemas/schema-form.json

fix(passwordless): make HTTP IdP compatible with passwordless

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/AbstractDomainResource.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Domain.java
gravitee-am-model/src/main/java/io/gravitee/am/model/SelfServiceAccountManagementSettings.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcDomain.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/mapper/SelfServiceAccountManagementSettingsConverter.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/dozer.xml
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_10_0/schema-add-self-service-account-settings.yml
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoDomainRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/DomainMongo.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/SelfServiceAccountManagementSettingsMongo.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DomainRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchDomain.java
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/settings/self-service-account/self-service-account.component.html
gravitee-am-ui/src/app/domain/settings/self-service-account/self-service-account.component.ts
gravitee-am-ui/src/app/services/domain.service.ts

closes gravitee-io/issues#5854

feat(account): create self service account management configuration

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/provider/UserProperties.java

fix: define source as UserProperties attribute

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAEnrollEndpoint.java

fix: set right MFA channel type for phone enrollement

---

gravitee-am-ui/src/app/domain/creation/domain-creation.component.html
gravitee-am-ui/src/app/domain/creation/domain-creation.component.ts
gravitee-am-ui/src/app/domain/settings/general/general.component.html
gravitee-am-ui/src/app/domain/settings/general/general.component.ts

closes gravitee-io/issues#5920

feat(domains): UI - add loader when creating or deleting a security domain

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseIdTokenHintHandler.java
gravitee-am-model/src/main/java/io/gravitee/am/model/application/ApplicationOAuthSettings.java
gravitee-am-model/src/main/java/io/gravitee/am/model/oidc/Client.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoApplicationRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/ApplicationOAuthSettingsMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchApplicationOAuthSettings.java
gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/general/general.component.ts
postman/collections/graviteeio-am-openid-core-collection-app-version.json

closes gravitee-io/issues#5924

feat(app): add option to enable/disable silent re-authentication feature

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/ClientServiceImpl.java

fix: initialize tls parameters for application mtls auth

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-ui/src/app/domain/applications/application/advanced/oauth2/grantFlows/application-grant-flows.component.ts

fix(app): send mtls information from the UI to the backend

---

gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/DefaultUser.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/authentication/HttpAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/HttpUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/resources/schemas/schema-form.json

closes gravitee-io/issues#5935

feat(idp): use enhance context to load pre-authenticated user for the HTTP IdP

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/granter/extensiongrant/ExtensionGrantGranter.java

closes gravitee-io/issues#5839

feat(webauthn): add more context to verify user identity

---

pom.xml

chore: update notifier api version

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java

fixes: gravitee-io/issues#6067

fix: test existence of user Factors

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/test/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProviderTest.java

fix(idp): do not hard code column name values

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/account/AccountResponseHandler.java
pom.xml

closes gravitee-io/issues#6078

chore(): bump tink version to remove org json dependency

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/ReactableExecutionContext.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/SimpleAuthenticationContext.java
pom.xml

Closes gravitee-io/issues#6051

fix(el): reintroduce request.method access

---

pom.xml

Closes gravitee-io/issues#5996

chore: Upgrade to gravitee-node to include missing dependencies

---

gravitee-am-service/src/main/java/io/gravitee/am/service/http/WebClientBuilder.java

Closes gravitee-io/issues#6032

fix(proxy): exclude query param to calculate host exclusions

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/handler/CustomRequestRejectedHandler.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java
pom.xml

fix: handle request rejected exception

---

pom.xml

fix: upgrade org.jsoup:jsoup from 1.13.1 to 1.14.2

---

pom.xml

fix: upgrade net.minidev:json-smart from 2.3 to 2.4.7

---

docker/compose/docker-compose.yml
docker/management-ui/Dockerfile
docker/management-ui/Dockerfile-dev
docker/management-ui/Dockerfile-nightly

fix: upgrade nginx from 1.19-alpine to 1.20-alpine (docker images)

---

postman/collections/graviteeio-am-openid-core-request-object-collection.json

fix: change the redirect_uri test on Request Object collection

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/discovery/impl/OpenIDDiscoveryServiceImpl.java

fix(oidc): re-introduce supported_subject_type field

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/JdbcAbstractProvider.java
pom.xml

Closes gravitee-io/issues#5966

fix(event): propagate node stop event when shutdown

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/AbstractUserService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateUser.java
gravitee-am-ui/src/app/domain/settings/users/user/profile/profile.component.ts
gravitee-am-ui/src/app/services/user.service.ts

fix(users): manage user display name

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/pom.xml

fix: upgrade com.unboundid:unboundid-ldapsdk from 4.0.4 to 6.0.1

---

gravitee-am-resource/gravitee-am-resource-twilio/src/main/java/io/gravitee/am/resource/twilio/TwilioVerifyResourceConfiguration.java
gravitee-am-resource/gravitee-am-resource-twilio/src/main/java/io/gravitee/am/resource/twilio/provider/TwilioVerifyResourceProvider.java
gravitee-am-resource/gravitee-am-resource-twilio/src/main/resources/schemas/schema-form.json

fix: manage proxy settings for twilio resource

---

gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/authentication/HttpAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/user/HttpUserProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-http/src/main/java/io/gravitee/am/identityprovider/http/utils/SanitizeUtils.java

fix(idp): sanitize credentials for HTTP IdP

---

gravitee-am-gateway/gravitee-am-gateway-certificate/src/test/java/io/gravitee/am/gateway/certificate/CertificateProviderManagerTest.java
gravitee-am-jwt/src/main/java/io/gravitee/am/jwt/DefaultJWTBuilder.java
gravitee-am-jwt/src/test/java/io/gravitee/am/jwt/DefaultJWTParserTest.java

closes gravitee-io/issues#6239

feat(jwt): add JWT typ header parameter

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java

fix(oauth2): add cors handler to OAuth 2.0 Authorization endpoint

---

gravitee-am-repository/gravitee-am-repository-jdbc/pom.xml
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/common/AbstractRepositoryConfiguration.java

fix(jdbc): upgrade liquibase to 4.4.3 to avoid exception with MySQL

---

gravitee-am-model/src/main/java/io/gravitee/am/model/PasswordSettings.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/internal/model/PasswordSettingsMongo.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewUser.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/PatchPasswordSettings.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/PasswordValidator.java
gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.html
gravitee-am-ui/src/app/domain/applications/application/advanced/password-policy/password-policy.component.ts
gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.html
gravitee-am-ui/src/app/domain/settings/password-policy/domain-password-policy.component.ts

closes gravitee-io/issues#6212

feat(password): add max password length control

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/manager/idp/IdentityProviderManager.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/manager/idp/impl/IdentityProviderManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/security/ManagementAuthenticationProvider.java

fix(org): only select organization idps during authentication

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/pom.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/pom.xml
pom.xml

closes gravitee-io/issues#6246

chore(): add latency policy to the default distribution

---

gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/JavaKeyStoreConfiguration.java
gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/java/io/gravitee/am/certificate/javakeystore/provider/JavaKeyStoreProvider.java
gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/resources/schemas/schema-form.json
gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/java/io/gravitee/am/certificate/pkcs12/PKCS12Configuration.java
gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/java/io/gravitee/am/certificate/pkcs12/provider/PKCS12Provider.java
gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/resources/schemas/schema-form.json
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/jwk/impl/JWKServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/CertificatesResource.java
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/resolvers/sign-certificates.resolver.spec.ts
gravitee-am-ui/src/app/resolvers/sign-certificates.resolver.ts
gravitee-am-ui/src/app/services/certificate.service.ts

feat: define the use attribute for JWK entity

---

docs/self-service-account-api-descriptor.yml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountWebAuthnCredentialsEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/util/AccountRoutes.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/AccountService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/store/RepositoryCredentialStore.java
gravitee-am-model/src/main/java/io/gravitee/am/model/Credential.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java

closes gravitee-io/issues#6247

feat(self-account): add webauthn credentials GET endpoints

---

pom.xml

fix(): remove test dependencies from distribution

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ApplicationScopeSettingsUpgrader.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/upgrades/ApplicationScopeSettingsUpgraderTest.java

fix: update application using the service to upgrade scopes

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieSessionHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/ParamUtils.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestParseParametersHandlerTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java

closes https://github.com/gravitee-io/issues/issues/6397
This PR enhances wildcard url for redirect_uri

feat: enhance wildcard url

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/utils/RequestUtils.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java

fix(oauth): better support of prompt login for external OIDC IdP

---

docs/self-service-account-api-descriptor.yml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/pom.xml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/AccountService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java
postman/collections/graviteeio-am-self-account-management-collection-app-version.json

feat: allow password update using SelfAccount API

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/pom.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/pom.xml

chore: add logback-json dependencies

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/utils/ConstantKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginCallbackEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginPostEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestParseParametersHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/AuthorizationEndpointTest.java

fix(oidc): handle prompt login callback properly

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
postman/collections/graviteeio-am-oauth2-par-version.json

fix: read oidc metadata on consent endpoint to allow par processing

---

gravitee-am-ui/src/app/domain/settings/audits/audits.component.ts
gravitee-am-ui/src/app/domain/settings/groups/group/members/members.component.ts

fix: add query parameter for search request on user resource

---

gravitee-am-common/src/main/java/io/gravitee/am/common/event/AlertEventKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/alert/AlertEventProcessor.java
gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java
gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/test/java/io/gravitee/am/gateway/services/sync/SyncManagerTest.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/node/GatewayNode.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/node/GatewayNodeMetadataResolver.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/test/java/io/gravitee/am/gateway/node/GatewayNodeMetadataResolverTest.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/test/resources/logback.xml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/node/ManagementNode.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/node/ManagementNodeMetadataResolver.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java
gravitee-am-model/pom.xml
gravitee-am-model/src/main/java/io/gravitee/am/model/Organization.java
pom.xml

Closes gravitee-io/issues#6118

feat(alert): add installation, env and org to event

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/exception/JWTOAuth2Exception.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/AuthorizationCodeResponse.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/HybridResponse.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/IDTokenResponse.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/ImplicitResponse.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/response/jwt/JWTAuthorizationResponse.java

fix: do not encode multiple time the query parameters

---

gravitee-am-repository/gravitee-am-repository-jdbc/pom.xml
gravitee-am-resource/gravitee-am-resource-twilio/pom.xml

chore: update apache commons-io to 2.11.0

---

gravitee-am-identityprovider/gravitee-am-identityprovider-ldap-common/src/main/java/io/gravitee/am/identityprovider/ldap/common/authentication/GroupSearchEntryHandler.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/LdapIdentityProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/LdapAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/java/io/gravitee/am/identityprovider/ldap/authentication/spring/LdapAuthenticationProviderConfiguration.java
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json

fix: look for all groups for a user (direct groups and ancestors)

---

docs/upgrades/3.x/3.6.0/mongodb/2-add-application-flow-permissions.js
docs/upgrades/3.x/3.6.0/mongodb/3-add-application-analytics-permissions.js
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_6_0/application-flow-permissions.yml
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_7_0/alert-notifiers-permissions.yml
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml

fixes: https://github.com/gravitee-io/issues/issues/6648
Check if the permissions are checked for owner roles

fix: missing management roles

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/AbstractUser.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcUser.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_10_10/schema-add-last-password-reset-date.yml
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java

fix(users): add missing last_password_reset field for the JDBC repository

---

gravitee-am-ui/src/app/domain/components/applications/select-applications.component.html
gravitee-am-ui/src/app/domain/components/applications/select-applications.component.ts

fix(ui): better UX for the select apps component

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/impl/IdentityProviderManagerTest.java

fix: read gravitee userProvider from the map of providers

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java

fix: apply a filter on technical claims during id_token generation

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider.java

fix(users): change JDBC user provider initialization phase to create users

---

pom.xml

chore: update cockpit connector to 2.0.1

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java

fix: inclue original parameters on the LoginCallbackFailure

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
postman/collections/graviteeio-am-oauth2-collection-app-version.json

closes: https://github.com/gravitee-io/issues/issues/6516
⚠️ This is a BREAKING CHANGE. openid may need to be associated with more scopes in the future

feat: scope openid should not be used to get full profile information

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/service/user/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java

fixes: https://github.com/gravitee-io/issues/issues/6688

fix: user password reset audit log

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
pom.xml

relates to: gravitee-io/issues#6227
related PR: https://github.com/gravitee-io/gravitee-service-geoip/pull/7

chore: geoip based configuration info added to gravitee.yml

---

gravitee-am-factor/gravitee-am-factor-api/src/main/java/io/gravitee/am/factor/api/FactorContext.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java

fix: filter technical claims from the user info response

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/forgot_password.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/registration_confirmation.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/reset_password.html

fix: execute inline JS inside document ready method

---

gravitee-am-ui/src/app/domain/settings/users/users.component.html

fix: allow to sort on users table columns

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/GraviteeWebAuthnOptions.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/WebAuthnFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/vertx/auth/webauthn/attestation/AttestationTest.java

fixes https://github.com/gravitee-io/issues/issues/6747

fix:Do not throw IllegalArgumentException if the a certificat is invaid for WebAuthn to allow domain startup

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/par/impl/PushedAuthorizationRequestServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/DynamicClientRegistrationResponse.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/ClientServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/clientregistration/impl/DynamicClientRegistrationServiceImpl.java
postman/collections/graviteeio-am-openid-dcr-collection-app-version.json

This PR fixes small issues on postman tests. The actual behaviour is not blocking the app to work on jdbc. It just stays consistent with the behaviour
fixes: https://github.com/gravitee-io/issues/issues/6755
fixes: https://github.com/gravitee-io/issues/issues/6759

fix: jdbc postman tests

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutCallbackEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java

fix: test existence of session before accessing to the client object

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ApplicationServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewApplication.java
postman/collections/graviteeio-am-client-management-collection-app-version.json

closes gravitee-io/issues#6774

feat(application): handle metadata during application creation

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html

fix: make JS function accessible

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html

fix: change JS to make SMS & EMAIL MFA work

---

.circleci/config.yml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/auth/user/User.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/dummies/DummyHttpRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/TokenEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-reactor/src/main/java/io/gravitee/am/gateway/reactor/impl/router/VHostRouter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java
gravitee-am-reporter/gravitee-am-reporter-jdbc/pom.xml
gravitee-am-repository/gravitee-am-repository-jdbc/pom.xml
pom.xml

closes: https://github.com/gravitee-io/issues/issues/6695
fixes: gravitee-io/issues#6696
~⚠️ This is still in draft.
⚠️ Do not merge until we have https://github.com/gravitee-io/gravitee-policy-groovy/pull/38 and https://github.com/gravitee-io/gravitee-service-geoip/pull/10 resolved~

chore: java 17 upgrade and vertx 4.2.3

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/pom.xml
gravitee-am-model/src/main/java/io/gravitee/am/model/safe/UserProperties.java
gravitee-am-reporter/gravitee-am-reporter-jdbc/pom.xml
gravitee-am-repository/gravitee-am-repository-jdbc/pom.xml
pom.xml

- This PR makes sur reactor netty 1.0.14 is dispatched correctly within the poms
- It also fixes an issue on jdbc during postman tests

chore(deps): reactor netty 1.0.14 accross pom.xml

---

pom.xml

fix(email): handle java mail properties

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/request/AuthorizationRequestFactory.java

fix(flow): handle PolicyChainException when it comes from the ALL flow

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-ldap/src/main/resources/schemas/schema-form.json
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/resources/schemas/schema-form.json
gravitee-am-reporter/gravitee-am-reporter-jdbc/src/main/resources/schemas/schema-form.json
gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/resources/schemas/schema-form.json
gravitee-am-resource/gravitee-am-resource-smtp/src/main/resources/schemas/schema-form.json

fix(plugins): unset non sensitive information

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcDeviceRepository.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/DeviceRepositoryTest.java

fixes: https://github.com/gravitee-io/issues/issues/6926

fix: expiration time checked for device for jdbc

---

docker/compose/docker-compose-dev.yml
docker/compose/docker-compose.yml
docker/gateway/Dockerfile
docker/gateway/Dockerfile-dev
docker/gateway/Dockerfile-nightly
docker/management-api/Dockerfile
docker/management-api/Dockerfile-dev
docker/management-api/Dockerfile-nightly

closes: https://github.com/gravitee-io/issues/issues/6853
still need to do them on https://github.com/gravitee-io/gravitee-docker

chore: docker images jre 17

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/main/java/io/gravitee/am/gateway/handler/scim/service/impl/UserServiceImpl.java

fixes: https://github.com/gravitee-io/issues/issues/6959

fix: do not remove staticly assigned role when updating SCIM

---

pom.xml

closes gravitee-io/issues#6984

chore(): upgrade gravitee-node to 1.18.3

---

gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-botdetection/src/main/java/io/gravitee/am/plugins/botdetection/plugin/BotDetectionPluginHandler.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-certificate/src/main/java/io/gravitee/am/plugins/certificate/plugin/CertificatePluginHandler.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-extensiongrant/src/main/java/io/gravitee/am/plugins/extensiongrant/plugin/ExtensionGrantPluginHandler.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-factor/src/main/java/io/gravitee/am/plugins/factor/plugin/FactorPluginHandler.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-identityprovider/src/main/java/io/gravitee/am/plugins/idp/plugin/IdentityProviderPluginHandler.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-protocol/src/main/java/io/gravitee/am/plugins/protocol/plugin/ProtocolPluginHandler.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-reporter/src/main/java/io/gravitee/am/plugins/reporter/plugin/ReporterPluginHandler.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-resource/src/main/java/io/gravitee/am/plugins/resource/plugin/ResourcePluginHandler.java

closes: https://github.com/gravitee-io/issues/issues/6985
This also has to be done on more recent plugins on other versions

chore: am plugin handlers extend AbstractPluginHandler

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderServiceProxyImpl.java
gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts

fix(management): allow missing users into inline-idp configuration

---

gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CommonUserRepository.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/OrganizationUserRepository.java
gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/UserRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcOrganizationUserRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcUserRepository.java
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/AbstractUserRepository.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/OrganizationUserRepositoryTest.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/UserRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/UserService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/DomainServiceTest.java

fix(delete): better manage users deletion during domain removal

---

gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/components/json-schema-form/material-certificate-component.ts
gravitee-am-ui/src/app/domain/settings/providers/creation/steps/step2/step2.component.ts
gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.html
gravitee-am-ui/src/app/domain/settings/providers/provider/form/form.component.ts
gravitee-am-ui/src/app/domain/settings/providers/provider/settings/settings.component.ts

closes: https://github.com/gravitee-io/issues/issues/6835
linked PR: https://github.com/gravitee-io/gravitee-am-identityprovider-saml/pull/24

feat: handle certificate for SAML assertion encryption

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginHideFormHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/identifier_first_login.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpointHandlerTest.java
gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html
postman/collections/graviteeio-am-login-collection-app-version.json

Also add the minimal template example for IDENTIFIER_FIRST_LOGIN
fixes gravitee-io/issues#6975

fix(login): rewrite IdentifierFirstLogin step to better manage request parameters

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/spring/StandaloneConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-container/src/main/java/io/gravitee/am/management/standalone/spring/StandaloneConfiguration.java
pom.xml

fixes gravitee-io/issues#7020
To validate with caution as we jump 2 version of gravitee-node.
Tests I have done:
* Create domain (with Mongo) with a user and an app + connect the user 
* postman run on AM started with my IDE
* postman run on AM started with docker dev images

chore: upgrade to gravitee-node 1.20

---

gravitee-am-model/src/main/java/io/gravitee/am/model/account/AccountSettings.java

fix: preserve defaultIdp for registration

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/web/WebConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/CookieHandler.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml

fix: make configurable the Cookie SameSite attribute

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/IdentityProviderManagerImpl.java

fix: try to load UserProvider if the id is missing from the map

---

gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/ScheduledSyncService.java
gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/SyncManager.java
gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/healthcheck/SyncProbe.java
gravitee-am-gateway/gravitee-am-gateway-services/gravitee-am-gateway-services-sync/src/main/java/io/gravitee/am/gateway/services/sync/spring/SyncConfiguration.java

feat(healthcheck): add sync probe to know if the gateway is ready to accept calls

---

pom.xml

chore: upgrade to gravitee-node 1.20.1

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/identifierfirst/IdentifierFirstLoginEndpoint.java

fix: escape email address before use it as login_hint

---

pom.xml

chore: upgrade vertx from 4.2.3 to 4.2.4

---

gravitee-am-reporter/gravitee-am-reporter-jdbc/pom.xml
gravitee-am-repository/gravitee-am-repository-jdbc/pom.xml
pom.xml

chore: upgrade spring from 5.3.13 to 5.3.15

---

gravitee-am-ui/src/app/domain/settings/providers/providers.component.html
gravitee-am-ui/src/app/domain/settings/providers/providers.component.scss

fix(ui): fix idp icon alignment

---

gravitee-am-repository/gravitee-am-repository-api/src/main/java/io/gravitee/am/repository/management/api/CredentialRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcCredentialRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_10_14/schema-add-webauthn-idx.yml
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/master.yml
gravitee-am-repository/gravitee-am-repository-mongodb/src/main/java/io/gravitee/am/repository/mongodb/management/MongoCredentialRepository.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/CredentialRepositoryTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/CredentialService.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CredentialServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java

fix(domain): be sure to remove webauthn credentials when deleting a domain

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/impl/FlowManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/PolicyChainHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/uma/policy/DefaultRulesEngine.java
gravitee-am-gateway/gravitee-am-gateway-policy/src/main/java/io/gravitee/am/gateway/policy/Policy.java
gravitee-am-gateway/gravitee-am-gateway-policy/src/main/java/io/gravitee/am/gateway/policy/PolicyMetadata.java
gravitee-am-gateway/gravitee-am-gateway-policy/src/main/java/io/gravitee/am/gateway/policy/impl/PolicyImpl.java
gravitee-am-gateway/gravitee-am-gateway-policy/src/main/java/io/gravitee/am/gateway/policy/impl/PolicyMetadataBuilder.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-policy/src/main/java/io/gravitee/am/plugins/policy/core/impl/PolicyContextFactory.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-policy/src/main/java/io/gravitee/am/plugins/policy/core/impl/PolicyPluginManagerImpl.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-policy/src/main/java/io/gravitee/am/plugins/policy/core/impl/SpringPolicyContextProvider.java

fixes https://github.com/gravitee-io/issues/issues/6942

fix: Plugin initializers onActivate onDeactivate

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/web/WebConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSPHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CSPHandlerFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/csp/CspHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/csp/NoOpCspHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/OAuth2Provider.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml

closes: https://github.com/gravitee-io/issues/issues/6716
Example of CSP configuration in `gravitee.yml`
Please suggest in terms of gateway url endpoint. I've put them all but we might not need them everywhere

feat: content security policy

---

gravitee-am-ui/src/app/services/role.service.ts

fix: make pagination of findAll role works

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpointHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenServiceTest.java

fix: do not provide the sub claim coming from the IDP

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/IdentityProvidersResource.java

fixes: https://github.com/gravitee-io/issues/issues/7119

fix: set correct boolean external value

---

gravitee-am-ui/src/app/domain/applications/application/idp/idp.component.html

fixes: https://github.com/gravitee-io/issues/issues/7124

fix: logos for social/enterprise providers in application identities

---

.gitignore
gravitee-am-cypress/LICENSE_TEMPLATE.txt
gravitee-am-cypress/cypress.json
gravitee-am-cypress/cypress/fixtures/elemets/login-page-elements.ts
gravitee-am-cypress/cypress/fixtures/users.ts
gravitee-am-cypress/cypress/integration/login-ui-test.ts
gravitee-am-cypress/cypress/model/users.ts
gravitee-am-cypress/cypress/plugins/index.js
gravitee-am-cypress/cypress/support/commands.js
gravitee-am-cypress/cypress/support/index.ts
gravitee-am-cypress/cypress/tsconfig.json
gravitee-am-cypress/license-check-config.json
gravitee-am-cypress/package-lock.json
gravitee-am-cypress/package.json
pom.xml

This branch includes cypress ui tests POC:
- Cypress setup 
- Login ui test

test: cypress setup and add login ui test

---

gravitee-am-reporter/gravitee-am-reporter-mongodb/src/main/java/io/gravitee/am/reporter/mongodb/audit/MongoAuditReporter.java

fix(reporter): rewrite index names to avoid size limit error

---

pom.xml

fix(notifier): upgrade email notifier to manage sensitive data filtering

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/login/LoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html

fix: fill username login field if login_hint parameter is available

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFailureHandler.java

fix: escape special characters on login failure for the login_hint

---

gravitee-am-model/src/main/java/io/gravitee/am/model/flow/Step.java
gravitee-am-ui/package-lock.json
gravitee-am-ui/package.json
gravitee-am-ui/src/main.ts

fixes: https://github.com/gravitee-io/issues/issues/7193

chore: upgrade and adapt policy studio

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/CorsHandlerFactory.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/spring/security/SecurityConfiguration.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

closes: https://github.com/gravitee-io/issues/issues/7221

feat: allow credentials in CORS configuration

---

gravitee-am-common/src/main/java/io/gravitee/am/common/policy/ExtensionPoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/impl/FlowManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-model/src/main/java/io/gravitee/am/model/flow/Type.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FlowServiceImpl.java
gravitee-am-service/src/main/resources/flow/am-schema.json
gravitee-am-service/src/test/java/io/gravitee/am/service/FlowServiceTest.java

closes: https://github.com/gravitee-io/issues/issues/7015
⚠️ Make sur to configure your SMTP on the gateway first 
1. Create a Policy flow (either at domain or application level)
2. Activate `Forgot Password` in your Login Settings
3. Initiate the login flow and reset the password
4. Verify the effects of your policies being applied before and after the reset password page (Latency should add latency, Http callout make the call, etc ...)

feat:reset password policy flow

---

docs/self-service-account-api-descriptor.yml
gravitee-am-factor/gravitee-am-factor-recovery-code/src/main/java/io/gravitee/am/factor/recovery/code/provider/RecoveryCodeFactorProvider.java
gravitee-am-factor/gravitee-am-factor-recovery-code/src/main/resources/schemas/schema-form.json
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/util/AccountRoutes.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/test/java/io/gravitee/am/gateway/handler/account/resources/AccountFactorsEndpointHandlerTest.java
postman/collections/graviteeio-am-self-account-management-collection-app-version.json

A new endpoint 'api/recovery_code' added to fetch user recoery code.
Also removed recovery codes from user factor list.
Relates to: https://github.com/gravitee-io/issues/issues/7147

feat(recovery-code): recovery code endpoint implemented

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/ExecutionPredicate.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/FlowManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/execution/ExecutionFlow.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/flow/impl/FlowManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/PolicyChainHandlerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/flow/FlowManagerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/flow/FlowPredicateTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/PolicyChainHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/uma/policy/DefaultRulesEngine.java
gravitee-am-gateway/gravitee-am-gateway-policy/src/main/java/io/gravitee/am/gateway/policy/Policy.java
gravitee-am-gateway/gravitee-am-gateway-policy/src/main/java/io/gravitee/am/gateway/policy/impl/PolicyChain.java
gravitee-am-gateway/gravitee-am-gateway-policy/src/main/java/io/gravitee/am/gateway/policy/impl/PolicyImpl.java
gravitee-am-model/src/main/java/io/gravitee/am/model/flow/Step.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-policy/src/main/java/io/gravitee/am/plugins/policy/core/PolicyPluginManager.java
gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-policy/src/main/java/io/gravitee/am/plugins/policy/core/impl/PolicyPluginManagerImpl.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcFlowRepository.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/model/JdbcFlow.java
gravitee-am-repository/gravitee-am-repository-jdbc/src/main/resources/liquibase/changelogs/v3_17_0/schema.yml
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/FlowRepositoryTest.java
gravitee-am-ui/src/app/domain/applications/application/design/flows/flows.component.html
gravitee-am-ui/src/app/domain/settings/flows/flows.component.html
postman/collections/graviteeio-am-flows-collection-app-version.json

closes: https://github.com/gravitee-io/issues/issues/7016
1. Create a Policy flow (either at domain or application level) to allow a validation of Conditional policy (see below)
Reverse the condition in the condition of the step to be able to assert the use

feat: conditional policies on flow steps

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/AbstractLogoutEndpoint.java

fix: manage invalidate_tokens parameter with SingleSignout enabled

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnResponseEndpoint.java

fixes: https://github.com/gravitee-io/issues/issues/7262

fix(webauthn): added user login status in the session

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-scim/src/test/java/io/gravitee/am/gateway/handler/scim/service/UserServiceTest.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UsersResourceTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/UserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/OrganizationUserServiceTest.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/UserServiceTest.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-service/src/main/java/io/gravitee/am/service/model/NewUser.java
gravitee-am-service/src/main/java/io/gravitee/am/service/model/UpdateUser.java
gravitee-am-service/src/main/java/io/gravitee/am/service/validators/email/EmailValidatorImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/OrganizationUserServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/UserServiceTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/EmailValidatorTest.java
gravitee-am-service/src/test/java/io/gravitee/am/service/validators/UserValidatorTest.java

fixes: https://github.com/gravitee-io/issues/issues/7289

fix: allow user email policy pattern in configuration

---

gravitee-am-service/src/main/java/io/gravitee/am/service/validators/email/EmailValidatorImpl.java
postman/collections/graviteeio-am-user-management-collection-app-version.json

relates to: https://github.com/gravitee-io/gravitee-access-management/pull/1725

fix: email validation message in postman tests

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/DomainNotifierService.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/CertificateManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/DomainNotifierServiceImpl.java

fix: avoid blockingAwait on deleteCertificateExpiryAcknowledge

---

gravitee-am-ui/src/app/domain/applications/application/idp/idp.component.html
gravitee-am-ui/src/app/domain/applications/application/idp/idp.component.scss
gravitee-am-ui/src/app/domain/applications/application/idp/idp.component.ts

related to: https://github.com/gravitee-io/issues/issues/7286

refactor: ux/ui on identity provider priority

---

gravitee-am-repository/gravitee-am-repository-jdbc/src/main/java/io/gravitee/am/repository/jdbc/management/api/JdbcFlowRepository.java
gravitee-am-repository/gravitee-am-repository-tests/src/test/java/io/gravitee/am/repository/management/api/FlowRepositoryTest.java

fix: manage condition of JDBC Step entity

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java

fix: test if loginSettings is null into the LoginCallbackFailureHandler

---

gravitee-am-ui/src/app/domain/applications/application/idp/selection-rule/create/create.component.html

fixes: https://github.com/gravitee-io/issues/issues/7357

fix: typo on selection rule modal

---

pom.xml

related-to gravitee-io/issues#6833

chore: upgrade gravitee-node to final 1.21.0

---

.circleci/config.yml

related to gravitee-io/issues#7380

chore: upgrade keeper orb to avoid issue on git chekout

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/OIDCProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/impl/IDTokenServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/resources/endpoint/UserInfoEndpointHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oidc/service/idtoken/IDTokenServiceTest.java

fix: provide new setting to restore legacy behaviour of openid scope

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/model/UserEntity.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/UserResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/UserResourceTest.java

feat: provide the sourceId in to user entity

---

.circleci/workflows.yml

related to https://github.com/gravitee-io/issues/issues/7337

chore: move postman test into PR workflow

---

.circleci/workflows.yml

Updated snyk scan job with slack notification to notify scan result. Also used command sets to reuse the commands in all 3 image scan steps
Thanks
Sakthi

chore: snyk scan result notification to slack

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/filter/JWTAuthenticationFilter.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/handler/CustomLogoutSuccessHandler.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/OrganizationUserService.java
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/OrganizationUserServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-service/src/test/java/io/gravitee/am/management/service/OrganizationUserServiceTest.java

fix(management): invalidate session on REST API after user logout

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/ReporterServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/ReporterServiceTest.java

fix: add reporter filename validation into the service layer

---

gravitee-am-factor/gravitee-am-factor-email/src/main/java/io/gravitee/am/factor/email/provider/EmailFactorProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

fix: update default settings for reset password token and email mfa code

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/CIBAProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestParametersHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/ciba/resources/handler/AuthenticationRequestParametersHandlerTest.java

fix: initialize scopeManager for CIBA scope resolver (UAT issue)

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/utils/ColumnMapRowMapper.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java

fixes: https://github.com/gravitee-io/issues/issues/7488

fix: NPE when username jdbc is null

---

pom.xml

fixes: https://github.com/gravitee-io/issues/issues/7479

chore: bump gravitee node for jetty configuration

---

gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/test/java/io/gravitee/am/identityprovider/mongo/authentication/EmbeddedClient.java
pom.xml

linked to [#7500](https://github.com/gravitee-io/issues/issues/7500)
simply update embed mongodb fix the issue.
Embed mongodb API have changed I simply rewrite the EmbeddedClient to use the new API

#7500 update de.flapdoodle.embed.mongo to 3.4.5

---

README.adoc
gravitee-am-common/src/main/java/io/gravitee/am/common/factor/FactorType.java
gravitee-am-common/src/test/java/io/gravitee/am/common/factor/FactorTypeTest.java
gravitee-am-factor/gravitee-am-factor-sms/src/main/java/io/gravitee/am/factor/sms/SMSFactorConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_enroll.html
gravitee-am-model/src/main/java/io/gravitee/am/model/factor/EnrolledFactorChannel.java
gravitee-am-resource/gravitee-am-resource-api/src/main/java/io/gravitee/am/resource/api/mfa/MFAType.java
gravitee-am-resource/gravitee-am-resource-mfa-mock/src/main/resources/plugin.properties
gravitee-am-ui/src/app/domain/applications/application/advanced/factors/factors.component.ts
gravitee-am-ui/src/app/domain/settings/factors/creation/steps/step1/step1.component.ts
gravitee-am-ui/src/app/domain/settings/factors/factors.component.ts

fixes gravitee-io/issues#7517. 
This work allows the [HTTP factor plugin](https://github.com/gravitee-io/gravitee-am-factor-http/pull/2) to work with AM.

feat: MFA factor for HTTP.

---

gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/AbstractCertificateProvider.java
gravitee-am-certificate/gravitee-am-certificate-api/src/main/java/io/gravitee/am/certificate/api/CertificateFormat.java
gravitee-am-certificate/gravitee-am-certificate-javakeystore/src/main/resources/schemas/schema-form.json
gravitee-am-certificate/gravitee-am-certificate-pkcs12/src/main/resources/schemas/schema-form.json
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oidc/service/utils/JWAlgorithmUtils.java
gravitee-am-jwt/src/main/java/io/gravitee/am/jwt/DefaultJWTBuilder.java
gravitee-am-jwt/src/main/java/io/gravitee/am/jwt/DefaultJWTParser.java
gravitee-am-jwt/src/test/java/io/gravitee/am/jwt/DefaultJWTParserTest.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/CertificateServiceImpl.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/DomainServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/CertificateServiceTest.java
gravitee-am-ui/src/app/domain/creation/domain-creation.component.ts

feat: support ECDSA JWT signing.

---

pom.xml

fixes: https://github.com/gravitee-io/issues/issues/7561

chore: upgrade gravitee-bom to 2.4 + spring 5.3.18

---

.circleci/workflows.yml

chore: updated snyk with application scan
https://app.zenhub.com/workspaces/graviteeio---access-management-5b17f74af58c642fb89cc49f/issues/gravitee-io/issues/7541
Added application scan for scanning app paths in the docker image

chore: updated snyk with application scan

---

gravitee-am-reporter/gravitee-am-reporter-kafka/src/main/java/io/gravitee/am/reporter/kafka/audit/KafkaAuditReporter.java

I have no Github issue linked to this PR. But I have a zeendesk ticket [#4091](https://graviteesource.zendesk.com/hc/en-us/requests/4091)

[AM] - Swap classpath to allow Jaas to discover Kafka login module with SPI

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-policy/gravitee-am-policy-send-email/src/test/java/io/gravitee/am/policy/send/email/SendEmailPolicyTest.java

fix: add failure handler for ResetPassword endpoint

---

.circleci/workflows.yml
gravitee-am-ui/pom.xml
gravitee-am-ui/sonar-project.properties
sonar-project.properties

relates to: https://github.com/gravitee-io/issues/issues/7590

chore: sonarcloud on frontend

---

gravitee-am-ui/src/app/domain/components/role-selection/role-selection.component.html
gravitee-am-ui/src/app/domain/components/role-selection/role-selection.component.ts

The autocomplete feature when assigning a role to a user is not working as expected.
Add autocomplete feature to user input.
Issue [#7542](https://github.com/gravitee-io/issues/issues/7542)

fix: assign roles to user list no getting filtered

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestEndUserConsentHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/AuthorizationRequestEndUserConsentHandlerTest.java
postman/collections/graviteeio-am-oauth2-collection-app-version.json

fix(oauth2): throw interaction_required error when user consent is required and prompt=none

---

gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/upgrades/ApplicationIdentityProviderUpgrader.java

https://github.com/gravitee-io/issues/issues/7730
The change is to remove the `blockingGet` from the identityProvider.
- Create a few domains, Apps and Idps and run the upgrade on 3.17.x

fix: application identity provider upgrader blocked on ONGOING

---

gravitee-am-factor/gravitee-am-factor-email/src/main/java/io/gravitee/am/factor/email/provider/EmailFactorProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAChallengeStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFAEnrollStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MfaFilterContext.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/chain/MfaFilterChain.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/AdaptiveMfaFilter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/EndUserEnrolledFilter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaSkipFilter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/MfaSkipUserStronglyAuthFilter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/RememberDeviceFilter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/filter/StepUpAuthenticationFilter.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/UserServiceImpl.java

fixes: https://github.com/gravitee-io/issues/issues/7394

fix: skipable enroll when adaptive MFA is active and no factor enrolled

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java

fix(gateway): append client_id in URL generated for email template

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/AbstractLogoutEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/LogoutEndpointHandlerTest.java

fix(logout): manage GET method for the single logout feature

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ResetPasswordEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/register/RegisterConfirmationEndpoint.java

fix: add client_id in resetPassword and registerConfirmation url

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginCredentialsEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterCredentialsEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnResponseEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-login-v2.js
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn-register-v2.js
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/assets/js/webauthn.auth-v2.js
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_login.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_register.html

fix(passwordless): create new webauthn implementation to fix mobile app redirection

---

CHANGELOG-v3.adoc

PR to update the changelog file for AM 3.10.19 waiting APIM team fix the changelog generation in the CI

Generate changelog for version AM - 3.10.19

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/TagServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/TagServiceTest.java

fix: initialize organizationId on sharding tag update

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/user/JdbcUserProvider.java

fix(idp): map email field for the JDBC IdP

---

CHANGELOG-v3.adoc

https://github.com/gravitee-io/issues/milestone/551
This PR brings the changelog of v3.15.9

Generate changelog for version AM - 3.15.9

---

CHANGELOG-v3.adoc

This PR brings the changelog for version 3.17.2

Generate changelog for version 3.17.2

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/provider/ClientBasicAuthProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/resources/auth/provider/ClientBasicAuthProviderTest.java
gravitee-am-ui/src/app/domain/applications/application/overview/overview.component.ts

fix: URLDecode client credentials when client_secret_basic is used

---

docs/self-service-account-api-descriptor.yml
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/AccountProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountConsentEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/util/AccountRoutes.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/AccountService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/services/impl/AccountServiceImpl.java

closes gravitee-io/issues#7680

feat(account): manage user consent from the self account service API

---

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/UserAuthenticationService.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginCredentialsEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnLoginPostEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterCredentialsEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterPostEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnResponseHandler.java

closes gravitee-io/issues#5363

feat(passworless) : allow passwordless for external users

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/internal/mfa/MFARecoveryCodeStep.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/AuthenticationFlowHandlerTest.java

https://github.com/gravitee-io/issues/issues/7872
This PR fixes the error 500 brought on MFA recovery code when it is disabled on application but the end users has an active factor
Check the scenario in the issue above ⬆️ 
@ashraf706 reproduced the issue

fix: MFA recovery error 500 when disabled on app but present in user

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/mfa_challenge_alternatives.html

fix(mfa): add default text description for HTTP Factor in the MFA alternatives page

---

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/RootProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/webauthn/WebAuthnRegisterEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnLoginHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnRegisterHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnResponseHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/endpoint/authorization/AuthorizationEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/AuthorizationRequestFailureHandler.java

1. added missing 'factormanager' in the constructor
2. changed ctx.next() call as necessary
3. removed PASSWORDLESS_CHALLENGE_USER_ID as no longer used

fix(uat): FIDO2 factor enroll step fixed

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/impl/RedirectHandlerImpl.java

fixes gravitee-io/issues#7889
:warning: during the review please evaluate the non regression on this one https://github.com/gravitee-io/issues/issues/7030 by testing a redirect to Azure IDP

fix: encode properly email address with alias notation for idfirst login

---

gravitee-am-ui/package-lock.json
gravitee-am-ui/package.json

chore(ui): upgrade ui-components dependency

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-account/src/main/java/io/gravitee/am/gateway/handler/account/resources/AccountEndpointHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/web/auth/provider/impl/UserAuthProviderImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/auth/provider/SocialAuthenticationProvider.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/logout/AbstractLogoutEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginFormHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginNegotiateAuthenticationHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/UserRequestHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/activity/UserActivityHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/user/register/RegisterProcessHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/webauthn/WebAuthnHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/endpoint/user/password/ForgotPasswordSubmissionEndpointTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/handler/authorization/consent/UserConsentProcessHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-users/src/main/java/io/gravitee/am/gateway/handler/users/resources/consents/AbstractUserConsentEndpointHandler.java
gravitee-am-service/src/main/java/io/gravitee/am/service/impl/user/activity/utils/ConsentUtils.java

https://github.com/gravitee-io/issues/issues/7919
This PR makes more check of IP and user agent in handlers

fix: more ip and user agent consent check in handlers

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/auth/user/impl/UserAuthenticationManagerImpl.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/platform/plugins/FactorPluginResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/JerseySpringTest.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/platform/plugins/FactorPluginResourceTest.java

fix: do not reject the FactorPlugin schema if plugin isn't installed

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/login.html
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/resources/webroot/views/webauthn_login.html
gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/intelligent/mfa-intelligent.component.ts
gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts
gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html

https://github.com/gravitee-io/issues/issues/7552
This PR rebrands Intelligent Adaptive Access to Risk-based MFA.
It also removes the consent checkboxes from the default template and moves them to the template examples in the form design

refactor: rebranding Intelligent Adaptive Access to Risk-based MFA

---

gravitee-am-ui/src/app/domain/applications/application/design/forms/forms.component.ts
gravitee-am-ui/src/app/domain/settings/forms/forms.component.ts

fix: Alway enable form template form forgot password and registration

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/spring/RiskAssessmentConfiguration.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/config/gravitee.yml
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/config/gravitee.yml

https://github.com/gravitee-io/issues/issues/7638
This PR fixes a few commented configuration mistakes not to confuse the administrator

chore: gravitee.yml risk assessment configuration nitpicks

---

gravitee-am-ui/src/app/domain/components/forms/form/dialog/form-info.component.html

closes gravitee-io/issues#7939

fix(webauthn): update default templates in the console ui

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeFailureHandler.java

fix: avoid NPE on MFAChallengeFailureHandler

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FlowServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/FlowServiceTest.java

fix: load all flows on domain and application level

---

gravitee-am-service/src/main/java/io/gravitee/am/service/impl/FlowServiceImpl.java
gravitee-am-service/src/test/java/io/gravitee/am/service/FlowServiceTest.java

fix: load all flows on domain and application level (backport 7964)

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeAlternativesEndpoint.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/endpoint/mfa/MFAChallengeEndpoint.java

This fix considers client MFAs and user registered MFAs for showing alternative link in MFA challenge step.
The issue 7928 contains steps to reproduce the problem. This fix makes sure that
1. Alternative MFAa links won't show if client has maximum 1 enabled MFA or or user has maximum 1 enrolled factor.
2. This fix also make sure that options in alternative MFAs are enrolled by the user and also enabled in the client.

 fix: inaccurate factor choice

---

gravitee-am-ui/src/app/domain/applications/application/advanced/factors/mfa-activate/mfa-activate.component.ts

https://github.com/gravitee-io/issues/issues/7689
Adds a warning message to use Risk-based MFA

fix: display warning message for Risk-based MFA

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/factor/FactorManager.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/factor/impl/FactorManagerImpl.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/factor/FactorManagerTest.java
gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/main/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicy.java
gravitee-am-policy/gravitee-am-policy-enroll-mfa/src/test/java/io/gravitee/am/policy/enroll/mfa/EnrollMfaPolicyTest.java

fix: in EnrollMFA policy, test if factor is active for the app

---

gravitee-am-ui/src/app/domain/applications/application/design/flows/flows.component.ts
gravitee-am-ui/src/app/domain/settings/flows/flows.component.ts

fix(policies): add default value for the enroll mfa policy to enable saving

---

CHANGELOG-v3.adoc

Generate changelog for version AM - 3.17.3

Changelog for AM - 3.17.3

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/provider/generator/JWTGenerator.java

fix: limit user information into the Management API cookie

---

gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-container/src/main/java/io/gravitee/am/gateway/node/GatewayNodeMetadataResolver.java

fix: avoid NullPointer when installation doesn't exist

---

gravitee-am-identityprovider/gravitee-am-identityprovider-jdbc/src/main/java/io/gravitee/am/identityprovider/jdbc/authentication/JdbcAuthenticationProvider.java
gravitee-am-identityprovider/gravitee-am-identityprovider-mongo/src/main/java/io/gravitee/am/identityprovider/mongo/authentication/MongoAuthenticationProvider.java

fix: do not remove the sub entry if sub is the identifier field

---

gravitee-am-plugins-handlers/gravitee-am-plugins-handlers-extensiongrant/src/main/java/io/gravitee/am/plugins/extensiongrant/core/ExtensionGrantPluginManager.java

fix: avoid NullPointerException during ExtensionGrant creation

---

gravitee-am-ui/src/app/domain/applications/application/design/flows/flows.component.ts
gravitee-am-ui/src/app/domain/settings/flows/flows.component.ts

fix: filter recovery_code in the EnrollMFA policy

---

CHANGELOG-v3.adoc

Generate changelog for version AM - 3.15.11

Changelog for AM - 3.15.11

---

gravitee-am-common/src/main/java/io/gravitee/am/common/i18n/FreemarkerMessageResolver.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/email/impl/EmailServiceImpl.java
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/blocked_account.html
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/header.html
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/mfa_challenge.html
gravitee-am-gateway/gravitee-am-gateway-standalone/gravitee-am-gateway-standalone-distribution/src/main/resources/templates/reset_password.html
gravitee-am-management-api/gravitee-am-management-api-service/src/main/java/io/gravitee/am/management/service/impl/EmailServiceImpl.java
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/certificate_expiration.html
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/header.html
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_en.properties
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/i18n/messages_fr.properties
gravitee-am-management-api/gravitee-am-management-api-standalone/gravitee-am-management-api-standalone-distribution/src/main/resources/templates/registration_confirmation.html

chore: update default email theme

---

CHANGELOG-v3.adoc

Generate changelog for version AM - 3.17.4

Changelog for AM - 3.17.4

---

docker/management-ui/Dockerfile
docker/management-ui/Dockerfile-dev
docker/management-ui/Dockerfile-nightly

The following vulnerabilities are fixed with an upgrade:
- https://snyk.io/vuln/SNYK-ALPINE315-CURL-2938004
- https://snyk.io/vuln/SNYK-ALPINE315-CURL-2938004
- https://snyk.io/vuln/SNYK-ALPINE315-OPENSSL-2941810
- https://snyk.io/vuln/SNYK-ALPINE315-OPENSSL-2941810
- https://snyk.io/vuln/SNYK-ALPINE315-PCRE2-2869384
fixes gravitee-io/issues#8183

fix: docker/management-ui/Dockerfile to reduce vulnerabilities

---

CHANGELOG-v3.adoc

Generate changelog for version AM - 3.18.1

Changelog for AM - 3.18.1

---

gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/resources/organizations/environments/domains/ThemeResource.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/test/java/io/gravitee/am/management/handlers/management/api/resources/ThemeResourceTest.java
gravitee-am-test/api/management/apis/ThemeApi.ts
gravitee-am-ui/src/app/app-routing.module.ts
gravitee-am-ui/src/app/app.module.ts
gravitee-am-ui/src/app/domain/settings/theme/theme.component.html
gravitee-am-ui/src/app/domain/settings/theme/theme.component.scss
gravitee-am-ui/src/app/domain/settings/theme/theme.component.spec.ts
gravitee-am-ui/src/app/domain/settings/theme/theme.component.ts
gravitee-am-ui/src/app/resolvers/themes.resolver.spec.ts
gravitee-am-ui/src/app/resolvers/themes.resolver.ts
gravitee-am-ui/src/app/services/theme.service.spec.ts
gravitee-am-ui/src/app/services/theme.service.ts

closes gravitee-io/issues#8122

feat(theme): UX-UI integration

---

gravitee-am-common/src/main/java/io/gravitee/am/common/utils/ConstantKeys.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginAbstractHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginCallbackFailureHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/main/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSelectionRuleHandler.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-core/src/test/java/io/gravitee/am/gateway/handler/root/resources/handler/login/LoginSelectionRuleHandlerTest.java

closes gravitee-io/issues#8312

feat(selection-rule): add identity provider in the SPEL context

---

CHANGELOG-v3.adoc

Generate changelog for version AM - 3.18.2

Changelog for AM - 3.18.2

---

CHANGELOG-v3.adoc

Generate changelog for version AM - 3.15.12

Changelog for AM - 3.15.12

---

CHANGELOG-v3.adoc

Generate changelog for version AM - 3.18.3

Changelog for AM - 3.18.3

---

gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/VertxHttpHeaders.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/VertxHttpServerRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/main/java/io/gravitee/am/gateway/handler/common/vertx/core/http/VertxHttpServerResponse.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-common/src/test/java/io/gravitee/am/gateway/handler/common/vertx/web/handler/PolicyChainHandlerTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/EvaluableRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-context/src/main/java/io/gravitee/am/gateway/handler/context/EvaluableResponse.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/ciba/service/request/CibaAuthenticationRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/request/AuthorizationRequestFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/resources/request/TokenRequestFactory.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/main/java/io/gravitee/am/gateway/handler/oauth2/service/request/BaseRequest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/AuthorizationRequestFactoryTest.java
gravitee-am-gateway/gravitee-am-gateway-handler/gravitee-am-gateway-handler-oidc/src/test/java/io/gravitee/am/gateway/handler/oauth2/service/request/TokenRequestFactoryTest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/DummyRequest.java
gravitee-am-identityprovider/gravitee-am-identityprovider-api/src/main/java/io/gravitee/am/identityprovider/api/context/EvaluableAuthenticationRequest.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/http/JettyHttpServerHeaders.java
gravitee-am-management-api/gravitee-am-management-api-rest/src/main/java/io/gravitee/am/management/handlers/management/api/authentication/http/JettyHttpServerRequest.java
pom.xml

fixes gravitee-io/issues#8357 and fixes gravitee-io/issues#8235

fix(policy): bump Policy HTTP Callout to 1.15.1 version
